### ISSUE TITLE
小米4点击全屏经常没有响应

### ISSUE THREAD

**Issue by babylikebird** [lipangit/JieCaoVideoPlayer#100]
问题如题。另外为全屏返回的时候有，有播放声音，但是没有画面（demo没有问题）。

**Comment by lipangit** [comment]
1.全屏没有响应的问题，头条用handler操作MediaPlayer，在onMessage中操作MediaPlayer，这方面的问题还没想清楚，因为处理message的时候也是主线程，就不会阻塞吗，一想这问题就头大T_T

2.没有图像的问题你看log有没有
recreate surfaceview from IllegalArgumentException或recreate surfaceview from IllegalStateException
没图像本质上JCMediaManager.instance().mediaPlayer.setDisplay(surfaceHolder);这行代码没调成功

**Comment by babylikebird** [comment]
拐球，在我的应用中全屏播放后，返回，小视频就卡在打开全屏的那一帧，有音频输出，有进度。无有效log输出。

**Comment by lipangit** [comment]
如果demo没这个问题的话，就严格按照demo中的JCVideoPlayerStandardShowShareButtonAfterFullscreen.java这个类做，完全按照demo的用法使用

**Comment by lipangit** [comment]
已经将操作MediaPlayer的部分添加到线程，develop分支可以体验
