### ISSUE TITLE
关于横屏竖屏显示的问题

### ISSUE THREAD

**Issue by causlayer** [lipangit/JieCaoVideoPlayer#1000]
设置了videoView.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;可以重力感应，全屏的时候为横屏，那竖屏的时候切换回原始状态（不是竖屏全屏）就不行了，请问这个如何设置，谢谢

**Comment by lipangit** [comment]
对，设计如此，重力感应是进入全屏才起作用，无法退出全屏，退出全屏要按back键或者按右下角退出全屏的按钮。

**Comment by lipangit** [comment]
全屏的时候重力感应只是修改全屏时候的方向。

**Comment by 18667366881** [comment]
点击全屏还是竖屏  需要改哪里  谢谢

**Comment by lipangit** [comment]
@18667366881 能具体点说你的问题吗

**Comment by 18667366881** [comment]
好的  我用了您的框架  播放没有问题    点击全屏的时候 还是竖屏  不能横屏    我的代码层级是  在viewpage 里面的  谢谢啦

**Comment by 18667366881** [comment]
QQ 674483879  谢谢你

**Comment by lipangit** [comment]
参照demo的OrientationActivity，设置JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;

**Comment by 18667366881** [comment]
嗯 好的  我去试试 谢谢你

**Comment by 18667366881** [comment]
嗯 点击全屏确实横屏了     但是 界面好像刷新了  列表页空白了   播放器不见了     好像界面重绘了  请问是啥问题

**Comment by 18667366881** [comment]
嗯 原来是   在点击横屏的时候   activity  重新启动了    现在可以横屏了 谢谢你 大神 祝你每天有个好心情
