### ISSUE TITLE
jcvideoplayer-lib中jc_layout_standard.xml布局中应该将android:id="@+id/back_tiny"和 android:id="@+id/back"这两个ImageView的visibility属性设置为gone，现在我集成在项目中发现如果设置成visible，在上拉刷新数据的时候会显示出来影响界面的美观，刷新完成才会消失。请楼主修改下jc_layout_standard.xml布局。

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JieCaoVideoPlayer#1002]

**Comment by lipangit** [comment]
原因是没调用setUp，展示控件的时候必须调用setUp

**Comment by StevenNick88** [comment]
我调用了，现在的问题是在上拉刷新的一瞬间会显示android:id="@+id/back_tiny"和 android:id="@+id/back"这两个ImageView，刷新完成之后就消失了，因为我在adapter中进行的setUp操作，在上拉刷新的一瞬间adapter应该来不及初始化，这个在上拉刷新的onRefresh方法中我没法传递setUp中的3个参数，所以没法调用。楼主为什么不能在jc_layout_standard.xml布局中将android:id="@+id/back_tiny"和 android:id="@+id/back"这两个ImageView的visibility属性设置为gone，这样并不影响你的sdk。

**Comment by lipangit** [comment]
好的，我试试

**Comment by lipangit** [comment]
已经把back_tiny gone，back不行，因为直接操作toplayout的 不直接操作back
