### ISSUE TITLE
播放地址问题

### ISSUE THREAD

**Issue by androidheweidong** [lipangit/JieCaoVideoPlayer#1003]
是否支持hls流媒体播放

**Comment by lipangit** [comment]
https://developer.android.com/guide/topics/media/media-formats.html 理论上支持

**Comment by androidheweidong** [comment]
我直接使用JCVideoPlayerStandard 然后setUp就可以嘛，我需要设置什么嘛，我这样尝试并不能播放~

**Comment by androidheweidong** [comment]
http://os5vfhbv8.bkt.clouddn.com/test000  这是一个切片后的视频 您可以试一下！

**Comment by lipangit** [comment]
超出老臣解决范围
