### ISSUE TITLE
屏幕的点击事件？

### ISSUE THREAD

**Issue by xiaolinzhang** [lipangit/JieCaoVideoPlayer#1006]
第一次点击屏幕和播放完毕再点击屏幕，事件不一样，请问这个点击事件在哪里？

**Comment by lipangit** [comment]
第一次点击屏幕的事件是“点击缩略图开始播放”，播放完毕点击屏幕是“CLICK_BLANK”。在JCUserActionStandard中定义

**Comment by xiaolinzhang** [comment]
我想在视频播放结束后，吧布局替换成近日头条哪种 有分享的UI，可是不会啊，怎么做，楼主提供个思路吧。

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，布局里加个按钮，复写setUiWitStateAndScreen函数，case autoComplete状态，显示分享按钮，其他状态隐藏按钮

**Comment by lipangit** [comment]
这个下版本会和头条保持一致
