### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by chentao7v** [lipangit/JieCaoVideoPlayer#101]
大神有没有考虑过做视频缓存啊

**Comment by lipangit** [comment]
android.media.MediaPlayer怎么缓存视频，好像没啥结论
看来缓存的呼声很高啊

**Comment by axeon** [comment]
我认为没啥用，缓存在本地占用大量空间，清理也是很麻烦的事情。
现在的网速可以支持实时视频了。

**Comment by chentao7v** [comment]
是的，特别是在ListView里面使用的话，缓存还是很有必要哒

**Comment by chentao7v** [comment]
@lipangit 是的，特别是在ListView里面使用的话，缓存还是很有必要哒

**Comment by chentao7v** [comment]
@axeon 如果想重发一遍，那就耗流量了啊

**Comment by lipangit** [comment]
目前感觉这个功能还是很重要，但是不一定放到JCVideoPlayerStandard里，因为JCVideoPlayerStandard这个是模仿头条，目标就是一模一样，头条不能手势修改亮度，我就也没加这个功能，如果我们每天被乱七八糟的功能追着跑，将会失去信念，疲惫不堪

我听过头条产品经理在李善友老师的混沌研习社的演讲，讲的很有道理，所以在我们的JCVideoPlayerStandard标准播放控件里，头条就是完美，它有的或没有的功能在我们这不需要考虑

现在是不知道怎么做缓存，如果知道的话头条没这功能，我们的标准库也没这功能，但是会给开发者这个接口，想有就能有，这是目的

**Comment by lipangit** [comment]
将来还会在DEMO里把优酷、youtube、土豆、爱奇艺、腾讯视频等主流播放器模仿一遍，目标也是一模一样

**Comment by axeon** [comment]
建议不要走偏了。。。
如果客户想要缓存，让他们提前下载就行了，这块和播放器无关。
另外，做到头条的功能就ok了，完善好基本功能很重要，现在包才50k，要做的更多集成了ffmpeg，那可能是5M起了，不一定有人用。

**Comment by lipangit** [comment]
头条现在有两点做不到啊
1.全屏切换播放进度流畅，我们的进度会跑偏
2.头条是用handler操作MediaPlayer，目的应该是解决操作MediaPlayer的时候的卡顿，一次我在WC网络特别差，点击缩略图每次都会卡住主线程，代码精髓在哪还没想明白

**Comment by axeon** [comment]
应该不会卡主线程的，可能哪里做错了。

**Comment by lipangit** [comment]
蒙蔽中0_0

**Comment by chentao7v** [comment]
@lipangit @axeon 哈哈，感谢大神们的建议

**Comment by axkza** [comment]
其实要做缓存和多种解码的话，建议可以另起一个项目了
JCVideoPlayer这个项目挺好的，**_主要是：包小，精简_**，实用！一般自己的服务器存视频都是以mp4格式的，目前这个项目已经非常够用了

**Comment by lipangit** [comment]
@axkza android.media.MediaPlayer 支持hls，支持RTSP

**Comment by lipangit** [comment]
不知道怎么做

**Comment by flztsj** [comment]
https://github.com/danikula/AndroidVideoCache
使用这个库，直接很简单的把视频url封装一层后就可以边播边缓存了。
