### ISSUE TITLE
求教，视频播放到一定时间就会报 java.net.ProtocolException: unexpected end of stream 错误

### ISSUE THREAD

**Issue by lvbell** [lipangit/JieCaoVideoPlayer#1010]
作者您好，我在播放一个10min长视频过程中，播放到最后几分钟的时候就会出现以下错误，然后视频停止播放，请问这是我传值问题或是因为别的问题引起的？

W/MediaHTTPConnection: readAt 23780704 / 8864 => java.net.ProtocolException: unexpected end of stream
07-03 11:34:26.940 30837-30849/com.xcar.activity E/MediaPlayer: error (1, -1004)
07-03 11:34:26.941 30837-751/com.xcar.activity E/MediaPlayer: Error (1,-1004)
07-03 11:34:26.941 30837-751/com.xcar.activity I/MediaPlayer: [HSM] stayAwake false uid: 10199, pid: 30837
07-03 11:34:26.952 30837-30837/com.xcar.activity E/JieCaoVideoPlayer: onError 1 - -1004 [50774110]

**Comment by lvbell** [comment]
我看stackoverflow上有一种说法是因为header 里的 content-length和视频的真实大小不一样导致的

**Comment by lipangit** [comment]
超出老臣解决范围
