### ISSUE TITLE
同个activity销毁，进去重新加载另一个视频播放一会突然停止

### ISSUE THREAD

**Issue by chenqunming** [lipangit/JieCaoVideoPlayer#1012]
E/MediaPlayer: Should have subtitle controller already set 
 E/BufferQueue: [unnamed-2367-3] disconnect: connected to another api (cur=0, req=3)

**Comment by lipangit** [comment]
需要更多描述，是不就是跳转activity？什么叫同个activity销毁

**Comment by chenqunming** [comment]
一个activity是singletask，finish掉，传不视频地址再进去播放，快速操作几次，视频会播放一会就停止了

**Comment by lipangit** [comment]
activity finish 会调用activity的onPause，然后会调用JCVideoPlayer.releaseAllVideos() 这时候视频就停止了

**Comment by chenqunming** [comment]
一个是网络地址，一个是本地文件地址，两个来回切换，比如：先进去播网络视频，退出重新进去再播本地视频，然后退出又重新进去播网络视频，现在这个网络视频播放中会突然停止
