### ISSUE TITLE
怎么在列表中点击全屏后默认显示横屏

### ISSUE THREAD

**Issue by 7hundeR** [lipangit/JieCaoVideoPlayer#1015]

**Comment by lipangit** [comment]
可以，参照demo origintationActivity，修改全屏之前和全屏之后的屏幕方向。

**Comment by 7hundeR** [comment]
谢谢，还有一个疑问，设置了 jcVideoPlayerStandard.ACTION_BAR_EXIST = false;
                jcVideoPlayerStandard.TOOL_BAR_EXIST = false;
还是没有效果怎么办

**Comment by 7hundeR** [comment]
抱歉，还有一个疑问，按照demo设置了，默认是横向的了，但是点击返回到列表的时候，整个列表也是横屏的了

**Comment by lipangit** [comment]
这两个变量是控制全屏之后ActionBar是否隐藏的，断点一下库里的代码，调试一下试试

**Comment by 7hundeR** [comment]
好的，谢谢您的解答😁
