### ISSUE TITLE
我将节操播放器放入到recyclerview中，怎么给他设置播放前封面而不是黑屏

### ISSUE THREAD

**Issue by ruwochunfeng** [lipangit/JieCaoVideoPlayer#1016]

**Comment by lipangit** [comment]
什么叫播放前封面，什么是黑屏的，再具体描述一下

**Comment by ruwochunfeng** [comment]
就是一般的app在你看一个视频的时候，在没有播的时候他是有个关于这个视频的图片在播放器中，比较直观点，当你点击播放按钮的时候就开始播放了，我做了个app视频模块，在没有播放之前是黑屏的，我想有画面体验好一点。
![85 1gvldo9 71fbzx 6l](https://user-images.githubusercontent.com/19380889/27798882-97ee2e44-6045-11e7-8749-5f3d8939b167.png)

**Comment by lipangit** [comment]
缩略图呢

**Comment by Greathfs** [comment]
自己抓取第一帧作为缩略图 用glide放进去就行了啊

**Comment by ruwochunfeng** [comment]
了解，谢谢各位
