### ISSUE TITLE
JCVideoPlayer内存泄漏bug

### ISSUE THREAD

**Issue by bethebest** [lipangit/JieCaoVideoPlayer#1017]
JCVideoPlayer类中的

public void initTextureView() {
        removeTextureView();
         **JCMediaManager.textureView = new JCResizeTextureView(getContext());**
        JCMediaManager.textureView.setSurfaceTextureListener(JCMediaManager.instance());
    }

textureView 是静态的，getContext获取activity的引用，导致activit内存不能释放造成内存泄漏

**Comment by lipangit** [comment]
有什么办法解决吗

**Comment by 18667366881** [comment]
我也是新手  不过我觉得  既然 这个  getContext   有问题    那就想办法绑定Activity  一起销毁  你们觉得如何

**Comment by chenjzcj** [comment]
继承该方法
@Override
    public void initTextureView() {
        //父类方法存在内存泄露，导致Activity不能被回收，使用getApplicationContext
        //super.initTextureView();
        removeTextureView();
        JZMediaManager.textureView = new JZTextureView(getContext().getApplicationContext());
        JZMediaManager.textureView.setSurfaceTextureListener(JZMediaManager.instance());
    }
