### ISSUE TITLE
在6.0上出现问题

### ISSUE THREAD

**Issue by JackHang** [lipangit/JieCaoVideoPlayer#102]
华为荣耀6 系统是EMUI4.0 播放大视频时候报错error (1, -1004)，视频链接：http://7xawdc.com2.z0.glb.qiniucdn.com/o_19p6vdmi9148s16fs1ptehbm1vd59.mp4

**Comment by lipangit** [comment]
是每次都出现吗，几率大吗，log只有error (1, -1004)定位到代码了吗

**Comment by JackHang** [comment]
每次都出现，小米这边好像应该也是这样，不过小米播放的时间长一点，出错的log我晚上下班后重新弄下看下。

**Comment by lipangit** [comment]
MEDIA_ERROR_IO ＝ -1004，你的网络有问题吗，我们这的7款测试机一直没啥问题

你把这个视频地址复制到demo中会有问题吗

**Comment by JackHang** [comment]
就是这个视频链接复制到Demo里面，而且不止这个项目，我试了3个基于系统的MediaPlayer，都是这个问题，一个是这个项目，一个是UniversalVideoView。我用Vitamio的就可以直接播放。低于6.0的小米手机也可以播放。都处于同一个网络

**Comment by lipangit** [comment]
都有IO问题。。。？

**Comment by Vincent1110** [comment]
我也遇到这个问题了，也是华为的荣耀。
log信息：
 E/MediaPlayer-JNI﹕ QCMediaPlayer mediaplayer NOT present
E/MediaPlayer﹕ error (1, -1004)

**Comment by lipangit** [comment]
QCMediaPlayer 这是啥。。

**Comment by Vincent1110** [comment]
QCMediaPlayer不是你们的log嘛。。。。。

**Comment by Vincent1110** [comment]
好奇怪，在华为荣耀上没法播放。
在小米TV上却正常。。。

**Comment by JackHang** [comment]
都是IO问题，我测试到现在，出错率是100%，但是家里的WIFI出错的时间就不定了，不知道是因为七牛那边的问题还是什么问题。出错的地方是MediaPlayer的Error监听直接抓取的，所以不清楚详细的代码问题。

**Comment by lipangit** [comment]
@Vincent1110 QCMediaPlayer不是这个库里的log

支持大视频，1小时的也能播

**Comment by Vincent1110** [comment]
@lipangit  嗯，我刚才测试了大视频，可以播放的。
很神奇：刚才我在华为荣耀上又测试了下，可以播放没问题了。。。

**Comment by lipangit** [comment]
这种情况就是扛住
