### ISSUE TITLE
华为 H30-T00 Android 4.2.2,onSurfaceTextureAvailable 没有回调

### ISSUE THREAD

**Issue by BuleB** [lipangit/JieCaoVideoPlayer#1020]
流程：前一活动JCVideoPlayerStandard加载视频没有问题，第二页 再加载视频onSurfaceTextureAvailable 没有回调，直接黑屏，排除了硬件加速的原因，小米4 6.0 正常 小米Pad 4.4.4 正常，华为6.0正常。然后这个莫名其妙的不走回调，请问这样的问题会出在哪里

**Comment by BuleB** [comment]
E/SurfaceTexture: [unnamed-2628-4](this:0x639a3f40,api:0) error creating EGLImage: 0x3008
 E/SurfaceTexture: [android::status_t android::SurfaceTexture::convertToAuxSlotLocked(bool)] create aux eglImage FAILED
E/libEGL: validate_display:251 error 3008 (EGL_BAD_DISPLAY)

**Comment by lipangit** [comment]
只要把TextureView addView到布局中就应该调用onSurfaceTextureAvailable，  可以单独操作一下TextureView 排除其他地方的干扰。
