### ISSUE TITLE
更换播放源后无法播放

### ISSUE THREAD

**Issue by MickeyBadBad** [lipangit/JieCaoVideoPlayer#1022]
正在播放一个URL的时候更换URL进行Prepare播放无效，出现MediaPlayer Error （1，-22）。
4.5版本有个prepareVideo函数可以直接换源播放的，5.5中没有对应的函数可以做到这一点。
尝试了prepareMediaPlayer还是会报错。
希望能改进。

**Comment by lipangit** [comment]
建议先releaseAllVideos，然后再播放

**Comment by MickeyBadBad** [comment]
releaseAllVideos  播放器就整个退了。。。
目标是更换清晰度～ 实实地。。。

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，然后切换url的时候用JCMediaPlayer.instance().mediaPlayer.release(),这个类能直接操作mediaPlayer
