### ISSUE TITLE
如何播放本地视频

### ISSUE THREAD

**Issue by naivor** [lipangit/JieCaoVideoPlayer#1025]
我用节操播放器播放本地视频，无论是直接使用本地路径，还是 “file://”+本地路径 都无法播放，请问节操支持播放本地视频吗

**Comment by shuruncs** [comment]
本地视频能播放，但是我想问下能播放h.264的本地文件吗？？我每次播放都失败！

**Comment by naivor** [comment]
下能播放h.264的本地文件，我也是这个问题

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27917176-d774c898-629d-11e7-8d35-86a2193e30a9.png)

用的是系统的mediaPlayer，你们尝试一下setDataSources那个能播放，然后我把这个方法暴露出去

**Comment by lipangit** [comment]
这个怎么做呢
