### ISSUE TITLE
在列表状态下，尝试多次播放相同位置的视频，第二次开始object里面的参数拿不到

### ISSUE THREAD

**Issue by qinyang1018** [lipangit/JieCaoVideoPlayer#1026]
我通过setUp中传递object参数来控制播放器的UI，当列表同一个位置不滑动被播放第二次后，object拿到的参数值不对。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27917056-7958b0a8-629d-11e7-8ed6-06d247ff7317.png)

你觉得是什么原因，只有setUp的时候设置objects，object是空吗第二次

**Comment by qinyang1018** [comment]
我是在setUp和JCVideoPlayerStandard.startFullscreen时给objects相同位置设置了一个参数。
在列表不滑动时，同一个播放位置 我之前setup传入的是1  第二次播放变成了0  。
我现在还是在处理播放广告的逻辑。
我现在逻辑是通过传入1和0 来表示是播放广告还是正片。 一个位置连续播放三个视频，前贴片，正片，后贴片。    第一次播放都是正常的。第二次在播放这个三个，前贴之前传入的1，变成了0
如果我表述的不清楚，和在群里聊  我也在群里

**Comment by lipangit** [comment]
JCVideoPlayerStandard.startFullscreen的时候不需要setUp，因为JCVideoPlayerStandard.startFullscreen是直接开启全屏，这个如果推出就全部推出，如果从这个函数启动全屏，是不会退出到普通窗口的。

**Comment by lipangit** [comment]
你的需求是一个控件里播放不同视频。你说的第二次播放的时候setUp了吗，断点setUp看看是哪里修改了objects。

**Comment by qinyang1018** [comment]
好的  我试试这个  有可能是我处理的问题   感谢您的回答
