### ISSUE TITLE
怎么在列表中，点击全屏播放后，再将手机打横，视频结束播放了，然后回到了列表页了，这是怎么回事呢

### ISSUE THREAD

**Issue by haegyeong** [lipangit/JieCaoVideoPlayer#1031]

**Comment by lipangit** [comment]
断点meidaPlayer的release方法的所有所在位置，看看是否哪里调用了releaseAllVideos

**Comment by AzAdkins** [comment]
这个是你的Activity在执行生命周期，  android:configChanges="orientation|screenSize"

**Comment by lipangit** [comment]
对，加上这个就好了
