### ISSUE TITLE
为什么播放视频只有声音没有画面

### ISSUE THREAD

**Issue by liuweig2257** [lipangit/JieCaoVideoPlayer#1032]
视频是avi格式的，播放视频只有声音，没有画面

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27985067-5ecb612a-6416-11e7-9975-d71c27be9a8d.png)


然后新建个项目用最简单的MediaPlayer和TextureView试试是否播放正常

**Comment by liuweig2257** [comment]
安卓的mediaPlayer不支持.avi的视频格式。JieCaoVideoPlayer支持除mp4之外的视频格式吗？

**Comment by lipangit** [comment]
安卓的mediaPlayer支持什么我们就支持什么https://developer.android.com/guide/appendix/media-formats.html

**Comment by liuweig2257** [comment]
能否告诉一下，mediaplayer支持哪几种视频格式吗？我无法翻墙。谢谢

**Comment by lipangit** [comment]
[Supported Media Formats _ Android Developers.pdf](https://github.com/lipangit/JieCaoVideoPlayer/files/1135503/Supported.Media.Formats._.Android.Developers.pdf)
