### ISSUE TITLE
列表播放，点击全屏，然后手机放横，就退回列表页面

### ISSUE THREAD

**Issue by JayChan95318** [lipangit/JieCaoVideoPlayer#1034]
java.lang.IllegalStateException
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:721)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:470)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:778)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:199)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:166)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:176)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.view.View.performClick(View.java:5609)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.view.View$PerformClick.run(View.java:22259)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.os.Looper.loop(Looper.java:154)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
07-08 23:02:34.522 11424-11424/com.jaychan.videoplayer W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
07-08 23:02:34.559 11424-11528/com.jaychan.videoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-08 23:02:34.560 11424-11528/com.jaychan.videoplayer W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
07-08 23:02:36.075 11424-11436/com.jaychan.videoplayer W/MediaPlayer: info/warning (3, 0)

**Comment by lipangit** [comment]
断点所有mediaPlayer.release() 看看列表哪里调用了JCvideoPlayer.releaseAllVideos()

**Comment by JayChan95318** [comment]
不是这个问题吧，是你代码那里有问题，你去看看

**Comment by JayChan95318** [comment]
找到解决方法了，在清单文件的activity节点加上  android:configChanges="orientation|screenSize|keyboardHidden"

**Comment by lipangit** [comment]
好
