### ISSUE TITLE
当前正在播放，点击全屏播放按钮，进入全屏停止播放，并且黑屏

### ISSUE THREAD

**Issue by liuchenyang** [lipangit/JieCaoVideoPlayer#1036]
当前正在播放，点击全屏播放按钮，进入全屏停止播放，并且黑屏，这时候点击播放按钮，直接退出全屏，因为我之前是直接下载lib包导入到项目，改了相关的代码，之前并没有问题

**Comment by lipangit** [comment]
检查全屏的textureView的生成surface的时候是否mediaplayer setsurface，应该是这个导致的
