### ISSUE TITLE
设置了JCVD为16:9，结果自定义View里的JCVideoPlayerStandard宽高match_parent不起作用

### ISSUE THREAD

**Issue by Virczz** [lipangit/JieCaoVideoPlayer#1038]
`mJcVideoPlayerStandard.widthRatio = 16; mJcVideoPlayerStandard.heightRatio = 9;`

我用了一个自定义View，包裹了JCVideoPlayerStandard,设置JCVideoPlayerStandard的宽高为match_parent，又设置了上面的代码，结果match_parent不起作用。
当我取消设置上面的代码后，match_parent又起作用了。
这个是因为JCVD里面关于播放器宽高的设置和match_parent有冲突吗？有解决方案吗？

**Comment by lipangit** [comment]
不冲突吧，设置比例之后match_parent应该就不起作用了

mJcVideoPlayerStandard.widthRatio = 0; mJcVideoPlayerStandard.heightRatio = 0; match_parent才起作用
