### ISSUE TITLE
播放在线视频卡顿

### ISSUE THREAD

**Issue by WooYu** [lipangit/JieCaoVideoPlayer#1039]
服务器的视频是一个视频和音频合成的。如果在线播放就会出现卡顿，下载到本地播放就正常。

**Comment by lipangit** [comment]
如果把地址放到demo里也卡顿的话应该是视频的问题

**Comment by WooYu** [comment]
放在demo中也卡。关键是下载了可以正常播放，这就搞不懂了

**Comment by lipangit** [comment]
超出老臣解决范围

**Comment by WooYu** [comment]
嗯。还是很感谢你提供的demo。🙏

**Comment by WooYu** [comment]
音视频合成问题，现在改用mp4parser合成可以了。
