### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by fanguangqiang** [lipangit/JieCaoVideoPlayer#1044]
![](https://user-images.githubusercontent.com/22962183/28167462-48b6e156-680e-11e7-91e2-f1e0b16d7e0e.jpg)

**Comment by ldy441040480** [comment]
releaseAllVideos 方法里面加一个清空单例变量TextureView，MediaHandler，MainThreadHandler的操作

**Comment by lipangit** [comment]
releaseAllVideos里会调用onComplete，这里已经置空TextureView，你感兴趣的话可以修改代码之后观察观察，怎么才能解决内存泄漏

**Comment by ldy441040480** [comment]
你说的对，但是有一种情况是不会调用onComplete，就是全屏点击返回页面关闭时先走backPress-->setFirstFloor(null)，这个时候SECOND_FLOOR_JCVD已经为空了

**Comment by ldy441040480** [comment]
public static void completeAll() {
        if (SECOND_FLOOR_JCVD != null) {
            SECOND_FLOOR_JCVD.onCompletion();
            SECOND_FLOOR_JCVD = null;
        }
        if (FIRST_FLOOR_JCVD != null) {
            FIRST_FLOOR_JCVD.onCompletion();
            FIRST_FLOOR_JCVD = null;
        }
    }
onCompletion是不会执行的亲

**Comment by ldy441040480** [comment]
还有一个内存泄露是mProgressTimerTask，这个的泄露原因是开启全屏时播放view的时候启动了timer,退出全屏只移除了view,没有取消task

**Comment by ldy441040480** [comment]
public void clearFloatScreen() {
        JCUtils.getAppCompActivity(getContext()).setRequestedOrientation(NORMAL_ORIENTATION);
        showSupportActionBar(getContext());
        JCVideoPlayer currJcvd = JCVideoPlayerManager.getCurrentJcvd();
       // 移除timer
        currJcvd.cancelProgressTimer();
        currJcvd.textureViewContainer.removeView(JCMediaManager.textureView);
        ViewGroup vp = (ViewGroup) (JCUtils.scanForActivity(getContext()))//.getWindow().getDecorView();
                .findViewById(Window.ID_ANDROID_CONTENT);
        vp.removeView(currJcvd);
        JCVideoPlayerManager.setSecondFloor(null);
    }
