### ISSUE TITLE
请问视频切换清晰度后不能跳转到自定义的进度怎么处理呢？

### ISSUE THREAD

**Issue by fbstyle** [lipangit/JieCaoVideoPlayer#1046]
int position = getCurrentPositionWhenPlaying();
        JCUtils.saveProgress(getContext(), mVideoSource.get(quality), position);
        release();
        initTextureView();
        addTextureView();
        AudioManager mAudioManager = (AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE);
        mAudioManager.requestAudioFocus(onAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        JCUtils.scanForActivity(getContext()).getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        seekToInAdvance = position;
        JCMediaManager.CURRENT_PLAYING_URL = mVideoSource.get(quality);
        JCMediaManager.CURRENT_PLING_LOOP = loop;
        JCMediaManager.MAP_HEADER_DATA = headData;
        JCMediaManager.instance().mediaPlayer.seekTo(position);

以上是我实现视频切换的代码，正常可以，但是播放进度都是从0开始的。

一下两句话未起到任何作用，请问要怎么才能有效呢
 JCUtils.saveProgress(getContext(), mVideoSource.get(quality), position);
   JCMediaManager.instance().mediaPlayer.seekTo(position);

**Comment by lipangit** [comment]
JCUtils.saveProgress(getContext(), mVideoSource.get(quality), position);//这是保存播放进度的，随时起作用

JCMediaManager.instance().mediaPlayer.seekTo(position);//这是seek进度，播放时候和暂停都起作用
