### ISSUE TITLE
能播放ts文件吗？

### ISSUE THREAD

**Issue by WooYu** [lipangit/JieCaoVideoPlayer#1047]
![image](https://user-images.githubusercontent.com/10032892/28204292-fadbeba0-68af-11e7-9e6f-fbc9e0ab82f8.png)
![image](https://user-images.githubusercontent.com/10032892/28204319-0eb91fe4-68b0-11e7-99db-4895ecd48bb2.png)
播放一个本地的ts文件失败了

**Comment by lipangit** [comment]
没测试过，超出老臣解决范围

**Comment by lipangit** [comment]
安卓自带的MediaPlayer如何播放本地的ts文件
