### ISSUE TITLE
请问如何做到像头条一样点击全屏直接进入横屏播放呢？我现在点击全屏还需要把手机横过来会横屏播放

### ISSUE THREAD

**Issue by Lesincs** [lipangit/JieCaoVideoPlayer#1048]

**Comment by lipangit** [comment]
参照demo的origintationActivity，控制全屏和非全屏时候的屏幕方向

**Comment by liuchenyang** [comment]
你直接在Activity里面添加  JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;    
这样的话你点击全屏按钮就是直接全屏播放
