### ISSUE TITLE
能不能播放 http://******.mp4?a=123类似这样后面有参数的视频内容

### ISSUE THREAD

**Issue by liuchenyang** [lipangit/JieCaoVideoPlayer#1049]

**Comment by liuchenyang** [comment]
这是播放的时候的打印信息

07-15 12:17:43.817 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:17:43.817 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:17:43.817 336-11119/? E/MM_OSAL: FileSource::FileSource
07-15 12:17:43.817 336-11119/? E/MM_OSAL: FileSource::FileSource m_bEveryThingOK 1
07-15 12:17:43.817 336-11119/? E/MM_OSAL: MM_File_Create failed .Efs Error No -1 , File Name /data/mmosal_logmask.cfg , Mode 0
07-15 12:17:43.877 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:17:48.187 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:17:48.187 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:17:48.397 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:17:53.717 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:17:53.717 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:17:53.887 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:17:56.917 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:17:56.917 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:17:57.917 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:18:01.967 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:18:01.967 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:18:02.207 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:18:07.557 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:18:07.557 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:18:07.747 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:18:10.747 336-11119/? E/NuCachedSource2: Reading source timed out for 3000000000 nanoseconds
07-15 12:18:10.747 336-11119/? E/NuCachedSource2: readAt timed out and return -EAGAIN
07-15 12:18:11.737 336-11128/? E/NuCachedSource2: It is an outdated message. Ignore
07-15 12:18:12.767 336-11119/? E/GenericSource: Failed to init from data source!
07-15 12:18:12.767 5426-5546/com.aastartups.chuangdao E/MediaPlayer: error (1, -2147483648)
07-15 12:18:12.767 5426-5536/com.aastartups.chuangdao E/MediaPlayer: Error (1,-2147483648)
07-15 12:18:12.767 5426-5426/com.aastartups.chuangdao E/JieCaoVideoPlayer: onError 1 - -2147483648 [345183200]

**Comment by lipangit** [comment]
服务器识别了吗，我没试过

可以设置header，参照demo

**Comment by liuchenyang** [comment]
我手机是oppo  ，在vivo手机就没事

**Comment by liuchenyang** [comment]
设置header 怎么设置，在demo里没找到

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28237037-ac5757ee-6968-11e7-8c9d-e4aa618ee544.png)

**Comment by liuchenyang** [comment]
添加了 head代码   还是不行

**Comment by lipangit** [comment]
服务器收到这些参数了吗

**Comment by liuchenyang** [comment]
后端今天没在，和服务器的关系大不大，因为我拿其他的测试机测试都是可以正常播放的，只有oppo不行

**Comment by liuchenyang** [comment]
总是提示我 
07-15 12:18:12.767 5426-5546/com.aastartups.chuangdao E/MediaPlayer: error (1, -2147483648)
07-15 12:18:12.767 5426-5536/com.aastartups.chuangdao E/MediaPlayer: Error (1,-2147483648)
07-15 12:18:12.767 5426-5426/com.aastartups.chuangdao E/JieCaoVideoPlayer: onError 1 - -2147483648 [345183200]

**Comment by lipangit** [comment]
超出老臣解决范围
