### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by XinYang5120** [lipangit/JieCaoVideoPlayer#105]
Hello，全屏播放，拖动进度条，处于缓冲状态时，然后窗口--全屏，全屏--窗口切换，很容易ANR。找个视频较长的测试并且网络状况不佳时。不然不好测试。

**Comment by lipangit** [comment]
谢谢你的反馈，会有这个问题，MediaPlayer有时候会阻塞主线程，有人反馈release()有时也需要很长时间，我反汇编头条是用handler操作MediaPlayer，在onMessage中再操作MediaPlayer

**Comment by XinYang5120** [comment]
Hello，如果是在播放状态（网络状态不佳时处于缓冲状态,onIfor()被调用，这是Mediaplay实际也是播放状态），就是在这种状态下是非常容易ANR，其他情况暂时没有发现。

**Comment by XinYang5120** [comment]
另外好像没有实现OnInforListener接口监听网络缓冲

**Comment by lipangit** [comment]
记得以前处理了setOnSeekCompleteListener，2.0的时候，进度被修改的时候会有loading图标，这版本忘了，有时间加上它

**Comment by lipangit** [comment]
重点是MediaPlayer阻塞主线程的问题，onMessage也是回调到主线程，然后还是在主线程操作MediaPlayer，核心问题想不明白，一想到这个问题就蒙蔽T_T

**Comment by lipangit** [comment]
已经添加到线程，感觉很流畅，develop分支可以体验
