### ISSUE TITLE
能不能获取到当前加载视频的时候的网速，例如100k/s  这种

### ISSUE THREAD

**Issue by liuchenyang** [lipangit/JieCaoVideoPlayer#1052]

**Comment by lipangit** [comment]
系统的android.media.MediaPlayer好像没这接口，你可以找找

**Comment by mflk007** [comment]
业务需要显示加载时候的网络请求速度，怎么实现呢？ 或者具体哪个版本可以加入这个功能？@lipangit

**Comment by lipangit** [comment]
没有现成的，先切换到ijkplayer，然后通过自定义播放器自己添加这功能
