### ISSUE TITLE
视频地址有错误时，播放的时候onError方法没走，不能正确监听错误回调

### ISSUE THREAD

**Issue by 867588763** [lipangit/JieCaoVideoPlayer#1053]
#     测试代码： 路径为错误路径
        mJcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
        mJcVideoPlayerStandard.setUp("654166"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");

# 运行后，出现以下错误信息：
07-18 14:01:39.944 24497-24497/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onClick start [3026135] 
07-18 14:01:39.947 24497-24497/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: startVideo [3026135] 
07-18 14:01:39.947 24497-24497/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: addTextureView [3026135] 
07-18 14:01:39.950 24497-24497/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onStatePreparing  [3026135] 
07-18 14:01:39.951 24497-24497/fm.jiecao.jiecaovideoplayer I/USER_EVENT: ON_CLICK_START_ICON title is : 嫂子不信 url is : 654166 screen is : 0
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [122501948] 
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: onMeasure  [122501948] 
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
07-18 14:01:39.960 24497-24497/fm.jiecao.jiecaovideoplayer I/JCResizeTextureView: viewRotation = 0
07-18 14:01:39.968 24497-24497/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureAvailable [86959506] 
07-18 14:01:39.976 24497-24561/fm.jiecao.jiecaovideoplayer E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-18 14:01:39.976 24497-24561/fm.jiecao.jiecaovideoplayer E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err: java.lang.reflect.InvocationTargetException
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:83)
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.Looper.loop(Looper.java:160)
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-18 14:01:39.978 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err: Caused by: java.io.IOException: setDataSource failed.
07-18 14:01:39.979 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1097)
07-18 14:01:39.979 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1071)
07-18 14:01:39.979 24497-24561/fm.jiecao.jiecaovideoplayer W/System.err: 	... 5 more
07-18 14:01:40.117 24497-24519/fm.jiecao.jiecaovideoplayer I/art: Starting a blocking GC Explicit
07-18 14:01:40.169 24497-24519/fm.jiecao.jiecaovideoplayer I/art: Explicit concurrent mark sweep GC freed 56783(5MB) AllocSpace objects, 15(916KB) LOS objects, 38% free, 25MB/41MB, paused 531us total 51.777ms

# **_重点错误：_**
  at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:83)

格外信息：
JCMediaManager JCVideoPlayer  里面的onError方法均没有回调

**Comment by 867588763** [comment]
http://65465464这个错误的可以正确回调    本地的这种“23121”什么的，错误回调不行，刚又测试了一下

**Comment by lipangit** [comment]
setUp的第一个参数是视频地址

**Comment by jfjbYXY** [comment]
@lipangit 他的意思应该是想要一个监听，在错误地址A播放失败的时候播放正确地址B

**Comment by 568285876** [comment]
有没有这个播放错误的监听回调？

**Comment by lipangit** [comment]
明白了，这个的错误回调应该在startMediaPlayer中启动，走了prepare的exception，没走onError。
![image](https://user-images.githubusercontent.com/2038071/57848048-89e4f380-780a-11e9-9734-db2f173a8e2c.png)

下个版本会在这里调用Jzvd的onerror。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/57848167-dc261480-780a-11e9-9eed-34eaaec150fc.png)
改成这样

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/57848519-af263180-780b-11e9-8dba-b2db9d40ee6e.png)

我把url换成 “1111” 然后onError的错误如下，没走这个exception。
你们什么问题 我没听明白。可以通过各种方式联系我，也可以录视频看你们那边具体什么效果。

@568285876  你那边什么播放错误，具体说明

**Comment by 568285876** [comment]
![QQ图片20190517093855](https://user-images.githubusercontent.com/11871366/57897595-28fc0080-7888-11e9-9204-f13aaf8b075d.png)
我的错误是这个，视频做了压缩处理就播放不了了，不过好像是Android 5.0 - 7.0之间的手机不能播放，我的小米6升级到Android 9.0的是没问题的，最后我换成了Exo播放引擎就没问题了。我的意识是用饺子默认的引擎如果不能播放，在当前的activity是不是可以有一个错误的回调监听，然后尝试更换播放引擎继续播放。我对视频播放不了解，所以不知道我这个想法是不是有问题或者说是幼稚，如果是就忽略我的回复吧。
（补充：当前版本6.3.1，尝试升级到7.0.3也是不行的）

**Comment by lipangit** [comment]
我觉得从视频文件上解决是长久之计。以目前的情况为什么不直接用exoplayer呢

**Comment by 568285876** [comment]
> 我觉得从视频文件上解决是长久之计。以目前的情况为什么不直接用exoplayer呢

OK, thanks for your reply.
