### ISSUE TITLE
本地的视频播放不了吗?

### ISSUE THREAD

**Issue by kirsong** [lipangit/JieCaoVideoPlayer#1056]
看代码的时候 发现有 本地的.但是已经注释掉了.
我尝试 按照那个代码 重新实现了一下.但获取失败

**Comment by lipangit** [comment]
直接把注释解开就能播放

通过android.media.MediaPlayer播放本地视频，你可以查询相关内容

**Comment by kirsong** [comment]
感谢您的回信.我就是注解相关代码的.
我给您贴出代码

myJCVideoPlayerStandard.setUp(Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");

**根据条件我把播放文件放到指定的位置上了.但无法播放.**
请问不是这个代码吗?

谢谢

**Comment by kirsong** [comment]
非常感谢.
自己解决了. 原来是 6.0以上没有设置 权限.
