### ISSUE TITLE
暂停以后，再播放，视频会卡上很长一段时间

### ISSUE THREAD

**Issue by dazhiyu** [lipangit/JieCaoVideoPlayer#106]

**Comment by lipangit** [comment]
我遇到的卡基本都是在开始播放，进入全屏或退出全屏的时候，所以下个版本会把操作MediaPlayer放到线程中。

你说的这个卡是不是只是视频卡顿，主线程并没有被阻塞吧。

**Comment by dazhiyu** [comment]
是，demo上也有卡顿

**Comment by lipangit** [comment]
加我微信吧，lipanhelloworld，发个小视频，想象不出来普通和播放的暂停为什么会卡，

**Comment by lipangit** [comment]
没这个问题了吧
