### ISSUE TITLE
getCurrentPosition for show FragmentDialog

### ISSUE THREAD

**Issue by victortu** [lipangit/JieCaoVideoPlayer#107]
Hello teacher, I love GitHub and your library, but I am not an expert in Android, how I can get the position of the video, to display a Dialog and after closing, to continue the video? In videoview exist getCurrentPosition.

Thank you, teacher

**Comment by lipangit** [comment]
You can extends JCVideoPlayerStandard, then override some methods you want.
example： JCVideoPlayerStandardShowShareButtonAfterFullscreen.java in demo .
Override onAutoCompletion(){} can let you know when the video stop.

Call this methods everywhere to get videoPosition , JCMediaManager.instance().mediaPlayer.getCurrentPosition();

**Comment by victortu** [comment]
thanks teacher, a cordial greeting of a student from the University of Mallorca (Spain). I'll play with your library, it is excellent.

You can write a little about the example? Sorry, I am electrical engineer and not much about programming.

Thank you very much again, @lipangit !!

**Comment by lipangit** [comment]
JCMediaManager.instance().mediaPlayer.stop();
U should call that when the video is playing , if video is not prepared it will error.

**Comment by victortu** [comment]
works correctly! Perfect, you're the best!

Thank you for your time, I hope I have not bothered.
