### ISSUE TITLE
How to send http header like mediaplayer 

### ISSUE THREAD

**Issue by jabedbd** [lipangit/JieCaoVideoPlayer#1071]
There is a simple way to send http header on mediaplayer.
```
 Map<String,String> headers = new HashMap<String,String>();
                                headers.put("key","value");
 mediaPlayer.setDataSource(context,Uri.parse(vsource),headers);
```

How can i send header like the mediaPlayer on JiecaoVideoPlayer? 
I try with the code bellow but it's not working :( 

```
 Map<String,String> headers = new HashMap<String,String>();
                                headers.put("key","value");
JCMediaManager.MAP_HEADER_DATA = headers;
myvideo.setUp(vsource,JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL,"");
```

**Comment by lipangit** [comment]
myVideo.headData=...

**Comment by jabedbd** [comment]
myvideo.headData = headers; 
also not working :(

**Comment by lipangit** [comment]
Ok

Can you help me to improve readme, my mother luanguage is not English, are you instrested in?

**Comment by jabedbd** [comment]
@lipangit Sure! It's a awesome project. I'm feel proud to working on this project :)

**Comment by lipangit** [comment]
Good!
