### ISSUE TITLE
播放不了视频

### ISSUE THREAD

**Issue by BBBB1** [lipangit/JieCaoVideoPlayer#1072]
http://222.37.159.225:13164/playurl.m3u8?xxx
http://xx.m3u8?
这两类视屏都不可以啊
QCMediaPlayer mediaplayer NOT present
07-23 16:32:06.531 21206 21316 E   MediaPlayer com.SL.TV                        error (-38, 0)
07-23 16:32:06.531 21206 21316 W   MediaPlayer com.SL.TV                        setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-23 16:32:06.531 21206 21316 E   MediaPlayer com.SL.TV                        prepareAsync called in state 0
07-23 16:32:06.531 21206 21316 W   System.err com.SL.TV                         java.lang.Illegal State Exception
07-23 16:32:06.531 21206 21316 W   System.err com.SL.TV                         at android

**Comment by VMystery** [comment]
我测了几台机器，4.4系统播放m3u8格式会出现这个问题，

**Comment by lipangit** [comment]
保持关注@VMystery

**Comment by asd7227600** [comment]
+1...我也遇到了这个问题....

**Comment by VMystery** [comment]
已修复JCMediaManager类中过早调用 method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);将此句放到后面调用即可，暂时未测出其他问题
mediaPlayer.setScreenOnWhilePlaying(true);
mediaPlayer.setOnSeekCompleteListener(JCMediaManager.this);
mediaPlayer.setOnErrorListener(JCMediaManager.this);
mediaPlayer.setOnInfoListener(JCMediaManager.this);
mediaPlayer.setOnVideoSizeChangedListener(JCMediaManager.this);
method.invoke(mediaPlayer, CURRENT_PLAYING_URL, MAP_HEADER_DATA);//放到设置监听语句后面
mediaPlayer.prepareAsync();
mediaPlayer.setSurface(new Surface(savedSurfaceTexture));

**Comment by VMystery** [comment]
@lipangit

**Comment by lipangit** [comment]
fix on 278ddf0 感谢你的方案 进群了吗 给你来个管理 @VMystery

**Comment by VMystery** [comment]
好的谢谢，在群里就叫VMystery。@lipangit
