### ISSUE TITLE
视频暂停问题

### ISSUE THREAD

**Issue by zhouguanglian** [lipangit/JieCaoVideoPlayer#1076]
场景
A页面视频还在加载当中，从A页面进入B页面
在A页面的hidden方法中用了
if (jcVideoPlayerStandard != null && jcVideoPlayerStandard.isPlaying())
                jcVideoPlayerStandard.startButton.performClick();
自己封装的isPlaying方法。
A页面视频依旧播放，performClick（）不能取消加载嘛？
那这样用什么监听呢？

**Comment by lipangit** [comment]
进入B页面之后a页面的视频会release

你想要什么效果

**Comment by lipangit** [comment]
你可以判断cu'rrent_state就知道当前视频的播放状态
![image](https://user-images.githubusercontent.com/2038071/28524231-2dd478e2-70b2-11e7-87e7-02e4541aae36.png)

**Comment by zhouguanglian** [comment]
嗯嗯  没有想到release会保存进度，用release处理好了。
3q 3q 23333
