### ISSUE TITLE
Long buffering

### ISSUE THREAD

**Issue by dima-ostapovets** [lipangit/JieCaoVideoPlayer#1077]
Hello, thank you for you lib.
Currently I'm going to play small videos - about 2-3 seconds.
The problem is that preparing and buffering takes too long time, sometimes 3-5 seconds, and longer video (~1 min) starts in 1-2 seconds. Could you give some advice how to fix this?

**Comment by lipangit** [comment]
This is where the system player needs to be optimized,I am not capable of solving this problem, I will always focuse on this problem.
