### ISSUE TITLE
播放时进度条和startButton不会自动隐藏

### ISSUE THREAD

**Issue by zhouguanglian** [lipangit/JieCaoVideoPlayer#1079]
1.播放时进度条和startButton不会自动隐藏
2.WIFI情况下自动播放  jcVideoPlayerStandard.backButton.performClick();不会播放，直接调用startVideo？？

**Comment by zhouguanglian** [comment]
原因依旧是在Fragment中的关系
DismissControlViewTimerTask 的
 if (getContext() != null && getContext() instanceof Activity) {
                    ((Activity) getContext()).runOnUiThread(new Runnable() {}
}导致的，新添加了判断

else {
                    bottomContainer.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            bottomContainer.setVisibility(View.INVISIBLE);
                            topContainer.setVisibility(View.INVISIBLE);
                            startButton.setVisibility(View.INVISIBLE);
                            if (currentScreen != SCREEN_WINDOW_TINY) {
                                bottomProgressBar.setVisibility(View.VISIBLE);
                            }
                            if (pw != null) {
                                pw.dismiss();
                            }
                        }
                    },1);
                }
暂时实现

**Comment by lipangit** [comment]
解决就好，有问题再提
