### ISSUE TITLE
Making video loopable

### ISSUE THREAD

**Issue by ivanviragine** [lipangit/JieCaoVideoPlayer#108]
Hi there! Firstly, thanks for this awesome lib. I've been struggling with a lot of libs to play video on Android and this seems to be the best for my needs! Thanks!

Secondly: I would like to be able to set video to be loopable. I can do this by making JCMediaManager.instance().mediaPlayer.setLooping(true), but since there's a lot going on on the onCompletion methods, this doesn't work.
It would be great to allow automatic looping.

**Comment by lipangit** [comment]
Ok, next version will add this feature.

**Comment by ivanviragine** [comment]
Ok! Thanks! Any due date?

**Comment by lipangit** [comment]
Every sunday will release a version.

**Comment by lipangit** [comment]
done in version 3.4 , release on sunday.

**Comment by ivanviragine** [comment]
@lipangit thanks for the feature! I noticed that some devices (actually, most devices) are not looping the video, but only the audio! Do you have any clue on how to get this to work?

**Comment by lipangit** [comment]
Do you mean setLooping(true); but it did not work?

**Comment by ivanviragine** [comment]
Yes @lipangit! Setting looping true only works on certain devices. Most devices loops only audio and video gets blank.

**Comment by lipangit** [comment]
Try demo on other devices

**Comment by ivanviragine** [comment]
I've tried. That's why I'm saying it works on some and doesn't on many. Do you think that there isn't a fix? I mean, it's a media player's bug not library specific bug?

**Comment by lipangit** [comment]
Maybe a system bug, I will focuse on it.

**Comment by ivanviragine** [comment]
Hi @lipangit! Any news on this?

**Comment by lipangit** [comment]
[Every weekend release a new version ](https://github.com/lipangit/JieCaoVideoPlayer/releases)

I am researching a new fullscreen way.
