### ISSUE TITLE
全屏播放直接退出Activity

### ISSUE THREAD

**Issue by HaoPz** [lipangit/JieCaoVideoPlayer#1080]
Activity 中设置了   android:screenOrientation="landscape"

Activity 也初始化   jcVideoPlayerStandard.setUp(videoModel.url, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, videoModel.title); 

1,Activity 中直接设置播放全屏，全屏按钮还是小窗口状态
2,播放完成，页面自动变成了竖屏
3,SCREEN_LAYOUT_NORMAL 设置后返回 JCvideoPlayer 没有返回按钮
4,点击返回，Jc 先变成了竖屏。

感谢提供这么棒的源库

**Comment by lipangit** [comment]
老臣惭愧，会继续努力
