### ISSUE TITLE
在activity中写了几个fragment，在fragment中使用播放器，然而全屏的时候软件就崩溃了

### ISSUE THREAD

**Issue by MiChongGET** [lipangit/JieCaoVideoPlayer#1083]
在点击全屏的时候，使用重力感应是视频全屏放大，结果软件就闪退了，是没设置好吗，可以手动取消重力感应的功能吗

**Comment by MiChongGET** [comment]
报了这个异常Caused by: java.lang.NullPointerException: Attempt to read from field 'int android.support.v4.app.Fragment.mContainerId' on a null object reference

**Comment by lipangit** [comment]
看看readme是不是AndroidManifest没设置好

**Comment by MiChongGET** [comment]
父activity已经设置过了，但是还是出现这种问题

**Comment by MiChongGET** [comment]
已经修复好了，还是activity设置问题
