### ISSUE TITLE
dont stop on back screen

### ISSUE THREAD

**Issue by xperiafan13-rom** [lipangit/JieCaoVideoPlayer#1085]
Hello, i hace a error, on back pressed, the video continue play on second plane, please help.. and another question, is possible to add resume support?

**Comment by lipangit** [comment]
What is second plane, can you describe more?

Resume and  go on play can be realised, But I have not studied

**Comment by xperiafan13-rom** [comment]
Im sorry, I already fix this, but i have another problem with auto rotation, when I rotate to landscape two ways, i have this error
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.view.ViewGroup.addViewInner(ViewGroup.java:4310)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4146)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.view.ViewGroup.addView(ViewGroup.java:4118)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.addTextureView(JCVideoPlayer.java:557)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:736)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at com.xperiafan13.com.hackmovie.Fragmentos.Reproductor.onConfigurationChanged(Reproductor.java:161)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4190)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4268)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5439)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-29 14:13:23.177 29991-29991/com.xperiafan13.com.hackmovie W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by lipangit** [comment]
see origintationActivity in demo this is landcape

**Comment by omidraha** [comment]
@xperiafan13-rom How do you fix your first problem, I already have this problem.
