### ISSUE TITLE
5.0播放失败

### ISSUE THREAD

**Issue by akiraxiao** [lipangit/JieCaoVideoPlayer#109]
fm.jiecao.jiecaovideoplayer E/MediaPlayer: Should have subtitle controller already set
fm.jiecao.jiecaovideoplayer E/MediaPlayer: error (1, -38)
fm.jiecao.jiecaovideoplayer E/MediaPlayer: Error (1,-38)
fm.jiecao.jiecaovideoplayer E/JieCaoVideoPlayer: onError 1 - -38 [fm.jiecao.jcvideoplayer_lib.JCVideoPlayerSimple{13c6d466 V.E..... ........ 0,0-1280,768}] http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4
3.3的lib

**Comment by lipangit** [comment]
This problem has troubled me for a long time.

Because I don't know which error will cause app crash , which error will let video stop , which error has no effect on playing video.

**Comment by lipangit** [comment]
啊 还以为你是老外

if (what != 38 && what != -38)  在onError的时候会忽略38和-38的error，你这个情况what是1，不知道能不能还继续播放，现在直接就进入error状态并且释放资源了

**Comment by akiraxiao** [comment]
但是我前面用3.2就没这问题

**Comment by lipangit** [comment]
3.2到3.3是小更新，感觉3.2也会有这个问题的，只是还没遇到_0_

**Comment by akiraxiao** [comment]
额 原来是这样

**Comment by naki35** [comment]
I'm using 3.6.1 and gives me the same error. Did you solve the problem? I don't understand Chinese, please help me.

**Comment by lipangit** [comment]
First confirm you video url and network is aviable, it can play in demo. 
If the error does not affect the play, you should ignore it.
If the error does not affect the play but JCVideoPlayer go into ERROR_STATE, you should tell me, Library should ignore the error

**Comment by naki35** [comment]
My Phone
`LG G3 - 6.0`

Emulator
`Genymotion - Samsung Galaxy S6 - 5.0.0`

I installed the `jiecaovideoplayer-3.6.1-demo.apk` on my phone and it worked fine
but on the emulator only the first video played

Here's my code (**video can be played on both phones**)
```java
public class MainActivity extends AppCompatActivity {
    JCVideoPlayerStandard jcVideoPlayerStandart;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        jcVideoPlayerStandart = (JCVideoPlayerStandard) findViewById(R.id.custom_videoplayer);
        jcVideoPlayerStandart.setUp("http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8",
                "title");
    }
    @Override
    protected void onPause() {
        super.onPause();
        JCVideoPlayer.releaseAllVideos();
    }
}
```
**I change link
`http://2449.vod.myqcloud.com/2449_bfbbfa3cea8f11e5aac3db03cda99974.f20.mp4`
this link work on my phone but doesn't work on emulator**

It gives this error
> **06-28 06:47:14.149 9611-9629/ncnyazilim.jcplayer E/MediaPlayer: Should have subtitle controller already set
06-28 06:47:17.090 9611-15691/ncnyazilim.jcplayer E/MediaPlayer: error (1, -38)
06-28 06:47:17.092 9611-15691/ncnyazilim.jcplayer E/MediaPlayer: error (1, -38)
06-28 06:47:17.092 9611-9629/ncnyazilim.jcplayer E/MediaPlayer: Error (1,-38)
06-28 06:47:17.092 9611-9629/ncnyazilim.jcplayer E/MediaPlayer: Error (1,-38)
06-28 06:47:17.092 9611-9611/ncnyazilim.jcplayer E/JieCaoVideoPlayer: onError 1 - -38 [461201649] 
06-28 06:47:17.103 9611-15691/ncnyazilim.jcplayer E/BufferQueueProducer: [unnamed-9611-6] connect(P): BufferQueue has been abandoned**

**I hope you can help me. Thank you in advance.**

**Comment by lipangit** [comment]
Your phone can play is successful, do not care emulator.
