### ISSUE TITLE
连续播放问题请教

### ISSUE THREAD

**Issue by wjy591416** [lipangit/JieCaoVideoPlayer#1091]
连续播放实现了，但是出现一个问题，在刚刚开始播放第一个视频的时候，进入全屏，播放几个视频后再推出全屏模式，又会从第一个重新开始播放，貌似，是无法传递播放进度currentUrlMapIndex标签，请教，这个该如何结局
主要问题在于，如在全屏播放时，有一个播放地址播放出错之后，会退出全屏，然后有从刚刚进入全屏时候的那个视频重新开始播放

**Comment by lipangit** [comment]
总结来说就是全屏切换的时候index的传递问题

**Comment by wjy591416** [comment]
谢谢，已经得到解决

**Comment by lipangit** [comment]
可以大概说说怎么解决的

**Comment by wjy591416** [comment]
对LISTVideoPlayer中的playOnThisJcvd方法重写，添加
currentUrlMapIndex = JCVideoPlayerManager.getSecondFloor().currentUrlMapIndex;
这样就能将在全屏模式下调整过的currentUrlMapIndex传给

**Comment by wenyongzhao** [comment]
可以说一下怎么实现连续播放的吗?

**Comment by lipangit** [comment]
@wenyongzhao 无缝的连续播放目前的架构还做不到，因为MediaPlayer是单例的必须要有loading的过程
