### ISSUE TITLE
how to set multi URL in JCVideoPlayerStandard ?

### ISSUE THREAD

**Issue by skhanbeiki** [lipangit/JieCaoVideoPlayer#1102]
how to set multi URL in JCVideoPlayerStandard ?

For example :
        String[] string = new String[]{};
        jcVideoPlayerStandard.setUp(string , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, click.getTitle());

**Comment by lipangit** [comment]
I am trying, this weekend release new version contains this feature.
