### ISSUE TITLE
开始播放缩略图消失闪屏黑屏问题处理方案

### ISSUE THREAD

**Issue by Lionet6** [lipangit/JieCaoVideoPlayer#1105]
@lipangit 第四步作者可以认真考虑下，我没仔细看源码，简单的处理了一下，只是提供了一下思路，作者看下是否有所帮助 http://blog.csdn.net/qq_24229505/article/details/76549397

**Comment by Seamo** [comment]
见仁见智吧。
有的需求是黑屏buffering，有的就是带预览图buffering直到prepare，有的是和你的需求一样，play的时候才把预览吃掉。
这可能并不是个问题。当然，你考虑把几种情况都集中一下，做个可切换的选项，然后提一个PR给作者应该是坠吼的。

**Comment by lipangit** [comment]
好的我研究研究，@Lionet6，有现成的效果能看吗

**Comment by Lionet6** [comment]
@lipangit 加载不出来就去上边的网址，我已经更新效果图了。

![效果图](https://user-images.githubusercontent.com/16394037/28866752-7d3f837c-77a6-11e7-9151-d9f9aa52ed9a.gif)

**Comment by lipangit** [comment]
好的，哥们你如果有时间可以提交一个pr，我这边如果改的话得下个礼拜了。其实这个问题的本质原因我还没搞清楚，我改的话需要时间研究。
