### ISSUE TITLE
有没有清晰度切换功能

### ISSUE THREAD

**Issue by GTooo** [lipangit/JieCaoVideoPlayer#1106]
有没有清晰度切换功能，传多个视频链接，点击切换，JC好像没看到清晰度切换的控件

**Comment by lipangit** [comment]
在develop分支，正在开发

**Comment by GTooo** [comment]
@lipangit 下载下来用了，发现个bug，点击图标切换全屏，接着返回原来窗口时，再次点击全屏的按钮时，播放会停止，也没有全屏，卡住了一样，然后中间显示暂停控件页也显示着

**Comment by lipangit** [comment]
亲测，点击全屏按钮，然后再点全屏按钮退出全屏，再点全屏按钮进入全屏，这个过程正常。

**Comment by GTooo** [comment]
@lipangit 刚刚重新导入了lib，就没问题了，可能是我修改到了哪里，清晰度切换那里可以上线使用了否，项目正好用到

**Comment by lipangit** [comment]
周末发版，在develop已经开发完，观察两天就可以发版了

**Comment by GTooo** [comment]
@lipangit 好勒
