### ISSUE TITLE
https 的视频连接无法播放

### ISSUE THREAD

**Issue by TitleZWC** [lipangit/JieCaoVideoPlayer#1107]
我用手机录制短视频，然后上传到七牛，通过jiecaoVideoPlayer播放七牛的https的链接，无法播放

**Comment by lipangit** [comment]
log是什么，记得以前亲测，可以播放

**Comment by TitleZWC** [comment]
附上log

08-04 17:47:40.998 22519 22519 I JieCaoVideoPlayer: onClick start [220485158]
08-04 17:47:41.003 22519 22519 D JieCaoVideoPlayer: startVideo [220485158]
08-04 17:47:41.004 22519 22519 D JieCaoVideoPlayer: addTextureView [220485158]
08-04 17:47:41.005  4953  4976 I MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10242/22519 clientId=android.media.AudioManager@598275fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1@f467c65 req=2 flags=0x0
08-04 17:47:41.006 22519 22519 I JieCaoVideoPlayer: onStatePreparing  [220485158]
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: onMeasure  [164571881]
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: videoWidth = 0, videoHeight = 0
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: viewRotation = 0
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: onMeasure  [164571881]
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: videoWidth = 0, videoHeight = 0
08-04 17:47:41.015 22519 22519 I JCResizeTextureView: viewRotation = 0
08-04 17:47:41.017 22519 22519 I JieCaoVideoPlayer: onSurfaceTextureAvailable [165282553]
08-04 17:47:41.018 22519 22519 D AudioManager: AudioManager dispatching onAudioFocusChange(-2) for android.media.AudioManager@210a38ffm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1@f467c65
08-04 17:47:41.019 22519 22519 W System.err: java.lang.IllegalStateException
08-04 17:47:41.021 22519 22519 W System.err: 	at android.media.MediaPlayer.isPlaying(Native Method)
08-04 17:47:41.021 22519 22519 W System.err: 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$1.onAudioFocusChange(SourceFile:960)
08-04 17:47:41.021 22519 22519 W System.err: 	at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2158)
08-04 17:47:41.021 22519 22519 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-04 17:47:41.021 22519 22519 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-04 17:47:41.021 22519 22519 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
08-04 17:47:41.021 22519 22519 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 17:47:41.021 22519 22519 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-04 17:47:41.021 22519 22519 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-04 17:47:41.022 22519 22519 D JieCaoVideoPlayer: AUDIOFOCUS_LOSS_TRANSIENT [256277605]
08-04 17:47:41.028 22519 23317 W MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
08-04 17:47:41.028 22519 23317 W MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28964110-0e69dea4-793e-11e7-9974-570c186be7ed.png)

表明系统里有其他声音干扰，能不能排除。这个问题能否复现。

**Comment by TitleZWC** [comment]
无法播放的视频：https://video.tanbeixiong.com/vod/video/36628686/e2b397b9d45c783dea9fa6c1f03fb235/7e7aa05e30474fa14f3bd113d0053409/show

使用https以前是可以播放的：
http://tbx-video.oss-cn-shenzhen.aliyuncs.com/vod/video/36628686/3c382224f6fc30fce6f7bd2f7351b0d5/6ac4663ad3974ceb6b6c6e2610180a6e/show

**Comment by lipangit** [comment]
1.表明系统里有其他声音干扰，能不能排除。
2.这个问题能否复现。
分别回答一下，上面的log的内容和https无关

**Comment by TitleZWC** [comment]
这个问题可以复现，我干扰声不知道该怎么排除

**Comment by lipangit** [comment]
是不是系统其他地方播放声音，jcvd得到广播。log显示是这个过程。

视频用chrome播放无图像，黑屏的，可以建议重新编码。

**Comment by TitleZWC** [comment]
我这个音轨编码是aac，视频编码原本是h264,然后用ffmpeg进行过处理。现在应该是mpeg-4 visual  这个目前在safari上播放是没有问题的。我在视频上传之前使用jiecaoVIdeoPlayer也没有问题的

**Comment by TitleZWC** [comment]
https://video.tanbeixiong.com/vod/video/73237229/ca807cc7ddf0239b373dffc0742988f3/bcc65fda7958414a6a65155a863baf61/show
这个链接也无法播放。这个是chrome可以直接播放的

**Comment by TitleZWC** [comment]
系统没有播放其他声音

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28965918-14f649e4-7946-11e7-859a-45087e7b0ba9.png)

可能超出老臣解决范围啊

**Comment by TitleZWC** [comment]
好的   谢谢你
