### ISSUE TITLE
播放时间问题

### ISSUE THREAD

**Issue by BlackMin** [lipangit/JieCaoVideoPlayer#111]
小窗口中暂停视频后进入全屏，全屏后不进行任何操作，稍等一段时长后，再返回小窗口，点击播放时，当前播放点自动跳到若干秒后（有时5秒，有时8秒，有时15秒。。。）

**Comment by lipangit** [comment]
没错，切换全屏的时候就会有这个问题，你有啥解决办法吗，有啥想法吗

**Comment by BlackMin** [comment]
我看了下午半天也没看出个❀，比较奇怪的是为什么处于播放状态时，进入全屏就没有问题

**Comment by BlackMin** [comment]
你清楚大致是哪里有问题吗?

**Comment by lipangit** [comment]
主要是setDisplay，切换surfaceHolder的时候进度就会跑偏

目前认为头条的视频全屏的本质是横屏，还在研究其中奥秘
