### ISSUE TITLE
自动播放视频完成后，点击播放崩溃

### ISSUE THREAD

**Issue by 7hundeR** [lipangit/JieCaoVideoPlayer#1113]
在继承Activity的类里设置自动播放，播放完成后点击播放按钮奔溃，错误日志：
Attempt to invoke virtual method 'void android.support.v7.app.AppCompatActivity.setRequestedOrientation(int)' on a null object reference
继承AppCompatActivity就不会崩溃

**Comment by lipangit** [comment]
继承了AppCompatActivity还会崩溃吗

**Comment by 7hundeR** [comment]
继承AppCompatActivity就不会崩溃

**Comment by lipangit** [comment]
好
