### ISSUE TITLE
RecyclerView中的JCVidedoPlayer在滑出屏幕后不会自动停止

### ISSUE THREAD

**Issue by huclengyue** [lipangit/JieCaoVideoPlayer#1116]
我看demo的会自动终止，但是自己使用就不会自动终止，同时也没有发现在哪里设置。

**Comment by lipangit** [comment]
setUp,里的onStateNormal

**Comment by huclengyue** [comment]
并不可以。测试过。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29068704-7b502ae4-7c6a-11e7-94c7-8b965f3e308d.png)
![image](https://user-images.githubusercontent.com/2038071/29068717-897140ea-7c6a-11e7-9a2b-416064e49620.png)
