### ISSUE TITLE
请问为什么播放视频会很卡顿

### ISSUE THREAD

**Issue by yan885283** [lipangit/JieCaoVideoPlayer#1118]
隔几秒就会卡一下缓冲，网络是没有问题的，求解决方案，找到问题原因，是因为播放的是m4v格式的，播放mp4的就不会卡顿，那请问怎么能播放m4v格式的不卡

**Comment by lipangit** [comment]
建议使用大众化的无脑的视频格式，视频格式问题超出老臣解决范围

**Comment by yan885283** [comment]
宝宝不开心了

**Comment by lipangit** [comment]
么么哒
