### ISSUE TITLE
DialogFragment in FullScreenVideo (JCFullScreenActivity)

### ISSUE THREAD

**Issue by victortu** [lipangit/JieCaoVideoPlayer#112]
Hello again! You're a genius, I love your library, I would like to show a DialogFragment when the screen in fullScreen is, I thought to check whether the screen is in FullScreenVideo, remove full screen, display dialog and then return from full screen but does not work because it takes about seconds out and broken.

How can I solve that? Or I can get the context of the activity JCFullScreenActivity, to show DialogFragment without leaving fullScreen? Currently fullScreen (JCFullScreenActivity) activity is private.

Thank you very much!

Currently, I use the next funtions to take a process, but take a error about seconds for change fullScreen to normal and it's ugly process.

```
jcVideoPlayerStandardShowTitleAfterFullscreen{
   public Boolean isFullScreenOn(){
     return mIfCurrentIsFullscreen;
   }
   public ImageView getViewFullScreen(){
     return fullscreenButton;
   }
}
jcVideoPlayerStandardShowTitleAfterFullscreen.backFullscreen();
jcVideoPlayerStandardShowTitleAfterFullscreen.getViewFullScreen().performClick();
```

**Comment by lipangit** [comment]
if mIfCurrentIsFullscreen = true, getContext() will get JCFullScreenActivity's context.

Code about show a DialogFragment should in JCVideoPlayerStandardShowTitleAfterFullscreen which extends JCVideoPlayerStandard.

You need logic is very complex, very likely is a trap, if I were you I would refuse to complete this requirement

**Comment by victortu** [comment]
Hello !, it felt so bad you think it's a trap, I wish you do not stay with that idea, I explain my situation,
I am a student of industrial electronics and automation engineering, and 6 months ago started working at a startup, this startup, is a driving school ONLINE (online videos that show how to study the theory test car) in this company, I learned a lot of programming and many other subjects. This year ended the career of industrial electronics engineering and offered to make their (online driving school) Android application as final thesis.

As an engineering student my computer skills are many and we do not know if the questions may seem rare.

The online driving school (https://superexpress.es/), has dynamic videos, the content explained car and stop to ask a question of what just appeared in the video, and when the student answers the new test question what you just learned in the video, the video continues.

I do not want you to think that is somewhat misleading or a trap, then you make a video of the App (not finished, ugly design) and also a video of the web (https://superexpress.es/prueba-gratis) where I teach what dynamic videos , and if necessary, we talk on skype or add me on facebook.

These are the two video capture to show my work:
https://youtu.be/hkSMuNW_0as
https://youtu.be/B0FFMYE4WyA

Thanks for your time.

**Comment by lipangit** [comment]
All right , I should not say that.

The library born for who want to roughly play a video, they don't need cool effect , do not care any detail .

So your need will not add the library as a standard function , but I will help you on your need.

**Comment by victortu** [comment]
Sorry for the misunderstanding, do not worry, it seems very strange the first time, your first thought was correct. 

I understand that you can not add to the library this particular case, but to display a DialogFragment, needed function getFragmentManager(), and from the class JCVideoPlayerStandardShowTitleAfterFullscreen I can not get getFragmentManager(). You have any solution? 

```
public class JCVideoPlayerStandardShowTitleAfterFullscreen extends JCVideoPlayerStandard {

  public void startDialog(){
    FragmentManager fragmentManager = getFragmentManager(); // Error not find function  
    fragmentDialog = TestFragmentoDialog.newInstance(second_stop_video);
    fragmentDialog .setTargetFragment(this, 0);
    fragmentDialog .show(fragmentManager, "dialog_videos");
  }
}
```

Thanks and sorry for the misunderstanding,

Víctor.

**Comment by lipangit** [comment]
((FragmentActivity) getContext()).getSupportFragmentManager();

Your base activity should be FragmentActivity.

**Comment by victortu** [comment]
Indeed, so I tried as well, but it happens, a mistake, remember that want to show the DialogFragment during full screen (your JCFullScreenActivity) because exit the full screen can be annoying for the user.

**Comment by victortu** [comment]
I think it's not a problem that extends from FullscreenActivity extends Activity since I'm using app.Fragment and not support.v4.app.Fragment, so I can use getFragmentManager and not getSupportFragmentManager. And my DialogFragment is necessary to display the questions of what the video ends of teaching. But despite that, I think being in another activity does not like and displays error.


>  E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                               Process: com.superexpress.autoescuela, PID: 14664
>                                                                               java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
>                                                                                   at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1411)
>                                                                                   at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1429)
>                                                                                   at android.app.BackStackRecord.commitInternal(BackStackRecord.java:687)
>                                                                                   at android.app.BackStackRecord.commit(BackStackRecord.java:663)
>                                                                                   at android.app.DialogFragment.show(DialogFragment.java:230)

**Comment by victortu** [comment]
I'm testing the ugly option fullScreen leaving, but mIfCurrentIsFullscreen returns false, even if it is in fullScreen. But this can control it with JCBuriedPointStandard, but rarely mIfCurrentIsFullscreen always = false

**Comment by prashanthd** [comment]
Sry for asking this question. I am not able to conclude after reading all your comments so I am asking the question.  **I want like, thumbnail view in activity and when user clicks full screen button I want to show full screen in dialog because if I open new activity I will loose lot of data(timers,handlers) which is in previous activity. is it possible?**

**Comment by lipangit** [comment]
Of course it is possible, but you will do more work , and more complex.
If your app is not professional play video, like youtube, I suggest you do not make thing complex

As I think， you should not save these data, in china many populor app if activity onpause when playing video, the video will release and will lose every data.

**Comment by prashanthd** [comment]
@lipangit  thanx for your reply. I not bothering about video data. My app is related to asking questions of video, some thing like quiz.  I need to pull each question from server after specified time so there will be timers and handlers. There is no problem if video release data in pause. Can you please give me sample code for showing video full screen in a dialog?

**Comment by lipangit** [comment]
Use DialogFragment life cycle similar with fullscreenActivity，I believe you can .

**Comment by prashanthd** [comment]
I know DialogFragment but there are no callbacks for user click events. How to when user clicked on full screen button? can you please give me some basic idea?

**Comment by prashanthd** [comment]
@lipangit  can you plz guide me. I am not able to proceed. Thanks in advance.

**Comment by lipangit** [comment]
fullscreenButton is public 

jcVideoPlayer.fullscreenButton.setOnclickListener(...);
