### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by backListed** [lipangit/JieCaoVideoPlayer#1128]
video not playing either from file storage or from web.. even the video link from demo not playing.. showing loading,, loading... and it never ends.....

**Comment by lipangit** [comment]
show me the url

**Comment by backListed** [comment]
holder.videoPlayer.setUp(Uri.fromFile(new File(Environment.getExternalStorageDirectory()+"/DNOTE/qqqe.mp4")).toString()
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");

**Comment by backListed** [comment]
![image](https://user-images.githubusercontent.com/16229185/29114341-92c7098e-7d11-11e7-957a-096c12e0cf0d.png)

**Comment by backListed** [comment]
actually it is not playing video on certain app... it plays without errors in another implemantation..... # # @lipangit

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29175491-c9d3d5f0-7e1b-11e7-91a4-52a07834c183.png)

It not work??

**Comment by backListed** [comment]
Yep..  It worked.. I was forgot to update here....  It was because the hardware acceleration....  I was made that to false in manifest....

**Comment by lipangit** [comment]
Ok solved just fine
