### ISSUE TITLE
状态栏本来隐藏的会重新出现

### ISSUE THREAD

**Issue by luqinmao** [lipangit/JieCaoVideoPlayer#1134]
点击全屏播放后返回小屏后，状态栏本来隐藏的会重新出现，请问怎么解决

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/29201710-6506f774-7e93-11e7-96c8-797d0d4efa67.png)
设置这两个变量

**Comment by luqinmao** [comment]
谢谢大神，可以了
