### ISSUE TITLE
5.81 mp3播放可以没有进度条，可是显示进度条吗？

### ISSUE THREAD

**Issue by entityOfClass** [lipangit/JieCaoVideoPlayer#1137]

**Comment by lipangit** [comment]
可以，参照这里修改ui
![image](https://user-images.githubusercontent.com/2038071/29210787-da25bffc-7ec7-11e7-828f-f3c2513901df.png)

**Comment by lizhanyou** [comment]
谢谢，刚才做事情，没看清楚就就提交，还好中文好理解~~~

- 

- 

1.

**Comment by entityOfClass** [comment]
谢谢
