### ISSUE TITLE
如何解决SurfaceView 在 ListView 或 ScrollView中滚动时 出现 黑块的现象

### ISSUE THREAD

**Issue by WinsonZhou** [lipangit/JieCaoVideoPlayer#114]
请问项目中是如何解决SurfaceView 在 ListView 或 ScrollView中滚动时 出现 黑块的现象的。

**Comment by lipangit** [comment]
你看的是昨晚更新的demo吗，那个用的textureview

**Comment by WinsonZhou** [comment]
是昨天下午的demo, 看到的是这个JCResizeSurfaceView

**Comment by lipangit** [comment]
你说的是拖动的时候SurfaceView跟列表比移动会有延迟是吗，现在好像也是这样

对surfaceView的处理只做了视频居中

**Comment by WinsonZhou** [comment]
恩，如果单独把一个SurfaceView放到ScrollView当中， 滚动的时候SurfaceView刷新的延迟看起来比较明显，但是用你们的demo来看，好像这个问题不是很明显

**Comment by lipangit** [comment]
低调
