### ISSUE TITLE
如何自动全屏播放？

### ISSUE THREAD

**Issue by yu893145181** [lipangit/JieCaoVideoPlayer#1146]
我的app有视频列表，点击某个视频，然后跳转页面能够自动全屏播放，该如何实现啊？

**Comment by lipangit** [comment]
跳转页面是指什么

**Comment by lipangit** [comment]
看demo有个directlyFullscreenActivity

**Comment by yu893145181** [comment]
嗯，是可以，还有一个问题，我想问下，如何自动播放，而不需要每次点击中间的按钮？

**Comment by lipangit** [comment]
你说的自动播放是什么意思？

**Comment by yu893145181** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        JCVideoPlayerStandard jcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.videoplayer);
        jcVideoPlayerStandard.setUp("http://7xp6gv.com2.z0.glb.qiniucdn.com/7e8f49f8-e21e-406c-981c-1bd82ce19e51.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "表土");

    }
这是播放的一个界面，布局也就是一个简单的JCVideoPlayerStandard，我想在每次启动这个界面的时候，能自动播放，情况是每次启动这个界面的时候，需要点击播放按钮才会加载播放

**Comment by Igotyouinmysight** [comment]
继承playerStandard  自定义一个方法,里面调用JCVideoPlayer里面的startVideo和 onEvent(JCUserActionStandard.ON_CLICK_START_THUMB);方法即可,然后调用你自已定义的这个view

**Comment by DadChen** [comment]
1，点右下角的全屏按钮，如何设置直接横屏切换过去呢？
2，里面这些UI图标可以自己修改吧？把大神的库jcvideoplayer-lib撸进project当modul依赖？
      (: 感谢回答呀~~

**Comment by yu893145181** [comment]
@DadChen 直接横屏不知道呢，图标是可以改的，方法就是你说的添加进project当modul

**Comment by DadChen** [comment]
@yu893145181 明白，谢谢大兄弟。  直接横屏的暂时解决了：全屏横屏的方法：参照demo的orientationActivity设置全屏前和全屏后的屏幕方向

**Comment by lipangit** [comment]
解决了就好，我就不钻牛角尖了，么么哒

**Comment by 164738777** [comment]
引用楼上答案并加以修改( 基于 6.0.2 版本)
```
    startVideo();
    onEvent(JZUserActionStandard.ON_CLICK_START_THUMB);
    updateStartImage();
```
