### ISSUE TITLE
如何获得全屏时的布局？

### ISSUE THREAD

**Issue by EmKs** [lipangit/JieCaoVideoPlayer#1155]
因为沉浸式状态栏的原因，需要在Layout中添加setFitsSystemWindows设置，我通过getLayoutId的方式findview并设置setFitsSystemWindows发现并无效果;

**Comment by lipangit** [comment]
全屏和非全屏用同一个布局，通过控件是否可见来区别

**Comment by lipangit** [comment]
setFitsSystemWindows以前没用过，刚查了一下，他是实现状态栏的各版本适配，咱们全屏是直接隐藏，状态栏什么颜色也无所谓。这个和普通的布局并无区别，你查查原因吧，我只能帮到这了。

**Comment by EmKs** [comment]
@lipangit 好的，那么请问全屏后哪个方法可以监听得到？

**Comment by EmKs** [comment]
感谢，已经找到，并且解决问题了，Thank
