### ISSUE TITLE
全屏播放时标题栏旁边的小箭头是否有监听事件？

### ISSUE THREAD

**Issue by EmKs** [lipangit/JieCaoVideoPlayer#1161]
如题，我在代码中找到了backButton，和tinyBackImageView，对其都设置了点击事件，发现并没有效果

**Comment by lipangit** [comment]
Override
onClick(View v){
  if(v.getId()== backButton.id){
    //your logic
  }
}

**Comment by EmKs** [comment]
@lipangit 监听无效，我是这么写的，
public void onClick(View view) {
        switch (view.getId()) {
        case fm.jiecao.jcvideoplayer_lib.R.id.back:

         break;
     }
}

**Comment by lipangit** [comment]
断点一下，看看点击小箭头之后onClick方法是在哪跳出的

**Comment by EmKs** [comment]
小箭头还是在id为back中跳出，不过不会进入到我重写的方法里，我重新写了一个类，继承自JCVideoPlayerStandard重写init和onclick就好了
