### ISSUE TITLE
不能在fragment中使用吗

### ISSUE THREAD

**Issue by as2227024221** [lipangit/JieCaoVideoPlayer#1162]

**Comment by EmKs** [comment]
肯定是可以的，我的项目中Fragment嵌套了RecyclerView再嵌套JieCaoVideoPlayer都是可以的，检查一下你的代码吧

**Comment by lipangit** [comment]
可以的

**Comment by themass** [comment]
RecyclerView 点击大屏，再横竖屏切换时，闪退。我参考的是ActivityListViewRecyclerView里的代码，请协助一下，还有我需要加载的速度显示出来，该怎么获取加载的速度。还有划出屏幕时我想要自动暂停视频，该参考哪个？
