### ISSUE TITLE
全屏返回后，设置的getWindow().setFlag中的无效了

### ISSUE THREAD

**Issue by 2966325911** [lipangit/JieCaoVideoPlayer#1168]
getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN)；设置了这个代码，但是从全屏返回之后，这又恢复到之前了，怎么解决

**Comment by lipangit** [comment]
你想要什么效果？

退出全屏后系统的标题栏会显示出来，所以你这的修改会被覆盖

**Comment by 2966325911** [comment]
就是退出之后，我之前的设置系统的状态栏隐藏效果任然是有效，包括点击电源键的时候，改了源码中的代码实现了，但是感觉不和谐

**Comment by lipangit** [comment]
么么哒

**Comment by lll-01** [comment]
是的 , 我也是本来全屏的 , 结果视频全屏播放 , 然后退出全屏之后状态栏出来了 ,

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/31890901-5dc5e0ae-b7ca-11e7-8064-e29221f1ff89.png)

@lll-01 调试一下这两个变量，控制状态栏的显示与否
