### ISSUE TITLE
RecyclerView 不显示

### ISSUE THREAD

**Issue by chengxingen** [lipangit/JieCaoVideoPlayer#1173]
刚刚使用发现的问题， 添加 fm.jiecao:jiecaovideoplayer:5.8.1 版本依赖后， RecyclerView item 无法显示，拿掉依赖又能正常显示；
开始以为原因是项目与 library 的V7 包版本不一样，将项目中的中的recyclerview & appcompat-v7 版本都改成了25.3.1，与library 一致，但是RecyclerView依然无法显示，发现是onBindViewHolder 未被调用，能否看看是什么问题

有历史版本记录吗，我想试试之前library 未添加v7 时是否有这个问题；

**Comment by chengxingen** [comment]
现在项目中已无问题，解决办法是下载library 到项目中作为module 依赖， 将原有buildToolsVersion 版本26.0.0 改与项目一致，为25.0.3，RecyclerView 无法显示问题解决；只是目前还未想清楚 这两者之间有什么关联；

**Comment by lipangit** [comment]
项目的依赖和google发布的stable保持一致，及时更新为好
