### ISSUE TITLE
嵌套在fragment中的Listview的时候 视频进度有的正常显示，有的只会跑几秒就不动，有的完全不会动，但是拖动或者暂停开始进度可以正常显示

### ISSUE THREAD

**Issue by linmomo** [lipangit/JieCaoVideoPlayer#118]

**Comment by lipangit** [comment]
感谢你的反馈，我好像也隐隐约约有这个体会，极少的情况会出现，但是不知道他是怎么来的，没法复现，也不知道他是怎么来的

**Comment by linmomo** [comment]
我这里的情况是图片和视频混合显示在同一个iteam中，只单独显示图片或者视频，写法是仿照demo中的那个listdemo，视频来源有用户自己传的，也有来自美拍之类的，测试情况是，大部分自己拍的进度条正常，也有一些进度条不会动，或者走几秒就停止了，有时又突然可以，来源自美拍之类的视频这个概率更大一些，不过没找到什么原因，我这里这个情况很普遍的存在，如果有查询到什么原因，麻烦告知一声，谢谢。

**Comment by lipangit** [comment]
这个难道和和视频源有关系吗

**Comment by UC10D** [comment]
个人感觉是seekbar那块写法有问题，端午改改试试

**Comment by lipangit** [comment]
@UC10D 具体有啥想法吗

**Comment by UC10D** [comment]
我这边发现的问题是，进度条拖动的效果不好，时间现实也有问题，我先改下看看。

**Comment by UC10D** [comment]
seekbar 快进的操作  seekto  放 onStopTrackingTouch 里面

**Comment by lipangit** [comment]
fixed 04f5e1ffe8ec521ce789aa9fefdf21878a612517

**Comment by linmomo** [comment]
最近忙了其它的，上来才看到已经修复的样子，感谢，辛苦了

**Comment by lipangit** [comment]
^_^
