### ISSUE TITLE
如何更改当前播放状态啊！有没有属性或者是方法可以让当前视频暂停

### ISSUE THREAD

**Issue by Mezart** [lipangit/JieCaoVideoPlayer#1180]

**Comment by lipangit** [comment]
startButton.performClick() 暂停视频

**Comment by Mezart** [comment]
谢谢 您 ！那我要是有这么个需求，我要在播放页面将视频分享出去，然后分享成功后回到页面我需要继续播放，是不是我就不能把JCVideoPlayer.releaseAllVideos(); sensorManager.unregisterListene(sensorEventListener);这个方法放到onpause()里面了？

**Comment by lipangit** [comment]
对，这个逻辑要自己写了，和Home键暂停，返回继续播放是一个功能。

**Comment by Mezart** [comment]
好的 谢谢您！
