### ISSUE TITLE
横屏页面直接全屏播放，返回后变竖屏。怎么解决？

### ISSUE THREAD

**Issue by VolleyCN** [lipangit/JieCaoVideoPlayer#1193]
JCVideoPlayerStandard.startFullscreen(activity, JCVideoPlayerStandard.class, videoPath, videoName);

**Comment by VolleyCN** [comment]
已经找到，已解决。 
JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
        JCVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;

**Comment by lipangit** [comment]
好
