### ISSUE TITLE
If add drag screen to change video progress and change the volume

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#12]

**Comment by ehaahe** [comment]
支持，现在这几个功能在播放视频的时候很实用，还有个问题，就是播放过程中暗屏的问题

**Comment by lipangit** [comment]
@ehaahe 暗屏是啥症状

**Comment by ehaahe** [comment]
就是播放了一会，然后屏幕就变暗了，好像是进入了准备锁屏的状态

**Comment by lipangit** [comment]
嗯 我的手机也这样，以前没当回事 ，我研究一下。

**Comment by qiushi123** [comment]
点击全屏播放时会崩，我查看了下，是因为类库中的FullScreenActivity没有用pbulic修饰。

**Comment by lipangit** [comment]
真的吗？编译通过了吗

**Comment by lipangit** [comment]
@ehaahe 我把屏幕变暗提成个issue了，你也帮忙看看，你要是能修改给你加进来

**Comment by lipangit** [comment]
@zhangzzqq 真的，这是个大bugT_T

**Comment by lipangit** [comment]
@zhangzzqq 已经修复，多谢提醒

**Comment by lipangit** [comment]
@zhangzzqq 很奇怪呀，demo中能调，其他项目就调不了，改成public也是

**Comment by lipangit** [comment]
I found that 今日头条 can drag touch screen to seek progress in fullscreen

**Comment by lipangit** [comment]
done
