### ISSUE TITLE
当我finish当前这个activity的时候，会报错，求解救？

### ISSUE THREAD

**Issue by pokercc** [lipangit/JieCaoVideoPlayer#121]
java.lang.IllegalStateException at android.media.MediaPlayer.getCurrentPosit(native method)

**Comment by dazhiyu** [comment]
我也遇到这个错误了，你是怎么解决的？

**Comment by pokercc** [comment]
我把这个开源库其中的Mediaplay换成了一个继承自android系统的第三方的Mediaplay（一个公司开发的），然后就出现了上面的问题，我跟他们的技术沟通之后，帮我解决了

**Comment by lipangit** [comment]
我之前也遇到过java.lang.IllegalStateException at android.media.MediaPlayer.getCurrentPosit(native method)这个闪退，这个应该怎么解决呢

**Comment by pokercc** [comment]
给mediaplayer添加一个OnPreparedListener，准备完成，再进行操作，就不会报错了。
