### ISSUE TITLE
Make JCMediaPlayerListener interface public

### ISSUE THREAD

**Issue by lucaFaverio** [lipangit/JieCaoVideoPlayer#122]
Hi, 
digging around I found the need to call a JCMediaPlarListener while writing my own implementation of  JCVideoPlayer. 
At some point, I needed a call to
`JCMediaManager.instance().listener.onCompletion();`
while I can access the listener 
`JCMediaManager.instance().listener`
I cannot call the method `onCompletion()` because the Interface is package-protected. 
Since the listener is public why the interface is protected? I think it would make more sense to make the interface public too.

**Comment by lipangit** [comment]
You are right, I will make it public next version.

 I used to think that everyone should use the library as my think, but it was wrong, I should open more api for people, so that other people can solve their own problems without my design.

**Comment by lucaFaverio** [comment]
Hi lipangit,
great thank you!
Another suggestion would be to call  `JCMediaManager.instance().listener.onCompletion();` before `      JCMediaManager.instance().mediaPlayer.release();` (for example in `JCVideoPlayer.releaseAll()`) this way i can still access video information (like the current position current position)

**Comment by lipangit** [comment]
You are right, UI should always before MediaPlayer.
