### ISSUE TITLE
只要依赖这个库，环信的jni就会调用失败

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#123]
并不是因为dex分包的问题，依赖之前就已经有两个dex了

**Comment by drduan** [comment]
1

**Comment by lipangit** [comment]
Really ? 节操精选用的也是环信啊，找到原因了吗，这个库好像和jni不沾什么边

**Comment by my19941001** [comment]
好像是因为项目的问题，我在环信官方demo上依赖就没事

**Comment by lipangit** [comment]
有朋友在邮件中告诉我，这个问题可以这样解决，不知道是否管用

只需要jniLibs新建一个armeabi-v7a，把armeabi的so移到这个文件夹就可以
