### ISSUE TITLE
Continue playing after rotate 

### ISSUE THREAD

**Issue by drdla49** [lipangit/JieCaoVideoPlayer#124]
Is there any way to continnue playing video after display rotate?

When I rotate display, video must be load again from server and play from start.

Equally if I click on fullscreen button, watch, rotate phone end exit full screen I need to continue with playing, but video stop and must be load again.

Thank you for your answer.

**Comment by lipangit** [comment]
All right, generally activity can not landscape
android:screenOrientation="portrait"
The screen direction can not be changed , I will test your situaction then answer you.
