### ISSUE TITLE
JCFullScreenActivity这个activity泄漏了

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#127]
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * references fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard$3.this$0 (anonymous subclass of java.util.TimerTask)
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * references xiao.mys104.custom.JCVideoPlayerStandardShowTitleAfterFullscreen.mResources
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * references android.content.res.Resources.mContext , matching exclusion field android.content.res.Resources#mContext
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * references android.app.ContextImpl.mOuterContext
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * leaks fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity instance
06-12 15:55:56.385 5690-10785/xiao.mys104 D/LeakCanary: * Retaining: 322 KB.

**Comment by lipangit** [comment]
那个timertask是个匿名内部类，你有啥改进的想法吗

**Comment by SSOOnline** [comment]
onDestory方法中Timer clean就可以了

**Comment by lipangit** [comment]
内存泄漏的问题修改过多处了
