### ISSUE TITLE
在哪里更改音量调节 和快进快退的样式布局

### ISSUE THREAD

**Issue by ZhetengDashen** [lipangit/JieCaoVideoPlayer#131]
RT

**Comment by lipangit** [comment]
暂时改不了
你的改动大吗

**Comment by ZhetengDashen** [comment]
我只是刚开始摸索这个项目，发现找不到。其实可以预留一些属性，改变进度条、音量、快进、快退等布局的色值。布局已经非常棒了，只是用在项目中的话，每个APP的主色调都不一致。因为一个改变色值去自定义播放布局有点小题大做。您觉得呢？

**Comment by lipangit** [comment]
有道理，正在考虑如何像播放器那样完全自定义它们的ui

**Comment by lipangit** [comment]
@ZhetengDashen 已经可以自定义dialog了，dialog的ui在JCVideoPlayerStandard中，新建一个类模仿JCVideoPlayerStandard集成JCVideoPlayer修改dialog的ui
