### ISSUE TITLE
全屏切回去后,无法播放

### ISSUE THREAD

**Issue by aikongmeng** [lipangit/JieCaoVideoPlayer#133]
3.5
小屏切换到全屏,在切换回来, 视频无法播放:视频画面卡住, 点播放按钮, 不播放.

换回3.3 之后, 可以了. 但是 来回切换发现进度条进度不一致, 有点跳.

**Comment by UC10D** [comment]
是不是黑屏，有声音

**Comment by lipangit** [comment]
具体点，是demo还是你集成到别的地方

请严格参照demo的做法，继承JCVideoPlayerStandard来写自己的逻辑

**Comment by aikongmeng** [comment]
视频画面卡住, 点播放按钮, 不播放.
换回3.3 之后,  可以了.  但是  来回切换发现进度条进度不一致, 有点跳.

**Comment by aikongmeng** [comment]
@lipangit 视频画面卡住, 点播放按钮, 不播放.

**Comment by lipangit** [comment]
@aikongmeng 
用最新的版本，然后严格参照demo来做。
继承JCVideoPlayerStandard是标准的布局，大布局不能改了，可以加个按钮，隐藏个标题，这种。

如果想完全自定义UI就要继承JCVideoPlayer，这样在你的类中完全不需要写跟视频有关的代码，只需要设置各个状态的UI就可以了。
