### ISSUE TITLE
3.1版本 崩溃 java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference

### ISSUE THREAD

**Issue by dazhiyu** [lipangit/JieCaoVideoPlayer#135]
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.SurfaceView.updateWindow(SurfaceView.java:610)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5253)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
06-15 14:35:14.561 2609-2609/com.bhtc.huajuan E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by lipangit** [comment]
请用引入gradle配置文件的方式随时更新最新版本

完全参照demo的使用方法继承JCVideoPlayerStandard之后，再写自己的逻辑

**Comment by dazhiyu** [comment]
继承JCVideoPlayerStandard之后可以再改成自己想要的布局格式吗

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard是标准的布局，大布局不能改了，可以加个按钮，隐藏个标题，这种。

如果想完全自定义UI就要继承JCVideoPlayer，这样在你的类中完全不需要写跟视频有关的代码，只需要设置各个状态的UI就可以了。
