### ISSUE TITLE
无法全屏显示 一点就崩  但Activity已注册

### ISSUE THREAD

**Issue by likuihaotime** [lipangit/JieCaoVideoPlayer#136]

**Comment by lipangit** [comment]
是demo还是集成到别的地方，log发来看看

**Comment by likuihaotime** [comment]
集成本项目

**Comment by likuihaotime** [comment]
自己项目  一部分log 帮看下
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.nnnnfg/fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity}; have you declared this activity in your AndroidManifest.xml?

at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1772)

**Comment by UC10D** [comment]
没注册。。。。

**Comment by lipangit** [comment]
加油

**Comment by likuihaotime** [comment]
谢啦大神 可以了   没细看demo
