### ISSUE TITLE
三星Note5 系统Android6.0播放无声音

### ISSUE THREAD

**Issue by yangqicong11** [lipangit/JieCaoVideoPlayer#137]
使用JCVideoPlayerStandard   setup视频文件播放时在三星6.0机型上有图像无声音，但是同样代码在其他机型可以正常播放图像和声音

**Comment by lipangit** [comment]
是demo吗

你新建个helloworld项目，用最简单的代码MediaPlayer播放一下视频，试试正常吗

**Comment by yangqicong11** [comment]
是DEMO，视频源是从美拍上面下载下来的，然后除了三星NOTE5 6.0.1这个系统版本播放没声音之外，其他Android测试机都有声音，而且在三星Note5 6.0.1上用自带的播放器同样无声音

**Comment by lipangit** [comment]
这估计是别人的坑，抗着吧，不耽误发版  ^_^
