### ISSUE TITLE
Full screen to back stops video and ask me to click for video start.

### ISSUE THREAD

**Issue by shankarpilli** [lipangit/JieCaoVideoPlayer#138]
Hi, I am using this library. In that I am loading video. When video start and goto full screen it's going fine. But when i comes back it's doesn't save the state. It again ask for perform click and start from first. 

Can you please help me on this.

In the layout:
[<fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
        android:id="@+id/shareit_video"
        android:layout_width="match_parent"
        android:layout_centerInParent="true"
        android:layout_height="200dp"/>](url)

videoView.setUp(videoUrl, title);

**Comment by lipangit** [comment]
Your layout is right.

**Comment by lipangit** [comment]
You should create a class extends JCVideoPlayerStandard, put your logic in that class.

complete with reference to the demo.

**Comment by shankarpilli** [comment]
In my fragment i find 

videoView = (JCVideoPlayerStandard)view.findViewById(R.id.shareit_video)

videoView.setUp(videoUrl, title);
videoView.startButton.performClick();
videoView.requestFocus();

But still the same issue.

**Comment by lipangit** [comment]
From the information you provided didn't see what's the problem

**Comment by lipangit** [comment]
You can make a breakpoint , find out where set the state to STATE_NORMAL

**Comment by lipangit** [comment]
How is it going
