### ISSUE TITLE
listview中动态加载界面闪烁

### ISSUE THREAD

**Issue by duanxifeng** [lipangit/JieCaoVideoPlayer#139]
比如demo中的ListActivity用handler 延迟设置adapter

**Comment by lipangit** [comment]
notifiDataChange应该不会闪烁，不可以在数据改变之后new Adapter()，这样图片都会闪烁的，onCreate的时候new Adatper(),是正常的做法

**Comment by duanxifeng** [comment]
notifiDataChange 也会闪烁

**Comment by lipangit** [comment]
不会吧

**Comment by lipangit** [comment]
你的List<Object> 也不应该在数据变动的时候再new，这个本质是个指针，如果notifiDataChange的时候List的对象变了也会出现列表闪烁的情况

**Comment by lipangit** [comment]
不是这个原因吗，加我qq吧，给你研究一下

**Comment by tauren2012** [comment]
在有些手机上（nexus4 原生5.1.1系统）进入activity后，listview不马上刷出来，从网络拉取数据后再刷新，会闪屏，demo中listactivity
new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
        listView.setAdapter(new VideoListAdapter(ListActivity.this));
      }
    }, 2000);
100%重现。

**Comment by lipangit** [comment]
朋友，VideoListAdapter要在onCreate中new，你这肯定闪烁

**Comment by lipangit** [comment]
adapter和List<>本质上都是指针，一个页面只能有一个，如果中途new一个会重新刷新所有item，肯定闪烁  @tauren2012

**Comment by tauren2012** [comment]
非常感谢@lipangit的回复，可能我没表达清楚。

  protected void onCreate(Bundle savedInstanceState) {
    listView = (ListView) findViewById(R.id.listview);

    new Handler().postDelayed(new Runnable() {
      @Override
      public void run() {
        listView.setAdapter(new VideoListAdapter(ListActivity.this));
      }
    }, 2000);

  }
这样会闪烁。 实际情况举例， 当进入一个页面，需要从网络获取视频数据，
拉取到数据以后刷新listview，此时在lexus4上状态栏标题栏都会闪，在小米3上
显示正常。
protected void onCreate(Bundle savedInstanceState) {
    listView = (ListView) findViewById(R.id.listview);
    listView.setAdapter(new VideoListAdapter(ListActivity.this， videoList));
   
  }
进入activity以后videolist是empty，当拿到数据以后VideoListAdapter.notifydatasetchanged
在lexus4 一加手机上状态栏标题栏都会闪，小米3ok。
如果listview里不用JCVideoPlayerStandard，只显示一个imageview，lexus 一加，小米3
全部显示正常，状态栏标题栏不会闪。

如果onCreate以后listview中马上显示至少一个JCVideoPlayerStandard，
之后listview无论显示多少个JCVideoPlayerStandard 状态栏标题栏都不会闪。

另把listview换成recyclerview在lexus 一加上还是会闪屏，小米3ok。

**Comment by lipangit** [comment]
你把VideoListAdapter弄成一个成员变量，然后只在onCreate中new一次，并且这个页面只new这一次，其他地方notifiDataChanged，就能解决你的闪烁问题，并且一个ListView只setAdatper一次（重点）！！

**Comment by tauren2012** [comment]
谢谢@lipangit 
VideoListAdapter mVideoListAdapter;
protected void onCreate(Bundle savedInstanceState) {
listView = (ListView) findViewById(R.id.listview);
mVideoListAdapter = new VideoListAdapter(ListActivity.this，videoList)
new Handler().postDelayed(new Runnable() {
@Override
public void run() {
mVideoListAdapter.notifydatasetchanged();
}
}, 2000);

}
在小米3ok。 在lexus4 一加手机上状态栏，标题栏会闪。
把JCVideoPlayerStandard换成imageview 全部ok。

**Comment by lipangit** [comment]
可以

**Comment by tauren2012** [comment]
android设备太碎片，现在在小米3ok，但是在lexus4 一加手机上状态栏，标题栏会闪。
@lipangit  这个能给个思路解决吗？
现在listview里是空的时候我强行贴了一个
JCVideoPlayerStandard，等有数据了再重新刷listview。这样解决lexus上状态栏闪。

这个项目是github上目前最好的一个，完美支持mp4， m3u8偶尔会出状态问题，
对recyclerview支持也完美（在item onViewDetachedFromWindow的时候需要player.oncompletion一下）

**Comment by lipangit** [comment]
标题栏闪烁估计还是代码哪出了问题

**Comment by tauren2012** [comment]
@lipangit 使用demo里面的代码

VideoListAdapter mVideoListAdapter;
protected void onCreate(Bundle savedInstanceState) {
listView = (ListView) findViewById(R.id.listview);
mVideoListAdapter = new VideoListAdapter(ListActivity.this，videoList)
new Handler().postDelayed(new Runnable() {
@Override
public void run() {
mVideoListAdapter.notifydatasetchanged();
}
}, 2000);

}

在小米3上正常，但是lexus4上标题栏就闪。
如果把JCVideoPlayerStandard换成imageview，所有的机型都ok。

节操精选是在显示最新页面的时候预加载了视频fragment，不会闪。

google的代码bug多，设备又碎片，头痛。
