### ISSUE TITLE
m3u8格式无法播放

### ISSUE THREAD

**Issue by liuhuicheng** [lipangit/JieCaoVideoPlayer#140]
m3u8格式无法播放

**Comment by lipangit** [comment]
https://developer.android.com/guide/appendix/media-formats.html

这个问题估计比较复杂，我这的实际结果是直播类的播放不了，不是的直播的可以播放

**Comment by liuhuicheng** [comment]
今天测了一下 小米3可以播放，红米播放不了，不是直播，只是服务器返回的是m3u8格式的

**Comment by lipangit** [comment]
这个问题目前认为如果为了播放m3u8或者其他格式就把android.media.MediaPlayer换成其他播放引擎会引起更多麻烦，坑更深，视频格式的需求确实很硬，但觉得还是仔细研究android官网的文档，让官方的播放器能播放我们的视频是正解
