### ISSUE TITLE
无法播放

### ISSUE THREAD

**Issue by ljxmlove** [lipangit/JieCaoVideoPlayer#141]
列表显示的情况

第一次打开的时候可以正常播放  然后我点开一个缓冲的时候（还没开始播放）我滑动列表到下面的视频然后点下面的视频播放 他就没法播放了 一直在那缓冲着转圈

**Comment by lipangit** [comment]
log是什么，MediaPlayer的操作会在线程的队列中按顺序执行，你的网络通畅吗，可能会有阻塞，缓冲中点下一个视频，我以前肯定试过，应该没啥问题

**Comment by tee133377** [comment]
阿里云视频无法播放，一直在缓冲，最后缓冲完成了只是时间变了一下，视频没有播放就退出了

**Comment by lipangit** [comment]
@tee133377 你看log里的error是什么
