### ISSUE TITLE
如何设置视频列表滑动时自动播放或暂停？

### ISSUE THREAD

**Issue by shuaimango** [lipangit/JieCaoVideoPlayer#144]
详情：https://github.com/waynell/VideoListPlayer

**Comment by lipangit** [comment]
这个需求你应该把重点放到ListView的监听上，你可以参照那个项目的ListView的监听。再用代码播放视频：jcVideoPlayerStandard.startButton.performClick(); 但是可能没办法暂停，因为列表是复用的，不会记住播放进度

这个项目是单纯的视频播放，不涉及列表

**Comment by shuaimango** [comment]
谢谢  ，我已经参考videoListPlayer实现了视频列表滑动时自动播放和暂停,并且用glide缓存视频文件。你说的列表复用我同意，那么怎么设置播放时直接从上次的观看位置开始播放呢？每个item我记录progress，然后再次滑动到该item时，我就从上次的观看位置开始播放。目前修改了一些源码，弄了好久但没实现出来。给个思路，谢谢

**Comment by lipangit** [comment]
1. 如果用glide缓存视频文件那么只能是完全缓存完视频之后再播放，要么视频相当于下载了两次，对不对，我对视频缓存很感兴趣，这个可能是一种方法。

2.缓存进度可能你需要把每个视频的地址和进度对应的保存起来，可以用key value的形式，再releaseAllVideos的时候记录一次，pause的时候记录一次，播放的时候取得它seek到这个位置。

**Comment by lipangit** [comment]
如果有其他疑问再问我

**Comment by shuaimango** [comment]
如何从指定位置开始播放，具体实现方法源码能给到么。
 已有代码    JCMediaManager.instance().mediaPlayer.start();
 能提供一个JCMediaManager.instance().mediaPlayer.start(int progress);方法么

**Comment by lipangit** [comment]
@shuaimango 正在考虑是否添加这个功能的接口，但是肯定不会添加到JCVideoPlayerStandard标准中，因为头条没这功能。

如果加的话我们的视频都是没办法缓存的，从中间播放也是要先加载，具体的那几行代码还需要测试

**Comment by zzzlw** [comment]
@shuaimango 可以分享一下滑动自动播放的代码吗？
