### ISSUE TITLE
How to Keep the screen on when Fullscreen?

### ISSUE THREAD

**Issue by anhbinhvodanh** [lipangit/JieCaoVideoPlayer#147]
How to Keep the screen on when Fullscreen?
Thank.

**Comment by lipangit** [comment]
Yes this is a bug,I wiil fix it next version

**Comment by lipangit** [comment]
My phone the screen is always on, I have not found that bug , thank you your feedback.

**Comment by ehaahe** [comment]
好像mediaplayer可以设置screenOn

**Comment by anhbinhvodanh** [comment]
I just add this line in library to fix it while wait for the new version
JCFullScreenActivity.java
`getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);`

**Comment by lipangit** [comment]
@anhbinhvodanh as you suggest， fix on 3f22284
