### ISSUE TITLE
How do I change the color of the progress bar

### ISSUE THREAD

**Issue by naki35** [lipangit/JieCaoVideoPlayer#148]
1- hi. like I said, how do I change the color.
2- My mother language is Turkish and I translated the strings into Turkish, I hope you add.

    <string name="no_url">URL Bulunamadı</string>
    <string name="tips_not_wifi">Şu anda mobil veriyi kullanıyorsunuz, yüksek veri kaybına yol açabilir</string>
    <string name="tips_not_wifi_cancel">Durdur</string>
    <string name="tips_not_wifi_confirm">Devam Et</string>

**Comment by lipangit** [comment]
1.You can create a class extends JCVideoPlayerStandard , override setUp()
{
    ........
    progressBar.setBackgroud(R.drawable....);
}

2.Ok . give me a pull request is better.

**Comment by lipangit** [comment]
1.Does it work?
2.Support on 288130f1d28464a1c4ec79fdda7d046a1ef1a52e
