### ISSUE TITLE
第一次点击全屏,全屏失败并重新加载当前activity

### ISSUE THREAD

**Issue by jesse920524** [lipangit/JieCaoVideoPlayer#149]
06-24 11:45:59.451 14378-14378/ren.yinwei.android D/JieCaoVideoPlayer: toFullscreenActivity [126720964] 
06-24 11:45:59.544 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: true
06-24 11:45:59.544 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow
06-24 11:45:59.607 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:27] Constructor
06-24 11:45:59.608 14378-14378/ren.yinwei.android D/cr_Ime: [ImeAdapter.java:241] attach
06-24 11:45:59.608 14378-14378/ren.yinwei.android W/art: Attempt to remove non-JNI local reference, dumping thread
06-24 11:45:59.609 14378-14378/ren.yinwei.android W/AwContents: onDetachedFromWindow called when already detached. Ignoring
06-24 11:45:59.610 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: false

**Comment by aikongmeng** [comment]
```java
06-24 11:45:59.451 14378-14378/ren.yinwei.android D/JieCaoVideoPlayer: toFullscreenActivity [126720964] 
06-24 11:45:59.544 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: true
06-24 11:45:59.544 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:65] hideSoftInputFromWindow
06-24 11:45:59.607 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:27] Constructor
06-24 11:45:59.608 14378-14378/ren.yinwei.android D/cr_Ime: [ImeAdapter.java:241] attach
06-24 11:45:59.608 14378-14378/ren.yinwei.android W/art: Attempt to remove non-JNI local reference, dumping thread
06-24 11:45:59.609 14378-14378/ren.yinwei.android W/AwContents: onDetachedFromWindow called when already detached. Ignoring
06-24 11:45:59.610 14378-14378/ren.yinwei.android D/cr_Ime: [InputMethodManagerWrapper.java:56] isActive: false
```

**Comment by lipangit** [comment]
从log上看好像不是闪退

**Comment by jesse920524** [comment]
找到原因:JCVideoPlayerStandard在ActivityB中,
ActivityB是由ActivityA的RectclerView的Adapter启动的,所以会报错.
自己做的demo测试,如果由Activity1跳转到Activity2(持有JCVideoPlayer),则不会有问题.
目前仍在寻找解决方案

**Comment by lipangit** [comment]
加油

**Comment by wudifamo** [comment]
由谁启动的没有关系吧?我有从listview的adapter启动的activityB 全屏就没有问题.重新加载activity原因可能是有的机型旋转屏幕会导致底层的activity被销毁而重新走oncreate
解决方法可以参考这个http://blog.sina.com.cn/s/blog_783ede0301014og5.html
不知道能不能帮到你

**Comment by jesse920524** [comment]
尝试了wudifamo的方法,仍然不行,下面是activity从onResume()到我手动点击全屏按钮之间的log
机型:LG Nexus5    android版本6.0.1

06-27 10:21:32.128 2706-2706/ren.yinwei.android D/详情页onResume: 详情页onResume执行了
06-27 10:21:32.198 2706-2706/ren.yinwei.android D/cr_Ime: [ImeAdapter.java:241] attach
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: [AdapterInputConnection.java:499] finishComposingText
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: [AdapterInputConnection.java:145] Constructor called with outAttrs: inputType=0xa1 imeOptions=0x12000000 privateImeOptions=null
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: actionLabel=null actionId=0
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: initialSelStart=0 initialSelEnd=0 initialCapsMode=0x0
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: hintText=null label=null
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: packageName=ren.yinwei.android fieldId=2131492966 fieldName=null
06-27 10:21:32.269 2706-2706/ren.yinwei.android D/cr_Ime: extras=null
06-27 10:21:32.434 2706-3130/ren.yinwei.android E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
06-27 10:21:32.559 2706-2706/ren.yinwei.android W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 2706
06-27 10:21:34.669 2706-2706/ren.yinwei.android D/JieCaoVideoPlayer: prepareVideo [207757216] 
06-27 10:21:34.669 2706-2706/ren.yinwei.android I/JieCaoVideoPlayer: addSurfaceView [207757216] 
06-27 10:21:34.699 2706-3113/ren.yinwei.android W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
06-27 10:21:34.704 2706-3113/ren.yinwei.android W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
06-27 10:21:35.981 2706-3113/ren.yinwei.android D/MediaPlayer: setSubtitleAnchor in MediaPlayer
06-27 10:21:36.322 2706-2859/ren.yinwei.android W/MediaPlayer: info/warning (3, 0)
06-27 10:21:36.335 2706-2706/ren.yinwei.android I/JieCaoVideoPlayer: onInfo what - 3 extra - 0
06-27 10:21:37.376 2706-2706/ren.yinwei.android D/JieCaoVideoPlayer: toFullscreenActivity [207757216] 
06-27 10:21:37.391 2706-2706/ren.yinwei.android D/详情页onPause: 详情页onPause执行了
06-27 10:21:37.652 2706-2706/ren.yinwei.android I/JieCaoVideoPlayer: addSurfaceView [206335913] 
06-27 10:21:37.808 2706-2706/ren.yinwei.android I/JieCaoVideoPlayer: releaseAllVideos
06-27 10:21:37.814 2706-2706/ren.yinwei.android I/JieCaoVideoPlayer: finishFullscreenActivity [206335913]

**Comment by jesse920524** [comment]
反馈:
    根据我的测试,点击button全屏功能会在:Android6.0.1的两台设备上(Nexus5, 小米4)上造成:
    首先finish掉FullscreenActivity,然后finish掉包含fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard控件的Activity,后重新创建包含fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard的Activity.
重新创建fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard的Activity后,如果再次点击全屏button,则可以正常全屏显示,不会再出现bug了.

    另外两台测试机型分别为:锤子T1(Android版本4.4.2)和天语手机K-Touch T99(Android版本4.2.2)
   
虽然目前我有很多问题需要面对,还是要先感谢JieCaoVideoPlayer作者的开源精神.
另外有个小小的请求,如果可以,请帮忙在6.0环境下测试,ActivityA的RecyclerView的Adapter通过Intent启动ActivityB,ActivityB中JieCaoVideoPlayer能否全屏.

**Comment by wudifamo** [comment]
我按你的要求写了个demo.HTC X9u Android6.0 下跑没有任何问题

**Comment by jesse920524** [comment]
@wudifamo 
目前我只能这样解决了:
 jcVideoPlayerStandard = (JCVideoPlayerStandard)findViewById(R.id.vv_article_details_myvideo);
        jcVideoPlayerStandard.setUp(testUrl, "冰封王座");
        jcVideoPlayerStandard.setVisibility(View.VISIBLE);
        JCFullScreenActivity.startActivity(ArticleDetailsActivity.this, testUrl, JCVideoPlayerStandard.class, "我全屏了!!");
即打开持有jcVideoPlayerStandard控件的Activity,自动调用全屏方法,就不会出现第一次手动全屏activity销毁了.
另外谢谢你,你很Cool.

**Comment by lipangit** [comment]
@jesse920524 恭喜，把问题解决才是最关键的
