### ISSUE TITLE
3.6全屏后切回竖屏,画面卡住,进度条和声音还在继续 (自己解决了)

### ISSUE THREAD

**Issue by wudifamo** [lipangit/JieCaoVideoPlayer#152]
旧版本没有这个问题,更新了3.6后出现的.而且我自己新建一个demo则没有这个问题,在我之前用的项目里直接更新就出现这个问题了.而且我在我现在的项目里新建一个和demo一样的activity,也会出现这个问题.
若我debug测试哪里state_normal了,应该在哪里设置breakpoint?

**Comment by wudifamo** [comment]
06-24 15:18:58.872: D/JieCaoVideoPlayer(17489): quitFullscreen [61385752] 
06-24 15:18:58.873: I/JieCaoVideoPlayer(17489): quitFullScreenGoToNormal [61385752] 
06-24 15:18:58.881: I/JieCaoVideoPlayer(17489): finishFullscreenActivity [61385752] 
06-24 15:18:58.924: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129410 had no ops on it (ever) at the point it was freed
06-24 15:18:58.924: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129410 ref=0
06-24 15:18:58.924: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129411 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129411 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129412 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129412 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129413 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129413 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129414 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129414 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129415 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129415 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129416 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129416 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129417 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129417 ref=0
06-24 15:18:58.925: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129418 had no ops on it (ever) at the point it was freed
06-24 15:18:58.925: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129418 ref=0
06-24 15:18:58.926: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129420 had no ops on it (ever) at the point it was freed
06-24 15:18:58.926: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129420 ref=0
06-24 15:18:58.926: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129421 had no ops on it (ever) at the point it was freed
06-24 15:18:58.926: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129421 ref=0
06-24 15:18:58.926: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129422 had no ops on it (ever) at the point it was freed
06-24 15:18:58.926: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129422 ref=0
06-24 15:18:58.926: E/IMGSRV(17489): :0: DeferFreeCallback: WARNING: Buffer ID=6129426 had no ops on it (ever) at the point it was freed
06-24 15:18:58.926: D/IMGSRV(17489): gralloc_unregister_buffer:1440: ID=6129426 ref=0
06-24 15:18:58.928: I/BufferQueueProducer(17489): [SurfaceTexture-0-17489-8](this:0xac96e9c8,id:8,api:3,p:479,c:17489) connect(P): api=3 producer=(479:???) producerControlledByApp=true


这个是点击结束全屏时的LOG

**Comment by wudifamo** [comment]
传回来的状态是CURRENT_STATE_PLAYING
按钮显示是暂停键

**Comment by wudifamo** [comment]
解决了....
在JCVideoPlayer的onBackFullscreen中加入addSurfaceView();
如下
 @Override
  public void onBackFullscreen() {
    mCurrentState = JCMediaManager.instance().lastState;
    addSurfaceView();
    setStateAndUi(mCurrentState);
  }

确实修复了这个问题,但不知道是否是合理的解决方案..

**Comment by lipangit** [comment]
你那如果这么做能解决你的问题当然没问题

但是，从竖屏进到全屏的时候，原来的Textureview是不销毁的，所以回来的时候会直接用已经有的Textureview，不需要重新add。。难道有什么情况让它销毁了吗

**Comment by wudifamo** [comment]
销毁的动作要在哪里breakpoint?

**Comment by wudifamo** [comment]
我在toFullscreenActivity的地方断点貌似没有什么异常,难道是内存机制不一样?

**Comment by wudifamo** [comment]
我能否通过什么方法判断原来的Textureview是否被销毁呢,如果再某些机型并没有被销毁,而重复addSurfaceView会有问题么?

**Comment by lipangit** [comment]
不会，在addSurfaceView的时候回把原来的删除

**Comment by lipangit** [comment]
解决了就关了哦
