### ISSUE TITLE
当视频地址是错误的时候，或者网络加载异常的时候，高概率闪退

### ISSUE THREAD

**Issue by axeon** [lipangit/JieCaoVideoPlayer#153]
当视频地址是错误的时候，或者网络加载异常的时候，高概率闪退

**Comment by lipangit** [comment]
上log，这么描述没用。

**Comment by wudifamo** [comment]
我也遇到这个问题,当时定位崩溃出现在JCMediaManager 108行附近,如下
case HANDLER_SETDISPLAY:
				if (msg.obj == null) {
					instance().mediaPlayer.setSurface(null);
				} else {
					Surface holder = (Surface) msg.obj;
					if (holder.isValid()) {
						try {
							instance().mediaPlayer.setSurface(holder);
						} catch (Exception e) {
							// TODO: handle exception
							e.printStackTrace();
						}
					}
				}
				break;
出错的就是try里面那一行
try cath是我加上的,只是为了避免崩溃的问题,但是还是没有解决视频地址错误的提示信息.正常应该是变成叹号图标的吧.
axeon  能不能提供一个错误的视频地址,我那天出错的地址今天怎么测都正常了....而且如果故意写错一个地址也不会出现上述问题...

**Comment by axeon** [comment]
现在手头木有环境了。。。
你可以把地址随便指向一个网页地址看看

**Comment by lipangit** [comment]
fixed on a27c2aa  

你试试，之前状态判断有问题
