### ISSUE TITLE
升级之后出现了一个小问题：有时候缓存已经完成了，但是原型进度条，并不会消失

### ISSUE THREAD

**Issue by pokercc** [lipangit/JieCaoVideoPlayer#154]
升级之后出现了一个小问题：有时候缓存已经完成了，但是圆形进度条，并不会消失，进度的文字的时间是00:00,几分钟都不会消失

**Comment by lipangit** [comment]
看了你发来的视频，可能状态判断有问题，每个状态的ui修改也有点问题
