### ISSUE TITLE
需求需要竖屏全屏，结果只有横屏的

### ISSUE THREAD

**Issue by dazhiyu** [lipangit/JieCaoVideoPlayer#157]
本来自己想单独在项目中写一个竖屏全屏的activity，但有很多属性是protected，只能导入源文件改了

**Comment by lipangit** [comment]
能说说具体的竖屏的全屏的需求吗，进度条在下面很短是不是很难看，其他的控件需要吗

**Comment by dazhiyu** [comment]
我的页面是自定义的，直接继承的jcVideoPlayer

**Comment by lipangit** [comment]
Good luck

过几天准备demo里加几个完全自定义的例子
