### ISSUE TITLE
直接全屏设置占位图怎么设置

### ISSUE THREAD

**Issue by aikongmeng** [lipangit/JieCaoVideoPlayer#158]
>  JCFullScreenActivity.startActivity(this,
                        "http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4",
                        JCVideoPlayerStandard.class, "嫂子真牛逼");

这样使用 coverImageView怎么设置呢?
为什么不直接将缩略图设置成coverImageView
(主要为解决加载时黑屏的问题)

**Comment by lipangit** [comment]
首先加载的时候好像所有的视频APP都不显示缩略图，这个库是高仿头条，所以也没那样做

如果不多一个cover就需要设置缩略图imageview的颜色，多加一个coverImageView只需要控制它的visible就好，方便

**Comment by aikongmeng** [comment]
后来想想, 加载时黑屏也没什么不好. 😄 . Tks.
