### ISSUE TITLE
播放结束后 不会显示缩略图 直接是黑屏了 能不能直接设置呢

### ISSUE THREAD

**Issue by daobao** [lipangit/JieCaoVideoPlayer#161]

**Comment by lipangit** [comment]
看JCvideoPlayer开头的log是什么，打下断点，onComplete方法进去了吗，setStateNormal了吗

过几天应该把log做的更细点

**Comment by daobao** [comment]
没有看到这个方法 不过走了CURRENT_STATE_AUTO_COMPLETE 

但是 没有初始化

**Comment by daobao** [comment]
还有就是宽屏播放回来 会黑屏 操作也进行不了

**Comment by daobao** [comment]
是版本的原因 我用的是fresco 这个版本你没更新 我将demo的替换了就OK了

**Comment by lipangit** [comment]
哦对，得想一个一劳永逸的办法，每次让frecso的也跟着更新

**Comment by mastergyp** [comment]
碰到一样的问题了 com.facebook.fresco:fresco:0.11.0 也是放完黑屏。

**Comment by wcbcslg** [comment]
试试google的glide了，我用的Glide，没有问题

**Comment by lipangit** [comment]
因为fresco那个videoplayer那个类相当于定制的ui，没跟着更新，需要对比JCVideoPlayer一下把最近的修改补上来
