### ISSUE TITLE
能不能记录播放进度

### ISSUE THREAD

**Issue by lvtanxi** [lipangit/JieCaoVideoPlayer#163]
像很多播放器那样能不能对同一个资源记录播放位置或者我自己记录播放位置没，下次播放的时候我直接从记录的位置的地方直接播放。这个不知道有木有

**Comment by lipangit** [comment]
可以有！！

这个库使用像头条那样播放个3、5分钟小视频那种，如果要记录播放进度的话肯能是播放电视剧这种了

**Comment by zabio** [comment]
或者说把进度接口暴露出来 让开发者记录

**Comment by lipangit** [comment]
你可以继承JCVideoPlayerStandard，然后在你自己的类中复写父类的方法能得到各种状态，然后记录和操作，变量都是开放的，你可以试试
