### ISSUE TITLE
全屏失败

### ISSUE THREAD

**Issue by renhui** [lipangit/JieCaoVideoPlayer#164]
在天语手机（4.1.2）上面测试的时候，发现全屏会出现播放失败的问题。

06-29 15:32:28.409: E/MediaPlayer(1534): Mediaserver died in 16 state
06-29 15:32:29.409: E/MediaPlayer(1534): Attempt to call getDuration without a valid mediaplayer
06-29 15:32:29.409: E/MediaPlayer(1534): error (-38, 0)
06-29 15:32:29.409: E/MediaPlayer(1534): Attempt to call getDuration without a valid mediaplayer
06-29 15:32:29.419: E/MediaPlayer(1534): Error (100,0)
06-29 15:32:29.419: E/MediaPlayer(1534): Error (-38,0)
06-29 15:32:29.419: E/MediaPlayer(1534): error (-38, 0)
06-29 15:32:29.419: E/MediaPlayer(1534): Attempt to call getDuration without a valid mediaplayer
06-29 15:32:29.419: E/MediaPlayer(1534): Error (-38,0)
06-29 15:32:29.419: E/MediaPlayer(1534): error (-38, 0)
06-29 15:32:29.419: E/MediaPlayer(1534): Attempt to call getDuration without a valid mediaplayer
06-29 15:32:29.419: E/MediaPlayer(1534): Error (-38,0)
06-29 15:32:29.419: E/MediaPlayer(1534): error (-38, 0)
06-29 15:32:29.419: E/MediaPlayer(1534): Attempt to call getDuration without a valid mediaplayer
06-29 15:32:29.419: E/MediaPlayer(1534): Error (-38,0)
06-29 15:32:29.419: E/MediaPlayer(1534): error (-38, 0)
06-29 15:32:29.419: E/MediaPlayer(1534): Error (-38,0)
06-29 15:32:29.439: E/JieCaoVideoPlayer(1534): onError 100 - 0 [1096752664] 
06-29 15:32:29.449: E/JieCaoVideoPlayer(1534): onError -38 - 0 [1096752664] 
06-29 15:32:29.449: E/JieCaoVideoPlayer(1534): onError -38 - 0 [1096752664] 
06-29 15:32:29.449: E/JieCaoVideoPlayer(1534): onError -38 - 0 [1096752664] 
06-29 15:32:29.449: E/JieCaoVideoPlayer(1534): onError -38 - 0 [1096752664] 
06-29 15:32:29.449: E/JieCaoVideoPlayer(1534): onError -38 - 0 [1096752664]

**Comment by lipangit** [comment]
是demo播放就不正常吗
