### ISSUE TITLE
在RecyclerView.Adapter子类当中使用无法正常播放

### ISSUE THREAD

**Issue by zhew117** [lipangit/JieCaoVideoPlayer#165]
06-29 15:29:24.524 1947-5260/cn.ahurls.news E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present

06-29 15:29:25.114 1947-5260/cn.ahurls.news E/MediaPlayer: Should have subtitle controller already set

**Comment by ttym** [comment]
我也是这个问题，其他机型都正常，但是唯独三星的手机不能正常播放

**Comment by lipangit** [comment]
T_T，三星怎么这么奇葩

**Comment by wsychina** [comment]
我也是这个问题

**Comment by ttym** [comment]
用VideoView就没这个问题，目前已经用VideoView+自定义controlBar的形式实现了。

**Comment by foolchen** [comment]
三星哪个手机又问题啊?我这试了两个三星的发现没啥问题

**Comment by lipangit** [comment]
相信已经解决了
