### ISSUE TITLE
无法直接打开全屏播放, intent 需要FLAG_ACTIVITY_NEW_TASK

### ISSUE THREAD

**Issue by zhew117** [lipangit/JieCaoVideoPlayer#167]
JCFullScreenActivity.startActivity(AppContext.getAppContext(),"11",
                            JCVideoPlayerStandard.class,
                            "test");

这行代码报
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                                   
intent 是startActivity里面 new 出的,如何设置 FLAG?

**Comment by lipangit** [comment]
你应该用activity的context
