### ISSUE TITLE
能否全屏切换时不跳转到一个新的Activity

### ISSUE THREAD

**Issue by wcbcslg** [lipangit/JieCaoVideoPlayer#168]
我看今日头条全屏切换时，应该是把视频播放控件拿出来，然后盖在当前页面上面，感觉它应该是  通过FrameLayout decor = (FrameLayout) getWindow().getDecorView();拿到根布局，然后将控件添加到decor根布局里面，实现全屏 @lipangit

**Comment by lipangit** [comment]
非常重要的情报，我一会试试这个layout能添加布局吗，你测试过吗

但是我之前的测试如果surfaceview从一个布局remove，surfaceview就会destory，addview的时候surfaceview会重新生成。

我反汇编的结果觉得头条的全屏就是横屏，然后重新布局所有控件，把播放器控件设置成屏幕一样大。

**Comment by wcbcslg** [comment]
@lipangit 我下午刚试过，在你的demo上，我用这种做法是可以实现今日头条的全屏的效果，不过播放会有点问题，不过我对你用surfaceview实现播放的做法不是太了解，你 可以试试，但是这种思路是可以实现全屏切换时无缝对接的，

**Comment by lipangit** [comment]
我能看看代码吗，能看看效果吗，建个分支吧push上来看看吧，给你加到开发者了

**Comment by wcbcslg** [comment]
好的，我明天整理一下弄上来 @lipangit

**Comment by lipangit** [comment]
期待

**Comment by wcbcslg** [comment]
demo发你微信了，github分支push代码不太熟悉，之前没用过 @lipangit

**Comment by EnhaoWu** [comment]
我在做listview里面播放视频然后全屏的时候，实现方式也是先remove掉listview里面的视频播放控件，然后再add到根部局，来实现全屏。但是这样有问题，remove的时候surfaceview就会destory，这样就在视频暂停的时候切换全屏，整个屏幕就会黑了。我想问下 @wcbcslg 你是怎么解决的然后实现今日头条的效果？能请教下吗
另外想问下 @lipangit ，我看在跳转到JCFullScreenActivity的时候，也会走onSurfaceTextureDestroyed这个回调，那在暂停视频的状态下，为什么也会保留暂停时候的那一帧图像，而不是变黑呢？

**Comment by lipangit** [comment]
@EnhaoWu 会在暂停的时候seekTo(position)，这时候会把图像显示出来，这个适配不好，有的机型仍然是黑的，正在研究新的全屏方式，敬请期待

**Comment by lipangit** [comment]
我觉得头条的全屏是横屏，重新布局所有控件。  因为在Methods Profiling中没找到surfaceView的destroy和create，所以认为头条没removeView和addView

**Comment by lipangit** [comment]
但是我们作为一个第三方的library，用getParent的方式操作其他控件这个难度太大，我觉得addView的方式还是可行的
