### ISSUE TITLE
视频地址不可用时会崩溃

### ISSUE THREAD

**Issue by wudifamo** [lipangit/JieCaoVideoPlayer#169]
今天终于抓到这个BUG的LOG了

07-01 10:58:38.147: E/AndroidRuntime(1406): java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
07-01 10:58:38.147: E/AndroidRuntime(1406): 	at android.media.MediaMetadataRetriever.native_finalize(Native Method)
07-01 10:58:38.147: E/AndroidRuntime(1406): 	at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:321)
07-01 10:58:38.147: E/AndroidRuntime(1406): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
07-01 10:58:38.147: E/AndroidRuntime(1406): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
07-01 10:58:38.147: E/AndroidRuntime(1406): 	at java.lang.Thread.run(Thread.java:841)
07-01 10:58:38.223: I/JieCaoVideoPlayer(1406): releaseAllVideos
07-01 10:58:44.735: D/dalvikvm(1406): GC_FOR_ALLOC freed 377K, 13% free 49313K/56044K, paused 21ms, total 21ms
07-01 10:58:44.735: E/MediaPlayer(1406): error (-38, 0)
07-01 10:58:44.763: D/dalvikvm(1406): GC_FOR_ALLOC freed 849K, 14% free 49815K/57400K, paused 19ms, total 19ms
07-01 10:58:44.779: D/dalvikvm(1406): GC_FOR_ALLOC freed <1K, 13% free 50715K/57852K, paused 12ms, total 12ms
07-01 10:58:44.779: W/MediaPlayer(1406): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-01 10:58:44.779: E/MediaPlayer(1406): prepareAsync called in state 0
07-01 10:58:44.779: W/System.err(1406): java.lang.IllegalStateException
07-01 10:58:44.779: W/System.err(1406): 	at android.media.MediaPlayer.prepareAsync(Native Method)
07-01 10:58:44.779: W/System.err(1406): 	at fm.jiecao.jiecaovideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:91)
07-01 10:58:44.779: W/System.err(1406): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-01 10:58:44.779: W/System.err(1406): 	at android.os.Looper.loop(Looper.java:136)
07-01 10:58:44.779: W/System.err(1406): 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-01 10:58:44.779: W/MediaPlayer(1406): setScreenOnWhilePlaying(true) is ineffective for Surface
07-01 10:58:44.779: E/BufferQueue(1406): [unnamed-1406-0] connect: BufferQueue has been abandoned!
07-01 10:58:44.779: W/MediaPlayer(1406): mediaplayer went away with unhandled events

**Comment by lipangit** [comment]
你的是什么机型，前两天我特意测试过错误的视频地址，没爆出exception闪退，而是回调了onError函数，在我的小米note3上进入了STATE_ERROR状态

**Comment by wudifamo** [comment]
我这全部机型都有这个问题,小米HTC 地址有点特殊,有时能播有时不能播
http://us.sinaimg.cn/004p97rBjx072yHcGbUY01040100dEXe0k01.mp4?KID=unistore,video&Expires=1466998246&ssig=J2a%2B0QvBWs
