### ISSUE TITLE
listview列表页播放视频时，切换全屏时为什么不能再当前页面的onPause()方法中调用JCVideoPlayer.releaseAllVideos();

### ISSUE THREAD

**Issue by wcbcslg** [lipangit/JieCaoVideoPlayer#170]
项目中有需求，屏幕熄屏停止播放，所以我得在onPause()方法中调用JCVideoPlayer.releaseAllVideos();，但是这样会导致我进行全屏操作时，进入全屏时会恢复到初始暂停状态，大概什么原因 @lipangit

**Comment by lipangit** [comment]
你用的什么版本，但是一直都不应该有这个问题，demo就有问题吗？

**Comment by lipangit** [comment]
现在试试吧，应该没这问题了
