### ISSUE TITLE
如何做到边下边播

### ISSUE THREAD

**Issue by tanranran** [lipangit/JieCaoVideoPlayer#171]
RT ，播放完，下次播放就不需要下载了。

**Comment by lipangit** [comment]
还不知道怎么做，google官方的代码没有这个接口，也取得不到视频的字节流

但是我注意到优酷的android客户端是缓存的，不知道怎么做的

**Comment by lipangit** [comment]
你有啥想法吗

**Comment by lipangit** [comment]
不知道怎么做缓存

**Comment by tanranran** [comment]
据我所知有两种方法,一种是不用原生的播放,用第三方的例如vitamio,另外一种就是走代理的方式,可以参考这个,https://github.com/danikula/AndroidVideoCache,
