### ISSUE TITLE
实现嵌套Listview里面时候 ,当item不可见的时候可以暂停播放

### ISSUE THREAD

**Issue by wcbcslg** [lipangit/JieCaoVideoPlayer#172]
在项目中遇到一个需求就是当listview滑动的时候，item不可见的时候可以暂停播放。
我的实现方法就是监听listview 的 OnScrollListener方法，然后通过mListview.getFirstVisiblePosition()和mListview.getLastVisiblePosition()获取当前的屏幕的上下可见的边界值，然后与我们自己的正在播放的position进行比较 ，当position < firstVisiblePosition  ||  position > lastVisiblePosition 时，我们调用	JCVideoPlayer.releaseAllVideos()停止播放，下面贴出我实现的关键代码
```

mListview.setOnScrollListener(new OnScrollListener() {
			@Override
			public void onScrollStateChanged(AbsListView arg0, int arg1) {

			}
			
			@Override
			public void onScroll(AbsListView view, int firstVisibleItem,
					int visibleItemCount, int totalItemCount) {
				int firstVisiblePosition = mListview.getFirstVisiblePosition();
				int lastVisiblePosition = mListview.getLastVisiblePosition();
				if ((indexPostion < firstVisiblePosition  || indexPostion >lastVisiblePosition) && isPlaying ) {
					indexPostion = -1;
					isPlaying = false;
					JCVideoPlayer.releaseAllVideos();
				}
			}
		});

```
每次点击播放时给indexPostion 重新赋值

**Comment by lipangit** [comment]
目前的计划是头条没有功能都不添加到JCVideoPlayerStandard中

这个我一会调试一下 如果没问题  给它加到demo里让其他去参考

**Comment by lipangit** [comment]
暂时不支持暂停播放

**Comment by Little-Huang** [comment]
@wcbcslg   遇到了同样的问题  请问一下你的这个indexPostion  是怎麽拿到的呢   作者的播放点击事件是在JCVideoPlayer中做的处理   貌似没有提供获取当前的播放位置  Thanks ！

**Comment by Little-Huang** [comment]
@lipangit   你好 现在也遇到了这个问题  然后因为项目包体积的显示  我们不准备集成ijkplayer  我们现在用的还是3.6.3版本  请问这个版本目前有啥简单点的方法解决这个问题呢

**Comment by lipangit** [comment]
@Little-Huang 不支持列表滑动暂停功能，正在开发列表滑动进入小窗继续播放，替代暂停

**Comment by Little-Huang** [comment]
@lipangit   Sorry , 可能是我没表诉清楚  其实我是想问这个异常的解决办法：

java.lang.IllegalStateException
at android.media.MediaPlayer._setVideoSurface(Native Method)
at android.media.MediaPlayer.setSurface(MediaPlayer.java:805)
at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
这个问题以前确实会有，在setDisplay的时候Textureview被销毁了，还不知道是什么原因，但是4.*版本自己就好了

**Comment by Little-Huang** [comment]
@lipangit   如果真不行的话  只能升到4.x了,   Thanks !
