### ISSUE TITLE
android 4.4.4红米note无法播放，错误提示

### ISSUE THREAD

**Issue by rophie123** [lipangit/JieCaoVideoPlayer#174]
07-04 12:17:50.122 13691-13691/net.hfnzz.www.hcb_assistant I/Timeline: Timeline: Activity_launch_request time:74243235
                                                                       
                                                                       --------- beginning of /dev/log/system
07-04 12:17:50.292 13691-13691/net.hfnzz.www.hcb_assistant D/-1-1: Camera2016-07-04#$@%!*getCameraDetail
07-04 12:17:50.292 13691-13691/net.hfnzz.www.hcb_assistant D/-1-1: 278f5598414314175e110830614205a6
07-04 12:17:50.412 13691-13691/net.hfnzz.www.hcb_assistant E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
07-04 12:17:50.412 13691-13691/net.hfnzz.www.hcb_assistant D/JieCaoVideoPlayer: prepareVideo [1129786624] 
07-04 12:17:50.412 13691-13691/net.hfnzz.www.hcb_assistant I/JieCaoVideoPlayer: addSurfaceView [1129786624] 
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant E/MediaPlayer: error (-38, 0)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant E/MediaPlayer: prepareAsync called in state 0
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err: java.lang.IllegalStateException
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:87)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-04 12:17:50.422 13691-16419/net.hfnzz.www.hcb_assistant E/MediaPlayer: Error (-38,0)
07-04 12:17:50.452 13691-13691/net.hfnzz.www.hcb_assistant E/JieCaoVideoPlayer: onError -38 - 0 [1129786624] 
07-04 12:17:50.462 13691-13691/net.hfnzz.www.hcb_assistant I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@43528730 time:74243582
07-04 12:17:50.802 13691-16419/net.hfnzz.www.hcb_assistant W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

**Comment by rophie123** [comment]
播放的是hls网络直播地址

**Comment by lipangit** [comment]
系统的MediaPlayer对hls等格式支持不好，已经换成ijkplayer，包大了不少
