### ISSUE TITLE
乐视 乐1上点击进入全屏后无法播放 黑屏

### ISSUE THREAD

**Issue by wangyi1993** [lipangit/JieCaoVideoPlayer#178]

**Comment by lipangit** [comment]
发下log，是不是退出全屏又正常了

**Comment by wangyi1993** [comment]
日志没有报错 我下载了你们的app发现有个别视频也有这种情况
就是在列表中点击进入全屏 进度条再走但是是黑屏退出后 列表中也是黑屏 手机是乐视乐1

**Comment by wangyi1993** [comment]
我想是不是和视频很短有关系  因为你们app出问题的那个视频只有9s 我的测试的有问题的也都是很短的视频

**Comment by lipangit** [comment]
这和视频长短应该没关系

1.我们app哪个视频有黑屏的情况，视频名字是什么？
2.这可能是逻辑问题，不报错，你用“JieCaoVideoPlayer”过滤一下log，发来看看，很有可能全屏的时候Textureview没初始化

**Comment by wangyi1993** [comment]
我发现真的是视频的原因  我用你们demo里面的url播放 完全没问题 然后我用下面的url替换你们demo中的url重新编译后发现也出现了同样的问题  视频是趣拍录制的
视频链接 http://test.pfmrw.cn/upload/video/20160707/557073331537507247.mp4
