### ISSUE TITLE
Overriding FullScreenActivity

### ISSUE THREAD

**Issue by ugurcany** [lipangit/jiecaovideoplayer#18]
Hi, I wanna use my own FullScreenActivity to be able to apply my custom fonts using Calligraphy. Is there any chance to set my FullScreenActivity by providing a setter method inside JCVideoPlayer class?

**Comment by lipangit** [comment]
Maybe this is a demand，if you eager to achieve this feature you can fork the project then modify it .
And I am thinking about if we can edit the interface from outside of the library,I used to think that no one needs to modify the interface.

**Comment by lipangit** [comment]
Will add costom ui .
