### ISSUE TITLE
get duration and current possition

### ISSUE THREAD

**Issue by Hitexroid** [lipangit/JieCaoVideoPlayer#182]
hi , thank you for this helpful library

how can i get current possition and duration in moment

**Comment by lipangit** [comment]
JCMediaManager.instance().mediaPlayer.getDuration()

JCMediaManager.instance().mediaPlayer.getCurrentPosition()

**Comment by Hitexroid** [comment]
it needs to prepare ? or not 
`JC.prepare(url, headData, loop);`
