### ISSUE TITLE
如何更改全屏时的布局 增加输入框功能

### ISSUE THREAD

**Issue by callmecaoye** [lipangit/JieCaoVideoPlayer#1837]
竖屏NORMAL时 是垂直布局 上边是播放器 下边是输入框
设置了JZVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
如何在横屏全屏时 显示输入框并改为水平布局？谢谢！

**Comment by sosa-sang** [comment]
我是想重写一下全屏模式的方法 让播放器的宽度不是MATCH_PARENT
或者我如何通过代码旋转整个播放器 达到横屏的效果？

**Comment by lipangit** [comment]
么么哒
