### ISSUE TITLE
problem with JCMediaPlayerListener

### ISSUE THREAD

**Issue by Hitexroid** [lipangit/JieCaoVideoPlayer#185]
Hi , i want to use Listeners , but that's not working

`		listener = new JCMediaPlayerListener() {
			
			@Override
			public void onVideoSizeChanged() {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void onSeekComplete() {
				Toast.makeText(getContext(), "onSeekComplete", 3000).show();
			}
			
			@Override
			public void onPrepared() {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void onInfo(int what, int extra) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void onError(int what, int extra) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void onCompletion() {
				Toast.makeText(getContext(), "Completed", 3000).show();
			}
			
			@Override
			public void onBufferingUpdate(int percent) {
				
			}
			
			@Override
			public void onBackFullscreen() {
				Toast.makeText(getContext(), "onBackFullscreen", 3000).show();
			}
			
			@Override
			public void onAutoCompletion() {
				// TODO Auto-generated method stub
				
			}
		};`

**Comment by lipangit** [comment]
You maybe forget setListener.

**Comment by Hitexroid** [comment]
how should i setListener  :( ?

**Comment by lipangit** [comment]
See demo MainActivity 

JCVideoPlayerStandard.setJcBuriedPointStandard(jcBuriedPointStandard);
