### ISSUE TITLE
为React Native封装播放器插件，不能正常播放

### ISSUE THREAD

**Issue by 86yankai** [lipangit/JieCaoVideoPlayer#188]
我在为React Native封装播放器插件后，只有声音，没有图像；

调试发现，onSurfaceTextureAvailable事件不会被触发，不知道什么原因。

**Comment by lipangit** [comment]
我也一直在关注跨平台开发的技术

你看后台的log，有没有addTextureView，onSurfaceTextureAvailable

**Comment by lipangit** [comment]
我感觉只要将Textureview addView到布局中，并且是可见的就会调用onSurfaceTextureAvailable，ReactNative调用应该没问题

**Comment by 86yankai** [comment]
执行addTextureView，并且JCResizeTextureView被添加到textureViewContainer中，但是JCResizeTextureView的onMeasure没有被调用，可能需要通知Player需要重新Layout？
日志：
 I/JieCaoVideoPlayer: onClick start [241783733] 
 D/JieCaoVideoPlayer: prepareVideo [241783733] 
 D/JieCaoVideoPlayer: addTextureView [241783733] 
 D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
 D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END

**Comment by lipangit** [comment]
702 你这是三星还是华为

**Comment by lipangit** [comment]
加油

**Comment by 86yankai** [comment]
知道问题了，requestLayout在RN下不工作导致TextureView没有重新Layout。需要修改源码了。。

**Comment by lipangit** [comment]
有什么发现别管有没有用都分享出来吧

**Comment by xiongzhongguo** [comment]
请问是怎么解决的，我也遇到了。

**Comment by gordonpro** [comment]
遇到了一样的问题。确实是 onMeasure没有调用
React Native 中用 ViewPager之前也遇到过类似问题，坑真多。

我现在解决方案比较简单，`比较另类仅供参考`。
在点击播放按钮之后，在RN里面调用一下修改 state 去强制刷新View, 画面就出来了

比如我现在用宽度做到 state 里面，假如一台手机宽度是360。

```
 this.state = { video_width: 360, ... }
```

```
<JZVideoView
                style={{ width: this.state.video_width, height: 200 }}
                video_url={this.state.video_url}
            />
```

然后点击播放之后，setState 把宽度-1，然后再改回来
```
this.setState({ video_width: 359 });
setTimeout(()=>{
     this.setState({ video_width: 360 })
}, 1)
```

**Comment by bozaigao** [comment]
@gordonpro 谢谢，你解决了困扰我很久的一个问题

**Comment by ldy441040480** [comment]
我之前也遇到这个问题，解决方案是给RN提供的视频控件重写以下方法。

    @Override
    public void onPrepared() {
        super.onPrepared();
        requestLayout();
    }

    private final Runnable mLayoutRunnable = new Runnable() {
        @Override
        public void run() {
            measure(MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
                    MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
            layout(getLeft(), getTop(), getRight(), getBottom());
        }
    };

    @Override
    public void requestLayout() {
        super.requestLayout();
        post(mLayoutRunnable);
    }
