### ISSUE TITLE
使用Fresco 方式加载图片，点击全屏播放，滑动不显示进度条

### ISSUE THREAD

**Issue by imliujun** [lipangit/JieCaoVideoPlayer#189]
在demo中 点击OTHER LOAD IMAGE LIBRARY 然后点击Fresco加载图片的视频进行全屏播放。
滑动不显示进度条和音量的布局

**Comment by lipangit** [comment]
那个类相当于完全定制UI的类，这次版本更新一下，感谢你的反馈
