### ISSUE TITLE
Bottom red progress bar

### ISSUE THREAD

**Issue by shiv71** [lipangit/JieCaoVideoPlayer#1908]
How to hide bottom red progress bar when video play.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/40819413-87634aac-658d-11e8-904a-077c5c041006.png)

 change the progressbar in every state

**Comment by shiv71** [comment]
I am using cn.jzvd.JZVideoPlayerStandard in recycleview  so how can do that. How to change the progressbar in every state

**Comment by lipangit** [comment]
GL
