### ISSUE TITLE
切换至全屏播放时卡顿问题？

### ISSUE THREAD

**Issue by yeerik** [lipangit/JieCaoVideoPlayer#193]
从非全屏切换至全屏播放，是不是新建了播放器，这样重新加载数据，怎么做到无卡顿播放

**Comment by lipangit** [comment]
并没有新建播放器，setDisplay的时候就会卡顿，正在研究新的全屏方式，敬请期待

**Comment by yeerik** [comment]
暂未看具体实现代码，，可以做到不同aci之间共享一个播放器么？
