### ISSUE TITLE
这周可能没办法发新版本。This weekend maybe can not release a new version。

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#196]
最近这段时间所有的探索和努力都是为了让视频在切换全屏的时候能连续播放，过程非常曲折，尽管目的可以达到，但是会引起其他方面的问题。

1.在使用了ijkplayer之后，mediaPlayer.setSurface(surface)的时候视频是连续的，解决了我们的首要问题，但是此时视频的缓存进度取得有问题，seekTo(position)有明显延迟。

2.在使用其他app的时候发现，视频头条和腾讯的天天快报这两个app都有小窗口播放功能，这个我相信他们解决了mediaPlayer.setSurface(surface)时候的视频连续的问题，反汇编的时候发现他们用的也是系统的android.media.MediaPlayer，不知道怎么做的。

Translate：

Recently this period of time all exploration and efforts is to make video in full screen switch can play continuously, the process is very tortuous, despite the purpose can be achieved, but can cause other problems.

1. After using the ijkplayer, mediaPlayer setSurface (surface) video is continuous, solved the problems of our primary, this video is a problem with the cache progress achieved, however, seekTo (position) have significant delay.

2. When using other apps found that 视频头条 and Tencent‘s天天快报 these two app has a small window function, this I believe. They solved the mediaPlayer setSurface (surface) when video continuous problems, the disassembly to find they use is also a system of android. Media. The mediaPlayer, don't know how to do it.

**Comment by lipangit** [comment]
发现视频头条 用的是精简版的ijkplayer，它取得缓存的进度也有问题，经常播放进度超过缓存进度，经常缓存的进度就不动了

**Comment by anhbinhvodanh** [comment]
Have you tried to use this https://github.com/google/ExoPlayer for your library?
And please makes a changelog for new version @@ thank

**Comment by lyzzbhoneyline** [comment]
Keep going, you will catch the truing meaning. :D

**Comment by lipangit** [comment]
@anhbinhvodanh this is  [log](https://github.com/lipangit/JieCaoVideoPlayer/releases) .

I will try.

**Comment by lipangit** [comment]
@lyzzbhoneyline thank you, I will do my best.
