### ISSUE TITLE
Error occurred while playing hls for android 4.4.4

### ISSUE THREAD

**Issue by lyzzbhoneyline** [lipangit/JieCaoVideoPlayer#197]
Log details:
07-11 00:50:23.145 12237-12237/com.test.testvideo D/JieCaoVideoPlayer: addTextureView [1256994252] 
07-11 00:50:23.145 12237-12237/com.test.testvideo I/JieCaoVideoPlayer: onClick start [1256994252] 
07-11 00:50:23.145 12237-12237/com.test.testvideo W/DebugConnManager: getNetworkInfo() on networkType 1
07-11 00:50:23.145 12237-12237/com.test.testvideo D/JieCaoVideoPlayer: prepareVideo [1256994252] 
07-11 00:50:23.145 12237-12237/com.test.testvideo D/JieCaoVideoPlayer: addTextureView [1256994252] 
07-11 00:50:23.181 12237-12767/com.test.testvideo E/MediaPlayer: error (-38, 0)
07-11 00:50:23.181 12237-12767/com.test.testvideo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-11 00:50:23.185 12237-12767/com.test.testvideo E/MediaPlayer: prepareAsync called in state 0
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err: java.lang.IllegalStateException
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:87)
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err:     at android.os.Looper.loop(Looper.java:136)
07-11 00:50:23.185 12237-12767/com.test.testvideo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 00:50:23.189 12237-12767/com.test.testvideo E/MediaPlayer: Error (-38,0)
07-11 00:50:23.205 12237-12237/com.test.testvideo E/JieCaoVideoPlayer: onError -38 - 0 [1256994252] 
07-11 00:50:23.329 12237-12237/com.test.testvideo W/EGL_emulation: eglSurfaceAttrib not implemented
07-11 00:50:23.341 12237-12237/com.test.testvideo I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1256994252] 
07-11 00:50:23.345 12237-12767/com.test.testvideo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface

Is there a way to solve? Thx : D

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/16720442/01346770-4769-11e6-95b5-73cc9114509c.png)

As test result before error code is -38 will not have effect on play video , so ignore -38.

android.media.MediaPlayer support not good on live stream.

**Comment by lyzzbhoneyline** [comment]
I've saw this part of code in your project. 
Android 6+ could play hls well without any errors.
Android 5+ could play hls well without any errors as well.
Android 4+ presents a loading state and display nothing whatever how long you wait, then I check the Android Monitor and found the errors "prepareAsync called in state 0....prepareAsync called in state 0....Error (-38,0)" .

**Comment by lipangit** [comment]
I think this problem caused by android system. This library should not do redundant work to solved the problem, and I do not know how to do to fix the problem.

**Comment by lyzzbhoneyline** [comment]
Alright, thx a lot.:D hava a nice day.

**Comment by wangxusky** [comment]
comment "mediaPlayer.setLooping(((FuckBean) msg.obj).looping);" in JCMediaManager may help, but error occurred while switching textureview

**Comment by lyzzbhoneyline** [comment]
I used ijk for a long time before, but I prefer to use vitamio.
