### ISSUE TITLE
通过旋转手机横屏时播放器横屏全屏展示

### ISSUE THREAD

**Issue by kaiyuanshengshichangan** [lipangit/JieCaoVideoPlayer#198]
通过重力感应旋转手机，界面横屏，但是播放器没有全屏，因为在你封装的里面点击全屏是跳转到一个新的Activity，所以就出现了不一样的情况，如何处理呢

**Comment by lipangit** [comment]
感应重力的功能跳转全屏是个好需求，下个版本会加进来，感谢你的反馈

**Comment by lipangit** [comment]
这个常识做了，但是细想还是很复杂，以后会继续做

**Comment by lipangit** [comment]
新版已经加入此功能
