### ISSUE TITLE
您好，问下如果说想做秒拍的那种可以拖拽的视频播放功能该从哪里下手

### ISSUE THREAD

**Issue by taany6210** [lipangit/JieCaoVideoPlayer#199]
我试了下，activity用的是一个自定义的拖拽控件，然后在adapter里面根部局用cardView ，然后再加上一个线性布局，JCVideoPlayerStandard和一个textview视频名称，然后视频播放有声音没画面，视频区域不能拖拽，只能拖拽下面的视频名称位置。大哥，指教下。

**Comment by lipangit** [comment]
没理解你说的拖拽是啥意思，不知道秒拍拖拽是什么样子，进群吧，发个小视频
