### ISSUE TITLE
Video format?

### ISSUE THREAD

**Issue by borjaruiz** [lipangit/jiecaovideoplayer#20]
Hi, which video format supports?
I see the url is a mp4, but does it support .flv, .mkv, .m4v?... 

Thanks.

**Comment by lipangit** [comment]
This library use android.media.MediaPlayer play videos,maybe support other video support.
Because this library work for company project,so we should upload  only one video format  to make our work simple.

I will test other video format to make the library better .

**Comment by lipangit** [comment]
android.media.MediaPlayer support many video fromat
See http://developer.android.com/guide/appendix/media-formats.html.
But I can not found flv in that page.

**Comment by lipangit** [comment]
And I try flv video,Just have voice but no image

**Comment by borjaruiz** [comment]
Thanks for your reply.
