### ISSUE TITLE
能加个竖屏手势控制就好了！

### ISSUE THREAD

**Issue by HzwSunshine** [lipangit/JieCaoVideoPlayer#201]

**Comment by lipangit** [comment]
竖屏手势是什么，有现成的效果吗

**Comment by HzwSunshine** [comment]
跟横屏手势一样。暴露一个方法，让开发者选择是否启用

**Comment by lipangit** [comment]
横屏手势是啥，进群吧，发个小视频看看长什么样

**Comment by wudifamo** [comment]
他的意思是竖屏状态下也可以左右滑动快进,上下修改音量

**Comment by lipangit** [comment]
已经添加

**Comment by Generalize** [comment]
竖屏手势怎么开启

**Comment by lipangit** [comment]
复写ontouch函数&nbsp; 不屏蔽竖屏的if



---原始邮件---
发件人: "Generalize"<notifications@github.com&gt;
发送时间: 2020年4月25日(周六) 晚上6:42
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 能加个竖屏手势控制就好了！ (#201)




 
竖屏手势怎么开启
