### ISSUE TITLE
为什么会生成2个图标？  

### ISSUE THREAD

**Issue by s162738** [lipangit/JieCaoVideoPlayer#202]
安装后有个JCVD图标， 然后点击某个视频后就会出现一个 Leaks 的图标，这是为何？
还有右边上划一般是控制声音，左边上划是控制亮度，希望大神可以改进。
第一个问题比较急。

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/179

**Comment by s162738** [comment]
还有，在安卓巴士上看到这个源码，也是用ijkplayer做的。大神也可以适当加入哦。很有用

**Comment by lipangit** [comment]
声音和亮度的问题，由于这个库是高仿今日头条，它没加，这里也没加，你可以自己复写onTouch方法监听。

**Comment by lipangit** [comment]
最近发现头条的视频好像没什么更新了，是不是可以换一个目标学习了

**Comment by lipangit** [comment]
什么情况，那个issue也是你提的@s162738

**Comment by s162738** [comment]
ijkplayer 库不是bilibili的吗

**Comment by s162738** [comment]
哦。可能上次提的给忘记看了@lipangit

**Comment by s162738** [comment]
我看了很多别人的源码，就觉得你这个非常实用。我想把它加入到自己的项目中。想要模仿做一个类似 内涵段子 这样的播放软件。 所以很关注你的项目，嘿嘿

**Comment by lipangit** [comment]
还是很初级很容易的
