### ISSUE TITLE
每次更新版本解决了什么问题从哪里可以看到？

### ISSUE THREAD

**Issue by liujinchaoDS** [lipangit/JieCaoVideoPlayer#204]
版本更新挺快的，就是不知道每次更新了些什么？是否需要升级？哪里可以看到吗？

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/16761813/70e9ab02-4854-11e6-8262-3744afb35876.png)
点击这里

如果你是按照官方推荐的使用方法，不主动修改库里的内容，每次升级只需要修改gradle中的配置

**Comment by liujinchaoDS** [comment]
谢谢！很棒！
