### ISSUE TITLE
3.6.3还是经常timeout

### ISSUE THREAD

**Issue by wudifamo** [lipangit/JieCaoVideoPlayer#205]
07-13 17:56:56.651: E/AndroidRuntime(4722): java.util.concurrent.TimeoutException: android.media.MediaMetadataRetriever.finalize() timed out after 10 seconds
07-13 17:56:56.651: E/AndroidRuntime(4722): 	at android.media.MediaMetadataRetriever.native_finalize(Native Method)
07-13 17:56:56.651: E/AndroidRuntime(4722): 	at android.media.MediaMetadataRetriever.finalize(MediaMetadataRetriever.java:321)
07-13 17:56:56.651: E/AndroidRuntime(4722): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
07-13 17:56:56.651: E/AndroidRuntime(4722): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
07-13 17:56:56.651: E/AndroidRuntime(4722): 	at java.lang.Thread.run(Thread.java:841)
怎么解

**Comment by lipangit** [comment]
timeout ... 确认网络没问题吗

**Comment by wudifamo** [comment]
网络没问题,视频地址可能有问题,这个出现就崩溃,应该在哪处理一下

**Comment by lipangit** [comment]
onError有错误的回调
