### ISSUE TITLE
Start video from specified time in msec

### ISSUE THREAD

**Issue by bkhezry** [lipangit/JieCaoVideoPlayer#206]
`JCMediaManager.instance().mediaPlayer.seekTo(60*1000);` not work. 
Video should be started and after that this code work.
how can I start video from specified time with start activity without need start video manually?

**Comment by lipangit** [comment]
next version contain this function， JCVideoPlayerStandard.seekToInAdvance = 10000;
can solve you problem, every sunday release a new version.

**Comment by lipangit** [comment]
done in  4.0_beta
