### ISSUE TITLE
在listview 或者你的demo 中列表  播放界面 基本全部出了屏幕  但是还是在播放

### ISSUE THREAD

**Issue by anjiao** [lipangit/JieCaoVideoPlayer#207]
RT

**Comment by lipangit** [comment]
item复用的时候才会停止，如果是多种类型的holder都在一个列表里，还要判断如果非视频的holder复用了视频的holder也要让视频停止，demo里有

**Comment by anjiao** [comment]
我拖动进度条 好像那个时间 显示有点问题

**Comment by anjiao** [comment]
demo 中好像也有这个问题！

**Comment by lipangit** [comment]
来个截图看看

**Comment by anjiao** [comment]
就是 有时候 拖动 然后前面显示进度的时间一直是 00:00 而且还在播放    ， 还有就是  比如我想全屏显示 但是我不用你的 那个 full activity  而是在一个 acitivity 全局中有一个布局   小屏幕播放 我 addview 进来这个 view   ，当我点击全屏的时候  我直接 remove  然后再  add 到全屏的那个view  但是 这样会出现 error  就是 播放点击放大或者缩小 会有那个 错误的图片在播放中间

**Comment by anjiao** [comment]
图片 （还有我想问问 你们的交流群是？）
![screenshot_20160715-092333](https://cloud.githubusercontent.com/assets/6157486/16860814/00177442-4a6e-11e6-85cd-f8fd52845961.png)

**Comment by lipangit** [comment]
这个库的初衷是3、5行代码就让app集成播放器功能，你这种大改库可能要辛苦调试一番了

**Comment by anjiao** [comment]
刚才上面说的 demo 中 比如我拖动进度条 然后  还在播放 但是时间是 00:00

![screenshot_20160715-101642](https://cloud.githubusercontent.com/assets/6157486/16861999/aa0a74fe-4a78-11e6-9dee-8a4f619d5797.png)

**Comment by anjiao** [comment]
你们的讨论交流群是 我很想和大家一起交流交流 能否麻烦告知？

**Comment by lipangit** [comment]
首页就有490442439
