### ISSUE TITLE
Crash after going back from fullscreen

### ISSUE THREAD

**Issue by Maragues** [lipangit/JieCaoVideoPlayer#209]
Steps I'm following
1. Have a JCVideoPlayerStandard with fixed size inside a custom ViewGroup
2. Invoke player.setup("video url")
2. Press play
3. Press full screen button
4. Go back, either with back key or with back arrow

The app crashes

```
java.lang.NullPointerException: Attempt to invoke interface method 'void fm.jiecao.jcvideoplayer_lib.JCMediaManager$JCMediaPlayerListener.onBackFullscreen()' on a null object reference 
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.quitFullScreenGoToNormal(JCVideoPlayer.java:708)
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.backFullscreen(JCVideoPlayer.java:731)
at fm.jiecao.jcvideoplayer_lib.JCFullScreenActivity.onBackPressed(JCFullScreenActivity.java:99)
```

If I use *JCFullScreenActivity.startActivity(getContext(), "...", JCVideoPlayerStandard.class, "");*, everything works fine

Sorry if it's a duplicated bug, unfortunately I don't understand chinese :(

**Comment by lipangit** [comment]
Your steps is right, It should not crash.

Whitch variable is null?  JCMediaManager.instance().lastListener?

**Comment by Maragues** [comment]
It's this line

```
JCMediaManager.instance().listener.onBackFullscreen();
```

**Comment by lipangit** [comment]
JCMediaManager.instance().listener   is null?

**Comment by Maragues** [comment]
Yes, that's where it's crashing.

As I said, the player is contained in a custom ViewGroup, maybe that's related?

**Comment by lipangit** [comment]
If this problem is still , open this again
