### ISSUE TITLE
进入全屏和退出全屏是又回到原来的初始播放位置（版本3.6.3）

### ISSUE THREAD

**Issue by stevenMieMie** [lipangit/JieCaoVideoPlayer#210]
你好，当我进入全屏或退出全屏时播放进度又会回到原来的初始位置，我已经在在onPause里调用了JCVideoPlayer.releaseAllVideos()方法

**Comment by lipangit** [comment]
还在播放吗

**Comment by stevenMieMie** [comment]
进入全屏的时候会自动播放（从头开始），退出全屏会进度条回到0等待播放的位置。

**Comment by lipangit** [comment]
切换全屏播放进度的跑偏问题4.0解决了，就是包有点大
