### ISSUE TITLE
seekbar的问题

### ISSUE THREAD

**Issue by ZzjBeatYou** [lipangit/JieCaoVideoPlayer#211]
拉底部的seekbar时，加载后视频继续播放了但loadview没有消失，并且再次拉seekbar没作用、左边的时间也变成00:00了。看了下log。出现这种情况的时候 MEDIA_INFO_BUFFERING_START打印了两遍，而MEDIA_INFO_BUFFERING_END只打印了一遍

**Comment by onlyoneyanyan** [comment]
@Override
    protected void setProgressAndTime(int progress, int secProgress, int currentTime, int totalTime) {
        super.setProgressAndTime(progress, secProgress, currentTime, totalTime);
        if (progress != 0) bottomProgressBar.setProgress(progress);
        if (secProgress != 0) bottomProgressBar.setSecondaryProgress(secProgress);
    }
估计这块代码 有些问题

**Comment by lipangit** [comment]
进群吧 发个小视频看看
