### ISSUE TITLE
中文文档中有一处错误

### ISSUE THREAD

**Issue by xhw035** [lipangit/JieCaoVideoPlayer#213]
`<fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard            
    android:id="@+id/custom_videoplayer_standard"
    android:layout_width="match_parent"
    android:lay3.6.3out_height="200dp"/>`

这个中文readme.md文档的布局文件中， android:layout_height写成了 android:lay3.6.3out_height，结果直接把你的代码贴过来误导人啊。

**Comment by lipangit** [comment]
改
