### ISSUE TITLE
文档又处一错，误导人要命啊

### ISSUE THREAD

**Issue by xhw035** [lipangit/JieCaoVideoPlayer#214]
`jcVideoPlayerStandard.thumbImageView.setThumbInCustomProject("http://p.qpic.cn/videoyun/0/2449_43b6f696980311e59ed467f22794e792_1/640")`

文档中的这个方法在项目报错啊，后来下源码才发现这个方法根本没有，demo中都是这么写的
`ImageLoader.getInstance().displayImage("http://p.qpic.cn/videoyun/0/2449_bfbbfa3cea8f11e5aac3db03cda99974_1/640", jcVideoPlayerStandard.thumbImageView);`

       这文档真是要命，是代码更新了文档没有更新吧

**Comment by lipangit** [comment]
根据不同项目的图片管理库，有多种方法设置缩略图
