### ISSUE TITLE
拖动进度条幅度过大，不能实现快进播放

### ISSUE THREAD

**Issue by xhw035** [lipangit/JieCaoVideoPlayer#215]
拖动进度条幅度过大，不能实现快进播放，而且页面一直出现加载图标，但是视频还是正常播放，这个bug待修复。

**Comment by lipangit** [comment]
进群吧，发个小视频看看，目前没发现有这个问题

**Comment by SicmiYang** [comment]
@xhw035 解决了么，我也出现相同的问题

**Comment by lipangit** [comment]
请用新版

**Comment by abc20899** [comment]
mSeekTimePosition = (int) (mGestureDownPosition + deltaX * totalTimeDuration / (mScreenWidth * 4));
