### ISSUE TITLE
全屏播放时播放错误的bug

### ISSUE THREAD

**Issue by Yellup** [lipangit/JieCaoVideoPlayer#218]
调用全屏播放当播放发生错误时，点击再次播放，全屏Activity退出
具体问题出在这里：
protected void prepareVideo() {
        ...
        if (JCMediaManager.instance().listener() != null) {
            JCMediaManager.instance().listener().onCompletion();
        }
        ...
}
另外，4.0beta版添加了ijkplayer（使用了部分，为解决一些问题），导致了APK体积的增大，所以想向您请教下，在引入ijkplayer后，与直接使用ijkplayer（我没用过）相比，JieCaoVideoPlayer的优势体现在哪些方面（界面修改？功能性？使用难度？），望不吝赐教，谢谢

**Comment by lipangit** [comment]
这个开源库的目的是3、5行代码让app集成视频播放功能
集成ijkplayer的目的   1.全屏切换的时候视频是连续的，为小窗播放做准备。  2.更好的支持更多视频格式，hls居多
我觉得只能让时间去慢慢抚慰APK体积变大的伤痛，时间长了习惯就好了

播放错误的问题如果你不大改库，应该没什么问题，如果还有问题的话请加群，发个小视频看看效果

**Comment by Yellup** [comment]
感谢您的解答，目前来看，体积的增加还可接受的范围内，希望未来播放器能够越做越好！
另，全屏播放发生错误时（比如设置无效视频链接），点击重新播放会让activity退出，是一个必现的bug，发生在
protected void prepareVideo() {
...
if (JCMediaManager.instance().listener() != null) {
JCMediaManager.instance().listener().onCompletion();
}
...
}
里回调
public void onCompletion() {
...
        finishFullscreenActivity();
...
}
中，会关闭activity，应该可以检查下播放状态
if (JCMediaManager.instance().listener() != null && mCurrentState != CURRENT_STATE_ERROR) {
            JCMediaManager.instance().listener().onCompletion();
 }
不知是否正确

**Comment by lipangit** [comment]
解决了就好
