### ISSUE TITLE
项目目录raw下视频不能播放，并且崩溃

### ISSUE THREAD

**Issue by zzhopen** [lipangit/JieCaoVideoPlayer#220]
String  path =  "android.resource://" + getPackageName() +"/"+ R.raw.shiwai;
JCFullScreenActivity.startActivity(this,path,JCVideoPlayerStandard.class,title);

**Comment by jiaruiz** [comment]
+1

**Comment by lipangit** [comment]
assert下的视频请先复制到sd卡再播放
