### ISSUE TITLE
录音和播放录音时 视频无法播放返回状态0  急急急 

### ISSUE THREAD

**Issue by Cemetery159** [lipangit/JieCaoVideoPlayer#2200]
**需求描述
配音功能，录音的时候要同步播放视频，视频静音。但一点录音，视频就返回state=0 求解决方案
**其他app是否实现
比如“爱乐奇”的配音功能
**截图或者小视频说明

**Comment by lipangit** [comment]
视频就返回state=0    这是什么意思

**Comment by Cemetery159** [comment]
> 视频就返回state=0 这是什么意思

在播放视频的时候，开始录音的话，视频当前状态变为CURRENT_STATE_NORMAL，
AudioManager.OnAudioFocusChangeListener 这个状态能不能变一下，达到录音不影响视频的播放的效果
