### ISSUE TITLE
当videoplay在listview滑出屏幕时还在继续播放，当我重新将这个条目滑回到可见区域时才可以停止播放

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#222]
我运用场景是一个多布局listview，除了视频还有音频，图像，这里我只使用了一个videoplay

**Comment by my19941001** [comment]
同样是刚刚的场景，不过我放了两个videoplay，当其中一个正在播放，我滑动到另一个videoplay进入屏幕时，上一个正在播放的才会停止，有什么解决办法吗？

**Comment by lipangit** [comment]
请看demo中的MutiHolderActivity，你需要在列表复用的时候你需要在非视频holder复用了视频holder的时候release掉上一个视频

**Comment by my19941001** [comment]
@lipangit 谢谢，我看见了这行代码

**Comment by dongshixiong** [comment]
当你的播放的View没有被复用的时候，是不会被停止的，可以尝试监听ListView的滚动事件，Item不可见时主动停止播放
