### ISSUE TITLE
在切换到全屏再切换到原来的界面，很卡，

### ISSUE THREAD

**Issue by hyr0318** [lipangit/JieCaoVideoPlayer#225]
切换到原来的界面要卡几秒才回到原来的界面。这是是和全屏模式是一个activity的原因么？切换到全屏可以更换成旋转屏幕和更改屏幕的尺寸的这种方式么？

**Comment by lipangit** [comment]
更改屏幕的尺寸的这种不好做，这里是第三方库，修改父项目的控件大小非常困难。

卡的问题demo应该不卡吧，不要修改library里的东西
