### ISSUE TITLE
在三星手机上，有些视频播放没有声音

### ISSUE THREAD

**Issue by itlws** [lipangit/JieCaoVideoPlayer#226]
在三星手机上，有些视频播放没有声音
测试机：三星note4，三星s7
视频链接：http://7xv5f7.com2.z0.glb.qiniucdn.com/vd_1fe79df1c0b4775d59a88609d9cd6b0f6de7948205989b6b82a0d7e372b6fc22

**Comment by lipangit** [comment]
Sorry，我也不知道怎么办
