### ISSUE TITLE
怎么播放网络视频,比如优酷腾讯视频

### ISSUE THREAD

**Issue by dasamanren** [lipangit/JieCaoVideoPlayer#227]
http://player.youku.com/player.php/sid/XMTU4MTY4OTg5Mg==/v.swf,比如这个视频,我设置之后,提示说播放地址无效
![image](https://cloud.githubusercontent.com/assets/6468888/17012470/8d71d914-4f4a-11e6-9b27-3d7a462ed0a8.png)
如果我不需要缩小全屏时也继续播放这个功能,是不是我能选择低一点的版本使用,如果可以,那版本是多少

**Comment by lipangit** [comment]
这种地址我感觉好像都播放不了，有能播放的demo吗。

**Comment by dasamanren** [comment]
之前用的是video++,能解析播放,那有什么办法能让我播放腾讯和优酷视频吗?比如说优酷视频,视频链接在这里获得
![image](https://cloud.githubusercontent.com/assets/6468888/17018357/f508c582-4f69-11e6-81bf-ebb16c384464.png)

**Comment by lipangit** [comment]
不能直接在手机播放吧，这些好像都是flash，视频网站都是故意不让别人播放的

**Comment by dasamanren** [comment]
也就是说只能用WebView来播放啦?有没有转换的方式,将flash转成mp4文件

**Comment by lipangit** [comment]
我相信应该有，但是我不知道怎么做
