### ISSUE TITLE
能否设置播放速度

### ISSUE THREAD

**Issue by canqihe** [lipangit/JieCaoVideoPlayer#230]
比如慢放 快放啥的

**Comment by lipangit** [comment]
不知道怎么设置，有思路吗

**Comment by yangwuan55** [comment]
同问

**Comment by lipangit** [comment]
同答  ^_^

**Comment by yangwuan55** [comment]
@lipangit  。。。不知道你还答。。。

**Comment by yangwuan55** [comment]
看错了 原来你是作者。。。。

**Comment by lipangit** [comment]
@yangwuan55 有demo吗，确实不知道怎么做

 这个不会加到JCVideoPlayerStandard中当做标准，但给大家提供接口还是合理的

**Comment by yangwuan55** [comment]
@lipangit 这个是可以的，我现在在寻找方法。目前的了解是android6.0以上是自带api的，6.0一下需要自己实现一个播放器，利用ffmpeg，vlc等。由于vlc基于gpl协议所以不敢乱用，ffmpeg得是专业人士去搞。
