### ISSUE TITLE
ArithmeticException: divide by zero;3.6.3崩溃,复现步骤未知.

### ISSUE THREAD

**Issue by somatezyc** [lipangit/JieCaoVideoPlayer#234]
07-29 20:24:15.463 E/AndroidRuntime( 2234): FATAL EXCEPTION: main
07-29 20:24:15.463 E/AndroidRuntime( 2234): Process: com.guangquaner, PID: 2234
07-29 20:24:15.463 E/AndroidRuntime( 2234): java.lang.ArithmeticException: divide by zero
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.showProgressDialog(JCVideoPlayerStandard.java:424)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onTouch(JCVideoPlayer.java:407)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onTouch(JCVideoPlayerStandard.java:148)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.View.dispatchTouchEvent(View.java:9987)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2828)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2499)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
07-29 20:24:15.463 E/AndroidRuntime( 2234): 	at android.view.View.dispatchPointerEvent(View.java:10228)

**Comment by lipangit** [comment]
应该是手势操作的时候的问题，需要判断一下

**Comment by somatezyc** [comment]
汗,这"稳定版"太狠了,刚介入崩溃咔咔的多.

**Comment by lipangit** [comment]
divide by zero 问题修复了
