### ISSUE TITLE
我想在自己定义的activity中全屏播放,并且可以左右滑动快进,我要怎么做

### ISSUE THREAD

**Issue by liuhui19991** [lipangit/JieCaoVideoPlayer#240]
因为我要在activity中上传视频播放进度,我直接用了fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard进去,可以实现全屏播放,但是不能实现滑动快进

**Comment by lipangit** [comment]
demo中有例子，可以复写一些父类的方法来写你自己的逻辑，不用自定义全屏的activity

**Comment by dongshixiong** [comment]
全屏的逻辑其实就是给MediaPlayer设置了另外一个显示控件
知道这个其实你想干什么都行

**Comment by liuhui19991** [comment]
@dongshixiong   我要在activity中做进度记录

**Comment by lipangit** [comment]
view中getContext也可以记录吧

**Comment by lipangit** [comment]
已经完成此功能
