### ISSUE TITLE
请问，Android 播放本地视频加上了吗？

### ISSUE THREAD

**Issue by cywmm** [lipangit/JieCaoVideoPlayer#241]

**Comment by lipangit** [comment]
播放assert目录下的好像播放不了，因为参数要file，播放本地路径的视频可以播放。

你可以先把它copy到本地路径播放。

**Comment by Jetereting** [comment]
播放本地路径的视频怎么写路径？
jcVideoPlayerStandard.setUp(Environment.getExternalStorageDirectory()
                        .getPath() + "/1.swf", "嫂子想我没");
我这样写的 报的E/IJKMEDIA: /storage/emulated/0/1.swf: Invalid data found when processing input
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
E/JieCaoVideoPlayer: onError -10000 - 0 [1108558776]

**Comment by lipangit** [comment]
https://www.google.nl/?gws_rd=cr&ei=gRmaV6KhKcTZaZH3qrAJ#q=mediaplayer+sdcard+file

**Comment by Jetereting** [comment]
对不起，jcVideoPlayerStandard.setUp(“https://www.google.nl/?gws_rd=cr&ei=gRmaV6KhKcTZaZH3qrAJ#q=mediaplayer+”+Environment.getExternalStorageDirectory()
.getPath() + "/1.swf", "嫂子想我没");是这样吗？试过不行
可以详细说下吗？

**Comment by lipangit** [comment]
那个链接是在搜索引擎上搜索你的问题，点开看看google上都有什么解决方案

**Comment by chensir000** [comment]
..
