### ISSUE TITLE
直接进入全屏失败

### ISSUE THREAD

**Issue by jesse920524** [lipangit/JieCaoVideoPlayer#242]
compile 'fm.jiecao:jiecaovideoplayer:4.1_alpha'
我的代码:
MainActivity
   case R.id.iv_listitem_type:
                        if (articleItem.getArticleType().equals("3")){
                            Toast.makeText(FirstActivity.this, "clicked type", Toast.LENGTH_SHORT).show();
                            JCFullScreenActivity.startActivity(FirstActivity.this, articleItem.getMediaUri(), JCVideoPlayerStandard.class, new Object[]{articleItem.getTitle()});
                        }
                        break;

参照了demo的代码.demo跑在我手机上没有问题,但我自己的项目就会出现进入全屏JCFullScreenActivity秒退并重新执行MainActivity的onCreate()

**Comment by jesse920524** [comment]
07-28 15:36:28.279 21033-21033/ren.yinwei.android D/JieCaoVideoPlayer: addTextureView [5111863] 
07-28 15:36:28.279 21033-21033/ren.yinwei.android I/JieCaoVideoPlayer: onClick start [5111863] 
07-28 15:36:28.280 21033-21033/ren.yinwei.android D/JieCaoVideoPlayer: prepareVideo [5111863] 
07-28 15:36:28.280 21033-21033/ren.yinwei.android D/JieCaoVideoPlayer: addTextureView [5111863] 
07-28 15:36:28.281 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_native_setup
07-28 15:36:28.282 21033-21382/ren.yinwei.android I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.0--20160715--001
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ffpipeline_create_from_android()
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_inject_opaque(0x4ca)
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_data_source(url="http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4")
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_data_source(url="http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4")=0
07-28 15:36:28.282 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-28 15:36:28.283 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setLoopCount
07-28 15:36:28.283 21033-21382/ren.yinwei.android W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-28 15:36:28.283 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_prepareAsync
07-28 15:36:28.283 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_prepare_async()
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: ===== versions =====
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.0--20160715--001
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: libavutil    : 55.27.100
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: libavcodec   : 57.48.101
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: libavformat  : 57.40.101
07-28 15:36:28.283 21033-30941/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [30941] ff_msg_loop
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: libswscale   : 4.1.100
07-28 15:36:28.283 21033-30941/ren.yinwei.android D/IJKMEDIA: message_loop
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: libswresample: 2.1.100
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: ===== options =====
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: player-opts : loop                         = 1
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: format-opts : ijkinject-opaque             = 1226
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: format-opts : ijkapplication               = -1593010400
07-28 15:36:28.283 21033-21382/ren.yinwei.android I/IJKMEDIA: ===================
07-28 15:36:28.284 21033-30941/ren.yinwei.android D/IJKMEDIA: FFP_MSG_FLUSH:
07-28 15:36:28.284 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_prepare_async()=0
07-28 15:36:28.284 21033-30942/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [30942] ff_vout
07-28 15:36:28.284 21033-30943/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [30943] ff_read
07-28 15:36:28.362 21033-21033/ren.yinwei.android D/JieCaoVideoPlayer: releaseAllVideos
07-28 15:36:28.362 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release
07-28 15:36:28.362 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-28 15:36:28.362 21033-21382/ren.yinwei.android D/IJKMEDIA: ffpipeline_set_surface()
07-28 15:36:28.362 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-28 15:36:28.362 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()
07-28 15:36:28.362 21033-30941/ren.yinwei.android D/IJKMEDIA: message_loop exit
07-28 15:36:28.362 21033-30941/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30941]
07-28 15:36:28.365 21033-21033/ren.yinwei.android D/JieCaoVideoPlayer: finishFullscreenActivity [5111863] 
07-28 15:36:28.365 21033-30942/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30942]
07-28 15:36:28.417 21033-30943/ren.yinwei.android E/IJKMEDIA: http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4: Immediate exit requested
07-28 15:36:28.417 21033-30943/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30943]
07-28 15:36:28.418 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()=void
07-28 15:36:28.418 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-28 15:36:28.418 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()
07-28 15:36:28.418 21033-21382/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()=void
07-28 15:36:28.418 21033-21382/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release

**Comment by lipangit** [comment]
哥们闪退的log没看到呀，只发现进了全屏之后马上就退出全屏了

**Comment by wbb631094818** [comment]
我的项目也出现了这个问题。全屏后播放器没打开就释放了

**Comment by lipangit** [comment]
@wbb631094818 请发log

**Comment by somatezyc** [comment]
url异常会导致闪退，你检查下。另外点击也会导致by zero错误，稳定版很不稳定。

**Comment by jesse920524** [comment]
@somatezyc 经过仔细测试,无论是从类中读取rul还是将url写死,都会导致进入全屏后马上退出全屏并重新执行activity的onCreate()

**Comment by jesse920524** [comment]
@wbb631094818 看来我们遇到了一样的问题.我的是6.0系统 google nexus5 和小米4测试均会导致上述bug

**Comment by jesse920524** [comment]
07-29 13:16:05.481 11070-11070/ren.yinwei.android D/JieCaoVideoPlayer: addTextureView [16279763] 
07-29 13:16:05.481 11070-11070/ren.yinwei.android I/JieCaoVideoPlayer: onClick start [16279763] 
07-29 13:16:05.482 11070-11070/ren.yinwei.android D/JieCaoVideoPlayer: prepareVideo [16279763] 
07-29 13:16:05.482 11070-11070/ren.yinwei.android D/JieCaoVideoPlayer: addTextureView [16279763] 
07-29 13:16:05.483 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release
07-29 13:16:05.483 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_native_setup
07-29 13:16:05.483 11070-11897/ren.yinwei.android I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.0--20160715--001
07-29 13:16:05.483 11070-11897/ren.yinwei.android D/IJKMEDIA: ffpipeline_create_from_android()
07-29 13:16:05.483 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_inject_opaque(0x2004a6)
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_inject_opaque()=void
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_data_source(url="http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4")
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_data_source(url="http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4")=0
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setOptionLong
07-29 13:16:05.484 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_setLoopCount
07-29 13:16:05.485 11070-11897/ren.yinwei.android W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-29 13:16:05.485 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_prepareAsync
07-29 13:16:05.485 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_prepare_async()
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: ===== versions =====
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.0--20160715--001
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: libavutil    : 55.27.100
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: libavcodec   : 57.48.101
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: libavformat  : 57.40.101
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: libswscale   : 4.1.100
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: libswresample: 2.1.100
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: ===== options =====
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: player-opts : loop                         = 1
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: format-opts : ijkinject-opaque             = 2098342
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: format-opts : ijkapplication               = -1699531072
07-29 13:16:05.485 11070-11897/ren.yinwei.android I/IJKMEDIA: ===================
07-29 13:16:05.486 11070-12187/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [12187] ff_msg_loop
07-29 13:16:05.486 11070-12187/ren.yinwei.android D/IJKMEDIA: message_loop
07-29 13:16:05.487 11070-12187/ren.yinwei.android D/IJKMEDIA: FFP_MSG_FLUSH:
07-29 13:16:05.490 11070-12188/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [12188] ff_vout
07-29 13:16:05.490 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_prepare_async()=0
07-29 13:16:05.491 11070-12189/ren.yinwei.android I/IJKMEDIA: SDL_RunThread: [12189] ff_read
07-29 13:16:05.568 11070-11070/ren.yinwei.android D/JieCaoVideoPlayer: releaseAllVideos
07-29 13:16:05.569 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release
07-29 13:16:05.569 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
07-29 13:16:05.569 11070-11897/ren.yinwei.android D/IJKMEDIA: ffpipeline_set_surface()
07-29 13:16:05.569 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
07-29 13:16:05.569 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()
07-29 13:16:05.569 11070-12187/ren.yinwei.android D/IJKMEDIA: message_loop exit
07-29 13:16:05.569 11070-12187/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [12187]
07-29 13:16:05.570 11070-11070/ren.yinwei.android D/JieCaoVideoPlayer: finishFullscreenActivity [16279763] 
07-29 13:16:05.571 11070-12188/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [12188]
07-29 13:16:05.601 11070-12189/ren.yinwei.android E/IJKMEDIA: http://o9rqd91ep.bkt.clouddn.com/panbaoqibingyugaopian.mp4: Immediate exit requested
07-29 13:16:05.601 11070-12189/ren.yinwei.android I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [12189]
07-29 13:16:05.602 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()=void
07-29 13:16:05.602 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_dec_ref(): ref=0
07-29 13:16:05.602 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()
07-29 13:16:05.602 11070-11897/ren.yinwei.android D/IJKMEDIA: ijkmp_shutdown_l()=void
07-29 13:16:05.602 11070-11897/ren.yinwei.android D/IJKMEDIA: IjkMediaPlayer_release

====================================================================================================================================
以上是log内容,以下是我的代码:
JCFullScreenActivity.startActivity(FirstActivity.this, articleItem.getMediaUri(), JCVideoPlayerStandard.class, articleItem.getTitle());

**Comment by lipangit** [comment]
用新版
