### ISSUE TITLE
Seek to specific position and play

### ISSUE THREAD

**Issue by ivanviragine** [lipangit/JieCaoVideoPlayer#244]
Hi!

I have a recyclerview with videos on it, and when user likes the video, recyclerview will bind the view again, so, the video will stop and start from the beginning.
That's not desirable.

So, before notifying the adapter that the data has changed (which is what happens when user likes the video, I need to update the UI and backing holder), I get the current position using "JCMediaManager.instance().mediaPlayer.getCurrentPosition()", and pass this long value to the notifyItemChanged from recyclerview as payload.
Ok, this is working fine.

So, when binding the view again, I have this payload value passed to seekTo method, using "JCMediaManager.instance().mediaPlayer.seekTo(holder.currentTime);".

This is working fine.
The problem is that, it's seeking ok, but I'm not able to start the player.
Using "JCMediaManager.instance().mediaPlayer.start();" will start from the beginning, and using "holder.contentVideo.onClick(holder.contentVideo.startButton);" will start from the beginning too.

So, my question is: how can I seek to a certain time and start playback from this point?

Thanks!

**Comment by lipangit** [comment]
jCVideoPlayerStandard.seekToInAdvance = 100

auto seek to the position when video prepared

**Comment by ivanviragine** [comment]
Thanks @lipangit!

The problem is to play the video from that position again... I see that the player seeked to the time correctly by printing the "JCMediaManager.instance().mediaPlayer.getCurrentPosition()", but, using the "JCMediaManager.instance().mediaPlayer.start();" or "holder.contentVideo.onClick(holder.contentVideo.startButton);" (where holder.contentVideo is the  jCVideoPlayer).

**Comment by lipangit** [comment]
You can also reset seekToInAdvance = -1  at a right time

**Comment by ivanviragine** [comment]
That's not the problem.

Let me try to be more clear:

Using this:

`
               jCVideoPlayerStandard.seekToInAdvance = holder.currentTime;
               jCVideoPlayerStandard.onClick(holder.contentVideo.startButton);
`

Isn't playing the video from the holder.currentTime position. I've checked the variables values, the player is really in the seek position, but once it starts, it goes back from the beginning, that is, it's not respecting my seekToInAdvance parameter.

So, I would like to know how can I start from holder.currentTime position, really.

**Comment by ivanviragine** [comment]
Hi! Any news on this? Tried adding a onSeekComplete listener and all of I could think of, nothing works.

**Comment by lipangit** [comment]
Seekbar already have a listener, you should not cover that old listener.

You should override function to listener seek complete.

**Comment by MaCls98** [comment]
> Hi! Any news on this? Tried adding a onSeekComplete listener and all of I could think of, nothing works.

Did you find a way to fix this? I'm having the same issue
