### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by xiyanglove** [lipangit/JieCaoVideoPlayer#245]
Android: 4.4.2
Manufacturer: HUAWEI
Model: X1 7.0
CrashReporter Key: 2A922CCE-F662-38C6-C9BD-30ECE75B66AF88A03888
Date: Fri Jul 29 13:15:27 GMT+08:00 2016
java.lang.IllegalStateException
at android.media.MediaPlayer._setVideoSurface(Native Method)
at android.media.MediaPlayer.setSurface(MediaPlayer.java:717)
at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:104)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lipangit** [comment]
如果是偶尔情况就先顶住吧，我们的umeng后台也有这个错误。

正在开发的新版本很有可能回避掉这个问题

**Comment by shaobin0604** [comment]
我们也遇到这个问题，目前崩溃率 4%, 绝大部分是这个。库版本 `3.6.3`

```
1 android.media.MediaPlayer._setVideoSurface(Native Method)
2 android.media.MediaPlayer.setSurface(MediaPlayer.java:723)
3 fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.void handleMessage(android.os.Message)(JCMediaManager.java:104)
4 android.os.Handler.dispatchMessage(Handler.java:102)
5 android.os.Looper.loop(Looper.java:136)
6 android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by lipangit** [comment]
本周日发一个4.*的正式版，接口不变，请及时更新

**Comment by shaobin0604** [comment]
4.x 版本是否还是使用系统的 `MediaPlayer ` ？ 我们的用户设备比较差，若是 `ijkplayer` 软解估计性能不够

**Comment by shaobin0604** [comment]
BTW, 3.x 版本的这个问题可否暴力点，将这个 exception catch 了

**Comment by lipangit** [comment]
4.X推出之后3.X就不再推荐使用了，同一个库同一个分支同一种用法比较好

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by xiyanglove** [comment]
ijkplayer兼容会不会没有MediaPlayer兼容性好,4.x已经改为ij了把?

**Comment by lipangit** [comment]
目前观察ijkplayer除了缓存进度取得有问题，seek进度延迟较大之外，别的都挺好
