### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by mvity** [lipangit/JieCaoVideoPlayer#246]
compile 'fm.jiecao:jiecaovideoplayer:4.1_alpha'

Error:Failed to resolve: tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.0
<a href="openFile:D:/GitHome/git/xInfo_Android_Native/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: tv.danmaku.ijk.media:ijkplayer-java:0.6.0
<a href="openFile:D:/GitHome/git/xInfo_Android_Native/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

怎么办

**Comment by lipangit** [comment]
是不是没下载下来，maven服务器是不是连不上

**Comment by mvity** [comment]
嗯， 找到原因， 是因为公司的nexus没有jcenter镜像，多谢
