### ISSUE TITLE
Fullscreen blank when integrated 

### ISSUE THREAD

**Issue by sridhar2392** [lipangit/JieCaoVideoPlayer#248]
I created a sample app with jcVideoPlayerStandard and it works perfectly fine both on portrait and landscape mode (on pressing expand button). But when I tried to integrate the same for the another app that I'm creating I get a black screen on pressing the video expand button but the audio is playing in the background. Couldn't get the reason why this is happening !! 

This is the code that I'm working: 
`  jcVideoPlayerStandard = JCVideoPlayerStandard)view.findViewById(R.id.custom_videoplayer_standard);
  jcVideoPlayerStandard.bringToFront();
  jcVideoPlayerStandard.setUp("http://2449.vod.myqcloud.com/2449_bfbbfa3cea8f11e5aac3db03cda99974.f20.mp4", "");
  ImageLoader.getInstance().displayImage("http://p.qpic.cn/videoyun/0/2449_bfbbfa3cea8f11e5aac3db03cda99974_1/640",jcVideoPlayerStandard.thumbImageView);
`

**Comment by lipangit** [comment]
No image on textureview?

You can break point on mediaPlayer.setDisplay(), not go over that methods will cause no image

**Comment by sridhar2392** [comment]
but when i did the same with an empty project it is working. This problem persist only when I tried to integrate it to some other app.  
problem - video does not play in fullscreen but audio does. In portrait mode it is perfectly fine,

Where would I set the breakpoint ? which file ?

**Comment by lipangit** [comment]
JCMediaManager.java search these words "instance().mediaPlayer.setSurface(holder);",
if that line went wrong  video will not play but audio is ok.

**Comment by sridhar2392** [comment]
When I set debugging to that line, I'm getting the following:
![bug](https://cloud.githubusercontent.com/assets/14996890/17283639/65df6df6-57d0-11e6-9396-90fbb6741684.png)

**Comment by lipangit** [comment]
check every activity android:hardwareAccelerated="true" in androidmanifest

**Comment by sridhar2392** [comment]
In one of the activity it is false when i made it true, the issue got resolved. Thanks a lot.
