### ISSUE TITLE
Big size videos only play some minutes

### ISSUE THREAD

**Issue by sjuniorvc89** [lipangit/JieCaoVideoPlayer#249]
i am using videos from internet , the size is arroung 1gb to 2gb , only plays some minutes the closed the video player,
is probably using a video cache? or something to dont close the videoplayer?

**Comment by lipangit** [comment]
Would you give me a url, I want to test

**Comment by sjuniorvc89** [comment]
URL : https://content-na.drive.amazonaws.com/cdproxy/templink/JwE-Cqv3gI8x68ORZ10QIfk-V6HVSra-kmP2XS6DTlkE0Xnc3?download=TRUE

others videos if conecction is lossing or low videoplayer closed
it is posible to wait some second to recconect before closing videoplayer?

**Comment by lipangit** [comment]
How is it going, is still have this problem reopen the issue
