### ISSUE TITLE
放到CollapsingToolbarLayout里报错

### ISSUE THREAD

**Issue by kingyangcn** [lipangit/JieCaoVideoPlayer#250]
放到CollapsingToolbarLayout里报错，放到其他地方没问题。
`java.lang.ClassCastException: android.support.v7.view.ContextThemeWrapper cannot be cast to android.app.Activity
                                                                       at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:281)`
小白求指教，谢谢

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/191 已经修复，下版本可用

**Comment by kingyangcn** [comment]
大神，还有点小问题。放到CollapsingToolbarLayout里报错，点击全屏的时候还会报错：
java.lang.ClassCastException: android.support.v7.view.ContextThemeWrapper cannot be cast to android.support.v7.app.AppCompatActivity

**Comment by lipangit** [comment]
你看看布局里是不是有个google兼容包的layout，叫啥名忘记了

**Comment by kingyangcn** [comment]
就是CollapsingToolbarLayout啊，还有就是v7里的Toolbar

**Comment by lipangit** [comment]
换一个layout吧

**Comment by kingyangcn** [comment]
我自己看了下源码修复了，不过希望官方的也能改一下。之前给你反馈的放到这个layout里不能播放的问题你已经修复了，你在JCUtils加了scanForActivity方法，我自己模仿着加了个scanForAppCompActivity，然后把JCVideoPlayer里相应的代码改了下就OK了（之前的问题context强转activity你有的地方没改完哦~）

**Comment by lipangit** [comment]
来个pr吧，库也改进一下
