### ISSUE TITLE
Cant play video

### ISSUE THREAD

**Issue by mittalharsh54** [lipangit/JieCaoVideoPlayer#252]
Error in playing videoes
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

I am trying to play this 
https://firebasestorage.googleapis.com/v0/b/boiling-fire-5986.appspot.com/o/01082016111327iOS.mp4?alt=media&token=dc60aae2-2231-490f-bb88-09c492ebb053
but it is  giving error.

**Comment by lipangit** [comment]
Ask this project https://github.com/Bilibili/ijkplayer , I have no idea

**Comment by mittalharsh54** [comment]
But i am getting this error in your demo app code when i place my url.

**Comment by lipangit** [comment]
Video engine is ijkplayer

**Comment by alex199568** [comment]
It seems like the player cannot play "https://..." urls, only "http://..."

**Comment by lipangit** [comment]
@alex199568 https://github.com/Bilibili/ijkplayer/issues/1632 
Yes, https is not support default
