### ISSUE TITLE
Android，引入类库，在6.0以下系统运行会出现ImageLoader 类找不到，Baidu地图jar包找不到，Logger 的jar包找不到

### ISSUE THREAD

**Issue by guanzhipeng** [lipangit/JieCaoVideoPlayer#254]
在6.0以上系统没问题，但是6.0以下所有的机型都有问题

**Comment by lipangit** [comment]
如果你引入的jar包，可能需要把jar包里引用的jar包也引入进来，我们这个项目的jar包才90k，但是光ijkplayer至少就是2M

其他jar包不清楚

**Comment by guanzhipeng** [comment]
引用的是jcvideoplayer－lib 类库，然后就出现这些问题
