### ISSUE TITLE
请问播放网络音频怎么使用改框架呢

### ISSUE THREAD

**Issue by xcsgithub** [lipangit/JieCaoVideoPlayer#256]
按照播放视频的方法来做会报无效的数据或者无法解码的错误

**Comment by lipangit** [comment]
来个音频链接，我还没试过播音频

我以为声音正常，没图像而已

**Comment by xcsgithub** [comment]
http://mp3.djwma.com/mp3/爆袭全站欢快节奏感觉那是杠杠滴.mp3

**Comment by xcsgithub** [comment]
我觉得应该是能音频和视频都能播才对

**Comment by xcsgithub** [comment]
我测试是不能播放音频，之前做的能确定可以播放么

**Comment by lipangit** [comment]
从log上看不支持播放这个，到ijkplayer里问问吧
