### ISSUE TITLE
视频分段问题

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#258]
你好，现在做的项目中有一个要求，就是需要对一段完整的视频进行分段播放，比如：整段视频是3分钟，我只是想播放20秒到60秒的地方，想问一下节操可以实现吗？目前没有什么思路=。=，我采用的是之前的MediaPlayer内核的节操，希望群主点拨哈。

**Comment by lipangit** [comment]
有一个seekToInAdvance的参数，设置之后会在此指定位置开始播放。取得播放进度有timer，复写一下timer调用的方法，可以取得当前的播放进度，择时退出

**Comment by jisuz** [comment]
好的好的，我试试看哈，谢谢群主

**Comment by jisuz** [comment]
群主，发现功能实现不了。我在JCVideoPlayer.java中加入了设置seekToInAdvance参数的接口：
public void setSeekToInAdvance(int seekToInAdvance){
		this.seekToInAdvance = seekToInAdvance;
	}

外部进行设置，发现启动播放后，进入缓冲中，然后还是从0开始。取播放进度的timer部分还没有做。只是单纯的设置了参数，发现没有反应。

**Comment by jisuz** [comment]
可以了，知道原因了
seekTo 	指定播放的位置（以毫秒为单位的时间）
我接收到的数据是以秒为单位的，直接赋值进去不行，需要做单位的转换（乘以1000）
谢谢群主。=。=
