### ISSUE TITLE
[数据统计] 如何统计视频的播放时长？

### ISSUE THREAD

**Issue by shaobin0604** [lipangit/JieCaoVideoPlayer#259]
感谢作者提供了这个开源库。

目前在项目中有一个需求：希望可以统计用户播放某个视频的时长，格式为 

    播放时长/视频总时长

请问该在什么时候计算 **播放结束** 的时间点？

**Comment by lipangit** [comment]
目前并没有，你觉得播放结束应该是什么逻辑

**Comment by shaobin0604** [comment]
@lipangit 用户主动从播放界面退出，可能是 PlayerActivity destroy 或是 SurfaceDestroyed

**Comment by shaobin0604** [comment]
另外，对于视频播放而言，还有几个指标是值得关注的，比如：

- 播放成功率
- 播放成功缓冲等待时长（`prepare` 时间）
- 播放取消率（`prepare` 时间太长，用户等不了了）

希望可以暴露相关的接口方便增加这些数据统计

**Comment by lipangit** [comment]
这些可能要自己手动计算之后记录了

**Comment by 18667366881** [comment]
同志们   视频总时长   可以获取到  那么  怎么才能拦截  视频播放结束  或者说  播放停止呢？

**Comment by lipangit** [comment]
@18667366881 继承JCVideoPlayerStandard，复写onPrepared，getDuration()能拿到总时长，复写onAutoComplete能拿到播放结束

**Comment by 18667366881** [comment]
好的 谢谢

**Comment by luoxiaojing** [comment]
JCVideoPlayerStandard这个在哪里 ？
