### ISSUE TITLE
视频链接直接提示Immediate exit requested

### ISSUE THREAD

**Issue by a137235** [lipangit/JieCaoVideoPlayer#263]

**Comment by lipangit** [comment]
log看一下

**Comment by a137235** [comment]
08-08 09:27:22.111 1687-2075/xin.yufeng.multimedia.app.video I/IJKMEDIA: ===== options =====
08-08 09:27:22.111 1687-2075/xin.yufeng.multimedia.app.video I/IJKMEDIA: player-opts : loop                         = 1
08-08 09:27:22.111 1687-2075/xin.yufeng.multimedia.app.video I/IJKMEDIA: format-opts : ijkinject-opaque             = 1049982
08-08 09:27:22.111 1687-2075/xin.yufeng.multimedia.app.video I/IJKMEDIA: format-opts : ijkapplication               = -1675326112
08-08 09:27:22.111 1687-2075/xin.yufeng.multimedia.app.video I/IJKMEDIA: ===================
08-08 09:27:22.113 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: ijkmp_prepare_async()=0
08-08 09:27:22.113 1687-2077/xin.yufeng.multimedia.app.video I/IJKMEDIA: SDL_RunThread: [2077] ff_vout
08-08 09:27:22.114 1687-2076/xin.yufeng.multimedia.app.video D/IJKMEDIA: FFP_MSG_FLUSH:
08-08 09:27:22.119 1687-2078/xin.yufeng.multimedia.app.video I/IJKMEDIA: SDL_RunThread: [2078] ff_read
08-08 09:27:22.129 1687-1687/xin.yufeng.multimedia.app.video D/ActivityThreadInjector: clearCachedDrawables.
08-08 09:27:22.162 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: releaseAllVideos
08-08 09:27:22.163 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: finishFullscreenActivity [119047102] 
08-08 09:27:22.163 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: IjkMediaPlayer_release
08-08 09:27:22.163 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
08-08 09:27:22.163 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: ffpipeline_set_surface()
08-08 09:27:22.163 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
08-08 09:27:22.163 1687-2075/xin.yufeng.multimedia.app.video D/IJKMEDIA: ijkmp_shutdown_l()
08-08 09:27:22.163 1687-2076/xin.yufeng.multimedia.app.video D/IJKMEDIA: message_loop exit
08-08 09:27:22.163 1687-2076/xin.yufeng.multimedia.app.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2076]
08-08 09:27:22.170 1687-2077/xin.yufeng.multimedia.app.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2077]
08-08 09:27:22.200 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: addSurfaceView [238028467] 
08-08 09:27:22.201 1687-1687/xin.yufeng.multimedia.app.video D/JieCaoVideoPlayer: prepareVideo [238028467] 
08-08 09:27:22.201 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: addSurfaceView [238028467] 
08-08 09:27:22.213 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: releaseAllVideos
08-08 09:27:22.214 1687-1687/xin.yufeng.multimedia.app.video I/JieCaoVideoPlayer: finishFullscreenActivity [238028467] 
08-08 09:27:22.216 1687-2078/xin.yufeng.multimedia.app.video E/IJKMEDIA: http://disp.titan.mgtv.com/c1/2016/dianshiju/qingyunzhi_22955/901D10D25B8334E2F6F76D85C8A14F12_20160806_1_1_836.mp4?ver=0.1&fmt=4&pno=1031&fid=901D10D25B8334E2F6F76D85C8A14F12&gsid=78dc207d833f42b2a69676d40c07fb7e: Immediate exit requested
08-08 09:27:22.216 1687-2078/xin.yufeng.multimedia.app.video I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [2078]

**Comment by lipangit** [comment]
这是退出全屏的activity，release MediaPlayer的时候吧，闪退了吗

**Comment by a137235** [comment]
直接播放时就闪退了

**Comment by a137235** [comment]
这个能解决吗，求助。。

**Comment by lipangit** [comment]
关键老臣暂时也不知道怎么解决
