### ISSUE TITLE
如果windowActionBar 是没有的，那么全屏是，并不能全屏，顶部的电池状态栏还在

### ISSUE THREAD

**Issue by google2720** [lipangit/JieCaoVideoPlayer#267]

**Comment by lipangit** [comment]
对对对，这是个问题

**Comment by lipangit** [comment]
已经修复了，512337d5ed1717966a6649eeb5bad914bf884e18

以后我们自己配置参数，原来是否有actionbar，原来是否就是全屏的，来判断是否隐藏actionbar和toolbar
