### ISSUE TITLE
您好，我直接导入jcvideoplayer-lib使用listview上出现下滑出界面的时候视频有声音在那播放。

### ISSUE THREAD

**Issue by q805699513** [lipangit/JieCaoVideoPlayer#268]
您的项目demo没问题。但是我拿过来用，还出现了拖动视频进度条快进或者快退之后 都会跳到从00:00开始播放的问题。而不是进度条位置播放，使用listview上出现下滑出界面的时候视频有声音在那播放。然后滑回去那个播放item的位置就立即暂停了。

**Comment by lipangit** [comment]
必须保证列表的tiem是复用的，视频移除界面，setUp新视频的时候才会停止上正在播放的视频

**Comment by q805699513** [comment]
额。我看demo好像是滑出播放界面之类的就暂停视频的播放啊。要点击新视频才会停止播放吗？？那为什么我点击播放后滑出界面，再滑动到那个有声音播放的视频那，他就自动暂停了。

**Comment by lipangit** [comment]
进群来个小视频看看吧，好像说不大清楚
