### ISSUE TITLE
播放带有中文名称的视频没有画面

### ISSUE THREAD

**Issue by LcTerry** [lipangit/JieCaoVideoPlayer#269]
RT只有声音没有画面

**Comment by lipangit** [comment]
没有画面有声音多半是因为没开启硬件加速

在manifest和代码中检查一下

**Comment by crazyandcoder** [comment]
开启了硬件加速还是不行，还是只有声音没有画面，三星S4 i9508

**Comment by lipangit** [comment]
T_T 加我qq发个短视频看看 你那到底什么效果

**Comment by Jacky-Xu** [comment]
@lipangit  带有中文播放地址播放视频没有画面。

**Comment by lipangit** [comment]
也有呀，urlEncode转换一下

**Comment by Jacky-Xu** [comment]
@lipangit 你测试这个视频地址试试 http://shixue-10008076.video.myqcloud.com/JSZG/kemu1/jiayonghongyouerZ/1-1%E8%B4%BE%E6%95%99%E5%B8%88%E9%A3%8E%E9%87%87.mp4 。

**Comment by lipangit** [comment]
应该是视频编码问题，确实没图像
