### ISSUE TITLE
你好，视频播放结束后，还有声音继续播放的问题。

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#270]
你好，今天改为使用V4.6的版本，在做分段视频播放的时候，播放20S-40S,在40S的时候画面移除了，但是声音还是继续往下播放，想问一下是不是少了什么设置需要设置。

**Comment by lipangit** [comment]
操作分两个部分，一个操作UI，一个操作MediaPlayer，你可能没停止或释放MediaPlayer

**Comment by jisuz** [comment]
可以了，没有释放MediaPlayer，谢谢
