### ISSUE TITLE
视频播放卡顿问题

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#271]
群主，我使用了你的3.6.3和4.6这两个版本  如果是用你提供的URL播放视频是没有问题的  如果修改成我们公司提供的视频连接就一直出现卡顿问题，一卡一卡的 ，想问一下这个是什么问题？ 格式都是MP4
网速：300-500KB/s  公司给的URL好像是高清的。

**Comment by jisuz** [comment]
带宽大小是5M

**Comment by lipangit** [comment]
用cdn吧，就是贵点
