### ISSUE TITLE
点击切换JZMediaIjk播放器，,提示没有so文件，可是依赖我也加了啊

### ISSUE THREAD

**Issue by Sky-Rookie** [lipangit/JieCaoVideoPlayer#2717]
**couldn't find "libijkffmpeg.so

*        jz_video.setUp(
            "http://jzvd.nathen.cn/342a5f7ef6124a4a8faf00e738b8bee4/cf6d9db0bd4d41f59d09ea0a81e918fd-5287d2089db37e62345123a1be272f8b.mp4"
            , "饺子快长大",
            JzvdStd.SCREEN_NORMAL,
            JZMediaIjk::class.java)

...
    implementation 'cn.jzvd:jiaozivideoplayer:7.5.0'
    implementation 'tv.danmaku.ijk.media:ijkplayer-java:0.8.4'
    implementation 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.4'
...
**截图或者小视频说明

**Comment by lipangit** [comment]
耐心研究和测试引入项目的方法。



---原始邮件---
发件人: "ARookieOfProgramming"<notifications@github.com&gt;
发送时间: 2020年9月25日(周五) 晚上6:53
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lipangit/JiaoZiVideoPlayer] 提示没有so文件，可是依赖我也加了啊 (#2717)




 
**需求描述
 
**其他app是否实现
 
**截图或者小视频说明
