### ISSUE TITLE
seekTo有问题

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#272]
版本：v4.6
在进行视频分段播放的时候：
20s-40s
在onPrepared中使用了seekTo到20s开始播放，加载成功后，画面开始播放，但是getCurrentPositionWhenPlaying（）一直取到的值为0，大概3-5秒左右才可以取到值，才开始显示进度。

想问一下这个问题需要怎么解决？
之前在还用MediaPlayer的时候是没有这个问题的。=。=

**Comment by lipangit** [comment]
恩。。忍了吧，不是什么大问题

**Comment by fushen0** [comment]
忍了可还行~ ovo 
我也在做这么个需求，也是同样的问题/裂开

**Comment by lipangit** [comment]
进度条不准，换别的内核试试

**Comment by lipangit** [comment]
所以现在很多短视频就没有进度条。长视频一般没这个问题



---原始邮件---
发件人: "fushen0"<notifications@github.com&gt;
发送时间: 2021年1月27日(周三) 下午3:27
收件人: "lipangit/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Nathen"<1066666651@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] seekTo有问题 (#272)




 
忍了可还行~ ovo
 我也在做这么个需求，也是同样的问题/裂开
