### ISSUE TITLE
求教！无法播放网络视频  版本3.6.1 

### ISSUE THREAD

**Issue by doubleZuo** [lipangit/JieCaoVideoPlayer#273]
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel*)] : [936] callback app listenerNotNull=1, send=1
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel*)] : [940] callback application
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer-JNI: [virtual void JNIMediaPlayerListener::notify(int, int, int, const android::Parcel*)] : [113] jni callback app
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer-JNI: [virtual void JNIMediaPlayerListener::notify(int, int, int, const android::Parcel*)] : [128] jni callback app
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: postEventFromNative  callback app
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: Message: MEDIA_INFO(200), ext1=Unknown MediaInfoType(1001), ext2=0
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest W/MediaPlayer: info/warning (1001, 0)
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel*)] : [936] callback app listenerNotNull=1, send=1
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: [virtual void android::MediaPlayer::notify(int, int, int, const android::Parcel*)] : [940] callback application
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer-JNI: [virtual void JNIMediaPlayerListener::notify(int, int, int, const android::Parcel*)] : [113] jni callback app
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer-JNI: [virtual void JNIMediaPlayerListener::notify(int, int, int, const android::Parcel*)] : [128] jni callback app
08-10 14:19:44.180 23473-23485/com.akm.toge.jiecaotest D/MediaPlayer: postEventFromNative  callback app

08-10 14:19:44.180 23473-23513/com.akm.toge.jiecaotest E/MediaPlayer: Error (1,-2147483648)
08-10 14:19:44.180 23473-23473/com.akm.toge.jiecaotest E/JieCaoVideoPlayer: onError 1 - -2147483648 [1105300344]

**Comment by lipangit** [comment]
这应该是视频源或网络的问题

现在推荐用最新的4.6版本

**Comment by doubleZuo** [comment]
@lipangit  换了4.6后可以播放了，但是，播放中点击全屏进行全屏播放，全屏播放结束后，退出全屏模式，视频黑屏，无法播放了。
![image](https://cloud.githubusercontent.com/assets/15321801/17548627/4c3fc35e-5f1f-11e6-9e4c-4d3cb3ca40b8.png)

**Comment by doubleZuo** [comment]
@lipangit 有的时候全屏播放结束，退出全屏是这种情况
![Uploading image.png…]()

**Comment by doubleZuo** [comment]
@lipangit 有的时候全屏播放结束，退出全屏是这种情况

**Comment by ATai2** [comment]
我也发现这个问题。请问你解决了吗？

**Comment by lipangit** [comment]
解决了，看昨天的commit
