### ISSUE TITLE
项目SeekBar怎么和sdk里面的关联起来呢？

### ISSUE THREAD

**Issue by 284361303** [lipangit/JieCaoVideoPlayer#2732]
**需求描述
我们的项目的seekbar不是在视频内下方，所以隐藏了sdk中的seekbar，单独在自己项目中增加了seekbar控件，现在拖动自己seekbar怎么和sdk里面的进度都保持一致呢，代码最小化，谢谢。
**其他app是否实现

**截图或者小视频说明

**Comment by 284361303** [comment]
已经通过继承实现

**Comment by Newwaygo** [comment]
继承的什么。

**Comment by lipangit** [comment]
继承jzvdstd复写getlayoutbyid函数，设置自己的xml布局，在此布局中修改需要的seekbar



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月12日(周一) 晚上6:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [lipangit/JiaoZiVideoPlayer] 项目SeekBar怎么和sdk里面的关联起来呢？ (#2732)




 
继承的什么。
