### ISSUE TITLE
是否支持recycleview？ 

### ISSUE THREAD

**Issue by ATai2** [lipangit/JieCaoVideoPlayer#274]
我用recycleview做list的时候为什么不像listview一样，在播放item退出屏幕外，在重新拉回来的时候视频回到初始状态，而是仍然播放？

**Comment by lipangit** [comment]
列表复用的时候setUp的时候，如果是播放的会重置这个播放器的播放，如果列表不是复用的就不会调用setUp，视频就会一直播放

**Comment by YuJunKui2016** [comment]
犹豫RecyclerView缓存是 屏幕显示数目+3
滑动当前播放的item滑出3个item的时候才会停止。
请在recyview界面添加如下代码
 recyclerView.addOnChildAttachStateChangeListener(new RecyclerView.OnChildAttachStateChangeListener() {
            @Override
            public void onChildViewAttachedToWindow(View view) {

            }

            @Override
            public void onChildViewDetachedFromWindow(View view) {
                if (JCVideoPlayerManager.listener() != null) {
                    JCVideoPlayer videoPlayer = (JCVideoPlayer) JCVideoPlayerManager.listener();
                    if (((ViewGroup) view).indexOfChild(videoPlayer) != -1 && videoPlayer.currentState == JCVideoPlayer.CURRENT_STATE_PLAYING) {
                        JCVideoPlayer.releaseAllVideos();
                    }
                }
            }
        });

**Comment by lipangit** [comment]
@YuJunKui2016 兄台对recycleview的研究如此之深，可否调试一下develop分支中的RecycleviewNormalActivity，这是别人贡献的代码，如果感兴趣可以帮忙调试一下，看看有什么问题有什么坑

**Comment by YuJunKui2016** [comment]
@lipangit RecycleviewNormalActivity  就是我写的啊

**Comment by lipangit** [comment]
对对，当时没发现^_^

**Comment by tommyfeng** [comment]
((ViewGroup) view).indexOfChild(videoPlayer) 一直为 -1， 不知道是为啥？

**Comment by lipangit** [comment]
@tommyfeng 源码显示-1是没有这个view

**Comment by lipangit** [comment]
recycleview的问题看demo，应该问题不大了
