### ISSUE TITLE
全屏播放完成退出全屏，无法再次播放问题。版本4.6

### ISSUE THREAD

**Issue by doubleZuo** [lipangit/JieCaoVideoPlayer#275]
你好，请教问题。版本4.6
全屏播放完成退出全屏，回复到默认屏幕（SCREEN_LAYOUT_LIST），video界面黑屏，进度在中间某一位置，再次点击播放，无法进行播放问题。

**Comment by lipangit** [comment]
进群吧发个小视频看看，也需要log和更多细节

**Comment by google2720** [comment]
对对，我也遇到了，我是在fragment中使用的，我播放的是本地文件，不是网络视频

**Comment by google2720** [comment]
群号在哪？

**Comment by lipangit** [comment]
[490442439](https://github.com/lipangit/JieCaoVideoPlayer/blob/develop/README-ZH.md)

已经发现问题了，有时间修复
