### ISSUE TITLE
How can i add referer

### ISSUE THREAD

**Issue by alphaDroid89** [lipangit/JieCaoVideoPlayer#276]
Hi @lipangit ,

Thanks for this library, i need to add referer url in the player how can i added this.

Map<String,String> headers = new HashMap<String,String>();
headers.put("Referer", "http://yyy");

The above header is need to be added i tried to add this in  JCMediaManager.Class - >MediaHandler. But the video is not playing. please correct me if i'm doing wrong. Thanks

**Comment by lipangit** [comment]
Do you want to set head data for every video player?

**Comment by lipangit** [comment]
If you do not want to put header data when setUp every time , you can extends JCVideoPlayerStandard Override setUp function and put header data in that function

**Comment by SkyNite** [comment]
@lipangit thanks for your quick response. Can you please elaborate,

Currently the setpUp method looks like


  @Override
    public boolean setUp(String url, int screen, Object... objects) {
        if (objects.length == 0) return false;
        if (super.setUp(url, screen, objects)) {
            
            titleTextView.setText(objects[0].toString());
            if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
                fullscreenButton.setImageResource(R.drawable.jc_shrink);
                backButton.setVisibility(View.VISIBLE);
                tinyBackImageView.setVisibility(View.INVISIBLE);
            } else if (currentScreen == SCREEN_LAYOUT_LIST) {
                fullscreenButton.setImageResource(R.drawable.jc_enlarge);
                backButton.setVisibility(View.GONE);
                tinyBackImageView.setVisibility(View.INVISIBLE);
            } else if (currentScreen == SCREEN_WINDOW_TINY) {
                tinyBackImageView.setVisibility(View.VISIBLE);
                setAllControlsVisible(View.INVISIBLE, View.INVISIBLE, View.INVISIBLE,
                        View.INVISIBLE, View.INVISIBLE, View.INVISIBLE, View.INVISIBLE);
            }
            return true;
        }
        return false;
    }
Thanks

**Comment by lipangit** [comment]
I was thinking about it, Do you have a better way?

**Comment by SkyNite** [comment]
I used like below in ActivityMain,

     Map<String, String> headers = new HashMap<String, String>();
        headers.put("Referer", "https://yyyy");
            jcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
        jcVideoPlayerStandard.setUp("http://myUrl"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, headers, "VideoTitle");

but i got error. **Protocol not found** -08-11 21:14:04.832 28352-28415/fm.jiecao.jiecaovideoplayer E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)

**Comment by lipangit** [comment]
https://ffmpeg.org/ffmpeg-protocols.html

**Comment by lipangit** [comment]
you can add header already

**Comment by CodeToxicant** [comment]
Map<String, String> headers = new HashMap<String, String>();
    headers.put("Referer", "https://yyyy");
        jcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
    jcVideoPlayerStandard.setUp("http://myUrl"
            , JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, headers, "VideoTitle");

这种设置好像不行
