### ISSUE TITLE
setUp之后提示视频地址无效，没进这个方法，求教

### ISSUE THREAD

**Issue by coder-luhao** [lipangit/JieCaoVideoPlayer#279]
自定义UI，我把jcvideoplayer-lib里面的JCVideoPlayerStandard和相关文件copy过来，去掉了上面的标题栏，然后按照那4个步骤添加进来，运行项目提示“视频地址无效”，我在setUp里面打Log发现并没有进这个方法，是哪里出问题了？求教

**Comment by lipangit** [comment]
地址无效是说压根没给地址赋值，是不是没调super.setUp()这个方法

**Comment by coder-luhao** [comment]
JCVideoPlayerStandard是直接copy过来的，我看到里面调用了此方法，在调用super之前打Log，并没有进入这个方法。xml控件已修改为自定义的名称，Activity里面setUp也能点到JCVideoPlayerStandard里的setUp。播放这块也不是自定义的，所以我很疑惑哪里出错了，还请指教~

**Comment by lipangit** [comment]
就是说你的子类调用了setUp方法，但是父类没调用setUp方法，导致url没被赋值，我也不知道为什么，感觉你还是哪里有些小错误，应该不是什么大问题

**Comment by coder-luhao** [comment]
在setUp之前我只做了findViewById找到JCVideoPlayerStandard，我不知道为什么没有调用父类的setUp方法，播放器的布局是写在RecycleView的头布局里面的，我不清楚是不支持RecycleView还是对JCVideoPlayerStandard的id有限制。

**Comment by lipangit** [comment]
我感觉只要调用了子类的setUp方法，父类的setUp肯定调用了，你仔细断点一下
