### ISSUE TITLE
Video sound is gone when enter fullscreen

### ISSUE THREAD

**Issue by Rygelouv** [lipangit/JieCaoVideoPlayer#28]
When enter fullscreen mode video sound is gone on Marshmallow

**Comment by lipangit** [comment]
Yes , I fund a android 6.0 phone to test , no sound after fullscreen , and back to not-fullscreen also no sound, Do you have any ideas

**Comment by Rygelouv** [comment]
Not yet, still working on it.

**Comment by lipangit** [comment]
Add you to Collaborators,If there is some progress, push directly

**Comment by lipangit** [comment]
v3.0 maybe fix this problem, @Rygelouv have a try.
