### ISSUE TITLE
Adaptive bit player

### ISSUE THREAD

**Issue by sridhar2392** [lipangit/JieCaoVideoPlayer#280]
I am using Standard player currently. In this player I couldn't see the video changing its quality according to the bandwidth when I try to play hls file (m3u8) . Is there anything I'm forgetting to invoke. This is the code that I'm currently using : 
     `jcVideoPlayerStandard = (JCVideoPlayerStandard)view.findViewById(R.id.custom_videoplayer_standard);
                    jcVideoPlayerStandard.setUp(vpath, "");
                    ImageLoader.getInstance().displayImage(setimage,jcVideoPlayerStandard.thumbImageView);`

**Comment by lipangit** [comment]
If you want to change quality you should change url

Can one url contains many quality video?

**Comment by sridhar2392** [comment]
yes it can .
An m3u8 url can contain different quality videos in the same url. It changes the screen size based on the bandwidth it is getting thus it changes the quality.

**Comment by lipangit** [comment]
I have less knowledge about m3u8, I am appreciate you can pull request a demo to change video quality.

**Comment by sridhar2392** [comment]
Do u mean u need a sample url ?  Or else a player integrated with the url for a demo purpose ?

**Comment by lipangit** [comment]
demo purpose

**Comment by sridhar2392** [comment]
I have made a demo from [this]( https://github.com/skyCracks/jiecaovideoplayer) link where the quality in which it is playing will be noted in the screen itself. Please run this app in high speed internet in order to see the result. 

apk file link : https://drive.google.com/open?id=0B_1YXYtMNYymRFZ0M0ZZbHR6U0E

**Comment by sridhar2392** [comment]
So did you check or have got any idea ?

**Comment by lipangit** [comment]
Still have problem repone this issue
