### ISSUE TITLE
Video actions

### ISSUE THREAD

**Issue by sridhar2392** [lipangit/JieCaoVideoPlayer#281]
Need to know the methods that should be called to pause a video completely and should not play even after hitting play unless the player is released (releaseAllvideos). Also to auto-play by calling a method.  I'm currently using standard video player.

**Comment by lipangit** [comment]
Extends JCVideoPlayerStandard and override some functions  can call back video actions.

**Comment by sridhar2392** [comment]
Can u please tell me which function to call exactly ?

**Comment by sridhar2392** [comment]
Can u please tell me the method that need to be called to **pause** a video
