### ISSUE TITLE
how can I get current play progress?(如何获取当前进度？)

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#283]
想做个桌面shortcut 保存进度。。

**Comment by AkashiWen** [comment]
mSeekTimePosition?

**Comment by lipangit** [comment]
JCMediaManager.instance().JCMediaManager.getCurrentPosition();

**Comment by prophet173** [comment]
there is no JCMediaManager after instance, it`s turning red

using latest version 4.6.1
