### ISSUE TITLE
可以加入一个直播中的延时时间，比如播放端延时超过10秒就重新刷新一下，然后将延时缩短到最短

### ISSUE THREAD

**Issue by danniu1314** [lipangit/JieCaoVideoPlayer#285]
目前七牛的那个已经出了这个了，延时上对比，延时会比你们的软件少一些，直播的过程中，他们延时有做处理。延时超过多少后就可以自动复位缩短延时。你们可以去借鉴下哦  PLDroidPlayer

**Comment by lipangit** [comment]
标题里‘然后将延时缩短到最短’是什么意思

**Comment by danniu1314** [comment]
直播累积延时优化，就是直播的过程中，观看端相比发布端出现延时过多的时候，可以设置下这个时间，如果延时超过一定时间，就重新刷新一下这个流，让延时始终保持在一定的范围内。不会出现延时越来越多的积累。

**Comment by lipangit** [comment]
可能比较复杂，暂时还没理解了
