### ISSUE TITLE
华为p9plus 不能播放

### ISSUE THREAD

**Issue by xihacode** [lipangit/JieCaoVideoPlayer#286]
` dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shzenon.huohuo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.shzenon.huohuo-2/lib/arm64, /data/app/com.shzenon.huohuo-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shzenon.huohuo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.shzenon.huohuo-2/lib/arm64, /data/app/com.shzenon.huohuo-2/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:379)`

还有提示播放地址无效 但是2.0_preview一切正常

**Comment by xihacode** [comment]
加上这个就好了  compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.0'

**Comment by lipangit** [comment]
请及时更新最新版
