### ISSUE TITLE
自定义状态栏时 横屏后状态栏不消失

### ISSUE THREAD

**Issue by xihacode** [lipangit/JieCaoVideoPlayer#287]

**Comment by lipangit** [comment]
用最新版
JCVideoPlayer.ACTION_BAR_EXIST
JCVideoPlayer.TOOL_BAR_EXIST
这两个参数手动控制

**Comment by xihacode** [comment]
还是不行，状态栏出现在是在左边的，但是视频是横屏的

**Comment by xihacode** [comment]
我用的状态栏是这种方案：
`// 设置状态栏透明
            activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
            // 生成一个状态栏大小的矩形
            View statusView = createStatusView(activity, color);
            // 添加 statusView 到布局中
            ViewGroup decorView = (ViewGroup) activity.getWindow().getDecorView();
            decorView.addView(statusView);
            // 设置根布局的参数
            ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);
            rootView.setFitsSystemWindows(true);
            rootView.setClipToPadding(true);`

**Comment by lipangit** [comment]
全屏的时候屏幕的属性是竖屏的

这个状态栏有什么不同吗，setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN）不能用这个方法隐藏吗

**Comment by xihacode** [comment]
我用的状态栏方案是生成一个状态栏大小的矩形放在状态栏上兼容4.4的    所以用setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN）是不行的，试过了。可以提供下方法设置下状态栏，另外全屏的时候屏幕的属性为什么要设置竖屏的呢？这样状态栏显示的时候会在右边的，感觉不太好，为什么不用setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);来改变属性呢？

**Comment by lipangit** [comment]
暂时你可以通过埋点里进入和退出全屏的回调显示和不显示你自己生成状态栏

横屏问题，觉得屏幕还是竖着档次高，再观察观察

**Comment by suoyo** [comment]
弱弱的问一句，通过埋点里进入和退出全屏的回调是什么意思？
