### ISSUE TITLE
魅族Pro6手机报这个错，

### ISSUE THREAD

**Issue by burgessjp** [lipangit/JieCaoVideoPlayer#288]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.trs.gygdapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.trs.gygdapp-1/lib/arm64, /data/app/com.trs.gygdapp-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"

Android 系统6.0

**Comment by burgessjp** [comment]
这个问题解决了，但是最新版本4.6.1有个问题，如果app使用的不是AppCompatActivity就会报错。

**Comment by lipangit** [comment]
所有activity必须继承AppCompatActivity，你的activity肯定要继承一个，就继承AppCompatActivity这个activity

**Comment by AkashiWen** [comment]
如何解决的？

**Comment by burgessjp** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/286

更新到最新版本应该也没问题，目前我用的 v3.6.3版本

**Comment by AkashiWen** [comment]
couldn't find "libijkffmpeg.so"的问题，我按某篇blog这样设置了一下可以：

ndk {
            //设置支持的SO库架构
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'armeabi' //, 'x86', 'armeabi-v7a', 'x86_64', 'arm64-v8a'
        }
