### ISSUE TITLE
关于进度条手动拖拉后的建议

### ISSUE THREAD

**Issue by zhangjiapei1** [lipangit/JieCaoVideoPlayer#289]
您好，关于视频播放后，手动拖拉进度条后，currentTimeTextView 会先改变为00:00然后再定位到拖拉的位置时间，请问，这个怎么解决！谢谢

**Comment by lipangit** [comment]
没发现有这个问题，进群或加我qq发个小视频看看现象

**Comment by zhangjiapei1** [comment]
我进群或者加qq都行，我的qq是32577296，或者您把群号、qq号发给我我加一下。到时候截一段视频给你看看




------------------
张佳培
北方大贤风电科技（北京）有限公司
平台定制事业部    项目经理
Tel:+86 10 57738529   Mob : +86 18911271071 
Email: zhangjiapei@dxwind.com
www.dxwind.com  北京市朝阳区芍药居北里101号世奥国际中心A座1915室，100029


 

 
 
 
------------------ Original ------------------
