### ISSUE TITLE
NavigationBar on top still exist while fullscreen (全屏时顶部状态栏还在)

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#291]
4.6
走的是 onClick: R.id.fullscreen
Log.i(TAG, "onClick fullscreen [" + this.hashCode() + "] ");
            if (currentState == CURRENT_STATE_AUTO_COMPLETE) return;
            if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
                //quit fullscreen
                backPress();
            } else {
                Log.d(TAG, "toFullscreenActivity [" + this.hashCode() + "] ");
                onEvent(JCBuriedPoint.ON_ENTER_FULLSCREEN);
                startWindowFullscreen();
            }

AndroidManifest.xml：
<activity
            android:name=".activity.PartActivity"
            android:configChanges="keyboardHidden|orientation|screenSize"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateAlwaysHidden|adjustResize"
            >

**Comment by lipangit** [comment]
用最新版本 https://github.com/lipangit/JieCaoVideoPlayer/releases/tag/v4.6.1

JCVideoPlayer.ACTION_BAR_EXIST and JCVideoPlayer.TOOL_BAR_EXIST手动控制toolbar显示与否

**Comment by AkashiWen** [comment]
可以 好用

**Comment by lipangit** [comment]
么么哒
