### ISSUE TITLE
enable / disable video click function doubt clarification

### ISSUE THREAD

**Issue by sridhar2392** [lipangit/JieCaoVideoPlayer#292]
is there any function available that can be called to permanently disable click (play icon) on video so that it can never be played and a function to enable them back ?

**Comment by lipangit** [comment]
Use button system function can achieve your goal

**Comment by sridhar2392** [comment]
Can you please elaborate as I am new to this development . Is it like android button specific or player specific functionality ?

**Comment by sridhar2392** [comment]
For example if i type " jcVideoPlayerStandard." in android studio a lot functions displays like the following:
  onrelease()
  isActivated()
performClick()  etc...

Just need to know if there is any function to disable click and to enable them back ?

**Comment by lipangit** [comment]
U can break point on theset functions , which break point stop , that is your function.

**Comment by sridhar2392** [comment]
I really couldn't find any functions for disabling play functionality . I tried setting breakpoints on all set functions .

**Comment by sridhar2392** [comment]
calling  changeUiToClear()  and changeUiToCompleteClear() fixed my problem . This is the function that I was looking for.
