### ISSUE TITLE
目前的全屏效果，由于Activity属性是竖屏，有些UI上不和谐的地方。

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#293]
全屏时，由于Activity还是竖屏，碰到了

1. 做Toast提示
2. 动态生成Dialog的覆盖层

还是按照非全屏的效果弹出来，看起来就。。。

希望能有 setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);的效果

**Comment by lipangit** [comment]
目前认为全屏时候是竖屏逼格更高

全屏时候横屏的呼声也很高，再观察观察，那目前就是尽量少toast少dialog

**Comment by AkashiWen** [comment]
好的，看到源码里控制进度的dialog是这样：
View localView = LayoutInflater.from(getContext()).inflate(fm.jiecao.jcvideoplayer_lib.R.layout.jc_progress_dialog, null);
            View content = localView.findViewById(R.id.content);
            content.setRotation(90);
我试试旋转角度。。

**Comment by lipangit** [comment]
加油^_^
