### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by yaojie520** [lipangit/JieCaoVideoPlayer#294]
java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.flyant.android.sf-2/base.apk"],nativeLibraryDirectories=[/data/app/com.flyant.android.sf-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
java.lang.Runtime.loadLibrary(Runtime.java:367)
java.lang.System.loadLibrary(System.java:988)
tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init>(JCMediaManager.java:82)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:76)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.isCurrentMediaListener(JCVideoPlayer.java:739)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setUp(JCVideoPlayer.java:136)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setUp(JCVideoPlayerStandard.java:67)

**Comment by lipangit** [comment]
参照demo添加ijkplayer的依赖包

![image](https://cloud.githubusercontent.com/assets/2038071/17722886/3767d64e-6468-11e6-8110-0e1ace9dccb7.png)
有必要研究一下tools:overrideLibrary
