### ISSUE TITLE
前进倒退问题

### ISSUE THREAD

**Issue by KKJJ** [lipangit/JieCaoVideoPlayer#296]
前进后退没有效果，后退有时候有，但也定位不准， 播放的是本地视频   求赐教

**Comment by lipangit** [comment]
1.定位不准的问题我有时候也遇到到了，一般在2s之内，有时间好好测测，是计算的整除问题吗

2.前进后退没有效果，这不知道什么原因，进群发个小视频看看到底什么效果吧

3.播放本地视频应该是file:///开头的路径

**Comment by KKJJ** [comment]
我用的是Android Studio直接接的库，所以也没办法调
群在哪

**Comment by lipangit** [comment]
中文版的readme里  490442439 验证信息:jcvd
