### ISSUE TITLE
希望在全屏的时候能够隐藏下输入法

### ISSUE THREAD

**Issue by wangyi1993** [lipangit/JieCaoVideoPlayer#299]
我上面一个edittextview 下面一个播放器  在我输入 文字的时候再去点击播放并全屏  这时候输入法没有隐藏 会挡住视频

**Comment by YuJunKui2016** [comment]
JCVideoPlayer.setJcBuriedPoint(new MyJCBuriedPointStandard());
设置监听后在对应事件中 自行隐藏输入法

**Comment by lipangit** [comment]
可能不会在库里处理这么特殊的需求，但是应该能通过各种方法解决
