### ISSUE TITLE
按home键后，再点击app出现bug

### ISSUE THREAD

**Issue by zhangzzqq** [lipangit/jiecaovideoplayer#3]
打开视频播放后，点击暂停，再按home键，然后点击app视频播放就播放不了。。

**Comment by zhangzzqq** [comment]
这是视频播放器，可以播放音频如MP3。播放MP3的时候怎样让它显示出自己设计好的背景图片呢？

**Comment by lipangit** [comment]
已经修复，感谢你的反馈。
在Activity的onPause中调用JCVideoPlayer.releaseAllVideo();
暂停的视频按home键，会回收暂停和播放中的视频，回到应用后所有视频都是初始化状态。

**Comment by lipangit** [comment]
蒽。。这种特殊需求的话你可以自己尝试修改。
建议：播放mp3时不隐藏缩略图^=^,这个思路会方便一些。

**Comment by zhangzzqq** [comment]
对MP3不隐藏缩略图，思路很好，谢谢。

**Comment by lipangit** [comment]
已经支持MP3播放
