### ISSUE TITLE
播放摄像头rtsp的问题

### ISSUE THREAD

**Issue by hwjtiw** [lipangit/JieCaoVideoPlayer#300]
大神你好，这个项目很棒，精简，易用。
不知道你有没有试过播放监控摄像头的场景
我试播放监控摄像头的rtsp地址，可以播放，但有点容易断，而且有延迟，大概延迟5、6秒左右，
google了一下，可能是原生的控件问题，一般有延迟5、6秒，一般的其他库的demo（vlc,ijkplayer）是延迟2、3秒，可能因为原生的方法需要缓冲,并不能很好实时，但是其他的demo难用而且比较大。
请问有什么解决方案吗？

http://stackoverflow.com/questions/10637392/android-videoview-rtsp-delay
camera rtsp
VideoView RTSP delay

@lipangit

**Comment by lipangit** [comment]
之前也感受到了系统MediaPlayer的局限，自从4.+之后用的也是ijkplayer作为播放器的引擎，咱们这个项目的本质是对MediaPlayer的管理和对UI的管理，不涉及视频流的传输和解析等底层功能，多谢夸奖，祝你好运

**Comment by hwjtiw** [comment]
@lipangit 
也对，如果能解决延时问题，用mediaplayer 还是可以做简单rtsp播放的
我自己编译ijkplayer的时候，总是没办法支持rtsp,要么编译失败，有这方面的教程可以分享一下吗？

**Comment by lipangit** [comment]
你到ijkplayer项目下问问找找吧，我没编译ijkplayer这方面的经验

**Comment by hwjtiw** [comment]
@lipangit 
感谢，也长期关注这个项目
