### ISSUE TITLE
m3u8格式多媒体，画面倒置180度的问题

### ISSUE THREAD

**Issue by jisuz** [lipangit/JieCaoVideoPlayer#301]
你好，在使用了本项目4.6的版本中，我播放的数据是摄像头的m3u8格式，出现了画面颠倒180度的问题，如下图所示：
![1](https://cloud.githubusercontent.com/assets/7007140/17796602/532e2710-65f4-11e6-9583-66c8b13a8703.png)

通过在JCVideoPlayer类中init函数，设置textureViewContainer.setRotation(-180);
如下图所示：
![2](https://cloud.githubusercontent.com/assets/7007140/17796613/6856a40a-65f4-11e6-9186-4b44c29fd07c.png)

播放的画面对了，但是摄像头里面的文件出现了颠倒

**Comment by lipangit** [comment]
怎么解决了

**Comment by jisuz** [comment]
是摄像头视频源的问题哈，我找了另外一个监控摄像头的视频源测试是没有问题的。
谢谢你哈，这个项目真心不错。
