### ISSUE TITLE
华为G750-T00   JCVideoPlayer.releaseAllVideos()报异常

### ISSUE THREAD

**Issue by yanchengmeng** [lipangit/JieCaoVideoPlayer#302]
OnPause()方法里面JCVideoPlayer.releaseAllVideos();报java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1654): could not load library "libOpenSLES.so" needed by "libijksdl.so"; caused by soinfo_relocate(linker.cpp:994): cannot locate symbol "߳xa]fmnh,ije" referenced by "libOpenSLES.so"...
直接闪退

**Comment by yanchengmeng** [comment]
华为G7播放视频也报异常，估计是同样问题

**Comment by lipangit** [comment]
播放可以播放但releaseVideo得时候会报错，我也不知道为什么

**Comment by yanchengmeng** [comment]
播放不了呀

**Comment by lipangit** [comment]
像demo一样把gradel中的配置引用全试试

**Comment by yanchengmeng** [comment]
你的Demo我放到华为G7上播放也是直接闪退

**Comment by lipangit** [comment]
ijkplayer官方的demo呢
