### ISSUE TITLE
Enter full screen mode with rotation

### ISSUE THREAD

**Issue by prophet173** [lipangit/JieCaoVideoPlayer#304]
i am entering full screen mode with setupPlayer.startWindowFullscreen();
but once i rotate, JCV also rotates and i`m ending up portrait mode once again. How to prevent player rotation and match current screen mode with Full Screen options?

**Comment by lipangit** [comment]
FULLSCREEN mode can not change , FULLSCREEN mode is full screen, can not mode is FULLSCREEN but display is not fullscreen

**Comment by prophet173** [comment]
then how to enter fullscreen without pressing FULLSCREEN BUTTON? i want to enter full screen with ROTATION

**Comment by prophet173** [comment]
anything? is there any way to start fullscreen mode on rotation?

**Comment by prophet173** [comment]
found solution inside source

jcVideoPlayer.setRotation(90); ->  public void startWindowFullscreen() {...

if we only had control of rotation, for example set True or false 
startWindowFullscreen(0), startWindowFullscreen(90)

**Comment by lipangit** [comment]
Good luck

**Comment by prophet173** [comment]
seriously? :D we have no control over full screen rotation, please make fullscreen video setRotation controllable, thanks in advanced

**Comment by lipangit** [comment]
I should not close the issue, I thought you have achive your goal.

I think screen is vertical when fullscreen is have grade  good look and science and technology feeling,  other people also said fullscreen should be landscape, we should observed the effect.

**Comment by prophet173** [comment]
after manual integration of lib and source editing, finally made it possible for player to follow rotations correctly on configChanges.
Thanks for that amazing player and for trying to help :) well if you wish, i can post my edit so anyone could use it
