### ISSUE TITLE
can't play map3?

### ISSUE THREAD

**Issue by gogolq** [lipangit/JieCaoVideoPlayer#305]
不能播放在线音频吗，我放入一个map3格式的在线音频地址，就报错了

**Comment by lipangit** [comment]
能播，就是没图像吧，播音频用这个库好吗，这个库是播视频的

**Comment by lipangit** [comment]
音频也能播，播的时候别隐藏缩略图就好了

**Comment by niuyun123** [comment]
我的也不能播mp3,  3.6的还可以,4.6直接就是爆破音然后就完了

**Comment by lipangit** [comment]
地址发来看看

**Comment by jitongkai** [comment]
我的mp3也播不了，而aac和m4a文件都能播。

**Comment by flztsj** [comment]
jiechao做的是UI，播放用的是ijkplayer，check下引用的ijkplayer版本。
