### ISSUE TITLE
关于旋转手机自动横屏，全屏播放的问题。

### ISSUE THREAD

**Issue by smallflybird** [lipangit/JieCaoVideoPlayer#307]
现在遇到一个问题，就是在标准播放模式下，如果不固定Activity的方向，旋转手机至横屏，在onConfigurationChanged(Configuration newConfig)方法中调用JCVideoPlayer 的startWindowFullscreen()方法触发全屏，这时Activity会旋转90度，而JCVideoPlayer会再次旋转90度，因为在View中添加FramLayout的时候会调用 jcVideoPlayer.setRotation(90);，这样导致全屏错乱。如果固定Activity的方向，就不能知道是否手机旋转到横屏，就不能触发JCVideoPlayer 的startWindowFullscreen()方法，使其全屏。

请问在旋转手机自动全屏，这个问题上，应该怎样操作？

**Comment by lipangit** [comment]
旋转手机自动全屏已经列入工作计划，正在酝酿好的实现方式

目前认为检测到屏幕旋转时候，手机不能横屏，然后调用startFullscreen()方法，这样比较好

**Comment by xiaocaishifu** [comment]
首先Activity要设置成竖屏不能旋转，否则调用startFullscreen()方法后会有多旋转90度的问题，这样的话，在固定竖屏的情况下，如何检测到屏幕旋转到横屏，然后调用startFullscreen()方法?

**Comment by lipangit** [comment]
监听重力吧，最好是有一个现成的函数回调，如果自己监听xyz重力感应的数值的话判断可能比较复杂，担心做不好

**Comment by xiaocaishifu** [comment]
用了OrientationEventListener这个监听来做，只能控制到某个区间，会反复调用startFullscreen()方法，这肯定是不行的，楼主有这方面现成的回调函数吗？

**Comment by lipangit** [comment]
还在研究

**Comment by lipangit** [comment]
已经添加此功能

**Comment by linfeizheng** [comment]
@lipangit 你说已经添加了，怎么实现呢

**Comment by lipangit** [comment]
参考demo的ActivityApi，进入通过重力感应进入全屏

**Comment by linfeizheng** [comment]
我将demo运行起来，ActivityApi无法自动横屏，还请帮忙

**Comment by lipangit** [comment]
感谢你的反馈，这块我也不知道原来是怎么想的 ，现在修改了
