### ISSUE TITLE
播放器放到xlistview中，在首页显示有不同的item时候，滑动xlistview，播放器会白屏没有界面只有声音，松开手后，点击事件结束，播放器会重新显示

### ISSUE THREAD

**Issue by yestin0303** [lipangit/JieCaoVideoPlayer#308]
播放器放到xlistview中，在首页显示有不同的item时候，滑动xlistview，播放器会白屏没有界面只有声音，松开手后，点击事件结束，播放器会重新显示

**Comment by lipangit** [comment]
xlistview 这是什么

**Comment by zeroci** [comment]
@yestin0303 建议更换listview组件 所谓的xlistview不怎么好用· 而且对其他view组件兼容不强，[https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh](url)  白屏可能是你cover占位了 你看是你的adapter是不是有cover

**Comment by lipangit** [comment]
必须复用item，重复setUp会release正在播放的video
