### ISSUE TITLE
请问播放视频时熄屏怎么解决啊？

### ISSUE THREAD

**Issue by itlws** [lipangit/JieCaoVideoPlayer#309]
请问播放视频时熄屏怎么解决啊？

**Comment by itlws** [comment]
是要自己手动调用PowerManager的方法来实现么？

**Comment by lipangit** [comment]
熄屏activity会onpause会重置视频，熄屏暂停功能还在酝酿

**Comment by itlws** [comment]
呃呃，是这样的，我使用的是老版本的源码sdk，好像是3.几的吧？原来的源码sdk全屏播放时打开的是JCFullScreenActivity，是这个Activity在播放的时候，会出现熄屏现象，我在onCreate方法里添加了    getWindow().setFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON,WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);设置，现在不会出现熄屏现象了，是不是更新到最新的sdk就没有这个问题了啊？

**Comment by lipangit** [comment]
熄屏问题已经解决，请保持用最新版

**Comment by itlws** [comment]
OK，谢谢了～
