### ISSUE TITLE
Leaked Memory

### ISSUE THREAD

**Issue by chazcharles** [lipangit/jiecaovideoplayer#31]
i found this log from leakcanary

* GC ROOT thread java.util.Timer$TimerImpl.<Java Local> (named 'Timer-3')
* references fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$2.this$0 (anonymous class extends  java.util.TimerTask)
* references fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.mContext

how can i avoid this memory leak issue?

**Comment by lipangit** [comment]
Yes we have two timer in JCVideoPlayer, One for update progress in bottom seekbar , another for dismiss bottom bar and title , Maybe activity already destroy then call time run() function the function call getContext() , it will cause memery leak.
I will test this function later , 
Add you to Collaborators ,I think you are working on it ,If you have some progress push directly.

**Comment by lipangit** [comment]
@chazcharles perfect , we make the library better together.
