### ISSUE TITLE
RecyclerView  黑屏

### ISSUE THREAD

**Issue by JamesGZM** [lipangit/JieCaoVideoPlayer#312]
播放视频没有图像只有声音

**Comment by JamesGZM** [comment]
好吧 我进行了测试  写死视频链接是有用的  但是用以前的视频链接显示黑屏  可能是格式不对吗 
链接：http://pic.4g.jxnews.com.cn/newwebdownload/video/20151026/1445822613323492.mp4 
这个下载下来是有用的

**Comment by JamesGZM** [comment]
这种下载下来才能看的视频有支持吗

**Comment by lipangit** [comment]
以前也遇到过这种视频源的问题，应该和recycleView没关系，不知道为什么有一种mp4在浏览器里能播放，但是用节操视频播放器就播放不了

**Comment by JamesGZM** [comment]
感觉像是编译ijkplayer的问题了  默认是不开启这个格式的解码的  
希望能够给上ijkplayer的编译完成之后 的文件

**Comment by lipangit** [comment]
用的maven仓库里的ijkplayer没有编译文件。。
