### ISSUE TITLE
全屏播放状态栏仍然没有隐藏

### ISSUE THREAD

**Issue by KKJJ** [lipangit/JieCaoVideoPlayer#313]
因为有设置 沉浸式状态栏，在全屏播放时 状态栏仍然可见 可有解？

**Comment by lipangit** [comment]
JCVideoPlayer的ACTION_BAR_EXIST，TOOL_BAR_EXIST
这两个参数手动控制toolbar和actionbar显示与否

**Comment by KKJJ** [comment]
能否说的再详细一点  不知道怎么设置    我用的是JCVideoPlayerStandard，没有自定义界面，尝试去设置你说的那两个值为false，后又改为true，均不见效果  仍然有状态栏

**Comment by KKJJ** [comment]
4.4.2系统，下面是状态栏着色代码
`      //只对api19以上版本有效
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            setTranslucentStatus(true);
        }
        //为状态栏着色
        SystemBarTintManager tintManager = new SystemBarTintManager(this);
        tintManager.setStatusBarTintEnabled(true);
        tintManager.setStatusBarTintResource(R.color.colorPrimary);
    

    @TargetApi(19)
    private void setTranslucentStatus(boolean on) {
        Window win = getWindow();
        WindowManager.LayoutParams winParams = win.getAttributes();
        final int bits = WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS;
        if (on) {
            winParams.flags |= bits;
        } else {
            winParams.flags &= ~bits;
        }
        win.setAttributes(winParams);
    }`

**Comment by YuJunKui2016** [comment]
之前有试过沉浸式通知栏的问题。
1、通知栏为一种颜色
2、通知栏为图片的一部分
当情况为1的时候同样使用你上面的代码，没问题
当情况为2的时候则上面代码基本无用。需设置根局部 android:fitsSystemWindows="true"
并且在布局预留出通知栏高度即可
下面回到你的问题，测试使用方案二即可解决全屏下沉浸式通知栏仍然显示的问题

**Comment by lipangit** [comment]
多谢提供方案

**Comment by YuJunKui2016** [comment]
都是 @lipangit 大神在帮我们解决视频播放问题

**Comment by LinkSy** [comment]
@jkdevKK 我出现了和你同样的问题 请问 你是如何解决的
