### ISSUE TITLE
红米note2闪退

### ISSUE THREAD

**Issue by MonkeyEatBanana** [lipangit/JieCaoVideoPlayer#314]
一进视频页就闪退了，系统5.0.1

**Comment by lipangit** [comment]
我用红米note3，没发现这种情况，log是什么

**Comment by yonzeo** [comment]
设备
vivo X6D(vivo)
系统版本
 Android 5.1,level 22
jar 4.6.1
java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.flyant.android.sf-2/base.apk"],nativeLibraryDirectories=[/data/app/com.flyant.android.sf-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
java.lang.Runtime.loadLibrary(Runtime.java:366)
java.lang.System.loadLibrary(System.java:988)
tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:205)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:196)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init>(JCMediaManager.java:55)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:49)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:755)

**Comment by frpan47** [comment]
同闪退,报java.lang.UnsatisfiedLinkErro异常,couldn't find "libijkffmpeg.so"

**Comment by frpan47** [comment]
直接添加你的依赖库,不需要有so库吗?

**Comment by lipangit** [comment]
compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.1'

添加其他CPU架构的依赖

**Comment by yonzeo** [comment]
把楼上的 加上就可以了   compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'   这个

**Comment by imknown** [comment]
@lipangit Readme 看来需要补充了, 很多人 不知道 BILIBILI 都...

**Comment by lipangit** [comment]
@imknown 没错，先酝酿酝酿，然后把readme好好弄弄

**Comment by yaojie520** [comment]
![image](https://cloud.githubusercontent.com/assets/18596432/18079198/ff24177a-6ec1-11e6-9f79-b929e5c5de9a.png)

**Comment by lipangit** [comment]
除了armv5别的都加上吧

**Comment by imknown** [comment]
@yaojie520 看看是不是 其他第三库 不支持 arm64
