### ISSUE TITLE
关于全屏的时候，怎么添加旋转动画的问题？

### ISSUE THREAD

**Issue by smallflybird** [lipangit/JieCaoVideoPlayer#315]
您好 请问 全屏的时候，怎么添加旋转动画？

**Comment by YuJunKui2016** [comment]
JCVideoPlayer类中startWindowFullscreen方法中的jcVideoPlayer就是全屏view对象。可以在这里试试

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/17930353/5a5367b0-6a38-11e6-9eb9-92379d543deb.png)
你把这两行注释去掉就有动画，但是非常生硬且有停顿，效果不好
