### ISSUE TITLE
vivo X6D(vivo)  Android 5.1,level 22    4.6.1   闪退  couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by yonzeo** [lipangit/JieCaoVideoPlayer#316]
设备
vivo X6D(vivo)
系统版本
Android 5.1,level 22
jar 4.6.1
已经 继承AppCompatActivity

java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.flyant.android.sf-2/base.apk"],nativeLibraryDirectories=[/data/app/com.flyant.android.sf-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libijkffmpeg.so"
java.lang.Runtime.loadLibrary(Runtime.java:366)
java.lang.System.loadLibrary(System.java:988)
tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:157)
tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:168)
tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:209)
tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:205)
tv.danmaku.ijk.media.player.IjkMediaPlayer.(IjkMediaPlayer.java:196)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.(JCMediaManager.java:55)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance(JCMediaManager.java:49)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:755)

**Comment by Joyce1991** [comment]
自己加上就好了
```java
dependencies {
    # required, enough for most devices.
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.1'

    # Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.1'

    # ExoPlayer as IMediaPlayer: optional, experimental
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.6.1'
}
```

**Comment by lipangit** [comment]
既然安卓有多重CPU架构的机型，所有这些库都应该在ijkplayer的包里都应该添加，难道使用ijkplayer的app是专门为某个机型的吗，但是ijkplayer把他们分开了

**Comment by yonzeo** [comment]
谢谢  @Joyce1991
