### ISSUE TITLE
列表点击全屏播放闪退

### ISSUE THREAD

**Issue by wangyi1993** [lipangit/JieCaoVideoPlayer#317]
![image](https://cloud.githubusercontent.com/assets/16251081/17966767/e1a968fa-6af5-11e6-92a2-96305d1ad204.png)

**Comment by lipangit** [comment]
容易复现吗，有什么线索吗，哪个view是null?

**Comment by wangyi1993** [comment]
复现啊  是一直出现  日志看不到哪个View 是null 这是全部的报错   就是正在播放的时候 点击全屏按钮就闪退

**Comment by wangyi1993** [comment]
我是在activity 中的fragment 里面有个listview 在listview item中全屏崩溃  但是我加上这段透明状态栏的代码后就正常了 
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Window window = getWindow();
            window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.setStatusBarColor(Color.TRANSPARENT);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            getWindow().addFlags(
                    WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
        }

**Comment by lipangit** [comment]
setSystemUiVisibility调用这个函数之前是不是要先判断一下
