### ISSUE TITLE
支持X86 CPU吗

### ISSUE THREAD

**Issue by ADL1121** [lipangit/JieCaoVideoPlayer#321]

**Comment by lipangit** [comment]
支持

# required, enough for most devices.
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.6.1'

    # Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.1'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.1'

    # ExoPlayer as IMediaPlayer: optional, experimental
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.6.1'

**Comment by ADL1121** [comment]
把下面的拷进去
compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.6.1'
compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'
compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.1'
compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.1'
在模拟器中还是会播放失败啊，是要在真机中才有用吗？谢谢你的回复

**Comment by lipangit** [comment]
应该是在真机才好用，我记得系统的MediaPlayer在模拟器中也播放不了
