### ISSUE TITLE
播放本地视频被旋转

### ISSUE THREAD

**Issue by liujinchaoDS** [lipangit/JieCaoVideoPlayer#322]
使用JCVideoPlayerStandard播放本地视频，左旋了90度

**Comment by lipangit** [comment]
放到浏览器是正常的吗，https://github.com/Bilibili/ijkplayer  放到这里库的demo里看看是不是也旋转了

**Comment by liujinchaoDS** [comment]
在他的demo里也是旋转的，但是在demo的设置中允许TextureView之后就正常了，请问如何设置可以开启？ https://github.com/Bilibili/ijkplayer/issues/707 此问题中建议使用TextureView。

**Comment by lipangit** [comment]
我们用的就是TextureView

**Comment by lipangit** [comment]
建议尝试其他的mp4文件，比如把我们demo中的视频文件下载下来放到本地，肯定是正的，还是mp4的猫腻

**Comment by liujinchaoDS** [comment]
我使用的是华为和小米手机录制的视频，用你们demo里的视频是正确的，手机录制的视频就不行。是否录制的视频文件中有旋转信息没有处理？下面是Bilibili里IjkVideoView的log
`08-29 09:37:34.637 27384-27384/tv.danmaku.ijk.media.example D/IjkVideoView: MEDIA_INFO_VIDEO_ROTATION_CHANGED: 90
                                                                            
                                                                            [ 08-29 09:37:34.637 27384:27384 E/         ]
                                                                            SurfaceView doesn't support rotation (90)!`
这里显示了视频需要旋转90度，但SurfaceView不支持旋转所以出现问题，使用demo中的TextureRenderView就可以旋转。

**Comment by lipangit** [comment]
@liujinchaoDS 老臣对录制视频理解不深，之前公司的项目有涉及到录制视频的功能是其他同事做的，确实有方向问题，建议用第三方的录制视频的库做这个功能

**Comment by liujinchaoDS** [comment]
我没有找到很好的录制视频的库，有推荐么？
Bilibili的demo中播放视频的控件IjkVideoView是有视频旋转的功能的，能否集成到您的项目里？
在您的JCVideoPlayer中的onInfo方法中可以得到视频的旋转信息
`what == IMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED`
此时，extra表示旋转角度，但需要重新计算JCMediaManager.textureView的比例，使视频能在控件内播放，JCMediaManager.textureView.setRotation(extra);可以旋转到正确的角度。

**Comment by lipangit** [comment]
都是public的，你可以自己设置

**Comment by liujinchaoDS** [comment]
我该如何调整textureView使视频旋转后能重新缩放？

**Comment by lipangit** [comment]
首先你要知道这个视频旋转多少才是正的

然后JCMediaManager.textureView.setRotation(extra)，这个貌似能用

**Comment by liujinchaoDS** [comment]
我继承JCResizeTextureView，在onMeasure中调整宽高比就OK了

**Comment by lipangit** [comment]
恭喜
