### ISSUE TITLE
请教logo添加播放页面

### ISSUE THREAD

**Issue by a137235** [lipangit/JieCaoVideoPlayer#323]
看到100%的在线视频软件，都会在左上角或者右上角添加水印，这种是假的水印，但为何全屏跳转或者其它动作那个水印基本没变化，这是怎么实现的呢？

**Comment by lipangit** [comment]
添加一个放logo的组件吗，我见到的水印都是合成到视频里的

**Comment by a137235** [comment]
没有吧，我把那些视频抓包出来是没有logo，而在播放的时候显示了的

**Comment by lipangit** [comment]
难道logo是本地的图片

**Comment by a137235** [comment]
应该就是，因为我反编译看到过相应的logo，就是不知道怎样实现比较好。。。

**Comment by YuJunKui2016** [comment]
你可以尝试下载源码 然后在工程依赖，在源码的xml中添加一个你们自己的logo(直接覆盖上去就可以)。不过还是建议上传前或者云服务器处理水印

**Comment by a137235** [comment]
我就只添加个logo而已，并没有其它用途，完全不需要底层来实现吧，我觉得可以通过在上层添加个imageview，但是位置可能不容易控制。。。。

**Comment by YuJunKui2016** [comment]
刚刚想错了。也必要修改源码。不过源码算不上底层的东西。有时间可以看看
回到你的问题。你可以参考Demo中的CustomView包里面的。定制播放器控件的例子进行添加一个logo  然后把项目里使用的JCVideoPlayerStandard改成你自定义的即可

**Comment by a137235** [comment]
我觉得添加个logo对软件宣传很不错，而且又不影响观影效果，框架应该可以添加下晒。。

**Comment by lipangit** [comment]
这时候自定义ui就派上用场了
