### ISSUE TITLE
moov not found

### ISSUE THREAD

**Issue by zhanghaoit445** [lipangit/JieCaoVideoPlayer#324]
你好 我通过使用此项目做一个网络视频播放的功能但是在播放的时候有时候出现moov not found  
  moov信息找不到导致解析mp4文件出错，但是同一个mp4文件有时候可以播放有时候会报错，不知道为什么请问您有遇到过么？
  jc_play_presseda08-26 18:01:59.327: 
08-26 18:01:59.325: E/IJKMEDIA(10300): moov atom not found
   E/IJKMEDIA(10300):
 http://vv.chinamil.com.cn/data/mediafile/pic/video/2016/08/26/8dc6ede80f5945cc86cf11927408b316.mp4:
 Invalid data found when processing input
08-26 18:01:59.325: E/IJKMEDIA(10300): moov atom not found
08-26 18:01:59.338: E/JieCaoVideoPlayer(10300): onError -10000 - 0 [73876588] 
08-26 18:01:59.338: E/JieCaoVideoPlayer(10300): onError -10000 - 0 [73876588]

**Comment by lipangit** [comment]
没遇到过这个问题，最好是用cdn托管视频文件比较稳定

**Comment by wangguifa** [comment]
我也遇到这个问题了  不知道什么原因  能帮我看下吗

**Comment by lipangit** [comment]
这估计是视频源的问题，找个好的稳定的视频源，我们公司也有这种情况，视频播放不了，让后台重新传一下就好了
