### ISSUE TITLE
Gravity Sensor

### ISSUE THREAD

**Issue by prophet173** [lipangit/JieCaoVideoPlayer#326]
Iv tried it, once, it was my very first solution, and... yay its easier way, but using device sensor will cause battery drain, cuz its always listening to rotation cases, so i suggest to use configChanges to preserve battery life, thats what i did...

**Comment by lipangit** [comment]
I think sensor manager is always working, even if I do not listen sensor manager, configChanges is also use sensor manager.
Battery is importent, I will test how battery drain.

I think fullscreen should not change screen direction, just call startWindowFullscreen() .

**Comment by prophet173** [comment]
sort of... but configChanges listens it to system level and not always.
well, anyway, if you do not want to change app mode, it is not better to use DisplayMetrics and Surface.Rotation? i dont really know which drains more battery, sensor or DisplayMetrics but....

**Comment by lipangit** [comment]
I will test them

**Comment by lipangit** [comment]
Sensor is ok ,try new version 4.8.1
