### ISSUE TITLE
gradle 添加之后 super报错

### ISSUE THREAD

**Issue by zzzlw** [lipangit/JieCaoVideoPlayer#327]
![image](http://i2.buimg.com/567571/2423625d64cd3aaa.jpg)

错误如图所示

**Comment by lipangit** [comment]
这只是语法和导入库的问题，你再看看

**Comment by zzzlw** [comment]
好像貌似不影响实际运行，就是一个报错，看着也挺闹心的。

**Comment by lipangit** [comment]
加油
