### ISSUE TITLE
android M 23 Issues Please fix

### ISSUE THREAD

**Issue by warkoy** [lipangit/JieCaoVideoPlayer#328]
08-29 11:16:35.879 10828-10828/com.xxxx.xxxx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.xxxx.xxxx, PID: 10828
                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.xxxx.xxxx/lib/x86/libijkffmpeg.so: has text relocations

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/18082789/fd84e44c-6ed2-11e6-88ba-e9f619b5ff23.png)
