### ISSUE TITLE
在线播放mpeg4编码的Mp4视频,只有声音没有视频. 播放h264编码的Mp4视频正常.

### ISSUE THREAD

**Issue by HaoRuiK** [lipangit/JieCaoVideoPlayer#332]

**Comment by HaoRuiK** [comment]
用了几个的其他视频播放器.都没办法同时播放两种编码的视频.不知道有没有其他的播放器推荐

**Comment by lipangit** [comment]
就靠你好好研究这个问题了

我们视频编码解码是用ffmpeg这个库做的，是最低层的，是linux运行环境，我们用的ijkplayer它这个播放器的本质可以理解成把ffmpeg这个库让它在android工作，我们这个库是更高层的封装，ijkplayer和我们都不涉及编解码的问题，你要是能找出解决办法你相当可以

**Comment by lijie815917** [comment]
那有什么办法和建议去解决这个问题吗

**Comment by HaoRuiK** [comment]
ExoPlayer可以播放,可以看下它采用的编解码方式是什么

**Comment by lipangit** [comment]
用固定的编码方式吧，我们只能去适应ijkplayer
