### ISSUE TITLE
请教一下， 能捕获视频中的某一帧吗

### ISSUE THREAD

**Issue by yangshude** [lipangit/JieCaoVideoPlayer#333]
请教一下， 能捕获视频中的某一帧吗，生成一张图片，设置到视频上

**Comment by zzzlw** [comment]
你想捕获第一帧就得先把视频下载下来，可以考虑一下，让服务器帮你做这个事情。

**Comment by lipangit** [comment]
@yangshude 暂时不知道怎么捕获，一般缩略图都是后台传上去的

**Comment by lipangit** [comment]
@yangshude 暂时不知道怎么捕获，一般缩略图都是后台传上去的

**Comment by lipangit** [comment]
可以，看库的源码有能取得当前帧
