### ISSUE TITLE
请教个关于全屏播放的问题

### ISSUE THREAD

**Issue by jyh149129** [lipangit/JieCaoVideoPlayer#335]
请问下，发现这个播放器，视频全屏后不需要重新缓冲就直接播放了，是如何实现的？，难道是直接动态改变了播放器的布局来做的吗？关键的代码能否给个链接，谢谢

**Comment by YuJunKui2016** [comment]
[http://blog.csdn.net/u013134391/article/details/52303595](url)
我博客有做分析笔记。不过不一定清晰
切全屏不需要重新缓存，是因为播放加载是由一个JCMediaManager来完成的。全屏只是切换了JCMediaManage里面的监听回调，重新设置下视频输出的Surface。
也就是说全屏的时候JCMediaManager的各种加载都是正常运行的，屏幕切换下视频输出  和 JCMediaManager的加载各种回调即可

**Comment by lipangit** [comment]
楼上正解
