### ISSUE TITLE
请问可以支持https播放吗？

### ISSUE THREAD

**Issue by Forsaken-sl** [lipangit/JieCaoVideoPlayer#336]
https播放就会返回-10000...

**Comment by lipangit** [comment]
我觉得这应该只是配置的问题
https://ffmpeg.org/ffmpeg-protocols.html

**Comment by Forsaken-sl** [comment]
我导入了一些编译的.so文件的jnilibs就好了。十分感谢。另外问一下，请问这个可以换比如那个playBtn么，或者我想自定义一些UI的显示或隐藏，比如去掉标题啊，去掉进度条啥的。

**Comment by Forsaken-sl** [comment]
其实没有也没关系，我继承了Player类然后在里面改了一下standard的布局。

**Comment by lipangit** [comment]
可以，JCVideoPlayer这个类完全不涉及UI，继承他的才涉及ui并且可以多重继承
