### ISSUE TITLE
请问有更换开始或暂停视频播放的按钮的API吗？

### ISSUE THREAD

**Issue by ancode-cn** [lipangit/JieCaoVideoPlayer#337]

**Comment by YuJunKui2016** [comment]
1、更换开始。重新开始播放  
重新setup  后调用jcVideoPlayerStandard.startButton.performClick()
2、暂时视频
jcVideoPlayerStandard.startButton.performClick()

**Comment by lipangit** [comment]
楼上正解

**Comment by 18233588665** [comment]
YuJunKui1995牛逼
