### ISSUE TITLE
请问大神如何支持在线视频的本地缓存

### ISSUE THREAD

**Issue by diaoxinqiang** [lipangit/JieCaoVideoPlayer#339]
就是说播放完在线视频后,下次再播放该视频为本地视频,请问是否有这个api呢?

**Comment by lipangit** [comment]
没有这个api，比如你看了个1G的视频难道要在sd卡上保存起来吗，估计是出于空间的考虑，手机上的播放引擎都没有缓存功能

**Comment by zabio** [comment]
多希望有这个接口 就像当初的某播一样

**Comment by lipangit** [comment]
android上所有的视频播放引擎都不支持边播放边缓存，完全不知道怎么做。

有人提出取得字节流保存起来，思路肯定没别的思路，快进怎么办，也没有接口能取出字节流

**Comment by zabio** [comment]
比较hack的做法就是开个新线程边播放边下载到本地

**Comment by lipangit** [comment]
群主表示不建议这么做，这估计是产品提的需求，技术上不太允许

**Comment by bravekingzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/4476322/20857764/ae325ea4-b970-11e6-9b0c-25f3c0008d56.png)
this may help you  .

**Comment by lipangit** [comment]
@bravekingzhang 看到了有个相关的开源项目是你的这个思路,还没仔细研究，如果快进快退能准确缓存视频那个播放时间的字节吗

**Comment by bravekingzhang** [comment]
Of course，only if the video cache is available。the same as you play a local video。

**Comment by flztsj** [comment]
https://github.com/danikula/AndroidVideoCache
使用这个库，直接很简单的把视频url封装一层后就可以边播边缓存了。

**Comment by bravekingzhang** [comment]
是的 ，但是AndroidVideoCache好像还存在一些小bug，经常会看到控制台输出一些断socket连接出现的异常，不过不会crash，但是，我也不能排除他是否会因为url的变化而导致jcvideo出现 Fatal signal 11 (SIGSEGV)

@flztsj
