### ISSUE TITLE
android M 23

### ISSUE THREAD

**Issue by pck77627** [lipangit/JieCaoVideoPlayer#340]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/xxx/lib/x86/libijkffmpeg.so: has text relocations

**Comment by lipangit** [comment]
compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.0'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.0'

include these in build.gradle

**Comment by pck77627** [comment]
![image](https://cloud.githubusercontent.com/assets/20160999/18157738/c69a7228-7051-11e6-97be-8b687e5d57d4.png)

还是不行的

**Comment by YuJunKui2016** [comment]
调用.so文件时报如下错误： 
libcooee.so: has text relocations 
说明编译.so文件时使用了较低版本sdk 
而project 中的配置 targetSdkVersion22 大于so编译时使用的sdkversion，所以只需要把功能中 
的targetSdkVersion降低即可 
defaultConfig { 
applicationId “com.example” 
minSdkVersion 16 
targetSdkVersion 22 
versionCode 1 
versionName “1.0” 
}
以上结果来自 http://blog.csdn.net/ocean20/article/details/50696923

**Comment by pck77627** [comment]
降低targetSdkVersion，我知道这个方法可以，但这是治标不治本吧。

**Comment by YuJunKui2016** [comment]
project 中的配置 targetSdkVersion22 大于so编译时使用的sdkversion  如果我引用别人的回答没问题。你就要找ijk提issuse

**Comment by yonzeo** [comment]
试试 compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.6.1'
compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.6.1'
compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.6.1'

**Comment by pck77627** [comment]
@yonzeo 试过，不行的，其它都对的，就x86没对
