### ISSUE TITLE
关于暂停黑屏的问题

### ISSUE THREAD

**Issue by xiaocaishifu** [lipangit/JieCaoVideoPlayer#341]
在正常情况下，暂停视频播放，然后按home键返回到后台，再切换到前台，这时候的屏幕是黑屏，点击播放按钮又能正常播放，这个黑屏是什么原因造成的？

**Comment by lipangit** [comment]
按home键之后Textureview 销毁进入onSurfaceTextureDestroyed方法，返回界面之后Textureview 重新初始化 进入onSurfaceTextureAvailable方法.极有可能是视频暂停的时候不会绘制图像，新初始化的Textureview没有图像

**Comment by xiaocaishifu** [comment]
有一些疑惑，为什么Activity进入暂停状态的时候(按Home键回到后台)  会执行TextureView.java的的以下这个方法，从而销毁掉TextureView，另外上面黑屏的问题有解决思路吗？

  /** @hide */
    @Override
    protected void onDetachedFromWindowInternal() {
        destroySurface();
        super.onDetachedFromWindowInternal();
    }

**Comment by lipangit** [comment]
可以尝试播放然后马上暂停，图像会不会出来，我再测试一下

**Comment by xiaocaishifu** [comment]
您好，试了您上面说的方法，我是播放后延迟100毫秒暂停的，能起到有图像的效果，但是会闪一下黑屏才会出现图像，另外这个100毫秒的时间间隔不知道是否会在某些情况下失效。

`  JCMediaManager.instance().mediaPlayer.start();
   setUiWitStateAndScreen(CURRENT_STATE_PLAYING);
   handler.sendEmptyMessageDelayed(100,100);`

`private Handler handler=new Handler(){
        @Override
        public void handleMessage(Message msg) {
            if (msg.what==100){
                JCMediaManager.instance().mediaPlayer.pause();
                setUiWitStateAndScreen(CURRENT_STATE_PAUSE);
            }
        }
    };`

**Comment by lipangit** [comment]
这种非常规的解决办法效果不好，还不如不加，不准备把这些代码放到标准的JCVideoPlayer中，还会持续关注这个问题

**Comment by YuJunKui2016** [comment]
可以在暂停切换 全屏小屏的时候获取Textureview 当前图像，然后当预览图设置上    
这个方案如果可以话。我今晚做下

**Comment by lipangit** [comment]
我觉得这个问题完美的解决办法是全屏和非全屏是相同的Textureview，这样Textureview就不会销毁

**Comment by lipangit** [comment]
如果代码够稳定的话，这样解决也不是不行

**Comment by flztsj** [comment]
已经解决了，develop上代码已经提交了。

**Comment by zynxiaonanzi** [comment]
@flztsj 为啥我现在用最新版本的,还是黑屏呢

**Comment by katherineqj** [comment]
你好 请问是怎么解决的 是截取当前帧还是textuteview不销毁啊

**Comment by lll-01** [comment]
怎么解决的呢 @SjAndy88

**Comment by lipangit** [comment]
@lll-01 这是很久的issue了，现在有这问题吗
