### ISSUE TITLE
请问视频播放完成的回调

### ISSUE THREAD

**Issue by MonkeyEatBanana** [lipangit/JieCaoVideoPlayer#344]
目前需要在视频播放完做些操作，请问怎么才能监听到视频播放完成呢？

**Comment by xiaocaishifu** [comment]
实现JCBuriedPointStandard这个接口， 然后 JCVideoPlayer.setJcBuriedPoint(new MyJCBuriedPointStandard());  Demo里面有实现。

**Comment by lipangit** [comment]
楼上说的是埋点，你如果有业务逻辑，你要继承JCVideoPlayerStandard 复写onComplete函数

**Comment by MonkeyEatBanana** [comment]
哦哦，好的，这边目前没有业务逻辑，就是播放完成弹出个对话框，问题已解决，灰常感谢大家的回答，赞一个
