### ISSUE TITLE
关闭wifi 播放本地视频的时候提示 "您当前正在使用移动网络，继续播放将消耗流量"

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#345]
<string name="tips_not_wifi">您当前正在使用移动网络，继续播放将消耗流量</string>

不知是否是我用法问题？
localPlayer.setUp(path, JCVideoPlayer.SCREEN_LAYOUT_LIST, partName);
JCVideoPlayerStandard.startFullscreen(this, JCVideoPlayerStandard.class, path, partName);

**Comment by lipangit** [comment]
就是这样提示的，没WiFi就会有提示

**Comment by AkashiWen** [comment]
soga
可我是播放本地视频 没有开流量的情况 
嗯建议除了wifi状态判断 再加上2 3 4G的判断会更完善些

**Comment by lipangit** [comment]
对对 是要这样判断

**Comment by YuJunKui2016** [comment]
@AkashiWen 本地播放的要加file:// 应该  如果开头是file的 就不会做wifi状态判断

**Comment by lipangit** [comment]
对对，下版本会这么改

**Comment by AkashiWen** [comment]
@YuJunKui2016 可以的 感谢！

**Comment by lipangit** [comment]
一直有是否播放本地视频的判断，刚才测试也是好用的
你放本地视频的时候弹出提示流量的对话框了吗？？这不应该呀，再试试

![image](https://cloud.githubusercontent.com/assets/2038071/18224741/75431b1a-7212-11e6-97c4-f56dee22ef6e.png)

**Comment by lipangit** [comment]
@AkashiWen 你说的234G检测是什么意思

**Comment by YuJunKui2016** [comment]
@lipangit 他本地播放已经可以了。234G检测 就是显示非wifi下细分   我觉得没必要搞

**Comment by lipangit** [comment]
一直是有本地视频不弹出对话框的判断的代码的，我担心是不是有些情况不管用

**Comment by lipangit** [comment]
234G都要费流量嘛，他们是一个情况

**Comment by flztsj** [comment]
应该也把无网络连接的情况分离出来

**Comment by AkashiWen** [comment]
@lipangit 嗯 我也觉得都视为流量就可以

**Comment by lipangit** [comment]
@flztsj 无网络会进入ERROR STATE，error状态，你是想无网络的话压根不会调用MediaPlayer对吧，也可以，用户也可以在播放器外面判断网络，如果库里无网络不能播放的话还要检查是否播放本地视频，本地视频无网络的时候可以播放
