### ISSUE TITLE
lastListener and listener

### ISSUE THREAD

**Issue by flztsj** [lipangit/JieCaoVideoPlayer#346]
![9b32d9b0-1166-4b5f-a530-95abf4c805dd](https://cloud.githubusercontent.com/assets/5946178/18167508/8b3499a2-7083-11e6-92b4-06f2d104684b.jpg)

            if (JCVideoPlayerManager.**lastListener()** == null) {//directly fullscreen
                JCVideoPlayerManager.**listener()**.onCompletion();
                showSupportActionBar(getContext());
                return true;
            }

why?

**Comment by lipangit** [comment]
What is your question?

**Comment by flztsj** [comment]
Why check lastListener is not null and invoke the listener.onCompletion function ?
Is it a mistake?

**Comment by lipangit** [comment]
yes ， it is a mistake

**Comment by flztsj** [comment]
看了下代码还是有问题  代码是lastListener() == null  问题里面描述成了lastListener is not null。
这块代码还是需要你重新check下，按照最新的代码会出空指针异常的

**Comment by flztsj** [comment]
按照我的理解，从全屏模式返回到窗口模式时，触发goToOtherListener，所以在goToOtherListener这里，listener()返回的是全屏模式的监听，lastListener()返回的是窗口模式的监听，所以应该是
            if (JCVideoPlayerManager.listener() != null) {//directly fullscreen
                JCVideoPlayerManager.listener().onCompletion();
                showSupportActionBar(getContext());
                return true;
            }
这边还需要你的确认

**Comment by lipangit** [comment]
对对，我蒙圈了，是当前的listener

**Comment by lipangit** [comment]
这个不影响使用，就不重新

**Comment by JupiterMx** [comment]
JCVideoPlayer中JCVideoPlayer这个方法逻辑有问题，当你初始全屏播放时，再回退就出现null 指针异常，null指针产生在453行，而为null的原因时因为设置了listener的值为lastListener

**Comment by JupiterMx** [comment]
应该改成：
if (JCVideoPlayerManager.lastListener() == null) {//directly fullscreen
                JCVideoPlayerManager.listener().onCompletion();
                showSupportActionBar(getContext());
                return true;
            }
因为lastListener为null，表示初始化显示为全屏，点击返回时结束当前（指listener）播放

**Comment by YuJunKui2016** [comment]
以前的代码是正确的  跟 @JupiterMx 贴的一样

**Comment by flztsj** [comment]
这个问题develop上已经修复
