### ISSUE TITLE
 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by yaojie520** [lipangit/JieCaoVideoPlayer#347]
![image](https://cloud.githubusercontent.com/assets/18596432/18195519/85f10868-711e-11e6-9e2a-dc3d15e966e7.png)

**Comment by lipangit** [comment]
这是什么测试工具，我记得以前也有人说过，release的时候MediaPlayer也会报这个错误

**Comment by yaojie520** [comment]
这是真机测试，vlvo手机。。。我也不知道别人是怎么测试出来的，只是我这里收到的打印log是这样的错误

**Comment by lipangit** [comment]
这用什么工具看log，牛逼呀

**Comment by yaojie520** [comment]
别逗我了，先帮我解决一下这个问题吧

**Comment by lipangit** [comment]
这个问题我先测试一下是不是MediaPlayer被release，然后seek进度会报错

**Comment by flztsj** [comment]
这个问题我也出现过，根本原因是MediaPlayer被release后又seek了。  
我出现的情况是全屏模式下，断网，出现加载错误，然后拖动进度条，App就Crash。
对应的代码我今天也提交到develop分支上了。

**Comment by lipangit** [comment]
@flztsj  这位朋友对项目的理解那是非常深的
