### ISSUE TITLE
播放本地视频时seekToInAdvance无效，在线视频没问题

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#348]
如题

主要代码如下 
    @Override
    protected void init() {
        final String path = "file://" + getIntent().getStringExtra("path");
        final String partName = getIntent().getStringExtra("partName");
        final int offset = getIntent().getIntExtra("offset", 0);
        if (offset > 0) {
            localPlayer.seekToInAdvance = offset;
        }
        localPlayer.setUp(path, JCVideoPlayer.SCREEN_LAYOUT_LIST, partName);
        JCVideoPlayerStandard.startFullscreen(this, JCVideoPlayerStandard.class, path, partName);
    }

跟了下代码，确定传入的值是1870，到源码onPrepared的时候显示是-1，然而也没看出源码里哪儿不对，比较纳闷。

**Comment by lipangit** [comment]
知道了，有时间我测测
