### ISSUE TITLE
节操 onpause生命周期暂停问题：全屏时切home--调用暂停--全屏的暂停ui没变

### ISSUE THREAD

**Issue by ximencx** [lipangit/JieCaoVideoPlayer#350]
`   if (jcVideoPlayerStandard != null && JCMediaManager.instance().mediaPlayer.isPlaying()) {
            jcVideoPlayerStandard.onEvent(JCBuriedPoint.ON_CLICK_PAUSE);
            JCMediaManager.instance().mediaPlayer.pause();
            jcVideoPlayerStandard.setUiWitStateAndScreen(JCVideoPlayer.CURRENT_STATE_PAUSE);
            //LogUitl.LogIMsg("jcVideoPlayerStandard pause");
        }`

**Comment by lipangit** [comment]
你想在activity onPause的时候暂停视频，回来继续播放是吧

你就把断点打到setUiWitStateAndScreen这个函数之内，只要ui有变化都会进这里，看看其他地方是否调用这个函数
