### ISSUE TITLE
JCVideoPlayer里的空指针异常

### ISSUE THREAD

**Issue by JupiterMx** [lipangit/JieCaoVideoPlayer#352]
JCVideoPlayer.java中的goToOtherListener方法，第444行代码空指针异常：
if (JCVideoPlayerManager.listener() == null) {//directly fullscreen
                JCVideoPlayerManager.listener().onCompletion();
                showSupportActionBar(getContext());
                return true;
}

**Comment by YuJunKui2016** [comment]
调用视频控件的 Activity要是AppCompatActivity   或者设置JCVideoPlayerStandard ACTION_BAR_EXIST为false

**Comment by flztsj** [comment]
这个问题需要 @lipangit 来解决下。 就 #346的问题，需要把逻辑重新理下，注释也明确下

**Comment by JupiterMx** [comment]
问题我想应该是解决了，具体在＃346里面我说明了，请检查下是否是这么解决。我目前测试没有问题

**Comment by YuJunKui2016** [comment]
if (JCVideoPlayerManager.lastListener() == null) {//directly fullscreen
JCVideoPlayerManager.listener().onCompletion();
showSupportActionBar(getContext());
return true;
}
就这样

**Comment by YuJunKui2016** [comment]
不对啊  判断不可能会进入   播放下listener不可能为null

**Comment by JupiterMx** [comment]
这个实际上是不为null，只是说写的这个代码写的这个代码有问题，如果为null就去调用
if (JCVideoPlayerManager.listener() == null) {//directly fullscreen
JCVideoPlayerManager.listener().onCompletion();
showSupportActionBar(getContext());
return true;
}

**Comment by flztsj** [comment]
起始应该就是下面的代码
if (JCVideoPlayerManager.lastListener() == null) {//directly fullscreen
JCVideoPlayerManager.listener().onCompletion();
showSupportActionBar(getContext());
return true;
}
JCVideoPlayerManager.lastListener()为null的话就是直接进入全屏模式的情况，而不是先是窗口模式再切换到全屏模式的。
直接进入全屏模式的情况下，JCVideoPlayerManager.listener()就不会为空，此时调用它的onCompletion()结束播放，再显示actionbar就结束了。

**Comment by flztsj** [comment]
这个问题develop上已经解决
