### ISSUE TITLE
部分手机上报：couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by NateRobinson** [lipangit/JieCaoVideoPlayer#353]
线上产品报找不到so库，引起crash，求大神指点如何加入判断控制
couldn't find "libijkffmpeg.so"
at java.lang.Runtime.loadLibrary(Runtime.java:367)
tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary (IjkMediaPlayer.java:157)
tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce (IjkMediaPlayer.java:168)
tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer (IjkMediaPlayer.java:209)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init> (IjkMediaPlayer.java:205)
tv.danmaku.ijk.media.player.IjkMediaPlayer.<init> (IjkMediaPlayer.java:196)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.<init> (JCMediaManager.java:55)
fm.jiecao.jcvideoplayer_lib.JCMediaManager.instance (JCMediaManager.java:49)
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos (JCVideoPlayer.java:751)
com.crosscourse.spritedroid.ui.fragment.p.MsgViewFragment.onPause (MsgViewFragment.java:497)

**Comment by lipangit** [comment]
引入足够的ijkplayer库

**Comment by YuJunKui2016** [comment]
android下目前有这几种架构的cpu
ARMv5，ARMv7，x86，MIPS，ARMv8，MIPS64和x86_64
你apk一般包涵以上某几种cpu架构的so文件。当应用安装在设备的时候只会把对应cpu架构的so引入。
其实一个cpu架构不只支持一种so。arm可以兼容。大部分x86的cpu可以兼容arm的，64位的cpu也可以运行32位的so，当然运行效率肯定没有对应的好，相关优化也没有，安卓碎片化的问题，很可能某个x86的cpu不支持arm兼容，或者运行起来很卡。
下面将你出现的问题，群里你说你的是运行在64位cpu下出的崩溃问题
比如我的项目中 有微博的SDK  微博可能提供了ARMv7，x86，MIPS，ARMv8，MIPS64和x86_64平台的。
当前我再去用JCVD，只引如了ijk的 armv7的包。这样我的项目会在mips   mips64  x86_64 等机器上出现crash

系统在装载So文件的时候会先检查当前cpu是否有对应的so  如果没有则查看是否有适配包的
如果没有会crash ，上面的实例中运行在mips的时候 他发现有mips的文件夹就会傻傻的认为 微博和JCVD都提供了mips的so，这样在使用JCVD的时候就会发生crash

解决你的问题 你可以结合上述 干掉某些so，其实最简单的是 设置
defaultConfig {
　　　　...
　　　　ndk {
　　　　abiFilters "armeabi-v7a",“xxcpu架构"
　　}

}
abiFilters后面保证你每个sdk提供的so都有，其实你看懂上述的内容 都不用这个配置可以搞定的
最后一点  不要以牺牲某个cpu构架的so来减少apk大小，尽可能使用更多cpu构架的so

**Comment by Haoxiqiang** [comment]
对于新版本`Build Tools`,可能会有一个`Deprecated`警告
可以在`gradle.properties`中新增一句
`android.useDeprecatedNdk=true`

**Comment by NateRobinson** [comment]
按照上面的步骤处理，已经不再遇到此问题了
