### ISSUE TITLE
窗口模式和全屏模式来回切换，出现播放“No mUrl”提示

### ISSUE THREAD

**Issue by flztsj** [lipangit/JieCaoVideoPlayer#354]
fm.jiecao.jcvideoplayer_lib.JCVideoPlayer 中的setUp中有：  
      if ((System.currentTimeMillis() - CLICK_QUIT_FULLSCREEN_TIME) < FULL_SCREEN_NORMAL_DELAY)
            return false;

加入这个判断的用意是什么？  这句话会引起我标题中描述的问题

**Comment by lipangit** [comment]
切换的时间小于500ms就会出这个问题

**Comment by flztsj** [comment]
为什么要加这个判断？

**Comment by lipangit** [comment]
列表中退出全屏，列表的setUp会一直调用，退出全屏会重置视频

**Comment by flztsj** [comment]
那我觉得不应该在setUp中加判断，而是应该在ListView中却加判断，可以增加个方法，看是否已经setUp过了。

**Comment by lipangit** [comment]
你可以写个demo试试效果，我也不想在setup中判断这个

**Comment by flztsj** [comment]
在 JCVideoPlayer 中加如下方法
    public boolean hasSetUp() {
        return !TextUtils.isEmpty(url);
    }

改写VideoListAdapter这种的getView方法
        if (!viewHolder.jcVideoPlayer.hasSetUp()) {
            boolean setUp = viewHolder.jcVideoPlayer.setUp(
                    videoUrls[videoIndexs[position]], JCVideoPlayer.SCREEN_LAYOUT_LIST,
                    videoTitles[videoIndexs[position]]);
            if (setUp) {
                ImageLoader.getInstance().displayImage(videoThumbs[videoIndexs[position]],
                        viewHolder.jcVideoPlayer.thumbImageView);
            }
        }

初步测试没有问题

**Comment by lipangit** [comment]
提交个pull request吧

**Comment by flztsj** [comment]
代码已经提交了
