### ISSUE TITLE
Play video from asset or raw folder

### ISSUE THREAD

**Issue by natig8x** [lipangit/JieCaoVideoPlayer#355]
Tried to play a video in my raw folder like this 

```
String path = "android.resource://"+  getPackageName() + '/' + R.raw.test;
videoView.setUp(path, JCVideoPlayerStandard.SCREEN_LAYOUT_DETAIL, "Test Video");
```

but it doesn't work and shows this error in the logcat "Protocol not found"

I tried to follow the instructions linked on the readme https://github.com/Bilibili/ijkplayer/issues/1013 but it's from a dependency project and the discussion is not very clear on how it applies to this library. Either way i tried some things they mentioned but that didn't work either 

```
Uri uri = Uri.parse(path);
        if(uri.getScheme().equals(ContentResolver.SCHEME_ANDROID_RESOURCE)) {
            AssetFileDescriptor fileDescriptor = null;
            try {
                fileDescriptor = getContentResolver().openAssetFileDescriptor(uri, "r");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
            IMediaDataSource dataSource = new RawDataSourceProvider(fileDescriptor);
            if(fileDescriptor != null)
                JCMediaManager.instance().mediaPlayer.setDataSource(dataSource);
            else{

                return ;
            }
        }
```

All my searches on how to do this have ended up with closed issues with no clear explanation. Maybe how to do this can be added in the sample app?

Also found this comment on the dependency project "Playback of asset file is not a completed feature, for now." https://github.com/Bilibili/ijkplayer/issues/1303 so if it's not supported yet maybe it should be removed from the readme

**Comment by YuJunKui2016** [comment]
Play video in assets you should copy to local path first.Try by myself like thistextureview will stop on first frame and error on logcat
没懂你什么意思 参见 主页这个解释

**Comment by lipangit** [comment]
I think somthing wrong with ijkplayer, ijkplayer should make function complete, should not let other people config before use.

**Comment by natig8x** [comment]
@YuJunKui2016 you're just repeating what's stated in the readme it doesn't work
@lipangit you're right...the admin him self said this on one of the issues "Playback of asset file is not a completed feature, for now." https://github.com/Bilibili/ijkplayer/issues/1303
Perhaps there's something we can do to allow it to play local files? I'll look into it...

**Comment by lipangit** [comment]
5.0+support assert video

**Comment by LSDsl** [comment]
@lipangit How? I tried use url "file:///android_asset/test.mp4", but this not work.

**Comment by lipangit** [comment]
Play video in asset folder, see demo ActivityApiCustomMediaPlayer.java， it will show you how to custom video player
