### ISSUE TITLE
关于快进，快退的问题

### ISSUE THREAD

**Issue by smallflybird** [lipangit/JieCaoVideoPlayer#356]
有一个100秒的视频，我直接拉到100秒最后(快进)，但是视频播放的时候是从95秒开始的，其他的任何时间都是这样，提供的Demo上也存在这样的问题，请问这是什么原因造成的？

**Comment by lipangit** [comment]
确实，持续关注这个问题，你要是有什么发现记得和我说一声

**Comment by lipangit** [comment]
不是什么大问题，可以忍
