### ISSUE TITLE
on start button click

### ISSUE THREAD

**Issue by abbasalim** [lipangit/JieCaoVideoPlayer#359]
hello i want to stop my media player when start video , why must i do it ?

**Comment by lipangit** [comment]
if video is playing , you click start video , it will stop.

**Comment by abbasalim** [comment]
no music is playing

**Comment by lipangit** [comment]
You should describe in detail what you want

**Comment by abbasalim** [comment]
i have two musicplayer and two JieCaoVideoPlayer
 in a activity,i want to stop my media player when start video

**Comment by lipangit** [comment]
Two way
1.Same as MyJCBuriedPointStandard in MainActivity
2.Extends JCVideoPlayerStandard override prepareVideo() function
