### ISSUE TITLE
关于只有声音没有图像的问题

### ISSUE THREAD

**Issue by puyafeng** [lipangit/JieCaoVideoPlayer#361]
能正常播放的视频，我用格式工程进行格式转换后(mp4,mov，其他格式没有尝试)，发现都只能播放出声音，没有图像，但是ios的的播放控件可以播放，android 的universalVideoView也可以播放，不知道是格式工厂转码的问题还是别的什么问题

**Comment by lipangit** [comment]
这个应该是ijkplayer的配置问题，好多人反应你这个问题，能给个有问题的mp4文件或链接吗 我测试一下

**Comment by itlws** [comment]
我也遇到了这个问题，http://movement.gzstv.com/streams/video_url/835/ 这是一个链接

**Comment by lipangit** [comment]
这个链接在chrome里播放也没有图像只有声音，看来mp4的猫腻也有很多

**Comment by itlws** [comment]
打印日志，提示No codec could be found with id 13这个警告

09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: max_frame_duration: 10.000
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://movement.gzstv.com/streams/video_url/835/':
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:   Metadata:
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     major_brand     : 
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: isom
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     minor_version   : 
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 512
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     compatible_brands: 
09-09 20:13:46.791 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: isomiso2mp41
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     encoder         : 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: Lavf54.6.100
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:   Duration: 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 00:01:59.24
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , start: 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 0.000000
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , bitrate: 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 1909 kb/s
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Stream #0:0
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: (und)
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: : Video: mpeg4 (mp4v / 0x7634706D), none, 720x576, 1776 kb/s
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 25 fps, 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 25 tbr, 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 25 tbn, 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 25 tbc
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:  (default)
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Metadata:
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:       handler_name    : 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: VideoHandler
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Stream #0:1
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: (und)
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 127 kb/s
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:  (default)
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Metadata:
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:       handler_name    : 
09-09 20:13:46.792 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SoundHandler
09-09 20:13:46.794 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
09-09 20:13:46.794 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_Android_AudioTrack: ENCODING_PCM_16BIT
09-09 20:13:46.801 23855-23937/fm.jiecao.jiecaovideoplayer D/AudioTrack: audiotrack 0x7f6f89c100 set Type -1, rate 44100, fmt 1, chn 3, fcnt 4096, flags 0000
09-09 20:13:46.802 23855-23937/fm.jiecao.jiecaovideoplayer D/AudioTrack: mChannelMask 0x3
09-09 20:13:46.804 23855-23937/fm.jiecao.jiecaovideoplayer D/AudioTrackCenter: addTrack, trackId:0x7f5e5da000, frameCount:4096, sampleRate:44100, trackPtr:0x7f6f89c100
09-09 20:13:46.804 23855-23937/fm.jiecao.jiecaovideoplayer D/AudioTrackCenter: mAfSampleRate 44100, sampleRate 44100, AfFrameCount 1024 , mAfSampleRate 44100, frameCount 4096
09-09 20:13:46.805 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
09-09 20:13:46.805 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: audio_session_id = 271
09-09 20:13:46.806 23855-23937/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: AudioCodec: avcodec, aac
09-09 20:13:46.806 23855-23937/fm.jiecao.jiecaovideoplayer W/IJKMEDIA: No codec could be found with id 13
09-09 20:13:46.806 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_get_msg: FFP_MSG_PREPARED
09-09 20:13:46.806 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: FFP_MSG_PREPARED:
09-09 20:13:46.806 23855-23954/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_RunThread: [23954] ff_audio_dec
09-09 20:13:46.807 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: FFP_MSG_BUFFERING_START:
09-09 20:13:46.807 23855-23855/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onPrepared  [198049015] 
09-09 20:13:46.807 23855-23855/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_start
09-09 20:13:46.807 23855-23855/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_start()
09-09 20:13:46.807 23855-23855/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_start()=0
09-09 20:13:46.808 23855-23953/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_RunThread: [23953] ff_aout_android
09-09 20:13:46.809 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_get_msg: FFP_REQ_START
09-09 20:13:46.811 23855-23953/fm.jiecao.jiecaovideoplayer D/AudioTrack: pause 0x7f6f89c100
09-09 20:13:46.811 23855-23953/fm.jiecao.jiecaovideoplayer D/android.media.AudioTrack: [HSM] AudioTrace pause() uid: 10218, pid: 23855
09-09 20:13:46.814 23855-23956/fm.jiecao.jiecaovideoplayer V/JieCaoVideoPlayer: onProgressUpdate 0/119240 [923589511] 
09-09 20:13:46.822 23855-23855/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
09-09 20:13:46.824 23855-23855/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
09-09 20:13:46.825 23855-23958/fm.jiecao.jiecaovideoplayer V/JieCaoVideoPlayer: onProgressUpdate 0/119240 [893223506] 
09-09 20:13:47.125 23855-23958/fm.jiecao.jiecaovideoplayer V/JieCaoVideoPlayer: onProgressUpdate 0/119240 [893223506] 
09-09 20:13:47.317 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: FFP_MSG_BUFFERING_END:
09-09 20:13:47.319 23855-23855/fm.jiecao.jiecaovideoplayer V/JieCaoVideoPlayer: onBufferingUpdate 1 [198049015] 
09-09 20:13:47.319 23855-23855/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
09-09 20:13:47.322 23855-23953/fm.jiecao.jiecaovideoplayer D/android.media.AudioTrack: [HSM] AudioTrace play() uid: 10218, pid: 23855
09-09 20:13:47.323 23855-23964/fm.jiecao.jiecaovideoplayer V/JieCaoVideoPlayer: onProgressUpdate 0/119240 [106015011] 
09-09 20:13:47.323 23855-23953/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: avcodec/Audio: first frame decoded
09-09 20:13:47.323 23855-23935/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: FFP_MSG_AUDIO_RENDERING_START:

**Comment by lipangit** [comment]
我感觉ffmpeg是支持播放它的，但是到了ijkplayer这层需要配置，再编译才能支持

**Comment by lijie815917** [comment]
这个问题解决了了吗，我也遇到了同样的问题

**Comment by lijie815917** [comment]
直接去ijkpayer，选择三个配置中的第一个，放开mpeg4,重新编译ffmpeg库，总之按readme的教程来就可以了，最后在用aar包替换掉当前的gradle依赖就可以了

**Comment by lijie815917** [comment]
对了，这个貌似ijkplayer0.61版本后才支持的，有兴趣的可以加群568707322，一起学习探讨

**Comment by lipangit** [comment]
引擎换成exoplayer之后可以播放了，过几天及时升级JCVD版本
