### ISSUE TITLE
希望可以增加对surface状态的回调接口，方便使用的时候自己加入想要做的事

### ISSUE THREAD

**Issue by shixiangyu** [lipangit/JieCaoVideoPlayer#363]

**Comment by lipangit** [comment]
继承JCvideoPlayerStandard，复写surface相关的函数

**Comment by shixiangyu** [comment]
就是这样做的，但在切屏的时候会报你所添加的listeener为空指针异常，一旦切屏那就不是同一个listener了！

**Comment by lipangit** [comment]
Textureview生命周期的回调函数中会把surface的变量传过来，这个函数只能操作当前的listener。

要么把相关部分代码截个图，把目的描述一下给你研究一下。
