### ISSUE TITLE
我想把ijk换了 但是全屏切换时 进度没法保存 

### ISSUE THREAD

**Issue by jianwenzhao** [lipangit/JieCaoVideoPlayer#364]

**Comment by lipangit** [comment]
保存进度具体逻辑是什么，卡在哪步了

**Comment by jianwenzhao** [comment]
我直接把IMediaPlayer改成MediaPlayer了 全屏切换时直接显示错误界面了 然后点击重新加载了 就是视频重新播放了 请问一下需要改下哪里吗

**Comment by lipangit** [comment]
error后的重新播放是不保存进度的，如果你需要这个功能你要自己做
