### ISSUE TITLE
希望可以添加手势亮度！

### ISSUE THREAD

**Issue by Destiny01** [lipangit/JieCaoVideoPlayer#365]

**Comment by lipangit** [comment]
这个我也很纠结，我们的信念是高仿今日头条，各种细节努力相同，他没有手势亮度，我也想加，但是想到我们的信念就没加，如果这功能对你来说是刚需 可以继承JCvideoPlayerStandard  复写相关函数自行添加

**Comment by lipangit** [comment]
当我们添加手势亮度的时候意味着我们要超越头条的束缚，暂时还没有这个那啥

**Comment by Destiny01** [comment]
好吧！
