### ISSUE TITLE
关于缓冲暂停和HTTPS的问题

### ISSUE THREAD

**Issue by smallflybird** [lipangit/JieCaoVideoPlayer#366]
您好，有两个问题咨询一下：
1、能否暂停视频的缓冲？(使用场景：在用户使用移动流量的情况下，暂停视频的话，需要同时暂停视频的缓冲，尽可能的节省用户流量)
2、是否支持播放视频地址为HTTPS的资源？

**Comment by lipangit** [comment]
1.ijkplayer如果有这个设置，你可以调用全局变量JCMediaPlayer.instance().mediaPlayer来设置

2.https资源需要打开https的配置重新编译ijkplayer

**Comment by xiaocaishifu** [comment]
“https资源需要打开https的配置重新编译ijkplayer” 这个问题能否再详细解释一下，我应该如何做？

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/18428596/6bd0f39a-7901-11e6-83f7-c1eda6c4674d.png)好像就在这些脚本里控制，然后替换JiecaoVideoPlayer中ijkplayer

我记得之前有人提过，enable-https=true,这类的，但是具体我也没做过
