### ISSUE TITLE
show image on finish video

### ISSUE THREAD

**Issue by mbf5923** [lipangit/JieCaoVideoPlayer#368]
hi
i have two questions:
one:
how i can show an image on player when video is finished?
my class is extends AppCompatActivity and i cant use override onCompletion.
and two:
thumbImageView.setScaleType(ImageView.ScaleType.FIT_START) not work correctly and no make change on showing thumb
im using 
`ImageLoader imageLoader = ImageLoader.getInstance();
                        DisplayImageOptions options;
                        options = new DisplayImageOptions.Builder()

                                .cacheInMemory(true)
                                .cacheOnDisk(true)
                                .considerExifParams(true)
                                .bitmapConfig(Bitmap.Config.RGB_565)
                                .displayer(new RoundedBitmapDisplayer(20))
                                .build();
                        imageLoader.init(ImageLoaderConfiguration.createDefault(sp));

                        jcVideoPlayerStandard.thumbImageView.setScaleType(ImageView.ScaleType.FIT_START);
                        imageLoader.displayImage(MyApplication.siteurl + thumb,
                                jcVideoPlayerStandard.thumbImageView, options);`
thanx

**Comment by lipangit** [comment]
1.when video finish , thumb will show,   is this you want?

2.You can set scal type in xml, ScalType is always work.

**Comment by mbf5923** [comment]
yes when video finish show thumb again but i want show  different thumb.
how i can set ScaleType in xml? in Attr.xml?

**Comment by lipangit** [comment]
If you want to show different thumb , you can add new imageview in layout.xml , override setUiWitStateAndScreen() you can control your new imageview, and other viewcontrol
