### ISSUE TITLE
RecyclerView notifyItemChanged(); 播放器界面会重置

### ISSUE THREAD

**Issue by DonaldMouse** [lipangit/JieCaoVideoPlayer#369]
你好，我项目中有个视频列表，用的是RecyclerView，同时可以为每条视频点赞。 当我点赞时notifyItemChanged()，然后播发器界面后重置到一开始的状态，而声音还在继续播放。 然后我在setUp方法中加入
 if (currentState != -1) {
      return false;
 }
进行拦截后，一次刷新重置到初始状态，再次刷新就回到正常播放画面。 纠结了好久一直没找到哪的问题

**Comment by lipangit** [comment]
只要代码走setUp视频就会重置，notifiDataChange这类函数肯定会进入setUp的

**Comment by lipangit** [comment]
点赞别刷新列表，只修改要修改的控件的text的就好了

**Comment by flztsj** [comment]
Develop分支的代码可以试试看

**Comment by DonaldMouse** [comment]
好像和notifyItemChanged()的刷新机制有关，adapter中拦截了刷新时重新setup 仍然这样，只是重置了界面，视频还是在继续播放的。 换成notifiDataChange() 就不会重置界面了， 但还是会闪一下

**Comment by lipangit** [comment]
notifyItemChanged的时候好像岂止是会闪，好像还会重置正在播放的视频
