### ISSUE TITLE
Remove animation when startFullscreen in this release

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#370]
Because this animation is not beautiful, animation at start time is fast , but finish time is slow , it will good.

如果动画在开始的时候运动的快，在结束的时候运动的慢，这样就好了

**Comment by flztsj** [comment]
试试Interpolator

**Comment by lipangit** [comment]
@flztsj 没错，但是用起来效果还是不够流畅，界面会先顿一下，然后才能开始动画
