### ISSUE TITLE
关于全屏播放

### ISSUE THREAD

**Issue by JupiterMx** [lipangit/JieCaoVideoPlayer#374]
你好，我在正常模式下播放，点击全屏按钮，进入全屏模式播放。播放结束后会自动退出全屏模式。这个时候我想继续播放下一个视频就不行了。请问是否有方法让我继续在全屏模式下播放下一个视频

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写onAutoComplete函数，通过回调或者eventbus去出触发下一个视频的startButton，点击startButton就播放下一个视频了

**Comment by DonaldMouse** [comment]
请问onAutoComplete和onCompletion 有什么区别  回调时机有什么不同  在代码中没有找到onAutoComplete是什么时候被回调的

**Comment by lipangit** [comment]
onAutoComplete是视频播放完毕自动调用的

onCompletion这是在A视频播放的时候，启动B视频，可以调用A视频的onCompletion，重置A的UI
