### ISSUE TITLE
找不到JCMediaManager?

### ISSUE THREAD

**Issue by CodingCodersCode** [lipangit/JieCaoVideoPlayer#378]
add xxx.aar to /libs/ ,
add  compile(name: 'jiecaovideoplayer-4.6.5', ext: 'aar') to  dependencies{}
add repositories{
    flatDir{
        dirs 'libs'
    }
}

but when i play video,i got the follow error:
java.lang.NoClassDefFoundError: Failed resolution of: Lfm/jiecao/jcvideoplayer_lib/JCMediaManager;
……
 Caused by: java.lang.ClassNotFoundException: Didn't find class "fm.jiecao.jcvideoplayer_lib.JCMediaManager" on path: DexPathList.........

Why???

**Comment by lipangit** [comment]
compile 'fm.jiecao:jiecaovideoplayer:4.6.5'
把上面配置的放到中 build.gradle吧

引入的不对

**Comment by FZJL** [comment]
我也碰到这个问题了
直接添加节操的 aar包 不够啊
还需要 ijkplayer 的包

改成  compile 'fm.jiecao:jiecaovideoplayer:4.6.5'  之后会自动下载 ijkplayer 的包
不过 它提示我  要更新 appcompat-v7:24.1.1'

**Comment by coderAndyYe** [comment]
我也这个问题，能帮忙解决下？

**Comment by lipangit** [comment]
姿势不对
