### ISSUE TITLE
如何让视频循环播放或移动到初始位置

### ISSUE THREAD

**Issue by liujinchaoDS** [lipangit/JieCaoVideoPlayer#379]
在视频播放结束时如何重新从头播放？onAutoCompletion里直接调用播放会出现准备的动画，或者有可以移动到初始位置的方法。

**Comment by lipangit** [comment]
mLoop这个变量设成true，会自动循环播放

**Comment by liujinchaoDS** [comment]
最新代码改成了looping这个变量，设置了这个可以循环，但是播放结束到下次播放中间会有prepare的动画，能不能直接移动到0的位置播放，省去prepare动画。

**Comment by lipangit** [comment]
这个是ijkplayer的问题，系统的android.media.MediaPlayer就不会prepare

你如果继承JCVideoPlayerStandard，复写相关函数，去掉循环的prepare动画
