### ISSUE TITLE
m3u8 stream doesn't start

### ISSUE THREAD

**Issue by carmelo-ruota** [lipangit/jiecaovideoplayer#38]
This library works fine with mp4 stream, but not with HLS stream.

**Comment by carmelo-ruota** [comment]
One workaround could be to change JCVideoPlayer.setProgressAndTimeFromTimer() method form:
`int progress = position * 100 / duration;`
to
`int progress = position * 100 / (duration==0?1:duration);`
However, the stream starts but showing a black screen on android 4.x

**Comment by lipangit** [comment]
Hello @carmelo-ruota your advice will work, you must look the library carefully, add you to Collaborators you can push the fix directly.

**Comment by lipangit** [comment]
HLS problem see : #20
