### ISSUE TITLE
请求关于缓冲暂停和HTTPS的问题的详解

### ISSUE THREAD

**Issue by smallflybird** [lipangit/JieCaoVideoPlayer#383]
这是在ijkplayer上提的问题，其中第二个答案貌似能解决，但是看不太明白，楼主能否给解释一下，点击链接可以查看

https://github.com/Bilibili/ijkplayer/issues/1967

问题概述：
“ 有两个问题咨询一下：
1、能否暂停视频的缓冲？(使用场景：在用户使用移动流量的情况下，暂停视频的话，需要同时暂停视频的缓冲，尽可能的节省用户流量)
2、是否支持播放视频地址为HTTPS的资源？ ”

**Comment by lipangit** [comment]
1.可能没办法，做不了
2.首先你要学会用默认配置编译ijkplayer，然后研究ijkplayer的配置都有哪些，做出修改后再编译，么么哒，加油

**Comment by xiaocaishifu** [comment]
1、修改MAX_QUEUE_SIZE的大小，现在默认是15m，setoption可以修改
2、init-android-openssl.sh，compile-openssl.sh，然后重新编译ffmpeg
这个第一句话是什么意思?是针对第一个问题的吗？

**Comment by lipangit** [comment]
第二个问题

**Comment by xiaocaishifu** [comment]
1、第一问题就没办法解决了？
2、“修改MAX_QUEUE_SIZE的大小，现在默认是15m，setoption可以修改” 这句话的内容跟HTTPS有关系么？

**Comment by lipangit** [comment]
2.你可以尝试编译一下

**Comment by DavyLin** [comment]
https 是不支持吗？

**Comment by lipangit** [comment]
@DavyLin 默认不支持https

**Comment by DavyLin** [comment]
@lipangit 你好，我查了相关资料，我也把ijkplayer重编了（加入了openssl的配置），是不是在可以在gradle 那边配置，引用自己重编后的lib或者ijk项目，达到支持https的功能；

**Comment by lipangit** [comment]
这种情况建议你引用aar

**Comment by DavyLin** [comment]
@lipangit  aar? 我去查下资料，看下怎么弄吧。。有问题，再请教你，谢谢：）

**Comment by bhltyou** [comment]
@smallflybird  你说的 修改MAX_QUEUE_SIZE的大小，现在默认是15m，setoption可以修改
这个可以实时去修改吗，比如进入后台去设置一下，用于暂停缓存
