### ISSUE TITLE
Slow video loading over Wifi network

### ISSUE THREAD

**Issue by Simonida** [lipangit/JieCaoVideoPlayer#385]
Video loading and buffering is very slow when device is connected to Wifi network.
When device is on 3/4G, video loading is normal.

You can see how this is manifested on real example in attached video.

Is there any solution for this problem?
[Video buffer.zip](https://github.com/lipangit/JieCaoVideoPlayer/files/473228/Video.buffer.zip)

**Comment by lipangit** [comment]
I have no idea, if you have some infomation you can share with us

**Comment by ClemMahe** [comment]
Hello @lipangit, thanks for the library, awesome work.
Is there a way to disable buffering ?
Thanks a lot.

**Comment by lipangit** [comment]
@ClemMahe  I do not think exoplayer is alternative of MediaPlayer, android.media.MediaPlayer is first choise to play video in android. If android.media.MediaPlayer will not meet your requirement, then you think about to change to other player.

**Comment by lipangit** [comment]
JiecaoVideoPlayer v5.2.1 based on exoplayer, you can refer it.

**Comment by ClemMahe** [comment]
@lipangit So you already tried with ExoPlayer but it didn't suit your needs ? I just though that MediaPlayer is a system class and has a lot of private methods. Also it seems that Exoplayer (full disclosure, i don't know it at all, i just read some articles) let the user set firstBuffer time and reBuffer time, that would be useful to be sure to get the first picture of the video quickly. Anyway thanks for the info ;)

**Comment by lipangit** [comment]
@ClemMahe ExoPlayer absolutly suit my needs. android.media.MediaPlayer is lightweight, android.media.MediaPlayer is better in most case.

**Comment by dima-ostapovets** [comment]
@Simonida @ClemMahe Did you solve the problem with slow buffering? I have the same problem, thank in advance
