### ISSUE TITLE
视频播放能静音么？

### ISSUE THREAD

**Issue by liujinchaoDS** [lipangit/JieCaoVideoPlayer#388]
在列表页希望能够静音播放，点击全屏有声音播放，请问该如何实现？

**Comment by lipangit** [comment]
继承JCvideoPlayerStandard，复写相关状态的函数，自行修改声音

**Comment by ArcherLucky** [comment]
能说具体一点吗...

**Comment by lipangit** [comment]
继承JCvideoPlayerStandard

复写init()函数，在方法里添加
if(currentScreen == FULLSCREEN){
//开启声音
}else{
//关闭声音
}

**Comment by MichaelLiu89** [comment]
在JCResizeTextureView中setVideoSize方法里增加
if (currentScreen == JCVideoPlayer.SCREEN_LAYOUT_LIST){
       // 静音
     JCMediaManager.instance().mediaPlayer.setVolume(0.0f,0.0f);
}else{
     JCMediaManager.instance().mediaPlayer.setVolume(1.0f,1.0f);
}
是否静音的判断
