### ISSUE TITLE
public static void startFullscreen(Context context...)参数Context感觉不是很合适

### ISSUE THREAD

**Issue by Haoxiqiang** [lipangit/JieCaoVideoPlayer#390]
```
public static void startFullscreen(Context context, Class _class, String url, Object... objects) 
```

这里是`Activity`比较好

第一,需要根据这个`context`获取`Window.ID_ANDROID_CONTENT`,则必然是`Activity`

```
ViewGroup vp = (ViewGroup) (JCUtils.getAppCompActivity(context)).findViewById(Window.ID_ANDROID_CONTENT);
```

第二,`getAppCompActivity`,如果`context`不是`AppCompActivity`可能会返回`null`,对于`hideSupportActionBar`就得再加判断了

**Comment by lipangit** [comment]
Window.ID_ANDROID_CONTENT 这个id也是在网上看到的，没有官方的说明

你是遇到什么问题吗，我感觉context和activity区别不大，如果可以减少代码也可以改成activity

startFullscreen这个方法是直接进入全屏的方法，和另一个startFullscreen的方法参数一样的

**Comment by Haoxiqiang** [comment]
`id` 应该就是 `android.R.id.content`

原因:今天有人的页面直接继承了`Activity`,就会出错了,如果是接收参数改为`AppCompActivity `,可以避免这样的勿用.另外如果这样,重构一下应该可以支持直接使用`Activity`

**Comment by lipangit** [comment]
请别使用android.app.activity，activity一律继承AppCompActivity

**Comment by Haoxiqiang** [comment]
嗯,`README`加一个说明吧

**Comment by lipangit** [comment]
好

**Comment by shixiangyu** [comment]
可以在JCUtils中加入
public static Activity getActivity(Context context) {
      ...
    }

**Comment by Haoxiqiang** [comment]
现有逻辑来看`startFullscreen`传入的`Context`就必须是`AppCompActivity`,`AppCompActivity `也算是现在比较通用的做法了,所以也没有什么影响,我本来想提一个`pullrequest`,想了想也没有太大必要
