### ISSUE TITLE
反复播放一段视频,前面流畅,后面卡顿     

### ISSUE THREAD

**Issue by fengbenpaao** [lipangit/JieCaoVideoPlayer#393]
1.我在测试视频播放的时候,用一个 在线与本地的 80M的mp4 相同的视频文件 分别播放 ,

发现,当播放第一次都是很流程的, 但是拖动进度条, 回来播放,  准备结束的时候,再拖回来播放, 这样 三到四次之后,

2.视频播放当到中间的阶段的时候, 就会一顿一顿的卡住,   本地与在线都会一样.  

但是使用以前3.6.0的那边版本对比,是没有这个问题的.

3.log如下:  
09-21 15:08:06.209 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 40 [1100960664] 
09-21 15:08:06.909 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 41 [1100960664] 
09-21 15:08:07.439 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 41 [1100960664] 
09-21 15:08:08.079 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 42 [1100960664] 
09-21 15:08:08.619 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 43 [1100960664] 
09-21 15:08:09.149 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 43 [1100960664] 
09-21 15:08:09.819 24110-24110/com.xxx.xx2 V/JieCaoVideoPlayer: onBufferingUpdate 44 [1100960664] 
09-21 15:08:09.909 24110-24619/com.xxx.xx2 D/IJKMEDIA: FFP_MSG_BUFFERING_START:
09-21 15:08:09.909 24110-24619/com.xxx.xx2 D/IJKMEDIA: FFP_MSG_BUFFERING_END:
09-21 15:08:09.909 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
09-21 15:08:09.919 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
09-21 15:08:09.919 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
09-21 15:08:09.939 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END
09-21 15:08:10.029 24110-24619/com.xxx.xx2 D/IJKMEDIA: FFP_MSG_BUFFERING_START:
09-21 15:08:10.029 24110-24619/com.xxx.xx2 D/IJKMEDIA: FFP_MSG_BUFFERING_END:
09-21 15:08:10.139 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
09-21 15:08:10.159 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
09-21 15:08:10.159 24110-24110/com.xxx.xx2 D/JieCaoVideoPlayer: onInfo what - 702 extra - 0

**Comment by flztsj** [comment]
看log，是ijkplayer会时不时去buffering，可以拍个视频，看看。

建议使用ijkplayer的android demo进行同样的操作看看能不能复现

**Comment by fengbenpaao** [comment]
我使用vlc对比, 那个播放器,怎么播放都是 正常的,不存在卡顿现象.    3.6.0的反复播放都是正常的

**Comment by lipangit** [comment]
试试5.+的版本
