### ISSUE TITLE
Play video need cookie

### ISSUE THREAD

**Issue by mbf5923** [lipangit/JieCaoVideoPlayer#394]
hi
how can i set cookie for play video in jcVideoPlayerStandard?
i try with this:

Map<String, String> headers = new HashMap<String, String>();
                            headers.put("Cookie", "jwt=" + token);
jcVideoPlayerStandard.setUp("http://domain.com/download/" + id + "?ext=-480.mp4"
                                    , JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, headers 
                            );

but not work
thank you

**Comment by lipangit** [comment]
That function is set http header

![image](https://cloud.githubusercontent.com/assets/2038071/18738780/5aa4e860-80d1-11e6-8e05-39a59c40008a.png)

try to break point here,check the param.
