### ISSUE TITLE
是不是不支持https开头的视频？？

### ISSUE THREAD

**Issue by xiyanglove** [lipangit/JieCaoVideoPlayer#395]
不支持 https开头的视频，E/IJKMEDIA: https://xxxxxx: Protocol not found

**Comment by lipangit** [comment]
https在默认的[ijkplayer](https://github.com/Bilibili/ijkplayer)中是关闭的，你要打开响应的配置，重新编译ijkplayer，才能播放

**Comment by harshamv** [comment]
i am also not able to get https to work. any solution?

**Comment by lipangit** [comment]
@harshamv [ijkplayer](https://github.com/Bilibili/ijkplayer)  openssl, I never config it before,I have no useful suggestion for you.
