### ISSUE TITLE
解决视频滑出去后继续播放的问题

### ISSUE THREAD

**Issue by shixiangyu** [lipangit/JieCaoVideoPlayer#397]
如果视频就一个，或者多holdertype情况，而两个video中间间隔较远，这时就会出现视频滑出去了继续播放的问题，到目前有什么好的解决方法吗，我给listview添加了个setRecyclerListener监听，通过view的回收机制解决，虽然解决了继续播放的问题，但是带来了新问题，一旦加载屏幕中出现新的video，当前正在播放的也会停止，这个问题很棘手

**Comment by lipangit** [comment]
在列表复用的时候加个判断，如果上个item是video的item就强转类型然后release它
