### ISSUE TITLE
视频的字幕和声音完全不同步是什么情况   http://la.sdiread.cn/o_1as1jp3qimkhhuo1o54sve1nlt9.mp4

### ISSUE THREAD

**Issue by grkbeyond** [lipangit/JieCaoVideoPlayer#399]
http://la.sdiread.cn/o_1as1jp3qimkhhuo1o54sve1nlt9.mp4    播放这个视频的时候声音和字幕完全不同步，用其他视频播放器不会这样

**Comment by lipangit** [comment]
这个视频的字母在视频里，chrome里播放字幕和语音是同步的，把地址复制到demo中字幕和语音也是同步的

**Comment by grkbeyond** [comment]
额，然道是我代码版本问题，我复制到demo为什么就是不同步。。。

**Comment by lipangit** [comment]
哥们，这个视频的字母不是单独的，如果字母和语音不同步的话表示这视频的图像和声音就不同步

**Comment by wudifamo** [comment]
开始众筹 我去面试过 然后
就没有然后了
