### ISSUE TITLE
播放MP3的时候横竖屏切换seekbar切换过快

### ISSUE THREAD

**Issue by zhangzzqq** [lipangit/jiecaovideoplayer#4]
MP3播放的时候有个小问题：横竖屏切换的时候 进度条（seekBar）切换过快，视频MP4播放没有这样的问题。

**Comment by lipangit** [comment]
^_^ 支持mp3的播放已经加到工作计划

**Comment by lipangit** [comment]
播放mp3时，全屏和退出全屏时seekbar没什么异常-_-

**Comment by zhangzzqq** [comment]
横屏切换竖屏的时候，你注意看下 红色的进度条（seekbar）。操作横屏播放--》按返回键

**Comment by lipangit** [comment]
是不是偶尔有进度条从0一下跳到当前进度的情况

**Comment by zhangzzqq** [comment]
操作流程 1.竖屏--》点击切换横屏 2. 点击返回按钮 3.观察效果 备注我的是华为荣耀6手机

**Comment by lipangit** [comment]
听了你的描述是从横屏返回的一瞬间界面的布局有问题，横向进度条提前显示出来，这个瞬间结束之后正常播放，目前认为并不是咱们app开发者能解决的问题^_^
