### ISSUE TITLE
Test Vitamio

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#40]

**Comment by carmelo-ruota** [comment]
Include Vitamio or Exoplayer inside this library would be awesome!

**Comment by lipangit** [comment]
Yes I am thinking about this , Vitamio only one purpose is support many video formate,  If we need that .

Vitamio's parent company is [miaopai](http://www.miaopai.com/) , they use mp4 to show videos, they needless  to use Vitamio and that project must not use Vitamio .

**Comment by lipangit** [comment]
But Vitamio support HLS stream , mabey that reason is strong to let us use Vitamio ,  Vitamio is big I think if we create new branch to  release jiecaovideoplayer with Vitamio

**Comment by carmelo-ruota** [comment]
I had already used Vitamio in my app and I discovered an issue: 
https://github.com/yixia/VitamioBundle/issues/312

In my app I need to use android:targetSdkVersion = 23. 
This was my workaround: I used native android VideoView for api >= 21 (Lollipop) that should support HLS,  and Vitamio VideoView for  api < 21

**Comment by carmelo-ruota** [comment]
In alternative it could use ExoPlayer

**Comment by lipangit** [comment]
@carmelo-ruota  sorry miaopai have live stream

**Comment by lipangit** [comment]
@carmelo-ruota you think which is better , and I also test both engine

**Comment by carmelo-ruota** [comment]
I think Exoplayer is better. You could also see this: https://github.com/brianwernick/ExoMedia

**Comment by lipangit** [comment]
@carmelo-ruota thank you your advise , I will try it later , if you have instrest you can try which media engine suit this project  :)

**Comment by carmelo-ruota** [comment]
I think ExoPlayer is more suitable for this project. However, you can take a look to ExoMedia to get ideas. How long time you think to need, to integrate one of these libraries into this project?

**Comment by lipangit** [comment]
@carmelo-ruota So many work every day, Aprial 2-4 is chinese Ching Ming Festival ， I have time to remove eventbus ,change video engine for more video formate. 

Then in other a few days I make the project real Custom ui .This project will accepted by more people.

5 days ago I mean if you have interest you can integrate ExoPlayer into the project.

**Comment by carmelo-ruota** [comment]
Unfortunately I have a lot of work to do in this period, so I have no time
to study and integrate ExoPlayer into your project :-(

2016-03-30 4:35 GMT+02:00 Nathen <notifications@github.com>:

**Comment by lipangit** [comment]
Never mind ^_^ , I will do that .

**Comment by carmelo-ruota** [comment]
Any progress? :-)

**Comment by baoziguo** [comment]
挺好的，望早点支持多视频格式~！

**Comment by lipangit** [comment]
@baoziguo 骚年，来个star吧

**Comment by baoziguo** [comment]
@lipangit no problem，坐等多视频格式。放分支里就挺好的，你上面说的多视频格式以及真正的自定义UI，正好是我想需要的。么么艹~！

**Comment by lipangit** [comment]
@baoziguo 必将不负众望

**Comment by mark-dlc** [comment]
I'm a complete outsider to this project, but in my opinion, adding Vitamio would not be optimal as it is a very heavy framework. Adding Vitamio to the project could result in ~25mb increase in size of the installable APK file for end users.

**Comment by lipangit** [comment]
not import vitamio
