### ISSUE TITLE
自定义播放页面显示dialog 

### ISSUE THREAD

**Issue by Vkingzzz** [lipangit/JieCaoVideoPlayer#400]
我自定义了全屏播放页面,做了一些点击后触发dialog,但是jcplayer 是覆盖在当前页面,

所以我专门新开了一个固定横屏activity 让播放在新的activity中播放,

但是jcplayer是旋转90°后全屏,所以我在源码中的 startFullscreen 方法中

将 jcVideoPlayer.setRotation(90);这里的90 改为了0  就会发生  播放画面变得很小,没有全屏,

而且进度条,上方的标题栏等全都消失不见,我想问问看我是在源码的哪里需要改一下

**Comment by Vkingzzz** [comment]
在startFullscreen方法中
把vp.addView(jcVideoPlayer, lp);
改成vp.addView(jcVideoPlayer);

**Comment by lipangit** [comment]
JCVideoPlayer.ACTION_BAR_EXIST 
JCVideoPlayer.TOOL_BAR_EXIST   这两个变量手动控制actionbar和toolbar的显示

dialog你就参照demo中搜索mDialogProgressBar，这个是全屏时手势修改进度的dialog

**Comment by lipangit** [comment]
不再旋转了，旋转的设计太2b了
