### ISSUE TITLE
能增加滑动改变屏幕亮度的功能吗

### ISSUE THREAD

**Issue by qq294685358** [lipangit/JieCaoVideoPlayer#402]
能增加滑动改变屏幕亮度的功能吗，横屏之后左半屏滑动改变音量，右半屏滑动改变亮度

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/365

无时不刻不想添加这功能

**Comment by KateJun** [comment]
希望尽快实现  坐等LZ更新
