### ISSUE TITLE
把节操播放器Add到WebView中滑动冲突。

### ISSUE THREAD

**Issue by zzzlw** [lipangit/JieCaoVideoPlayer#403]
滑到节操播放器的那个位置，不会响应webView的滚动，试过其他自定义View并没有这个问题。很奇怪的是ListView中并没有这个问题。

**Comment by lipangit** [comment]
你看JCVideoPlayer中会为了和viewPager嵌套的时候不影响viewPager的滑动，会拦截手势，不知道这个对webview的滑动有无影响，你可以断一下点看看

另外，怎么讲一个View add 到webview中呀？是什么效果

**Comment by zzzlw** [comment]
拦截方法是哪个啊？是ontouch吗？但是我看最后返回都是false啊。而且我发现个很奇怪的现象，注释掉 textureViewContainer.setOnClickListener(this); 这个监听后，播放以后的滑动就可以正常了，但是预览图时候的滑动还是会被拦截。

**Comment by lipangit** [comment]
只要播放控件监听了onClick滑动就不正常吗，你能在项目中单独抽这个功能的例子，我调试一下

**Comment by zzzlw** [comment]
我找到问题的原因了，跟项目无关，我发现是在WebView里面AddView ,只要你添加的视图，拥有自己的点击事件，事件就传递不到webView....

**Comment by lipangit** [comment]
怎么解决的
同事对你的WebView addView非常感兴趣

**Comment by zzzlw** [comment]
暂时还没解决,滑动冲突的问题，我播放器内部重写事件分发，发给webview一份，但是滑动还是有点小卡顿，可能是造成循环了？？ webView本身就有addView 方法，我也是最近根据需求才发现的， 我是通过js回调返回的宽高和位置。

**Comment by lll-01** [comment]
@zzzlw 你最后是怎么解决的啊

**Comment by lipangit** [comment]
@zzzlw 可以把核心的几行代码分享出来给别人参考一下

**Comment by zzzlw** [comment]
@lipangit @lll-01 当时我确实这样做过，不过后来优化后效果不太好，而且还得用android过时的方法实现，我当时看了微信 内置浏览器 也是有同样的滑动冲突问题，大概前一段时间，我看现在微信已经换了解决方案，可以看一下微信逻辑，如果想实现微信同样功能，可以使用x5webview，腾讯开源的，使用体验跟微信QQ基本一样，且支持h5 video标签，避免重复轮子。
