### ISSUE TITLE
 Problem when enlarging video (screen stuck halfway) on Samsung devices

### ISSUE THREAD

**Issue by MuhammadShaker** [lipangit/JieCaoVideoPlayer#404]
Hello,

I have a problem when click fullscreen button the screen stuck halfway as shown in attached image and that happened only on Samsung devices.

<img width="396" alt="screen shot 2016-09-26 at 19 46 09" src="https://cloud.githubusercontent.com/assets/10682377/18843667/b01f32e2-8422-11e6-8e26-9830be71071a.png">

and It doesn't take care of RTL layout so that controls margin is not good
thanks in advanced

**Comment by lipangit** [comment]
Does this problem occur on demo?
Try demo on Samsung devices, Do not change code in library.

**Comment by flztsj** [comment]
This is RTL problem.
It's better to use full_screen_oreitation branch can fix this problem.

**Comment by MuhammadShaker** [comment]
Yes, it's RTL problem
When I change the layout direction to LTR it works fine.
Can you please fix this problem? 
thanks

**Comment by lipangit** [comment]
@flztsj good job

**Comment by MuhammadShaker** [comment]
If you want to support RTL you can edit JCVideoPlayer class , startWindowFullscreen function
replace 
lp.setMargins((w - h) / 2, -(w - h) / 2, 0, 0);
with
if (RTL)
       lp.setMargins(0, -(w - h) / 2, (w - h) / 2, 0);
else
       lp.setMargins((w - h) / 2, -(w - h) / 2, 0, 0);

thanks

**Comment by flztsj** [comment]
@lipangit  可以考虑把之前的full_screen_oreitation功能合并到主分支了，兼容性会好很多

**Comment by flztsj** [comment]
@MuhammadShaker  
you can check the branch code with your problem.
https://github.com/lipangit/JieCaoVideoPlayer/tree/full_screen_orientation

**Comment by lipangit** [comment]
@flztsj 正在做自动小窗功能这礼拜，然后看到头条的ui已经更新了，下礼拜咱们也更新成一样的，然后把full_screen_oreitation这个分支弄成和头条一模一样的逻辑，再发一个版本
