### ISSUE TITLE
Google Ads IMA integration

### ISSUE THREAD

**Issue by pathanjalisrinivasan** [lipangit/JieCaoVideoPlayer#407]
Does this player support Ad integration ? If it does then where to include the details ?

Sample reference [link](https://developers.google.com/interactive-media-ads/docs/sdks/android/quickstart) for the sdk integration : https://developers.google.com/interactive-media-ads/docs/sdks/android/quickstart

**Comment by lipangit** [comment]
There is no demo for Ads IMA, you can integration it by yourself.
