### ISSUE TITLE
是否考虑基于Exoplayer2.0开发？

### ISSUE THREAD

**Issue by liujinchaoDS** [lipangit/JieCaoVideoPlayer#409]
google最新发布了exoplayer2.0，重构了代码，是否可以基于此开发一个版本？

**Comment by flztsj** [comment]
不用重新开发，对应的mediaplayer替换下，相应的代码改改就好了。jiechao只是做界面和逻辑的。

**Comment by lipangit** [comment]
没错，不管用哪家MediaPlayer，都要和android.media.MediaPlayer系统的MediaPlayer的api一样，这样换起来方便

exoplayer咱们有一个分支尝试过，但是他在切换surfaceview的时候图像要卡半天才能显示，就是切换全屏了，全屏要黑几秒钟，然后才显示图像，这个问题没法解决

**Comment by liujinchaoDS** [comment]
是使用最新的2.0出现的黑屏吗？

**Comment by lipangit** [comment]
切换全屏的时候黑屏2秒钟

**Comment by lipangit** [comment]
exoplayer已经集成
