### ISSUE TITLE
onEventMainThread这个方法是什么时候调用的？

### ISSUE THREAD

**Issue by easonCn** [lipangit/jiecaovideoplayer#41]
其实我是想知道setUp这个方法的url如果该参数不是一个正常的MP4等格式的时候，我想做一些错误处理，这时候我需要监听事件，想问下这有提供有api吗？麻烦告诉我一下。谢谢

**Comment by lipangit** [comment]
url的检测请在seUp之前检测，如果错误直接就处理了，库里没有错误的监听，你那可能会出现什么错误能描述下吗

onEventMainThread 这个是用来埋点的，请参照demo使用，demo是参照eventbus官方的方法使用的

**Comment by lipangit** [comment]
QQ回复过了
