### ISSUE TITLE
Video Stops Suddenly

### ISSUE THREAD

**Issue by naveenfunk** [lipangit/JieCaoVideoPlayer#412]
Hello, First of all thank you for providing this library to us . This lib is of great help to us. Thnx a lot for this.

This is regarding one issue that I am facing while playing a video url from server , the link is of .mp4 format. While video is playing it suddenly stops and this is what i get in my logcat.

> 10-06 23:52:41.729 1359-11847/com.jugnitv E/IJKMEDIA: Stream ends prematurely at 3940287, should be 33965307
> 10-06 23:52:41.729 1359-11847/com.jugnitv E/IJKMEDIA: stream 0, offset 0x3c32b3: partial file
> 10-06 23:52:41.729 1359-11847/com.jugnitv E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
> 10-06 23:52:41.729 1359-11845/com.jugnitv D/IJKMEDIA: FFP_MSG_BUFFERING_END:
> 10-06 23:52:41.729 1359-1359/com.jugnitv D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
> 10-06 23:52:41.729 1359-1359/com.jugnitv D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END
> 10-06 23:52:41.729 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 41533/376743 [629359809] 
> 10-06 23:52:42.030 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 41326/376743 [629359809] 
> 10-06 23:52:42.330 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 41618/376743 [629359809] 
> 10-06 23:52:42.630 1359-12070/com.jugnitv E/IJKMEDIA: Invalid NAL unit size.
> 10-06 23:52:42.630 1359-12070/com.jugnitv E/IJKMEDIA: Error splitting the input into NAL units.
> 10-06 23:52:42.640 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 41899/376743 [629359809] 
> 10-06 23:52:42.740 1359-11847/com.jugnitv E/IJKMEDIA: stream 0, offset 0x3c3425: partial file
> 10-06 23:52:42.740 1359-11847/com.jugnitv E/IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown
> 10-06 23:52:42.931 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 42200/376743 [629359809] 
> 10-06 23:52:43.231 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 42503/376743 [629359809] 
> 10-06 23:52:43.531 1359-12829/com.jugnitv V/JieCaoVideoPlayer: onProgressUpdate 42802/376743 [629359809] 
> 10-06 23:52:43.741 1359-11847/com.jugnitv I/IJKMEDIA: ffp_toggle_buffering: error: -5
> 10-06 23:52:43.741 1359-11847/com.jugnitv E/IJKMEDIA: stream 0, offset 0x3c4706: partial file
> 10-06 23:52:43.741 1359-11845/com.jugnitv D/IJKMEDIA: FFP_MSG_ERROR: 0
> 10-06 23:52:43.741 1359-2456/com.jugnitv E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
> 10-06 23:52:43.741 1359-1359/com.jugnitv E/JieCaoVideoPlayer: onError -10000 - 0 [719440767] 

I will really appreciate if you can help us out of this.

**Comment by lipangit** [comment]
What exception ?What symptoms?
I can not catch useful infomation in these logcat.I need more infomation

**Comment by naveenfunk** [comment]
![screenshot_2016-10-07-23-01-26](https://cloud.githubusercontent.com/assets/11697370/19199674/c3046422-8ce2-11e6-82ab-ff04218a40b4.png)
![screenshot_2016-10-07-22-58-53](https://cloud.githubusercontent.com/assets/11697370/19199675/c30b9dd2-8ce2-11e6-8558-c90685fca6e8.png)

As shown in the above images the video is playing smoothly but suddenly this error comes(for which logcat is shared above) and video screen shows a image in middle with (!) mark as shown in images

**Comment by tommyfeng** [comment]
我也碰到了这个问题，在线播放TS或者MP4格式视频文件时，也会出现，求问大神怎么解决！！！

**Comment by lipangit** [comment]
@naveenfunk @tommyfeng 
You can break point here,and get more information
![image](https://cloud.githubusercontent.com/assets/2038071/19221860/50949fae-8e7e-11e6-9d51-2d29ea3d4fdd.png)

**Comment by lipangit** [comment]
@tommyfeng 对于这种问题，大神也懵逼

**Comment by tommyfeng** [comment]
@lipangit看起来像是 ijkplayer 的问题，我用ijkplayer的demo测试也会出现 unknown 的问题，也就是播放中途或者播放到最后的时候出错。JCVD当进度条超过缓冲条的时候，必会出现！

**Comment by lipangit** [comment]
@tommyfeng 我查查！

**Comment by naveenfunk** [comment]
This is what I see when I debug with breakpoints
![ss](https://cloud.githubusercontent.com/assets/11697370/19244332/849a60ac-8f39-11e6-94c5-6804f0bf8bdc.png)

**Comment by lipangit** [comment]
-10000 的error如果是偶尔出现的话建议再观察观察

然后你说JCVD当进度条超过缓冲条的时候，必会出现，亲测没遇到这种情况，error状态以前遇到过，但是点击进度条能进入error状态没遇到过，怎么办，还有其他情报吗

**Comment by naveenfunk** [comment]
Can you please explain in english..?

**Comment by naveenfunk** [comment]
If you got what I'm facing here then can you please suggest a solution ? I've to finish this asap .

**Comment by lipangit** [comment]
If this error is not occur every time, you can ignore it, maybe something wrong out side.

**Comment by DawinderGill** [comment]
Hi Lipangit,
I am also facing same issue with almost every video. Can you please give me any solution for this?
This will be great help for me.
Thanks.

**Comment by naveenfunk** [comment]
But this appears almost in 9/10 videos... I'm playing a HLS URL also but in that case it's playing smoothly... Isn't there any legit solution for this?

**Comment by lipangit** [comment]
There is "\t" in my url , it will cause error, String.trim() your urls.

Sorry this project is working for make video UI easy, I have no Idea on mediaplayer and underlying of Video.

**Comment by tommyfeng** [comment]
播放正常时Log  (normal)
![qq 20161013120114](https://cloud.githubusercontent.com/assets/20334082/19336339/03926ac6-913d-11e6-9c19-ba6408661d7c.png)

播放中途出错时Log (unnormal)
![qq 20161013120154](https://cloud.githubusercontent.com/assets/20334082/19336361/2d8ba360-913d-11e6-8f69-6babb2352890.png)

请问能看出来是什么问题吗？

**Comment by lipangit** [comment]
@tommyfeng fffffffb好像表示一个颜色，并且解析失败了。这两个log是播放同一个视频吗？

我也不知道为什么，我们公司播放视频都很稳定，没有这种情况

**Comment by tommyfeng** [comment]
@lipangit 是的，播放的是同一个视频。保存在七牛云上的TS格式视频文件。在线播放有时候是正常的，但是播放一段时间后出错也经常出现，不知道是什么原因。

**Comment by naveenfunk** [comment]
@lipangit it's same as described by tommyfeng also my video is different from his with same log cat output.

**Comment by tommyfeng** [comment]
@lipangit  @naveenfunk  https://github.com/Bilibili/ijkplayer/issues/445  Mentioned here, but I do not know if this is the reason。

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/19358018/b83f6f28-91a6-11e6-8090-1ba89e650f7f.png)

**Comment by tommyfeng** [comment]
@lipangit  直接complie 项目的要怎么设置。。。我试着添加代码发现并没有用

**Comment by tommyfeng** [comment]
@lipangit @naveenfunk  problem is solved，add mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "reconnect", 1); and it works well.

**Comment by naveenfunk** [comment]
@tommyfeng Brother can you please tell me where you have implemented this code ? If possible can you please send my you whole class code ?

Thank you in advance

**Comment by tommyfeng** [comment]
@naveenfunk 
![qq 20161014153039](https://cloud.githubusercontent.com/assets/20334082/19379179/56fa8496-9223-11e6-97b4-dd9c0c5b7a2a.png)
![qq 20161014153118](https://cloud.githubusercontent.com/assets/20334082/19379195/67aad96c-9223-11e6-86aa-e6d166162023.png)

try it.

**Comment by lipangit** [comment]
yes，thank you @tommyfeng

**Comment by naveenfunk** [comment]
@tommyfeng Thank you . It solved the problem . Thnx a ton

**Comment by lipangit** [comment]
这个option如果是默认的属性更方便一些
