### ISSUE TITLE
Video aspect ratio

### ISSUE THREAD

**Issue by naveenfunk** [lipangit/JieCaoVideoPlayer#413]
I want to stretch video to make it full screen.
Is there any way to set aspect ratio of the video or any other alternative to achieve this ?

**Comment by lipangit** [comment]
There is function onVideoSizeChanged in JCVideoPlayer, You can set value on JCMediaManager.currentVideoWidth and JCMediaManager.currentVideoHeight change JCMediaManager.textureView to your size.

**Comment by lipangit** [comment]
Extends JCVideoPlayer override onVideoSizeChanged() function.

**Comment by naveenfunk** [comment]
Thnx a lot...  It really worked

**Comment by bravekingzhang** [comment]
thanks you .I need this.
