### ISSUE TITLE
只有声音，没有图像

### ISSUE THREAD

**Issue by wdmxzf** [lipangit/JieCaoVideoPlayer#415]
用手机录制的视频，使用ffmpeg压缩后，在手机的播放器里面可以播放，在JieCaoVideoPlayer中播放只有声音，没有图像！

**Comment by lipangit** [comment]
有声音没图像
1.硬件加速必须开启，Textureview才会工作
2.Textureview.setSurface()方法必须执行，才有图像，断点下图位置
![image](https://cloud.githubusercontent.com/assets/2038071/19221879/a0b90fa6-8e7e-11e6-842d-06fbcb6a86cd.png)
3.有时候改源码，可能逻辑混乱

**Comment by wdmxzf** [comment]
源码我没有改变，我是使用gradle集成的“compile 'fm.jiecao:jiecaovideoplayer:4.6.5'”

**Comment by wdmxzf** [comment]
我查找的原因好香是IjkMediaPlayer不支持我这种格式－－麻烦你们帮我看看
![qe kr hmgh n 9 n1w6 j](https://cloud.githubusercontent.com/assets/19531732/19231860/0d607406-8f0f-11e6-97ec-0c6652c9ddb8.png)
![so gnr v 6lp576qd dsn i](https://cloud.githubusercontent.com/assets/19531732/19231871/1a08f8a4-8f0f-11e6-9217-2da333039b14.png)

**Comment by lipangit** [comment]
暂时不知道怎么办，其他小伙伴应该有这个经验，不知道他们怎么解决的

**Comment by wdmxzf** [comment]
这个zip包就是这个类型的视频，你们呢可以看看，怎么能解决，我使用IjkMediaPlayer 和SurfaceView 写的播放器也播放不出图像来，而用MediaPlayer和SurfaceView可以正常播放

[Uploading compress40e29cc3-42d1-407b-9467-bef8d0c7d644.mp4.zip…]()

**Comment by lipangit** [comment]
试试5.0exoplayer能播放吗
