### ISSUE TITLE
嵌套在 Fragment 中，播放第二个视频会崩溃。

### ISSUE THREAD

**Issue by laibinCN** [lipangit/JieCaoVideoPlayer#416]
ActionBar ab = JCUtils.getAppCompActivity(context).getSupportActionBar();
JCUtils.getAppCompActivity(context)是 null 时，程序崩溃

**Comment by lipangit** [comment]
要继承AppCompactactivity，正在考虑这个是不是要只继承Activity就可以，这样可以少引用一个库

**Comment by laibinCN** [comment]
那当然最好，还兼容了所有 Activity

**Comment by laibinCN** [comment]
或者写个类型判断，不是AppCompactactivity 抛出异常，并提示使用AppCompactactivity

**Comment by lipangit** [comment]
这个问题还在研究，你们的app还在兼容2.3吗，用的是actionbarsherlock

**Comment by jeremyyu123** [comment]
你好,这个问题有解决吗,getactionBar为null的问题

**Comment by lipangit** [comment]
@jeremyyu123 如果用actionbarsherlock，就只能改库了,替换AppCompactactivity
