### ISSUE TITLE
Https urls not working

### ISSUE THREAD

**Issue by bheemanm7** [lipangit/JieCaoVideoPlayer#417]
I am passing https://..... link, view shows error. When http:// link is used it plays video.

Code with https url
jcVideoPlayerStandard.setUp("https://s3.amazonaws.com/skreem-dev/campaigncreatives/127/sd_location-test1-9a0f6467.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "test");

Code with http url:
jcVideoPlayerStandard.setUp("http://s3.amazonaws.com/skreem-dev/campaigncreatives/127/sd_location-test1-9a0f6467.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "dummy");

any way to play video with https url

**Comment by lipangit** [comment]
Yes ， Https is not default int this project, https://github.com/Bilibili/ijkplayer

You should config and rebuild ijkplayer .

**Comment by bheemanm7** [comment]
@lipangit i do not have NDK. is there a way to do it or any one has done n uploaded a jar i can use?

**Comment by lipangit** [comment]
sorry no , I am powless @bheemanm7
