### ISSUE TITLE
关于最近开发的列表小窗播放

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#418]
列表自动进入小窗功能已经经过数个月的酝酿和开发，已经初有雏形，但是，总差那么一点点不完美，总能发现一点点问题，这时候已经明显感受到脑子有些不够用了，总有些地方想不清楚，改不明白，如何弥补硬件缺陷呢，只能用长时间的思考琢磨，和体力上的反复调试解决。

目前认为，小窗功能是一个值得做的功能，有必要给开发者们提供一个接口，1、2行代码激活这个功能，但是这个功能做的不完善，我觉得这个功能不是没有不行，如果有，大家就用，没有大家可以不用，正因为总有那么一点点问题不能release这个功能，如果release就release一个市面上最好的列表小窗，release个有问题的将会带来非常不好的影响。

所以先把今日头条的UI更新一下，和全屏后的重力感应旋转做完，然后继续小窗功能。

**Comment by YuJunKui2016** [comment]
小屏问题调起来好蛋疼

**Comment by lipangit** [comment]
别急，慢慢解决

**Comment by lipangit** [comment]
5555555555，小窗还没做出来
