### ISSUE TITLE
保持全屏状态，切换视频？

### ISSUE THREAD

**Issue by AkashiWen** [lipangit/JieCaoVideoPlayer#419]
player继承了JCVideoPlayerStandard

setup中的screen传JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN

然后手动调用player.onclick触发startbutton

发现视频画面保持的是前一个视频的最后状态，但进度条刷新为新视频的

**Comment by AkashiWen** [comment]
解决了。。。再加一句player.startWindowFullscreen();

**Comment by AkashiWen** [comment]
最终方案：

全屏时切换视频源，setUp里应用SCREEN_LAYOUT_LIST

然后马上onclick触发startbutton并调用startWindowFullscreen()

目前没有全屏动画 还算快所以感觉不太到中途那一闪

**Comment by AkashiWen** [comment]
另外还有个问题困扰我很久

播放器对象全屏的时候好像会变成另一个新的，初始化时注入的对象都为null，全局变量会变成初始值

**Comment by lipangit** [comment]
对，全屏时候的播放器和非全屏时候的播放器不是同一个，但在同一个activity中

**Comment by lipangit** [comment]
在不切换JCVideoPlayer的情况下能播放完一个视频继续播放下一个视频，知道这个需求了，以后会考虑加到demo中，提供接口

**Comment by AkashiWen** [comment]
OK

**Comment by wman0211** [comment]
抱歉  插一个口 <_<
在这个issue还没有fixed之前别close咯

**Comment by yangyiRunning** [comment]
路过……

**Comment by yangyiRunning** [comment]
路过……
