### ISSUE TITLE
Test ExoPlayer

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#42]

**Comment by lipangit** [comment]
image has 3s delay when change surfaceholder  . -_- means to fullscreen or quit fullscreen will have 3s delay

**Comment by carmelo-ruota** [comment]
What can be the cause?

**Comment by lipangit** [comment]
https://github.com/lipangit/TestExoPlayer

There have two surfaceview click a surfaceview will play on the surfaceview. we will see image 1s-4s delay but the sound is continuous,

**Comment by lipangit** [comment]
enter fullscreen exoplayer can not make video smooth
