### ISSUE TITLE
全屏问题

### ISSUE THREAD

**Issue by laijunxi** [lipangit/JieCaoVideoPlayer#420]
我现在想做的是一个在横屏浏览，播放，点击全屏就直接全屏播放，但是目前点击后又会旋转到竖屏，请问这个应该怎么解决。或者说怎么可以判断在横屏情况下点击全屏就直接全屏，竖屏时点击全屏就旋转到横屏。

**Comment by lipangit** [comment]
在全屏的时候会通过重力感应退出全屏，你是想只能通过点击全屏按钮退出全屏吧

想办法吧重力感应去掉或者屏蔽能解决这个问题

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/19342170/3c4bcbfc-9163-11e6-9877-cb7c96d2c141.png)

你说的直接全屏和旋转到横屏有什么区别

**Comment by laijunxi** [comment]
我的意思是如果在横屏状态下，点击全屏按钮就直接全屏播放。目前的情况是在横屏状态下点击全屏按钮会旋转90。还有在竖屏情况下，点击全屏会旋转90，然后横着看又会旋转90。而且目前在没有点击全屏按钮，让手机横屏并没有出现全屏效果。我使用的是4.6.5.

**Comment by gnastnosaj** [comment]
发现同样的问题，没考虑到landscape模式

**Comment by gnastnosaj** [comment]
FrameLayout.LayoutParams lp = null;
            if(w < h) {
                lp = new FrameLayout.LayoutParams(h, w);
                lp.setMargins((w - h) / 2, -(w - h) / 2, 0, 0);
            }else {
                lp = new FrameLayout.LayoutParams(w, h);
            }
            vp.addView(jcVideoPlayer, lp);
            jcVideoPlayer.setUp(url, JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, objects);
            jcVideoPlayer.setUiWitStateAndScreen(currentState);
            jcVideoPlayer.addTextureView();
            if(w < h) {
                jcVideoPlayer.setRotation(90);
            }

**Comment by gnastnosaj** [comment]
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        int screenType = JCVideoPlayerManager.getFirst().getScreenType();
        if(screenType == 2) {
            jcVideoPlayerStandard.startWindowFullscreen();
        }
    }

**Comment by lipangit** [comment]
全屏问题还在调试，周日发版
