### ISSUE TITLE
拖拽进度条,左边时间跟着改变怎么实现

### ISSUE THREAD

**Issue by zynxiaonanzi** [lipangit/JieCaoVideoPlayer#421]
当前的功能是,拖拽完,松手后,时间和视频才变,我想实现的是,拖拽过程中(不松手),时间就跟着变,怎么实现

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写进度条的拖动函数，在此函数修改时间

**Comment by zynxiaonanzi** [comment]
原谅我的无知,哪个是进度条的拖拽函数?怎么修改呢?能不能说的具体一点呢,万分感谢

**Comment by zynxiaonanzi** [comment]
@lipangit 原谅我的无知,哪个是进度条的拖拽函数?怎么修改呢?能不能说的具体一点呢,万分感谢

**Comment by lipangit** [comment]
解决了吗，正常在修改进度的函数中只修改进度条，你可以在修改进度条的地方修改时间的显示
