### ISSUE TITLE
关于android 4.3 以下播放 ”http://183.221.168.53:8083/videos/live/17/51/958cxpfHCjqwj/958cxpfHCjqwj.M3U8” 直播时声音与视频不同步的问题 

### ISSUE THREAD

**Issue by mygoodname** [lipangit/JieCaoVideoPlayer#426]
如题 在android 4.1、4.2上面播放http://183.221.168.53:8083/videos/live/17/51/958cxpfHCjqwj/958cxpfHCjqwj.M3U8  时声音与视频严重不同步； 声音在视频前面而且随着播放时间的递增，声音与视频之间相差的时间越来越大；求破

**Comment by lipangit** [comment]
demo中第一个apple.com的m3u8视频连接，就是这样，越播视频和图像的时间差距越大

**Comment by mygoodname** [comment]
是声音与视频不同步，就是声音和视频的字幕不同步
