### ISSUE TITLE
JCVideoPlayerStandard.startFullscreen(this, JCVideoPlayerStandard.class, "http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4", "嫂子辛苦了");

### ISSUE THREAD

**Issue by LMJWEIJY** [lipangit/JieCaoVideoPlayer#428]
用 JCVideoPlayerStandard.startFullscreen这个方法
全屏后，点击手机返回键，应用崩溃。但还在播放声音。小米4c手机 
9:59:12.977 2836-3392/com.dijiaapp.bfapplication V/JieCaoVideoPlayer: onProgressUpdate 64/9880 [576340667] 
10-17 09:59:13.287 2836-3392/com.dijiaapp.bfapplication V/JieCaoVideoPlayer: onProgressUpdate 320/9880 [576340667] 
10-17 09:59:13.587 2836-3392/com.dijiaapp.bfapplication V/JieCaoVideoPlayer: onProgressUpdate 623/9880 [576340667] 
10-17 09:59:13.887 2836-3392/com.dijiaapp.bfapplication V/JieCaoVideoPlayer: onProgressUpdate 921/9880 [576340667] 
10-17 09:59:14.167 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] query: BufferQueue has been abandoned
10-17 09:59:14.167 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] query: BufferQueue has been abandoned
10-17 09:59:14.167 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] dequeueBuffer: BufferQueue has been abandoned
10-17 09:59:14.167 2836-3362/com.dijiaapp.bfapplication E/Surface: dequeueBuffer failed (No such device)
10-17 09:59:14.167 2836-3362/com.dijiaapp.bfapplication E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
10-17 09:59:14.187 2836-3392/com.dijiaapp.bfapplication V/JieCaoVideoPlayer: onProgressUpdate 1222/9880 [576340667] 
10-17 09:59:14.207 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] query: BufferQueue has been abandoned
10-17 09:59:14.207 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] query: BufferQueue has been abandoned
10-17 09:59:14.207 2836-3362/com.dijiaapp.bfapplication E/BufferQueueProducer: [unnamed-2836-3] dequeueBuffer: BufferQueue has been abandoned
10-17 09:59:14.207 2836-3362/com.dijiaapp.bfapplication E/Surface: dequeueBuffer failed (No such device)
10-17 09:59:14.207 2836-3362/com.dijiaapp.bfapplication E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19

**Comment by LMJWEIJY** [comment]
参考源码，已经解决问题

**Comment by lipangit** [comment]
么么哒

**Comment by hiddow** [comment]
怎么解决的？

**Comment by LMJWEIJY** [comment]
@hiddow `@Override
    protected void onPause() {
        super.onPause();
        JCVideoPlayer.releaseAllVideos();
    }`
