### ISSUE TITLE
在listview中的整个页面会闪烁一下

### ISSUE THREAD

**Issue by romantiskt** [lipangit/jiecaovideoplayer#43]
如题,我在scrollview中嵌套了listview ,listview的每一个item就是一个video,当我加载这个页面的时候,整个页面会闪烁一下

**Comment by romantiskt** [comment]
此问题已解决,可以在对应activity的oncreate中添加如下:
 getWindow().setFormat(PixelFormat.TRANSLUCENT);
或者给布局一个宽高1dp 1dp 的surfaceview,

**Comment by lipangit** [comment]
把你添加到开发者了，提交上来 :)

**Comment by lipangit** [comment]
done . add a 0dp surfaceview.
