### ISSUE TITLE
android 5.0以下播放flv格式的视频 都是只有声音 没有画面

### ISSUE THREAD

**Issue by ycl110120** [lipangit/JieCaoVideoPlayer#431]

**Comment by lipangit** [comment]
发个链接看看

**Comment by ycl110120** [comment]
我是eclipse版本的 代码集成的
https://github.com/lipangit/JieCaoVideoPlayer

**Comment by ycl110120** [comment]
IMediaPlayer和IjkMediaPlayer我都是用MediaPlayer替换的，这是4.7版本的。
低版本的也不行。
都是android 5.0以下播放flv格式的视频 都是只有声音 没有画面，但是5.0和6.0的都可以。
我想问JieCaoVideoPlayer可不可以播放flv格式的

**Comment by lipangit** [comment]
我要的是视频的链接，帮你试试

**Comment by ycl110120** [comment]
http://www.jznmhzs.org/Viedo/video.flv

**Comment by lipangit** [comment]
手机端的视频格式建议使用mp4，微信、微博、秒拍、美拍都用mp4，使用flv的理由并不充分

**Comment by ycl110120** [comment]
额 这是上面要求的

**Comment by lipangit** [comment]
荒唐，但习惯了

**Comment by ycl110120** [comment]
呵呵 我也习惯了

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/19462993/f8362958-9522-11e6-98fd-437e3a7598f2.png)

红米note4，android6.0，播放你的地址闪退！

**Comment by ycl110120** [comment]
不会啊 我用华为6.0的测试 是可以播放的

**Comment by lipangit** [comment]
你到ijkplayer问问吧，可能我这搞不定

**Comment by lipangit** [comment]
播放不了，一直在loading，然后1分钟多吧，必然闪退

**Comment by ycl110120** [comment]
好 谢谢 点赞

**Comment by lipangit** [comment]
这个地址新版5.0还是播放不了
