### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported Service: audio

### ISSUE THREAD

**Issue by babylikebird** [lipangit/JieCaoVideoPlayer#432]
java.lang.UnsupportedOperationException: Unsupported Service: audio   at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:602)   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.init(JCVideoPlayer.java:134)   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.init(JCVideoPlayerStandard.java:63)   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.<init>(JCVideoPlayer.java:111)   at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.<init>(JCVideoPlayerStandard.java:58)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)

**Comment by lipangit** [comment]
我们播放视频会发出一个系统广播去暂停其他有声音的播放，这个能复现吗，还有其他情报吗
