### ISSUE TITLE
与jpush冲突

### ISSUE THREAD

**Issue by cydenghua** [lipangit/JieCaoVideoPlayer#433]
在build.gradle中增加：    compile 'fm.jiecao:jiecaovideoplayer:4.7.1_preview'

项目中有集成jpush-sdk-release1.7.5.jar，所以在MyApplication初始化jpush：
     JPushInterface.setDebugMode(false); // 设置开启日志,发布时请关闭日志
     JPushInterface.init(this); // 初始化 JPush

初始化时报错：
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.asimo.t1018-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.asimo.t1018-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjpush175.so"

**Comment by lipangit** [comment]
当前的稳定版本是v4.6.5

我们也用极光推送，没发现这个问题，混淆脚本添加了吗

**Comment by cydenghua** [comment]
重新集成了极光推送最新版， 问题没有了，感谢回复

**Comment by YuJunKui2016** [comment]
这个问题可以参考 353
