### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by cydenghua** [lipangit/JieCaoVideoPlayer#435]
以下代码会引发程序崩溃：
videoPlayer.setUp(null, JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "");
也就是说， 当视频url传null值的时候。
版本为:compile 'fm.jiecao:jiecaovideoplayer:4.7.1_preview'

**Comment by lipangit** [comment]
视频地址不能是null，有什么需求需要传参数null

**Comment by cydenghua** [comment]
嗯嗯， 主要是直接没注意， 接口返回的数据是null， 后面自己做了判断， 处理了。
