### ISSUE TITLE
视频播放缓冲慢，播放卡顿

### ISSUE THREAD

**Issue by wdmxzf** [lipangit/JieCaoVideoPlayer#436]
播放本地视频没什么问题，播放在线视频，点击播放按钮，开始转圈圈，需要转三分钟左右，才开始播放，播放时卡顿。
![ede519e8849e62b96356687761af7e8d](https://cloud.githubusercontent.com/assets/19531732/19586692/39403b46-978a-11e6-9fa5-a0414f3c65f8.jpg)

**Comment by lipangit** [comment]
发个视频链接看看

**Comment by wdmxzf** [comment]
http://7xtfon.com1.z0.glb.clouddn.com/07128a7e-337a-41a0-9395-881d6391856b?e=1477043888&token=Ah0MrGmdD0mrtScDjidLFu9DP4s9PirBdQ6SUTzS:GFZC1pwnd8deF7Nsr7ROd--rAFE=
