### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KateJun** [lipangit/JieCaoVideoPlayer#439]
10-21 17:16:26.700 17237-21075/com.jvideo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)
10-21 17:16:26.710 17237-17237/com.jvideo E/JieCaoVideoPlayer: onError -10000 - 0 [1109420592] 
请问这是什么问题？视频连接在浏览器可以正常使用

**Comment by lipangit** [comment]
播放链接看看

**Comment by KateJun** [comment]
"http://182.61.96.125:8001/videofile/201610201553/big_buck_bunny_trailer.mp4"

**Comment by KateJun** [comment]
请帮忙看看， 谢谢了

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/441

你的和这个朋友的log一样，他把录完的视频压缩之后就播放不了，估计是mp4的编码有问题

**Comment by lipangit** [comment]
这你要到ijkplayer项目里问问了，这里解决不了
