### ISSUE TITLE
Fullscreen or quit fullscreen image will fuzzy 2s on android 5.0

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#44]

**Comment by liudaoxiang** [comment]
android 6.0 is ok. @lipangit Do you have fixed this issue?I have done my best,but can not find out the reason

**Comment by lipangit** [comment]
This issue bug have no idea yet.
In android 6.0, fullscreen or quit fullscreen no sound , image is normal.
Can you push your fix. add you in collaborators .

**Comment by liudaoxiang** [comment]
sorry, I have not found this problem before(no sound),I will continue to focus on this problem.

**Comment by lipangit** [comment]
Ok

**Comment by liudaoxiang** [comment]
hi ,Do you have a solution?

**Comment by lipangit** [comment]
I have no idea and I need help T_T.  android 4.0 is ok, I think the MediaPlayer on android 5.0 will optimize pixel , when change surfaceholder will trigger the problem .

**Comment by lipangit** [comment]
image is normal but position is wrong
