### ISSUE TITLE
请问都有神马版本的啊

### ISSUE THREAD

**Issue by qweawdqq** [lipangit/JieCaoVideoPlayer#440]
我现在工程里面直接导入导入不进去
Error:(44, 13) Failed to resolve: fm.jiecao:jiecaovideoplayer:4.6.5_preview
<a href="openFile:C:/Users/Administrator/Desktop/NewWork/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
是不是我的版本低啊》？

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/19620555/abd95f92-98b2-11e6-8d4f-2c43a0eb8431.png)
这里有所有的版本，稳定版本看readme
