### ISSUE TITLE
在线播放视频，播放不了！

### ISSUE THREAD

**Issue by wdmxzf** [lipangit/JieCaoVideoPlayer#441]
视频地址：http://7xtfon.com1.z0.glb.clouddn.com/d00461c3-e0d3-470d-8875-cbd79c31444b?e=1477300126&token=Ah0MrGmdD0mrtScDjidLFu9DP4s9PirBdQ6SUTzS:x3mQ5jBi06Ojkg7YE9g_iUqKsRs=

**Comment by lipangit** [comment]
这视频在chrome中也播放不了

**Comment by wdmxzf** [comment]
我这chrome可以播放

**Comment by dingchao823** [comment]
我也播放不了，360浏览器

**Comment by wdmxzf** [comment]
本地的视频是可以播放的，但上传到服务器后，就不能播放了！！

**Comment by lipangit** [comment]
确认没压缩，是原封不动的视频文件？

**Comment by wdmxzf** [comment]
压缩后的视频，在本地可以播放，传到服务器，然后在线播就播不了了
