### ISSUE TITLE
退出全屏

### ISSUE THREAD

**Issue by laijunxi** [lipangit/JieCaoVideoPlayer#442]
目前我需要的是全程在横屏下操作（屏幕固定为横向），但是在全屏返回的时候会自动回到竖屏的列表状态。我可以直接在源码将
public static void switchNormalOrientation(Context context) {
        getAppCompActivity(context).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }
改成landscape就可以了吗？

**Comment by lipangit** [comment]
你的办法可以

没考虑你这种情况，你需要改源码了，下版本改成让用户配置这个属性
