### ISSUE TITLE
虚拟按键的手机上全屏，竖向时进度条会被手机导航栏遮住

### ISSUE THREAD

**Issue by Droidin** [lipangit/JieCaoVideoPlayer#443]
虚拟按键的手机上全屏后，并且竖向时进度条部分会被手机导航键遮住

![image](https://cloud.githubusercontent.com/assets/16255157/19637478/e3145098-9a01-11e6-960e-a632eeda79b1.png)

**Comment by lipangit** [comment]
知道了，没有这样的手机，你有什么想法吗，视频控件是match_parent的，虚拟按键到底是什么属性的控件，我去研究一下

**Comment by Droidin** [comment]
window decor view 应该是包含了虚拟导航按键部分的 ，如果是  activity 的跟布局的话也就是 android.R.id.content 在这个下面显示视频控件应该就可以。我把代码里面的那个注释了试了下貌似是可以得
![image](https://cloud.githubusercontent.com/assets/16255157/19672985/2edc901a-9aae-11e6-9066-04d19bad2aa9.png)

![image](https://cloud.githubusercontent.com/assets/16255157/19673110/60862210-9aaf-11e6-95db-512d5f7d531c.png)

**Comment by lipangit** [comment]
好，测试之后下版本修改

**Comment by qinyang1018** [comment]
我现在也遇见这个问题了
![image](https://cloud.githubusercontent.com/assets/15726024/26713696/702539ba-47a0-11e7-9970-68aee9543a3b.png)
华为mate8使用的是5.5.4的库
