### ISSUE TITLE
v4.8.1版本中非常谨慎的做了一些和今日头条不一样的全屏效果

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#444]
在全屏状态下不仅能水平方向全屏，还能通过重力感应竖直方向全屏
[朋友们可以下载demo体验一下](https://github.com/lipangit/JieCaoVideoPlayer/releases/download/v4.8.1/jiecaovideoplayer-4.8.1.apk)

**Comment by scar1et** [comment]
请问一下我只想要横向或着竖向的全屏如何设置呢？能否禁止重力感应转向？

**Comment by baikingrio** [comment]
这个版本的全屏效果好多了，可是怎么使用的啊？@lipangit更新一下Demo代码呗。

**Comment by lipangit** [comment]
@scar1et 这可能要修改源码了，修改JCUtil.switchFullOrientation方法里的activityInfo可以配置全屏的视频方向。

**Comment by lipangit** [comment]
@baikingrio 无需修改库外的代码，更新库版本即可

**Comment by gnastnosaj** [comment]
建议后续增加屏幕锁定和DLNA等功能

**Comment by scar1et** [comment]
@lipangit 这样啊，那我还是用之前的版本吧，感觉之前的版本够用了，请问一下是4.8.1刚刚更新的此功能，我换4.8.0就好了吗？之前我用的是4.6.1没问题，更新之后发现全屏逻辑不一样了。。

**Comment by scar1et** [comment]
@lipangit 详细想了一下，还是你您这个效果比较好，只需要在第一次的时候给用户加个可以转向的引导效果就能解决用户不知道的情况了。

**Comment by lipangit** [comment]
@gnastnosaj 微信的鸡汤告诉我们，活是干不完的，功能是加不完的，优秀的人要清楚砍掉什么样的需求，砍掉没用的计划，让自己进步的更快，所以添加功能这方面一直都很小心谨慎，但是势头很猛，总有一天会爆发出来。

**Comment by lipangit** [comment]
@scar1et 明智

**Comment by gnastnosaj** [comment]
全屏模式下系统的虚拟按键会遮挡进度条导致进度条无法点击

**Comment by lipangit** [comment]
@gnastnosaj 这个问题已经知道了，有的机型会遮挡有的不会，这周发个版本修改此问题

**Comment by zouwansheng** [comment]
魅族手机 魅蓝note3.当点全屏的时候是竖着的全屏，然后当我想横屏看的时候，旋转手机，就会自动退出app。

**Comment by junchenChow** [comment]
我想进入全屏立马横屏显示 有没有直接可以调用的api

**Comment by lipangit** [comment]
JCVideoPlayer.FULLSCREEN_ORIENTATION和JCVideoPlayer.NORMAL_ORIENTATION 手动控制进入和退出全屏的屏幕方向 @junchenChow
