### ISSUE TITLE
每次seekto的时候，视频都要重新联网下载缓存,而不是使用已有的缓存 

### ISSUE THREAD

**Issue by dingchao823** [lipangit/JieCaoVideoPlayer#445]
这个怎么解决

**Comment by lipangit** [comment]
确实是这样，这是播放引擎ijkplayer的问题，用系统MediaPlayer就没这个问题

测试今日头条他们也有你说的这个问题，不知道头条用的哪个播放引擎

**Comment by a137235** [comment]
@dingchao823 这个应该是缓存机制的问题，可以自己写个缓存机制来代替系统或者ijk的

**Comment by flztsj** [comment]
https://github.com/danikula/AndroidVideoCache
使用这个库，直接很简单的把视频url封装一层后就可以边播边缓存了。
