### ISSUE TITLE
续播功能：如何打开播放器，直接跳到相应的进度

### ISSUE THREAD

**Issue by bingxuebage** [lipangit/JieCaoVideoPlayer#446]
如题，直接setUp后，并startPlayLogic()，如何再直接跳到相应进度?

**Comment by lipangit** [comment]
设置seekToInAdvance变量即可，相关文档会陆续完善

**Comment by bingxuebage** [comment]
谢大师点拨，能再点拨一下seekToInAdvance和percent怎么算吗？
