### ISSUE TITLE
内存泄漏好像很严重_JCMediaManager.textureView 

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#448]
![screenshot_20161025-165622](https://cloud.githubusercontent.com/assets/13553319/19679363/0b2d6d76-9ad4-11e6-911d-c3fc79a28792.png)
这是leak的图片 或者是我使用姿势不对吗

**Comment by lipangit** [comment]
你的姿势正确，如果你有什么想法可以尝试修改一下，应该不难

**Comment by junchenChow** [comment]
那只能等我新功能搞完有空的时候去fork了

**Comment by lipangit** [comment]
ok

**Comment by sujianqingfeng** [comment]
现在解决没有呀

**Comment by lipangit** [comment]
这个问题还是要靠热心的朋友们解决

**Comment by lipangit** [comment]
@chenjzcj 临床试验过吗老铁

**Comment by chenjzcj** [comment]
> @chenjzcj 临床试验过吗老铁

试验过

**Comment by lipangit** [comment]
已经加进去了
