### ISSUE TITLE
全屏状态下 怎么控制暂停和播放 貌似没找到相关api

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#450]
我又来了～

**Comment by lipangit** [comment]
和非全屏一样，startButton.performClick(),模拟用户点击

**Comment by junchenChow** [comment]
嗯 刚看到一个bug ，在全屏播放视频 快结束的时候 拖住音量不放 再关闭全屏 这时候调节音量的那个控件就一直悬浮在activity里面 只有销毁操作才能去掉。
还有一个小疑问 怎么监听全屏切换的动作。
![screenshot_20161026-201346](https://cloud.githubusercontent.com/assets/13553319/19725578/df7683d0-9bb8-11e6-8696-02fd2e9f5427.png)

**Comment by lipangit** [comment]
bug知道了

继承JCvideoPlayer，复写相关函数能监听相关状态
