### ISSUE TITLE
Can not play video from https url

### ISSUE THREAD

**Issue by secfabregas0** [lipangit/JieCaoVideoPlayer#453]
Hello i Can not play video from url "https" url="https://lh3.googleusercontent.com/FLiU19WtmWIzBKqQds0naHuj9y_cz2Pq9iQHzKncz9d7nMnd0ZLWfS5TwkbtlfeGws8jWZn4qR4=m18"
Please help me !!!!!!

**Comment by lipangit** [comment]
It do not support https default.

https://github.com/lipangit/JieCaoVideoPlayer/issues/320#issuecomment-244386455

**Comment by Piscen** [comment]
You can try this:
 if (url.startsWith("https")) {
                    url= url.replace("https://", "http://");
                }

**Comment by lipangit** [comment]
If Piscen's method works

**Comment by NingSo** [comment]
Uri uri = Uri.parse(videoUrl);
 if (uri.getScheme().equalsIgnoreCase("https")) {
                            videoUrl = videoUrl.replaceFirst("https", "http");
                        }

**Comment by lijie815917** [comment]
I have aar ,it can support https ,h264,and mpeg4
