### ISSUE TITLE
会碰到有的视频播放的时候只有声音，图像是黑屏的现象

### ISSUE THREAD

**Issue by Vikaso** [lipangit/JieCaoVideoPlayer#454]
http://memory100.oss-cn-qingdao.aliyuncs.com/B0/2015060122/A150601_221243_221257.mp4 这个视频 播放的时候黑屏，能听到声音。这个是怎么回事呢？

**Comment by lipangit** [comment]
这个地址浏览器里点击之后是白屏，如果直接放到demo中无法播放可能是图像编码的问题

**Comment by Vikaso** [comment]
这个有解决的办法吗？

**Comment by rel4** [comment]
我也是，很多视频只有声音没有图像

**Comment by lipangit** [comment]
视频图像的编码问题我的研究也不深入，等我们把exoplayer研究明白之后，编码问题应该得以解决
