### ISSUE TITLE
怎么自动开始播放

### ISSUE THREAD

**Issue by DonaldMouse** [lipangit/JieCaoVideoPlayer#455]
项目需求，进入详情界面视频自动播放，但是对可以开始播放的时机还不是很清楚，现在在调用setUp方法后延迟0.3s 调用startButton的onClick事件，但还是偶尔会报null mp错误。 想请教下有没有哪个回调或方法可以确认播放器完全准备好了可以播放了

**Comment by lipangit** [comment]
播放器是单例的，点击startButton之后才会去初始化和播放，需要更多信息帮你解决这个问题
