### ISSUE TITLE
RecycleView中播放就崩溃

### ISSUE THREAD

**Issue by cfh763551832** [lipangit/JieCaoVideoPlayer#457]
不好意思，我第一次用，RecycleView中直接就挂了，报空异常

**Comment by cfh763551832** [comment]
holder.mJCVideoPlayerStandard.setUp(bean.getVideo_uri(), JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "");后面的标题不给的话就错了

**Comment by lipangit** [comment]
你可以给个空字符，能讲讲你的使用场景吗，如果有需要的话，库里应该判断，如果是标题是空就隐藏标题。

**Comment by cfh763551832** [comment]
嗯，搞定了，感谢，本人刚入门的小菜感谢大神解惑

**Comment by lipangit** [comment]
么么哒
