### ISSUE TITLE
如何禁止竖直方向的全屏

### ISSUE THREAD

**Issue by adojayfan** [lipangit/JieCaoVideoPlayer#459]
项目要求点击全屏就直接切换为横向全屏，不需要竖直方向的全屏。

**Comment by lipangit** [comment]
这可能要改库了

![image](https://cloud.githubusercontent.com/assets/2038071/19837873/70b3a5c4-9efe-11e6-86eb-a09335b1edac.png)

修改ActivityInfo为横屏即可

**Comment by PiPiCaptain** [comment]
@lipangit 我也有这个需求，能不能让我们可以自己配置

**Comment by lipangit** [comment]
@PiPiCaptain 你看JCvideoPlayer中有两个全局变量，手动控制全屏和退出全屏的屏幕方向
