### ISSUE TITLE
Playing mp3 can not into fullscreen

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#46]
Because custom set thumb image the project can not get thumb image url ,so every fullscreen no thumb image url, play mp3 in fullscreen without thumb not good look.

**Comment by lipangit** [comment]
dismiss the fullscreen button

**Comment by lipangit** [comment]
done

**Comment by WinMinTun** [comment]
@lipangit I cannot play mp3. Pls kindly help. Here is my code
`jcVideoPlayerStandard.setUp("http://www.stephaniequinn.com/Music/Allegro%20from%20Duet%20in%20C%20Major.mp3", JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "嫂子闭眼睛");`

**Comment by deryfath** [comment]
how to play mp3 just show thumbnail only? my video player dont show anything just blank dark screen. 

thanks
