### ISSUE TITLE
魅族手机遇到的问题,全屏播放,不能到边,上下都有空隙

### ISSUE THREAD

**Issue by zynxiaonanzi** [lipangit/JieCaoVideoPlayer#461]

**Comment by lipangit** [comment]
恩看到你在群里说的了，我们的视频的大小是水平或竖直充满全屏，另外两个方向根据宽高比例在视频不变形的情况下居中，你的截图中水平方向已经充满了，如果上下到边会拉伸视频的尺寸，所有上下有空隙是对的正常的
