### ISSUE TITLE
crash on 7.0

### ISSUE THREAD

**Issue by NingSo** [lipangit/JieCaoVideoPlayer#462]
11-01 11:52:54.086 2321-2801/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x566f61436002b8 in tid 2801 (JieCaoVideoPlay)
                                       
                                       [ 11-01 11:52:54.092   376:  376 W/         ]
                                       debuggerd: handling request: pid=2321 uid=10283 gid=10283 tid=2801
11-01 11:52:54.226 3622-3622/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-01 11:52:54.227 3622-3622/? A/DEBUG: Build fingerprint: 'google/angler/angler:7.0/NBD90X/3254009:user/release-keys'
11-01 11:52:54.227 3622-3622/? A/DEBUG: Revision: '0'
11-01 11:52:54.227 3622-3622/? A/DEBUG: ABI: 'arm64'
11-01 11:52:54.227 3622-3622/? A/DEBUG: pid: 2321, tid: 2801, name: JieCaoVideoPlay  >>> com.theme.valenciacf <<<
11-01 11:52:54.227 3622-3622/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x566f61436002b8
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x0   0000007ee230a588  x1   69566f614365694a  x2   0000007ee1efc800  x3   0000000000000000
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x4   0000000000000038  x5   0000007efec38d90  x6   0000007efecea980  x7   0000000000000000
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x8   69566f6143600250  x9   000000000000004a  x10  0000000000000056  x11  0000007edfff54e8
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x12  fffffffffffff000  x13  ffffffffffffefff  x14  00000000ffffffff  x15  0000007f09365000
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x16  0000007f0935a5a0  x17  0000007f09301d5c  x18  0000000000000000  x19  0000007ee1efc800
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x20  69566f614365694a  x21  0000007ee230a588  x22  0000000000000000  x23  0000007f09365800
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x24  0000007f0936586c  x25  0000007ed91f0000  x26  0000007eda70cef0  x27  0000000000000000
11-01 11:52:54.227 3622-3622/? A/DEBUG:     x28  0000000000000000  x29  0000007edfff4000  x30  0000007f093293d4
11-01 11:52:54.227 3622-3622/? A/DEBUG:     sp   0000007edfff3fd0  pc   0000007f09328e90  pstate 0000000080000000
11-01 11:52:54.241 3622-3622/? A/DEBUG: backtrace:
11-01 11:52:54.241 3622-3622/? A/DEBUG:     #00 pc 000000000008fe90  /system/lib64/libc.so (ifree+88)
11-01 11:52:54.241 3622-3622/? A/DEBUG:     #01 pc 00000000000903d0  /system/lib64/libc.so (je_free+128)
11-01 11:52:54.241 3622-3622/? A/DEBUG:     #02 pc 0000000000147258  /data/app/com.theme.valenciacf-2/lib/arm64/libijkffmpeg.so (av_dict_free+48)

**Comment by lipangit** [comment]
试试5.+，还有这个问题吗
