### ISSUE TITLE
可不可以直接进入全屏播放的那个操作，就直接是横屏

### ISSUE THREAD

**Issue by IdioticMadman** [lipangit/JieCaoVideoPlayer#463]
1. 如题，就是这个操作
![image](https://cloud.githubusercontent.com/assets/16788980/19881661/b95ee654-a042-11e6-8b96-ae751e7dba5d.png)
可不可以直接进入横屏？
2. 可不可以判断当前播放的视频支不支持快进或者快退？

**Comment by lipangit** [comment]
1.这个版本可能要改库了JCUtil.java中，将全屏方法中的ActivityInfo修改成横屏属性即可，以后版本可以考虑给大家配置

2.有不支持快进快退视频的链接吗，我试试，除了hls我还没见过

**Comment by IdioticMadman** [comment]
一般的直播流应该都是不支持快进或快退的吧，支持快进或者快退的话，一般都是一个视频的文件，或者经过流媒体转发的视频文件。我记得ijkplayer里面有这个方法https://github.com/Bilibili/ijkplayer/blob/master/android/ijkplayer/ijkplayer-example/src/main/java/tv/danmaku/ijk/media/example/widget/media/IjkVideoView.java#L857
不过貌似没怎么实现。。。
