### ISSUE TITLE
Activity横屏播放，跳出后再回来 就变成竖屏了，已经在AndroidManifest.xml设置为横屏了

### ISSUE THREAD

**Issue by RaulXiao** [lipangit/JieCaoVideoPlayer#466]
Activity横屏播放，跳出后再回来 就变成竖屏了，已经在AndroidManifest.xml设置为横屏了

**Comment by lipangit** [comment]
JCUtil.java里的最后一个方法，把它的ActivityInfo改成你想要的屏幕方向就好了
