### ISSUE TITLE
后期是否增加切换信源功能：播放源或者清晰度

### ISSUE THREAD

**Issue by GaoMatrix** [lipangit/JieCaoVideoPlayer#469]
在视频播放这个功能挺常见和重要的

**Comment by AkashiWen** [comment]
切换清晰度就是切换播放源，切换播放源就是setUp()

**Comment by lipangit** [comment]
对 本质上是修改url变量。

@GaoMatrix 感谢你的建议，对于添加这些锦上添花的功能我们一直很谨慎，之后会考虑添加这个功能

[功能是加不完的，需求是无穷尽的，即便百人的团队精力也是有限的](https://github.com/lipangit/JieCaoVideoPlayer/projects/2)，[wiki](https://github.com/lipangit/JieCaoVideoPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)中已经有关于清晰度问题的解释，可能还要更细化一些，也在研究让wiki换一个风格，让它更整洁更美观。

**Comment by lipangit** [comment]
不是说没时间开发，而是因为现在在精神的高度对这个功能的理解还不到位

比如说加这个功能，1个小时就能开发完，测试测试，周日就能发版，但是按照现在对开源视频播放器的理解，和对一些信念和逻辑的理解，我的直觉告诉我还不能在JCVideoPlayerStandard中加这个功能

我们的接口非常开放，已经帮助好多朋友继承JCVideoPlayerStandard实现这个功能了，根据自己项目的需要添加这个功能，并不算麻烦

**Comment by cgztzero** [comment]
切换清晰度的功能我实现了 不过是基于4.6.5版本的。
 4.8.1的还在写 我正在往我们项目里导入修改 写完的话可以发到QQ群里 大家指正下

**Comment by lipangit** [comment]
@cgztzero 可以放到demo里给大家参考

**Comment by GaoMatrix** [comment]
@lipangit 请问qq群是多少，能加一下么

**Comment by lipangit** [comment]
@GaoMatrix  Q群:490442439 验证信息:jcvd

**Comment by qq294685358** [comment]
@cgztzero 大兄弟，我在做连播功能， 跟你的切换清晰度功能差不多，但是我遇到了bug，我的qq是294685358，你能加下我QQ大家交流下吗？谢谢了!
