### ISSUE TITLE
Would take a moment and update your example

### ISSUE THREAD

**Issue by PrathameshKesarkar** [lipangit/jiecaovideoplayer#47]
Can please some time out of your busy life and Upate your demo Cause the setUp() showing me I need to override three function i.e. Url , Thumbnail and Title however the example just pass the two items 

Also when I passIn three items it is force closing my app Because U have used ImageLoader somewhere and not Initialized anywhere  and its saying me to have a single Instance of ImageLoader

**Comment by lipangit** [comment]
Ok example will update in 15h

**Comment by PrathameshKesarkar** [comment]
What's the deal with the ImagLoader thing

**Comment by PrathameshKesarkar** [comment]
Ok I fixed it look like u have to Initialize the ImageLoader and set the default configuration.
@lipangit  But why have you kept the seekToPosition() and all those stuff private why can't I access it from player Object

**Comment by lipangit** [comment]
I will remove imageloader,because I believe every project will have it's own load image function, Is likely to be not different , So I make public thumbImage view for people can set thumb by theirselves.

**Comment by PrathameshKesarkar** [comment]
Also can you make moving to a particular position on Video public that would be great also implement a wake lock on VideoPlayer Activity cause the app is going to sleep after some time

**Comment by lipangit** [comment]
This library suit for less then 10min videos, I do not suggest seek position when play small video . if you want to play like TVplay more than 1 hour , you maybe save the position and seekto the position and go on see that video.

**Comment by PrathameshKesarkar** [comment]
So can u add that  feature

**Comment by lipangit** [comment]
Yes seek position many people want, I will add the feature (save position and go on play) to make this library good use

**Comment by lipangit** [comment]
And you can join us if have some progress you can push and share you code

**Comment by lipangit** [comment]
I have question , do you mind this project use eventbus ?  and Do you need to customize the UI

**Comment by PrathameshKesarkar** [comment]
No I have no background in VideoResurface View so I don't think I can help much Yes Custom UI sounds aewsome. 
Also add this to FullScreenVideoPlayerActivity.java   

`getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);`

**Comment by lipangit** [comment]
good idea, you can push it add you to Collaborators

**Comment by lipangit** [comment]
release v1.10

**Comment by PrathameshKesarkar** [comment]
Dude Where is the function in which progressChanges

**Comment by lipangit** [comment]
U can catch VideoEvents.VE_MEDIAPLAYER_UPDATE_BUFFER , this event is from mediaPlayer.setOnBufferingUpdateListener .

But there is no api to catch play progressChanges, JCMediaManager is private ,U can not get play progress.

What is your usage scenarios? Why you want to get progress progressChanges?

**Comment by PrathameshKesarkar** [comment]
Dude can u remove all those Event Bus logs they are  spamming my Logcat and also is there any chances for implementing the Seek Thing in one-two days. I need it urgently

**Comment by lipangit** [comment]
What log, library have just 3 line logs , eventbus logs are all in demo.

**Comment by lipangit** [comment]
What is your application scenarios ? you want to get the video playback progress or you want to seek video progress in your code . Even I add the feature (save position and go on play) seek position API maybe not public , library will save position get position and seek position and go on play .

This library's concept is customers just config the library , customer don't need to write code about video .

**Comment by PrathameshKesarkar** [comment]
Dude I want to Save the position of every video in database so next time I want to watch that video I directly Jump to that Position also If I rotate my device it restart my video from the start

**Comment by lipangit** [comment]
Yes save position of every video is in my workline , but 2 or 3 days may not complete .

**Comment by PrathameshKesarkar** [comment]
Why don't you keep the functionality open so other can modify it without relying on you 
Sorry If I sound rude but I need that feature very badly just keep the doorway open so I can configure as I want

**Comment by lipangit** [comment]
If you save video position for go on play video , I will say NO , because the concept is customer do not need to write code about video ,the library will do that for you.   If you get video position for other purpose has nothing to do with video , I will say YES

**Comment by lipangit** [comment]
#50 will add this feature, next is custom ui
