### ISSUE TITLE
内存泄露怎么解决呀？

### ISSUE THREAD

**Issue by guangjie0916** [lipangit/JieCaoVideoPlayer#470]
D/JieCaoVideoPlayer: onInfo what - 3 extra - 0
I/JieCaoVideoPlayer: onSurfaceTextureUpdated [202331946] textureSizeChanged=false
I/art: hprof: heap dump "/storage/emulated/0/Download/leakcanary-fm.jiecao.jiecaovideoplayer/suspected_leak_heapdump.hprof" starting...
I/art: hprof: heap dump completed (44MB) in 5.859s
W/AudioTrack: releaseBuffer() track 0x7f96e71100 disabled due to previous underrun, restarting
V/JieCaoVideoPlayer: onProgressUpdate 0/195102 [19885874] 
I/Choreographer: Skipped 350 frames!  The application may be doing too much work on its main thread.

**Comment by lipangit** [comment]
能看到MemLeak的log吗，你如果解决了提交上来吧，分享给大家

**Comment by guangjie0916** [comment]
嗯，好的
