### ISSUE TITLE
是否考虑加入视频流截图功能呢？

### ISSUE THREAD

**Issue by tommyfeng** [lipangit/JieCaoVideoPlayer#471]
后期是否可以考虑加入视频流截图功能呢。。 @lipangit

**Comment by YuJunKui1995** [comment]
JCMediaManager.textureView.getBitmap  可以获取到播放的视频截图

**Comment by tommyfeng** [comment]
@YuJunKui1995 好像没有参数可以指定视频播放进度的截图。比如说我要截取第10秒的，应该怎么做？

**Comment by YuJunKui1995** [comment]
getCurrentPositionWhenPlaying()可以获取到当前播放进度

**Comment by tommyfeng** [comment]
@YuJunKui1995 没有设置当前播放进度的参数啊 
![qq 20161105103644](https://cloud.githubusercontent.com/assets/20334082/20027038/def14d90-a343-11e6-9367-580253f0314a.png)

**Comment by YuJunKui1995** [comment]
本来就没有设置播放进度的  
你可以通过监听getCurrentPositionWhenPlaying()的值
如果到你希望获取的时间后调用
JCMediaManager.textureView.getBitmap 
不过这个方案只适合在播放中获取视频截图

**Comment by IdioticMadman** [comment]
@YuJunKui1995 那要截取视频的话，有什么方式？
