### ISSUE TITLE
播放器悬浮于整个app时全屏问题

### ISSUE THREAD

**Issue by LFen** [lipangit/JieCaoVideoPlayer#472]
当使用window manager将播放器悬浮于整个app时，点击全屏，会出现全屏播放界面被原播放界面遮住，或者是全屏播放界面不出现的问题。

麻烦帮忙看一下，谢谢

**Comment by lipangit** [comment]
看看你是怎么addView的，加Q群来个小视频吧看看具体什么效果

**Comment by LFen** [comment]
这是我addView的代码：
////////////////////////////////////
int screenWidth = PlatformUtil.getScreenDisplayMetrics()[0];

// BizrankingVideoPlayer是我自己自定义UI的播放器
BizrankingVideoPlayer player = new BizrankingVideoPlayer(activity);

WindowManager.LayoutParams params = new WindowManager.LayoutParams(screenWidth, (int) (screenWidth*(9f/16f)), WindowManager.LayoutParams.TYPE_SYSTEM_ALERT, WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE, PixelFormat.TRANSLUCENT);

params.gravity = Gravity.TOP;
WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);
wm.addView(player, params);
        
player.setUp(url, BizrankingVideoPlayer.SCREEN_LAYOUT_LIST, "");
/////////////////////////////////////

因为要使播放界面悬浮于整个app，所以使用了window manager，这样播放就不受页面切换的影响。

**Comment by LFen** [comment]
视频已上传到群里  播放器悬浮于整个app时全屏问题 #472.mp4

**Comment by lipangit** [comment]
看到你的视频了，多个addView应该是依次覆盖的，全屏应该盖住你的悬浮的View，如果不是依次覆盖的话，建议你全屏的时候remove掉你悬浮的控件。

**Comment by LFen** [comment]
嗯，我在全屏的时候将windowmanager里的view remove掉，然后退出全屏的时候重新add回来就可以。
不过，我还遇到一个问题就是，比如我在activity A中打开这个悬浮的视频界面，然后再切换到activity B，这个时候，播放界面是在最上层的，但是切换全屏的时候，那个全屏的界面就跑到activity B下层去了，只有退出activity B才能看到全屏的播放界面，但是同样的切换全屏的操作只要不切换activity就没有这个问题，请问下有什么好的建议呢？

谢谢！

**Comment by lipangit** [comment]
ViewGroup vp = (ViewGroup) (JCUtils.scanForActivity(context))//.getWindow().getDecorView();
                .findViewById(Window.ID_ANDROID_CONTENT);
现在用的是这个代码取得全屏的容器，如果用getWindow().getDecorView();可能是整个应用级别的。
