### ISSUE TITLE
在listview 中，itemclick 事件不被调用。

### ISSUE THREAD

**Issue by laibinCN** [lipangit/JieCaoVideoPlayer#473]
在demo 中，把item_videoview.xml布局中添加任意控件。
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
        android:id="@+id/videoplayer"
        android:layout_width="match_parent"
        android:layout_height="200dp" />
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

</LinearLayout>`
在ListViewNormalActivity 中添加onitem点击事件，程序运行后点击空白区域，onitem 点击事件不被调用。
在我自己的项目的listview中，在暂停情况onitem可以响应，在播放时第一次itemclick不会响应，地俄日此点击才会响应itemclick事件。

**Comment by laibinCN** [comment]
在我自己的项目的listview中，在暂停情况onitem可以响应，在播放时第一次itemclick不会响应，第二次点击才会响应itemclick事件。

**Comment by lipangit** [comment]
节操精选APP也有这个需求，点击item进入详情页，但是是正常的没有你说的问题，你断点一下，看看第一次点击哪块代码相应了？
