### ISSUE TITLE
全屏状态的时候,所有listener都为空了,必须这样吗?能让listener不为空么

### ISSUE THREAD

**Issue by zynxiaonanzi** [lipangit/JieCaoVideoPlayer#474]

**Comment by lipangit** [comment]
什么listener？是JCVideoPlayerManager里的listenerList吗，开发者不需要操作这里的东西

**Comment by zynxiaonanzi** [comment]
@lipangit 嗯呢,暂停状态下,如果切换到全屏,在回来,就会黑屏,打印log,显示listener为空了

**Comment by lipangit** [comment]
改源码了吧

**Comment by zynxiaonanzi** [comment]
嗯,一些需求,需要改源码

**Comment by lipangit** [comment]
切换全屏的时候listener不要动，这个容易蒙圈，你好好调试调试，问题也不大。
