### ISSUE TITLE
How to determine when the jcvd move out from field of vision

### ISSUE THREAD

**Issue by lipangit** [lipangit/JieCaoVideoPlayer#475]
title: 如何判断视频控件移除屏幕了

Now when setUp or reuse the holder to determine jcvd move out from field of vision, obviously this is not good.

现在是通过什么时候复用列表来判断视频控件是不是移出视野了，这样做非常局限并且非常不准确，更准确的判断视频控件移出手机屏幕了呢

**Comment by lipangit** [comment]
一五得五   二五一十   五五..五五..三十五  呜呜呜太难了

**Comment by cgztzero** [comment]
这个我做了。listview有一个监听setRecyclerListener 重写里面的方法onMovedToScrapHeap(View view)。里面的view就是listview被移动出屏幕的view。欢迎各位探讨

**Comment by cgztzero** [comment]
4.6版本我实现了 是listview的setRecyclerListener监听。但是4.8版本是屏幕旋转了 这个监听在横屏变回竖屏的时候也会调用，目前还在想办法ing。

**Comment by cgztzero** [comment]
4.8.2版本我实现。还是RecyclerListener的监听，并且判断移动的view的坐标是否超过屏幕界限就可以了

**Comment by lipangit** [comment]
@cgztzero 怎么实现的，你在qq群吗
