### ISSUE TITLE
你这个库支持那些视频格式？

### ISSUE THREAD

**Issue by my-sunshine** [lipangit/JieCaoVideoPlayer#477]

**Comment by lipangit** [comment]
播放引擎用的[ijkplayer](https://github.com/Bilibili/ijkplayer)

https://ffmpeg.org/ffmpeg-formats.html

**Comment by my-sunshine** [comment]
怎么再视频播放完的时候，退出视频播放器？

**Comment by lipangit** [comment]
全屏播放完会退出全屏，你说的退出哪个播放器
