### ISSUE TITLE
Audio not working in some HLS links

### ISSUE THREAD

**Issue by naveenfunk** [lipangit/JieCaoVideoPlayer#478]
I've been using this library to play all kind of links but now I've encountered a problem with these links
http://stream.rtvpunjabi.com/rtvpunjabi1.m3u8 
http://158.69.124.9:1935/5aabtv/5aabtv/playlist.m3u8

These link plays fluently but their audio doesn't work . But if i use android default video player to play these links then it plays normally without any issue.

Can someone please tell me is there anything wrong with these links or there is some other problem.

**Comment by DawinderGill** [comment]
Hi @naveenfunk 
I am also facing same issue but with some links. 
I have also used your given links same problem m also facing.

Please tell me also if you found any solution for this.

**Comment by lipangit** [comment]
You both can go to ask [ijkplayer](https://github.com/Bilibili/ijkplayer).

This project use [ijkplayer](https://github.com/Bilibili/ijkplayer) as video engine,JieCaoVideoPlayer work on UI and Logic not video formate.
