### ISSUE TITLE
Remove Pause button onstart video

### ISSUE THREAD

**Issue by naguchennai** [lipangit/JieCaoVideoPlayer#479]
My videos are just 10 to 60seconds videos.. when i use autoplay video pause button showing nearly 5 second..  how can i disable pause button on video start?

**Comment by lipangit** [comment]
extends JCVideoPlayerStandard, Override setUiWitStateAndScreen(int);case CURRENT_STATE,
invisible startButton except STATE_NORMAL.

**Comment by naguchennai** [comment]
jcVideoPlayerStandard.setUp(VIDEO_URL, JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "");
        jcVideoPlayerStandard.startButton.performClick();
        jcVideoPlayerStandard.startButton.setVisibility(View.GONE);

I try this still pause button showing ... my video is auto play

**Comment by lipangit** [comment]
jcVideoPlayerStandard.startButton.setVisibility(View.GONE); this will not work

**Comment by lipangit** [comment]
nds JCVideoPlayerStandard, Override setUiWitStateAndScreen() function , int this function swtch CURRENT_STATE

**Comment by naguchennai** [comment]
lol i cant undertand... public class VideoView_Activity extends JCVideoPlayerStandard{  ?? this not work

**Comment by lipangit** [comment]
Create  a new Class, called VideoView extends JCVideoPlayerStandard,Use VideoView in activity

**Comment by fukemy** [comment]
hello. I cant not find setUiWitStateAndScreen method to Override

```

public class CustomJZVideoPlayerStandard extends JZVideoPlayerStandard {

    public CustomJZVideoPlayerStandard(Context context) {
        super(context);
    }

}
```
