### ISSUE TITLE
请问在6.0或7.0上工作正常么？

### ISSUE THREAD

**Issue by Forsaken-sl** [lipangit/JieCaoVideoPlayer#480]
之前引用的这个库，工作正常，但是最近测试时发现，在5.0系统上工作正常，而换成6.0或7.0系统之后，同样的视频，能显示出预览，但是无法播放，返回E/JieCaoVideoPlayer: onError -10000 - 0 [23234732] 错误。请问这个有什么好的解决方式么？

**Comment by Forsaken-sl** [comment]
我开始也以为是，但是在红米note3上，三星的s7e, nexus5上都试了一下，都不可以。
虽然我的视频是https开头的，但是上次已经编译加入.so文件了 － －
肝疼

**Comment by lipangit** [comment]
我上一个手机是红米note3，可以的，可能是https或者编译有问题

**Comment by Forsaken-sl** [comment]
这个原因找到了，是因为编译openssl的时候，不知道为啥arm64-v8a没有编译成功，只成功了一个armeabi－v7a，而我测试用的正好是个armeabi－v7a的手机（5.0系统），而6.0系统的测机又正好都是arm64-v8a，就导致了一个假象是系统原因。。。
升级ndk重新编译openssl之后就好了。

**Comment by lipangit** [comment]
haha 好
