### ISSUE TITLE
Video Autoplay

### ISSUE THREAD

**Issue by pmpandit04** [lipangit/JieCaoVideoPlayer#483]
Is there a way to autoplay the video without starting it in full screen? I would like to set it up like this but with AutoPlay enabled.
 
jcVideoPlayerStandard.setUp("http://streaming.hearstdigitalstudios.com/hearst_magazines/573b974ed55930587ca86f44_1463523182.m3u8"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");

**Comment by lipangit** [comment]
jcVideoPlayerStandard.looping=true;

**Comment by pmpandit04** [comment]
Thank you!

**Comment by kr1stjans** [comment]
Doesn't work for me.

`
jcVideoPlayerStandard.looping = true;
jcVideoPlayerStandard.setUp(getSource(),JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");
`

What am I doing wrong?

**Comment by lipangit** [comment]
@pmpandit04 Is you mother lauguage English, could you help me to improve readme.md, make it in native English.

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/48599061-05bbcb80-e9a1-11e8-9135-93ad91a31f60.png)

use new version
