### ISSUE TITLE
Expand video on device rotation

### ISSUE THREAD

**Issue by pmpandit04** [lipangit/JieCaoVideoPlayer#486]
Hello,

I inflate a JCVideoPlayerStandard  layout inside of an **_Activity_** and I use the code below to autoPlay the video. 
```
JCVideoPlayerStandard jcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.videoplayer_standard);
        jcVideoPlayerStandard.setUp("http://streaming.hearstdigitalstudios.com/hearst_magazines/573b974ed55930587ca86f44_1463523182.m3u8"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "");
        jcVideoPlayerStandard.looping = true;
        jcVideoPlayerStandard.prepareVideo();
```
How do I change the layout of the video to expand and change its orientation to horizontal once the device and **_Activity_** rotates horizontally? And then bring it back to vertical on device rotation to vertical. Also, how do I continue playing the video when the device is rotated? Right now it is resetting itself.

**Comment by pmpandit04** [comment]
I found the answer. 

I have to set android:configChanges="keyboardHidden|orientation|screenSize" in android manifest for that Activity.

**Comment by lipangit** [comment]
I will write the tip in readme.
