### ISSUE TITLE
全屏直接闪退

### ISSUE THREAD

**Issue by iknow4** [lipangit/JieCaoVideoPlayer#487]
报错日志：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference
E/AndroidRuntime(20946): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.hideSupportActionBar(JCVideoPlayer.java:952)
E/AndroidRuntime(20946): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.startWindowFullscreen(JCVideoPlayer.java:691)
E/AndroidRuntime(20946): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onClick(JCVideoPlayer.java:239)
E/AndroidRuntime(20946): 	at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:168)
E/AndroidRuntime(20946): 	at android.view.View.performClick(View.java:4908)
E/AndroidRuntime(20946): 	at android.view.View$PerformClick.run(View.java:20382)
E/AndroidRuntime(20946): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime(20946): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(20946): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(20946): 	at android.app.ActivityThread.main(ActivityThread.java:5692)
E/AndroidRuntime(20946): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20946): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(20946): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime(20946): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

可否帮忙看一下？谢谢！

**Comment by iknow4** [comment]
我是把JCVideoPlayerStandard放在一个dialog的布局当中来进行视屏播放。
播放的时候直接就黑屏，但是有声音

**Comment by lipangit** [comment]
啊 对，在dialog中可能要处理一下，我没想到有这种情况，现在都默认是在activity中播放的

**Comment by lipangit** [comment]
你创建dialog的activity是继承的AppCompatActivity吗

**Comment by iknow4** [comment]
我继承了AppCompatActivity之后，硬件加速也打开，播放视频还是黑屏，这一点让我和不理解！

**Comment by lipangit** [comment]
把你的地址直接放到demo中如果也是黑屏的话就是图像编码的问题，可以到ijkplayer项目里问问

**Comment by iknow4** [comment]
@lipangit  放到demo是ok的

**Comment by lipangit** [comment]
@iknow4  仔细和demo对比一下吧，估计是什么地方落下了

**Comment by HywTony** [comment]
@lipangit 所以，dialog的情况加入video。全屏的情况该怎么处理呢。

**Comment by lipangit** [comment]
dialog也能取得context吧
