### ISSUE TITLE
请问如何修改JCUtils

### ISSUE THREAD

**Issue by adojayfan** [lipangit/JieCaoVideoPlayer#488]
把jcvideoplayer-lib导入项目后，没有发现switchFullOrientation和switchNormalOrientation两个方法。
使用gradle依赖能看到这两个方法，但是是无法修改的。。。
这是编译时才会生成的吗？

**Comment by lipangit** [comment]
使用最新版本，4.8.2的library

**Comment by adojayfan** [comment]
大哥，最新版的jcvideoplayer-lib也没有这2个方法啊。。。

**Comment by lipangit** [comment]
对对对，这两个方法删除，因为方法里只有一行代码，觉得多余。

![image](https://cloud.githubusercontent.com/assets/2038071/20333114/590efbb8-abeb-11e6-801d-91b02360c155.png)

手动修改这两个变量修改 达到全屏前和全屏后屏幕的方向

**Comment by adojayfan** [comment]
谢谢大哥，问题终于解决了
