### ISSUE TITLE
大神，能否出个API文档？

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#489]
大神，你好，很喜欢你这个视频播放类库。但API说明太少，能否出个API文档？现在我经常要去查看源码才能做下去，要是有份API文档就方便多了

**Comment by lipangit** [comment]
看wiki中简单的介绍

**Comment by PiPiCaptain** [comment]
@lipangit 对了，我在使用的过程中，有些视频时间比较长的。播放过程中，突然会报错。是因为只支持播放短小视频么？

**Comment by lipangit** [comment]
这应该是ijkplayer的bug
