### ISSUE TITLE
Issue wiht playing YouTube Videos 

### ISSUE THREAD

**Issue by pirupius** [lipangit/JieCaoVideoPlayer#494]
A case in point is this trailer for "The beauty and the beast" hosted in this url ( https://www.youtube.com/watch?v=SqQvZ_VUtg8 ) .  when passed to the video player, it gives a bad url error and when i tracked the cause, it turns out it transforms the upper case letters to lower case so the url being read by the player is "https://www.youtube.com/watch?v=sqqvz_vutg8" which is invalid.  

Any help on this issue will be deeply appreciated.

**Comment by lipangit** [comment]
This project use ijkplayer to play video, it can not play youtube url, that url is not point at video file.

I do not know how to play youtube videos, do you have example I will learn it before.

**Comment by pirupius** [comment]
i came across this repository while looking for an alternative to the YouTube API intent and that's why am asking. But when i find a work around, I'll update you.

**Comment by lipangit** [comment]
This project with Ijkplayer can not play youtube video directly by that url .

**Comment by lipangit** [comment]
try version 5.+ maybe support
