### ISSUE TITLE
Orientation cange not working

### ISSUE THREAD

**Issue by drdla49** [lipangit/JieCaoVideoPlayer#496]
I used version 4.8.3 and follow your example. I can use auto fullscreen when I rotate. But this issue is even if I turn on or off this functionality.

I my device is in landscape and I click play, activity auto rotate to portrait, even if device is styll landscape and not start playing.
If I am in portrait and rotate device, video pause and display is still in portrait.
This issue is in both, fullscreen and non fulllscreen mode.

Thank you fro adwice or for soltion this issue.

**Comment by lipangit** [comment]
Do you forget AndroidManifest, see demo AndroidManifest.

**Comment by drdla49** [comment]
Thank you! It solv my problems about rotate and fullscreen.
But still I have problem with play in landscape. If my device and sceen are in landscape and I click play, device screen rotate to portrait and start loadnig video.
Any advice?
Thank you so much.

**Comment by drdla49** [comment]
Thank you!! It solv most my problems. But still I have one problem.
If I start play in landscape, go to fullscreen, and click back button. 
Player continue play in portrait, but not in landscape, even If I start from landscape.
Any advice? 
Thank you so much.

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/20507969/568c2692-b099-11e6-937f-f6524980bf1f.png)
this two can control before fullscreen and after fullscreen orientation
