### ISSUE TITLE
网络慢时，播放进度拖拉太快 只会停留在第一次拖进度哪里，要等加载完成后才能拖拉下一次。

### ISSUE THREAD

**Issue by janecer** [lipangit/JieCaoVideoPlayer#497]

**Comment by lipangit** [comment]
我觉得可以接受

**Comment by janecer** [comment]
目测 爱奇艺，其它播放器都是随拖随加载
额 能问一下 在你的源码库里哪里可以修改么？

**Comment by lipangit** [comment]
这个是播放引擎 [ijkplayer](https://github.com/Bilibili/ijkplayer)

因为这个想改源码，有够任性

**Comment by janecer** [comment]
产品要求了，木办法

**Comment by janecer** [comment]
解决了，这不是ijkplayer问题。我改了JCVideoPlayer 这里
//        if (currentState != CURRENT_STATE_PLAYING &&
//                currentState != CURRENT_STATE_PAUSE) return;
        if(JCMediaManager.instance().mediaPlayer != null && JCMediaManager.instance().mediaPlayer.isPlaying()) {
            int time = seekBar.getProgress() * getDuration() / 100;
            JCMediaManager.instance().mediaPlayer.seekTo(time);
            Log.i(TAG, "seekTo " + time + " [" + this.hashCode() + "] ");
        }

**Comment by lipangit** [comment]
厉害
