### ISSUE TITLE
华硕  T00J 4.3 Java Runtime error: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#499]
华硕  T00J 4.3 Java Runtime error: java.lang.UnsatisfiedLinkError: Couldn't load ijkffmpeg from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.xxx.android-1.apk"],nativeLibraryDirectories=[/data/app-lib/me.xxx.android-1, /vendor/lib, /system/lib, /system/lib/arm]]]: findLibrary returned null, Process: me.xxx.android, PID: 24280, Line: 2966  

华硕这款机型 ijklib有问题～

**Comment by lipangit** [comment]
是运行的demo吗？

觉得还是引入包的方法有问题。demo在云测上测过，没有兼容问题

**Comment by junchenChow** [comment]
这个就是在Testin 测试出来的 引入包是之前的4.6.5版本

**Comment by lipangit** [comment]
这手机都没卖的了T_T，别的机型还有兼容问题吗

**Comment by aaronsu** [comment]
oppo R9 andorid 5.1
 dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.movikr.cinema-1/base.apk"],nativeLibraryDirectories=[/data/app/com.movikr.cinema-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"
                                                                    
你的demo 运行没问题.我引入就会报这个错误很是奇怪
我引入的方式为:
    compile 'fm.jiecao:jiecaovideoplayer:4.8.3'

**Comment by lipangit** [comment]
李易峰充电五分钟通话两小时的R9，这机型还是要关注一下

**Comment by aaronsu** [comment]
哈哈...蛋疼的手机...不过您的demo下载没问题.我引入有问题...也试验了 用aar的方式引入也不行,正准备下载源码library的方式弄..不过公司网络太差,还在等待.有结果麻烦说下..多谢..

**Comment by SunshineExit** [comment]
魅族 PRO 5，CPU架构：arm64-v8a，同样报这个错误
java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yimiao100.sale-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yimiao100.sale-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libijkffmpeg.so"

我直接把demo里的lib包导入到AS里依赖的。但是同样会报这个错误。我还没有试过demo
