### ISSUE TITLE
JCVideoPlayer中cacheImageView报错

### ISSUE THREAD

**Issue by linmomo** [lipangit/JieCaoVideoPlayer#500]
项目中使用库引入,在多类型listview中使用viewstub中出现此问题，旧版的没有出现这个问题，但是控件是存在的，不知是哪里写的不对，求解

    android.view.InflateException:Binary XML file line #11: Error inflating class fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                                                                  android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                  ......
                                                                  cause by:
                                                                  java.lang.NoSuchFieldError:No static field cache of type I in class Lfm/jiecao/jcvideoplayer_lib/R$id; or its superclasses (declaration of 'fm.jiecao.jcvideoplayer_lib.R$id' appears in /data/app/com.starwinwin.mall-1/base.apk:classes3.dex)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.init(JCVideoPlayer.java:136)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.init(JCVideoPlayerStandard.java:53)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.<init>(JCVideoPlayer.java:123)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.<init>(JCVideoPlayerStandard.java:48)
                                                                  java.lang.reflect.Constructor.newInstance(Native Method)
                                                                  java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                  android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                  android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                  android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                  android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                  android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                  android.view.ViewStub.inflate(ViewStub.java:264)

**Comment by marvinotr** [comment]
还百度的吧

**Comment by lipangit** [comment]
不建议把控件放到viewstub中，这里会及时回收资源的，平时并不会占用过多资源，不想看到gone就好了

**Comment by linmomo** [comment]
@marvinotr 检查过了，才会出来问的，一般这个问题缺少一个构造方法，控件不存在都检查过了，应该不是这些问题，在demo上是正常的，是将库引入项目，但是项目中用就会报这个问题

**Comment by linmomo** [comment]
@lipangit 按你说的，不放在viewstub中，按你说的方式处理，但是还是报一样的问题，实在Recyclecler中使用，没有多类型，只是显示隐藏，但是还是会报上述的问题，很奇怪，完全不知道为什么

**Comment by lipangit** [comment]
没这么复杂吧，setVisibility GONE 没问题的,  要么你抽一些代码发给我看看，就把onCreate里怎么调用JCVD会出错的代码发过来我帮你看看

**Comment by linmomo** [comment]
@lipangit 问题是不复杂，用你说的方法也是可以的，最早的版本在viewStub中也是可以的，现在是在适配器中，使用最新版JCVideoPlayerStandard，RecyclerView列表一加载就报那个问题，以前的ListView列表换成这个也会有这个问题，用很早以前的版本就不会，出问题的类是JCResizeImageView，主要是在 JCVideoPlayer中cacheImageView = (JCResizeImageView) findViewById(R.id.cache)这句报错，我也看了半天也很不理解为什么这个会报错，异常是
> EXCEPTION MSG: No static field cache of type I in class Lfm/jiecao/jcvideoplayer_lib/R$id; or its superclasses (declaration of 'fm.jiecao.jcvideoplayer_lib.R$id' appears in /data/app/com.starwinwin.mall-2/base.apk:classes3.dex)
11-22 15:59:37.652 32490-32490/com.starwinwin.mall E/CrashReport: # EXCEPTION STACK:
                                                                   android.view.InflateException:Binary XML file line #86: Error inflating class fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                                                                  android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                  ......
                                                                  cause by:
                                                                  java.lang.NoSuchFieldError:No static field cache of type I in class Lfm/jiecao/jcvideoplayer_lib/R$id; or its superclasses (declaration of 'fm.jiecao.jcvideoplayer_lib.R$id' appears in /data/app/com.starwinwin.mall-2/base.apk:classes3.dex)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.init(JCVideoPlayer.java:136)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.init(JCVideoPlayerStandard.java:53)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.<init>(JCVideoPlayer.java:123)
                                                                  fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.<init>(JCVideoPlayerStandard.java:48)
                                                                  java.lang.reflect.Constructor.newInstance(Native Method)
                                                                  java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                  android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                  android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:747)
                                                                  android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                  android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                  android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                  android.view.LayoutInflater.inflate(LayoutInflater.java:418)
                                                                  com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:962)
                                                                  com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:629)
                                                                  com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:625)
                                                                  com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:507)
                                                                  com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:57)
                                                                  android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                                  android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                                  android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                  android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                  android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                  android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                  android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                  android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                  android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                  android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                  android.view.View.layout(View.java:15714)
                                                                  android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                  android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                  android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                  android.view.View.layout(View.java:15714)
                                                                  android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                  android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                  android.view.View.layout(View.java:15714)
                                                                  android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                  android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                  android.view.View.layout(View.java:15714)
                                                                  android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                  android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)

这是xml中
>        
<fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
            android:id="@+id/list_video"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:visibility="gone"/>

这是调用处理
> if (comtyListBean.isIsVideo()) {
            nineGridImageView.setVisibility(View.GONE);
            jcVideoPlayerStandard.setVisibility(View.VISIBLE);
            ComtyImgListBean comtyImgListBean = comtyImgList.get(0);
            int videoHeight = imgWidth * comtyImgListBean.getImgHeight() / comtyImgListBean.getImgWidth();
            jcVideoPlayerStandard.getLayoutParams().width = imgWidth;
            jcVideoPlayerStandard.getLayoutParams().height = videoHeight;
            jcVideoPlayerStandard.coverImageView.getLayoutParams().width = imgWidth;
            jcVideoPlayerStandard.coverImageView.getLayoutParams().height = videoHeight;
            jcVideoPlayerStandard.coverImageView.setScaleType(ImageView.ScaleType.CENTER_CROP);
            jcVideoPlayerStandard.setUp(comtyImgListBean.getComtyVideo(), JCVideoPlayer.SCREEN_LAYOUT_LIST, "");
        } else {
            //九宫格
            nineGridImageView.setVisibility(View.VISIBLE);
            jcVideoPlayerStandard.setVisibility(View.GONE);
            nineGridImageView.setAdapter(new NineGridViewClickAdapter(mContext, comtyImgList));
            //设置单图
            if (comtyImgList != null && comtyImgList.size() == 1) {
                nineGridImageView.setSingleImageSize(imgWidth);
                nineGridImageView.setSingleImageRatio(comtyImgList.get(0).getImgWidth() * 1.0f / comtyImgList.get(0).getImgHeight() * 1.0f);
            }
        }

**Comment by lipangit** [comment]
布局里控件id匹配吗，检查继承view的类的混淆

目测看不出有什么问题

**Comment by linmomo** [comment]
@lipangit 是咯，就是一个简单的控件查找，控件id我把两个实现类都换了个名字，项目没有混淆，所以我也很莫名，这个只要再xml中声明就会报错，目测是初始化的时候出问题

**Comment by linmomo** [comment]
@lipangit 问题解决了，把原来引入项目中旧的代码都删除掉，就不会又这个问题了，麻烦了，谢谢！
