### ISSUE TITLE
播放完成后想保留最后一帧 怎么搞

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#501]
播放完成后想保留最后一帧 怎么搞 ， 大神？

**Comment by marvinotr** [comment]
这个不太好用，建议你用七牛+百度点播

**Comment by lipangit** [comment]
@yuxinLi 参照 demo中 AboutUI  -> Small change ui -> 嫂子还在浪   是你想要的效果

**Comment by lipangit** [comment]
@marvinotr 可能有些视频编码适配有问题 机型适配也不是很好， 给很多人造成过麻烦

**Comment by yuxinLi** [comment]
全屏之后 ， 播放完成后不需要退出全屏 ， 
我把最下面两行注释掉实现了此效果 ， 不知道会不会有其他问题？

@Override
    public void onAutoCompletion() {
        Log.i(TAG, "onAutoCompletion " + " [" + this.hashCode() + "] ");
        onEvent(JCBuriedPoint.ON_AUTO_COMPLETE);
        setUiWitStateAndScreen(CURRENT_STATE_AUTO_COMPLETE);
//        JCVideoPlayerManager.popListener();//自己进入autoComplete状态，其他的进入complete状态
//        JCVideoPlayerManager.completeAll();
    }

**Comment by yuxinLi** [comment]
@lipangit

**Comment by yuxinLi** [comment]
@lipangit 
 我这里全屏播放完成后会自动退出全屏，怎么解决？

**Comment by hackboy** [comment]
@lipangit demo里没看到这个例子

**Comment by lipangit** [comment]
@hackboy 是嫂子想旅行
