### ISSUE TITLE
compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.7.4'编译报错,求助!

### ISSUE THREAD

**Issue by zxydream** [lipangit/JieCaoVideoPlayer#502]
Error:Execution failed for task ':app:processAnzhiDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [tv.danmaku.ijk.media:ijkplayer-arm64:0.7.4] /Users/zxy/AndroidStudioProjects/dachen/androidEDA/app/build/intermediates/exploded-aar/tv.danmaku.ijk.media/ijkplayer-arm64/0.7.4/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="tv.danmaku.ijk.media.player_arm64" to force usage

因为在测试时使用一款paid时闪退,错误提示是缺少arm64,但是我在minSdkVersion 16的情况下是用不了tv.danmaku.ijk.media:ijkplayer-arm64:0.7.4~,请问一下如何可以解决!

**Comment by zxydream** [comment]
已解决,
在AndroidManifest中添加<uses-sdk tools:overrideLibrary="com.example.ijkplayer_x86_64,tv.danmaku.ijk.media.player_arm64"/>

**Comment by lipangit** [comment]
库里已经添加过了

解决了就好
