### ISSUE TITLE
1080电影，CPU占用较高，界面卡顿现象比较严重。

### ISSUE THREAD

**Issue by ATai2** [lipangit/JieCaoVideoPlayer#503]
想在天猫魔盒上开发，但是在使用jiecao播放1080的电影时，出现较严重的卡顿现象。高清的电视直播源也存在，只有画面没有声音。MediaPlayer播放视频没问题~~~

**Comment by lipangit** [comment]
这是ijkplayer的问题，我们JCVD没法解决，正在尝试替换ijkplayer

**Comment by 18667366881** [comment]
啊 高清的视频会卡吗   我没试过  但是我准备要把直播的线路 放到JCVD上播放  不知效果如果   内存是否吃得多？
