### ISSUE TITLE
升级到4.8.3的崩溃

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#504]
之前是用的4.6.5 后面升级了引入版本到最新  原封不动的代码  全屏之后自动全屏一感应就直接崩溃了 看了下崩溃日志 是我播放页面的presenter为空指针 应该是自动全屏的时候崩溃了 导致我之前的activity 尝试恢复 然后这时候之前持有的presenter已经为空了。
主要是想知道为什么全屏会崩溃，代码都是以前4.6.5的 应该不致于有什么东西没调用。

**Comment by lipangit** [comment]
检查一下Manifest的activity config
