### ISSUE TITLE
全屏播放完成后，会自动退出全屏

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#505]
全屏播放完成后，会自动退出全屏 ， 怎么破

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard 复写onAutoComplete函数，如果是全屏状态拦截父类的逻辑，写自己的逻辑

**Comment by yuxinLi** [comment]
@lipangit 
全屏的时候 ， 我注释掉了最后一行 ， 播放完成后没有退出全屏了
@Override
    public void onAutoCompletion() {
        if (currentScreen == SCREEN_WINDOW_FULLSCREEN){
            Logger.e(" onAutoCompletion == full screen");
            Log.i(TAG, "onAutoCompletion " + " [" + this.hashCode() + "] ");
            onEvent(JCBuriedPoint.ON_AUTO_COMPLETE);
            setUiWitStateAndScreen(CURRENT_STATE_AUTO_COMPLETE);
            JCVideoPlayerManager.popListener();//自己进入autoComplete状态，其他的进入complete状态
//            JCVideoPlayerManager.completeAll();
        }else {
            super.onAutoCompletion();
        }
    }

但是我点击播放按钮 ， 这时会自动退出全屏 ， 并且没有播放

**Comment by yuxinLi** [comment]
@lipangit 
1. 这个库逻辑点击 startButton 的时候会强制竖屏的? 

-->prepareVideo() 
    --> JCVideoPlayerManager.completeAll() 
       --> JCVideoPlayer.onCompletion() 
          -->clearFullscreenLayout();
               JCUtils.switchNormalOrientation(getContext());


2.  JCVideoPlayerManager.LISTENERLIST    一般最多是不是有两个？ 一个横屏、一个竖屏
JCVideoPlayerManager.completeAll 就是把  LISTENERLIST    清空 ？ 然后prepare的时候再
重新加入 JCVideoPlayer

**Comment by lipangit** [comment]
1. JCUtils.switchNormalOrientation 这个方法已经被干掉了，
![image](https://cloud.githubusercontent.com/assets/2038071/20557201/85e43d8c-b1a5-11e6-8225-49581669b000.png)这里手动修改进入和tui'chu退出全屏的屏幕方向

2. JCVideoPlayerManager.LISTENERLIST 开始播放有一个，进入全屏有两个，退出全屏剩一个

**Comment by yuxinLi** [comment]
@lipangit 
Demo 首页 --> 嫂子真嘚瑟 
这个视频为什么 全屏  播放完成后 ， 没有退出全屏 并且自动重播 ？这个是用了 JCVideoPlayerStandard，
我的也是用 JCVideoPlayerStandard ， 但是播放完成会退出全屏，没看出啥区别 ， 求大神指点

**Comment by lipangit** [comment]
@yuxinLi  Main Activity 设置了 looping=true,  循环播放

**Comment by yuxinLi** [comment]
@lipangit 
 设置了 looping=true 就没走 onAutoCompletion() 和 onCompletion() 了，所以没有竖屏。

**Comment by yuxinLi** [comment]
![image](https://cloud.githubusercontent.com/assets/16236879/20595325/7be29566-b274-11e6-84f9-fa8708fabe69.png)
![image](https://cloud.githubusercontent.com/assets/16236879/20595364/9f6a7436-b274-11e6-8192-026c965357ef.png)
![image](https://cloud.githubusercontent.com/assets/16236879/20595401/b8c561ac-b274-11e6-92c1-536f65f6682c.png)


@lipangit 
我改了几个函数，好像可以了， 不过有点方，不知道这样改有没有其他问题？

**Comment by lipangit** [comment]
对

api很开放，用着没问题，那就没问题了

我们的库两个礼拜更新一次，你可以集成JCVideoPlayer来修改，改库的话以后升级版本可能麻烦一些
