### ISSUE TITLE
Https streaming

### ISSUE THREAD

**Issue by scroozer** [lipangit/JieCaoVideoPlayer#508]
Is it possible to stream with https protocol ? If so how can it be achieved ? I keep getting error telling to recompile ffmpeg with openSSL support can you please recompile the native libs and add ssl support ?

**Comment by lipangit** [comment]
The way is correct, recompile ijkplayer open openSSL config, I have never do that, I have no useful infomation for you.

Next version use exoplayer with many benefits.

**Comment by scroozer** [comment]
I have no experience in working with NDK and .so libs so cant get it done, does exoplayer support https ?

**Comment by lipangit** [comment]
yes

**Comment by scroozer** [comment]
I just tested out exoplayer, its loads really fast and has low cpu usage , do you know when you will update your player with exoplayer instead of ijkplayer ?

**Comment by lipangit** [comment]
next weekend

**Comment by scroozer** [comment]
Awesome , will wait then , thanks for your help

**Comment by lipangit** [comment]
@scroozer Are you live out of china? Can you play video in demo?

**Comment by scroozer** [comment]
Yep in europe , and I already implemented your player and it works fine for other videos but when the source has https protocol it doesnt accept it and returns protocol not found

**Comment by lipangit** [comment]
I mean can you play these urls in demo out of china

**Comment by scroozer** [comment]
All urls are working fini except https ones , I dont live in china

**Comment by Maragues** [comment]
That would be a great fix @lipangit, thanks for your hard work.

Let me know if you need some testing, I'm stuck in 3.6.3 due to this issue (which I already commented here https://github.com/lipangit/JieCaoVideoPlayer/issues/320) and I've ran into a bug which might be fixed in newer versions, but I can't upgrade until https streaming works.

**Comment by lipangit** [comment]
@Maragues exoplayer is better than ijkplayer, but code is complex, it is difficult for us to use. How do you think about this.

**Comment by scroozer** [comment]
I actually managed to implement exoplayer it was more easier to implement than ijkplayer,  but created a custom view from scratch since I needed https as soon as possible but you probably will get this done way better so when you release I will probably replace mine with yours

**Comment by Maragues** [comment]
@lipangit I'm an ignorant in video stuff, but ExoPlayer seems to be Google's preferred way, so it seems like a good idea to follow.

By the way, I'm trying to compile ijkplayer with open-ssl, I've managed to compile my own ijkplayer-java-release.aar and JieCaoVideoPlayer/app/ runs fine and plays https:// videos.

When I include the *jiecaovideoplayer-release.aar* in my project it compiles ok but I get a 

    java.lang.NoClassDefFoundError: Failed resolution of: Lfm/jiecao/jcvideoplayer_lib/JCMediaManager;

Any hint?

I'm working on this branch https://github.com/Maragues/JieCaoVideoPlayer/tree/ijkplayer-openssl

**Comment by Maragues** [comment]
Ok, I've managed to make it work by also including *ijkplayer-java-release.aar* in my project

**Comment by lipangit** [comment]
I will not study ijkplayer, I think exoplayer is in the trend, I will make it better.

**Comment by DnAGroup** [comment]
@scrdev could you share how you managed to run the player with https?

**Comment by scrdev** [comment]
@DnAGroup I am not sure if the dev did as he said and replaced ijkplayer with Google Exoplayer in his project, I actually reimplimented exoplayer and built my own videoplayer and I recommend you do the same there will be a moment when you would need features that jieciaovideoplayer doesnt have so its better to do it yourself. Read the exoplayer docs and I would recommend you use SimpleExoPlayer in the Exoplayer library

**Comment by DnAGroup** [comment]
@scrdev So you used the same library, but replaced ijkplayer with Exo, right?

**Comment by scrdev** [comment]
Nope I rebuilt a whole library since ijkplayer is a lot different than
exoplayer but exoplayer is much better. Just take a look at Exoplayers docs
it shouldnt be that hard

**Comment by DnAGroup** [comment]
@scrdev could you show me an example of your player?
