### ISSUE TITLE
ImageLoader change to Glide do not disply Thumb

### ISSUE THREAD

**Issue by E-Nomine** [lipangit/jiecaovideoplayer#51]
ImageLoader.getInstance().displayImage("http://p.qpic.cn/videoyun/0/2449_bfbbfa3cea8f11e5aac3db03cda99974_1/640", videoController2.ivThumb);

Glide.with(context).load("http://cos.myqcloud.com/1000264/qcloud_video_attachment/842646334/vod_cover/cover1458036374.jpg").into(videoController2.ivThumb);

**Comment by lipangit** [comment]
I can display thumb with glide.

1.add this:
  compile 'com.github.bumptech.glide:glide:3.5.2'
  compile 'com.android.support:support-v4:22.0.0'
2.
![fb0411ab-4f22-41c9-b31d-5a972820d686](https://cloud.githubusercontent.com/assets/2038071/14347753/4dbd71f4-fceb-11e5-996f-90652515a559.png)

Then I can see the image.

reference : http://blog.csdn.net/fancylovejava/article/details/44747759

I will add other image library in demo.

**Comment by lipangit** [comment]
See LoadImageActivity in demo.
