### ISSUE TITLE
请问在多布局的情况下正在播放的视频滑出去后停止播放？

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#510]
`if (convertView != null && convertView.getTag() != null) {
            boolean b = convertView.getTag() instanceof ViewHolderVideo;
            if (b)
                JCVideoPlayer.releaseAllVideos();
}`
以前接入的是3.6.3，用的是这种方式，现在变成4.8.3后这样做确实能停止，但是全屏播放会抛空指针

**Comment by lipangit** [comment]
是用最新的4.8.3吗，我们节操精选的app里也是这么用的，不会崩溃

崩溃的log发来看看
