### ISSUE TITLE
无网的时候 ， 缓冲的视图 会一直转。有没有设置缓冲时间的方法

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#511]
拖动进度条 ， 如果没有网 ， loadingProgressBar 会一直旋转 ，有没有一个设置时间段限制的方法，
过一段时间没有缓冲好就显示 error视图 ？

**Comment by lipangit** [comment]
会有超时吧，超时之后进入error视图，记得添加error视图的时候会超时会进入error的

你测试的结果几分钟都不会超时吗

**Comment by yuxinLi** [comment]
@lipangit 
没有额， 会一直转 ， demo 首页 ---> 嫂子真嘚瑟 也是这样子的
1. 如果没有网 ， 点击 startButton 会进入error视图
2. 有网 ， 点击 startButton 正常播放 --> 暂停播放 ,关掉网络 ---> 拖动进度条 
这时 loadingProgressBar就 会一直旋转

**Comment by lipangit** [comment]
知道了
