### ISSUE TITLE
JCUserActionStandard not called 

### ISSUE THREAD

**Issue by drdla49** [lipangit/JieCaoVideoPlayer#515]
Hi, I use vesrion 4.8.3 and follow your example.
I have this:
`JCVideoPlayer.setJcUserAction(new UserAction());`

And this:
`class UserAction implements JCUserActionStandard {

        @Override
        public void onEvent(int type, String url, int screen, Object... objects) {
        }
    }`

On event is called OK, but after while there is no onEvent call.
I need only ON_AUTO_COMPLETE, but this is never called.

Thank you for answer.

**Comment by lipangit** [comment]
bug on user event,next version will fix it

**Comment by lipangit** [comment]
Yes, this is a big bug, you are very careful, How do you think about it?

**Comment by drdla49** [comment]
Sorry but I don´t know what do you mean your last comment.

**Comment by lipangit** [comment]
I remove weakrefrence,now is strongrefrence.

**Comment by lipangit** [comment]
fix on 5.+
