### ISSUE TITLE
节操播放器打开下面网址为什么只有声音没有图像呢

### ISSUE THREAD

**Issue by FanYimin** [lipangit/JieCaoVideoPlayer#516]
http://advred.file.alimmdn.com/upload/2016/11/01/bac29987-eb45-48aa-97c6-22f345bba84e.mp4?auth_key=1480389396-0-0-d77041900cd28b1a48c7b87bc2b1599e

**Comment by lipangit** [comment]
这个地址在chrome中打开也没有图像，应该是MP4格式下图像编码的问题

**Comment by FanYimin** [comment]
对，应该是编码问题。但是我们公司的视频编辑不想给我改。这个视频在微信公众号上是可以播放的。
我试了github上大部分的播放器，基于ijkPlayer的都打不开。最后发现exoPlayer和easy video player可以打开。现在上面视频授权码已过期，都不能打开了

**Comment by lipangit** [comment]
你可以把视频拿过来自己格式化，然后发给运营

**Comment by mcd316** [comment]
http://zb.tarseen.com/Video/RedHeadAVI.mp4
这个视频我也不能播放，在浏览器上试过，有的可以有的不可以。求解答

**Comment by FanYimin** [comment]
@lipangit 求教格式化的方法，点右键没有发现格式化菜单啊 ？ :D

**Comment by lipangit** [comment]
我们只能适应ijkplayer，用能播放的格式

也可以通过配置重新编译ijkplayer能支持更多格式
