### ISSUE TITLE
全屏播放时，禁止根据重力感应切换屏幕方向

### ISSUE THREAD

**Issue by cydenghua** [lipangit/JieCaoVideoPlayer#519]
由于目前播放器没有识别视频的方向，在全屏播放时想旋转屏幕使得能在正确的方向看视频，但是此时重力感应把屏幕的方向也切换了， 如果可以禁止全屏时重力感应切换屏幕？

**Comment by cydenghua** [comment]
补充一下， 我看 节操精选 APP就可以做到全屏时不自动根据重力感应切换屏幕方向。

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/20671037/a44f7b3c-b5b6-11e6-9a4e-9ca880cbe36f.png)
这两个变量可以手动修改全屏之后和退出全屏的屏幕方向

新版节操精选在全屏的时候可以通过重力感应任意旋转屏幕

**Comment by Aeiric** [comment]
谢谢，已解决，主要是为了解决全屏时横屏播放暂停的问题

**Comment by cydenghua** [comment]
这样修改句一定要下载源码，然后把源码加入到工程才行，不能使用jar包引入的方式了

**Comment by lipangit** [comment]
@cydenghua 这是全局变量，在哪修改都行

**Comment by LeoYe168** [comment]
jcVideoPlayerStandard.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;       这样修改？修改后直接挂了

**Comment by cydenghua** [comment]
@lipangit 非常感谢，解决问题了。
就是在activity里面重新赋值：
JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_NOSENSOR;
