### ISSUE TITLE
Auto Play option in this library

### ISSUE THREAD

**Issue by shankarpilli** [lipangit/jiecaovideoplayer#52]
Hi, 

In the how can i add auto play.

JCVideoPlayer jCVideoPlayer = (JCVideoPlayer) findViewById(R.id.videocontroller);
        jCVideoPlayer.setUp("http://2449.vod.myqcloud.com/2449_43b6f696980311e59ed467f22794e792.f20.mp4", "嫂子别摸我");

thanks 
Shankar

**Comment by lipangit** [comment]
jCVideoPlayer.ivStart.performClick();
