### ISSUE TITLE
backPress 之后 ，Listener size 没变

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#520]
情景是这样：
先  PORTRAIT 播放 ，              size = 1；
然后 LANDSCAPE ，                size =2 ；
然后 REVERSE_LANDSCAPE ， size = 3;
然后 LANDSCAPE  ，               size = 4;
....

然后竖屏，需要退出播放器
                int i = 1; 
                if (videoPlayer.currentState == CURRENT_STATE_AUTO_COMPLETE){
                    i = 0; //  没遇过这种情况，一般都是 1
                }

                while (JCVideoPlayerManager.LISTENERLIST.size() > i){
                    Logger.e(" 退出一次 = ");
                    VideoPlayerView2.backPress(); // 退出全屏
                    Logger.e(" 退出一次后 size = "+ JCVideoPlayerManager.LISTENERLIST.size());
                }        

发现 退出一次后 ， size 没有变 ，这是偶现现象

**Comment by lipangit** [comment]
改库了吧，没改库应该不会出这个情况，

给操作这个list的地方打断点吧，看看哪出了问题

我之前调试过这种问题，很痛苦

**Comment by yuxinLi** [comment]
库倒是没改 ，不过 这些代码是写在一个 方向传感器里面的， 没用 系统的重力感应，核心代码如下
![image](https://cloud.githubusercontent.com/assets/16236879/20695308/e27fdf22-b625-11e6-8da3-1dcc069dc52e.png)
![image](https://cloud.githubusercontent.com/assets/16236879/20695316/f40fbee2-b625-11e6-9cc3-9df5071b7686.png)

**Comment by lipangit** [comment]
好的，有时间调试一下你的代码

复制代码吧要么我得手打
