### ISSUE TITLE
Fragment中 全屏后，转换成横屏  播放界面不见了，但播放还在继续

### ISSUE THREAD

**Issue by zaxcler** [lipangit/JieCaoVideoPlayer#524]
如图，我在fragment中进行播放，全屏后，转换成横屏  播放界面不见了，但播放还在继续

**Comment by lipangit** [comment]
没有图

改库了吗，如果改库的话调试起来很麻烦

**Comment by zaxcler** [comment]
没有改库哦，只是以library的形式导入

**Comment by zaxcler** [comment]
结构是这样的  activity中包含viewpager，viewpager的 fragment里面进行播放 @lipangit

**Comment by lipangit** [comment]
这个结构可以播放，参照demo 检查manifest的配置 和activity onPause等配置
