### ISSUE TITLE
Activity设置为横屏，并且整个Activity在xml属性设置为全屏，重新setUp之后会出现状态栏

### ISSUE THREAD

**Issue by xiangzhenwang** [lipangit/JieCaoVideoPlayer#525]
Activity设置为横屏，并且整个Activity在xml属性设置为全屏，重新setUp之后会出现状态栏，这个该怎么解决！

**Comment by lipangit** [comment]
JCVideoPayer.NORMAL_ORIENTATION  手动控制普通时候的屏幕方向

**Comment by xiangzhenwang** [comment]
我在JCVideoPayer这个类修改为public static int NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;，横屏没问题，因为我在视频的右上角放了一个imageview，点击imageviewx需要切换一下视频源重新播放，但是此时会出现状态栏

**Comment by lipangit** [comment]
断点一下showSupportActionBar和操作toolbar的函数吧

以前没考虑过这种情况，是在不行改库吧
