### ISSUE TITLE
h265 mp4 不支持吗?

### ISSUE THREAD

**Issue by weizai** [lipangit/JieCaoVideoPlayer#526]
用jiecaoVideoPlayer播放时有音频无视频, 系统自带播放器播放没问题. ijkplayer应该是支持h265的吧?测试视频地址http://210.51.212.12:8081/video1/qwwz.mp4

**Comment by lipangit** [comment]
这个地址用chrome播放也没图像

**Comment by weizai** [comment]
用android系统视频播放器可以播放， ijkplayer编译ffmpeg时好像需要添加某些参数才可以支持h265

**Comment by lipangit** [comment]
试一下新版5.+
