### ISSUE TITLE
传URL进去只有声音没有图像

### ISSUE THREAD

**Issue by mcd316** [lipangit/JieCaoVideoPlayer#527]
1.http://zb.tarseen.com/Video/RedHeadAVI.mp4
这个视频我也不能播放，在浏览器上试过，有的可以有的不可以。求解答
2先全屏后横屏会报错

**Comment by lipangit** [comment]
1.mp4格式中ijkplayer不支持当前的图像编码，所以没图像

2.报错的log是什么

**Comment by lipangit** [comment]
你这url有问题，检查一下服务器吧，延迟很大很卡
