### ISSUE TITLE
Can't stop player properly 

### ISSUE THREAD

**Issue by slumcattt** [lipangit/JieCaoVideoPlayer#528]
Hi, 
I have a list view with some video URL .
at 2nd activity I'm using your player. but I'm getting force close when I'm pressing back and the video is not properly stopping. 

I have gone through the process mentioned in androidarsenal, can you help? 💕❤please :)

**Comment by lipangit** [comment]
See demo, onPause(){JCVideoPlayer.releaseAllVideos();}

Check code between your project and demo.

**Comment by slumcattt** [comment]
bro I checked the demo, wasn't working as well. below is my code. please if you have sometime , can you tell me the issue ?

public class player extends Activity {
	JCVideoPlayerStandard jcVideoPlayerStandard ;
	@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.playerx);
			
		
   }
   
	public void onStart()
    {
		String i = getIntent().getExtras().getString(("key"));
		JCVideoPlayerStandard jcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.custom_videoplayer_standard);
		jcVideoPlayerStandard.setUp(i
									, JCVideoPlayerStandard.SCREEN_LAYOUT_LIST, "iptv");
		
        super.onStart();

    }
	@Override
	public void onBackPressed() {
		if (JCVideoPlayer.backPress()) {
			return;
		}
		super.onBackPressed();
	}
	@Override
	protected void onPause() {
		super.onPause();
		JCVideoPlayer.releaseAllVideos();
	}

	
}

**Comment by slumcattt** [comment]
sorry I fixed. I had to extend action bar not activity . 🐸 nice library dudd
