### ISSUE TITLE
全屏之后 我自定义的listener 都为空了

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#529]
![1a188d7e-ffb2-457c-91c5-1659c8e22c6e](https://cloud.githubusercontent.com/assets/13553319/20779924/c04a3c48-b7b2-11e6-896c-5b7e926393fb.png)
![default](https://cloud.githubusercontent.com/assets/13553319/20779931/c671ec42-b7b2-11e6-9396-ac9053aa2fb8.png)
我现在只能用eventbus来控制ui层次的变化了。

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard复写相关函数取得相关事件的回调，不需要新建listener.

**Comment by junchenChow** [comment]
主要是需要有一个action的call back 我需要立刻做一些交互的逻辑

**Comment by lipangit** [comment]
我的建议是在使用CourseVideoView的时候也是readme中的4个步骤，其他操作都在CourseVideoView中完成，你这样写当然也没问题。
