### ISSUE TITLE
How to use Fresco set thumb.

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#53]
In LoadImageActivity show us ImageLoader Glide Picasso Volley to load thumb, But Fresco should use SimpleDraweeView , I can not include that class in library .

**Comment by baoziguo** [comment]
宝宝每天看你更新了支持多格式的视频不，结果你整了加载图片的，宝宝心里苦啊~！你那个videoController.ivThumb就是个imageview啊，一般看下都会了吧。

话说，我有几个意见哎，视频缓冲，觉得该给个回调，这样可以显示加载进度，类似于vitamio的，如下：
/** 是否需要自动恢复播放，用于自动暂停，恢复播放 */
    private boolean needResume;
 
    @Override
    public boolean onInfo(MediaPlayer arg0, int arg1, int arg2) {
        switch (arg1) {
        case MediaPlayer.MEDIA_INFO_BUFFERING_START:
            //开始缓存，暂停播放
            if (isPlaying()) {
                stopPlayer();
                needResume = true;
            }
            mLoadingView.setVisibility(View.VISIBLE);
            break;
        case MediaPlayer.MEDIA_INFO_BUFFERING_END:
            //缓存完成，继续播放
            if (needResume)
                startPlayer();
            mLoadingView.setVisibility(View.GONE);
            break;
        case MediaPlayer.MEDIA_INFO_DOWNLOAD_RATE_CHANGED:
            //显示 下载速度
            Logger.e("download rate:" + arg2);
            break;
        }
        return true;
    }
在最后的那里可以拿到下载进度，这样我可以自定义一个dialog来显示。

那个视频多格式支持的完成了圈我下吧~

**Comment by baoziguo** [comment]
最后加油啦，很喜欢这个库~！

**Comment by lipangit** [comment]
多视频格式的问题，https://github.com/lipangit/TestExoPlayer。这个库测试了ExoPlayer全屏的代码，结果是全屏的过程中声音是连续的，但是图像会有几秒的延迟，所以多视频格式的计划就推到了完全自定义UI之后了，你需要播放什么视频格式？

**Comment by baoziguo** [comment]
嗯。这个我看了下。我需要播放B站视频源，通过B站的H5拿到他们的视频源链，比如这个http://www.bilibili.com/video/av3473986/，通过获取H5返回数据，可以拿到视频源链：http://cn-sddz4-cu.acgvideo.com/vg3/c/b1/5518924.mp4?expires=1453364400&ssig=9b0tHHpJkYnQeGa5UC_M9w&oi=1875527658&internal=1&rate=0，按理来说是MP4格式的，但是播放不了，用vitamio是可以的。Google原生的medio，播放的url是不是必须link的后缀是mp4？

**Comment by lipangit** [comment]
看你的代码里需要 开始加载，加载完成和播放进度的回调，库里已经分别设置3个状态UI了，比如你想换个地方显示播放进度吗？你是想自定义一个dialog来显示加载状态吗？
那么请期待正在开发的功能：完全自定义UI，这个功能的目的是我们不需要写任何操作视频的代码，比如开始、暂停、修改进度、全屏等功能类的代码，因为库里已经都帮我们做了，并且能自定义UI，比如修改功能按钮的位置，自定义添加分享收藏等功能按钮

**Comment by baoziguo** [comment]
嗯。这样用户体验相对好些，现在的视频播放器也都是这样，vitamio我就弄了，网速不好，或者服务器带宽不够，就缓冲，同时显示加载进度200kb/s 50%这样的。你说的这些相当nice，可以说让我们不能更懒了。

**Comment by lipangit** [comment]
那个链接的mp4文件能拿到吗，浏览器直接访问403没权限

**Comment by baoziguo** [comment]
http://cn-gdgz4-cmcc.acgvideo.com/vg7/d/89/5518924.mp4?expires=1460317800&ssig=WSiYOtcbB5DWUiGMPC-PRw&oi=2051492735&internal=1&rate=0

可以的，就这个，你点击下就哦了

**Comment by lipangit** [comment]
刚试了一下，确实播放不了，但是视频好像确实是mp4格式。。

**Comment by baoziguo** [comment]
是的，link丢迅雷下载下来的话，也是MP4，所以我就估摸着是不是Google原生的medio类里是否直接做的判断，endwithmp4类似这样的，link后缀必须为格式名称，用vitamio这些第三方是可以的

**Comment by lipangit** [comment]
你给的地址用迅雷和迅雷的离线下载都下载不了，但是能用浏览器下载，感觉这个地址有猫腻。

**Comment by baoziguo** [comment]
噫、、、没试过，上次我丢的浏览器么，我也不记得了，反正是下过，我试试迅雷

**Comment by lipangit** [comment]
高速通道能下载，刚才卡住有几分钟

**Comment by baoziguo** [comment]
我刚刚试了超级旋风的，可以直接下载，没点问题，5518924.mp4。。。迅雷本本是没装，解压种子什么的，迅雷经常翻车，超级旋风才是王道→_→

**Comment by lipangit** [comment]
我去给google提个bug去^_^，就问为啥不能播你那个地址

**Comment by baoziguo** [comment]
2333Google工程师一砖头就拍过来了，所以这个才是我希望你早点弄下多格式视频的原因，我自己再撸APP，用的bmob，B站不让开发者申请APPkey了，所以就H5抓的视频源链

**Comment by lipangit** [comment]
顶住，做完UI就全力研究这个，明天问问我司做后端的，这个地址有啥猫腻

**Comment by baoziguo** [comment]
可以，我就喜欢你这样的，搞基嘛，微信QQ什么的来一发

**Comment by lipangit** [comment]
直男有木有，老直了，微信：lipanhelloworld  github用的qq邮箱

**Comment by carmelo-ruota** [comment]
English please!! :(

**Comment by lipangit** [comment]
He said he can not play that mp4 with android.media.MediaPlayer, but finally we foud that server 403 Forbidden , because that address is crawled from other server, he should pay attention on the timing .

**Comment by baoziguo** [comment]
I didn't expectto see you up.

**Comment by lipangit** [comment]
?

**Comment by imliujun** [comment]
给个建议，将封面图这个View写成外部set进来，然后在库内再将封面图通过addView 添加到layout 。
这样开发者可以设置ImageView也可以设置SimpleDraweeView。

**Comment by lipangit** [comment]
@imliujun 哥们也可以试试先remove ImageView，然后add一个SimpleDraweeView进去，如果把缩略图从库里删除是下策。

如果你能研究一下提交代码可就太好了

**Comment by lipangit** [comment]
see demo LoadImageActivity.
