### ISSUE TITLE
弹wifi框的逻辑有误

### ISSUE THREAD

**Issue by yuxinLi** [lipangit/JieCaoVideoPlayer#530]
![image](https://cloud.githubusercontent.com/assets/16236879/20780315/f4531be8-b7b4-11e6-9f2a-ed9adaf68da3.png)

没有网的时候也进来了

**Comment by lipangit** [comment]
是吗，isWifiConnected函数失效了吗

**Comment by yuxinLi** [comment]
isWifiConnected 判断是否是链接的wifi ， 没有网的时候也 返回 false，
然后就弹框提示：您当前正在使用移动网络，继续播放将消耗流量，

没有网络的时候应该不弹这个提示框了

**Comment by lipangit** [comment]
如果是file，有没有网络都不应该弹这个提示

**Comment by yuxinLi** [comment]
有修复计划么。。

**Comment by lipangit** [comment]
下个版本修复

**Comment by DevelopmentMan** [comment]
我也遇到这个问题：sd卡视频播放也弹出提示框，有解决方法吗？

**Comment by lipangit** [comment]
下版本修复

**Comment by caozenghui** [comment]
网络从wifi变为移动流量时没有弹出提示框

**Comment by lipangit** [comment]
这版本看看

**Comment by lipangit** [comment]
路径以'/' 开头不会有提示框了 fix in 72cb36c

目前感觉播放中wifi变为流量，不需要随时提示提示框，开始播放提示一次就好。
