### ISSUE TITLE
4.8.3 魅族note3，当点击全屏，一开始是竖着的全屏，然后当我想横着看的时候，旋转手机，就会退出APP

### ISSUE THREAD

**Issue by zouwansheng** [lipangit/JieCaoVideoPlayer#531]
概率大概是40%。这是什么原因。

**Comment by lipangit** [comment]
log是什么

**Comment by zouwansheng** [comment]
Surface: dequeueBuffer failed (No such device)
IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
BufferQueueProducer: [unnamed-16211-0](this:0x7f8865c000,id:0,api:2,p:16211,c:-1) query: BufferQueue has been abandoned
MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport

**Comment by DavyLin** [comment]
@lipangit 我这边也出现这个问题了，附上日志：
E/BufferQueueProducer: [unnamed-32012-4] queueBuffer: BufferQueue has been abandoned
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/Surface: queueBuffer (handle=0x99917790) failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_unlockAndPost: failed -19
E/BufferQueueProducer: [unnamed-32012-4] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-4] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-4] dequeueBuffer: BufferQueue has been abandoned
E/Surface: dequeueBuffer failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
E/BufferQueueProducer: [unnamed-32012-5] queueBuffer: BufferQueue has been abandoned
E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
E/Surface: queueBuffer (handle=0x8638cb50) failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_unlockAndPost: failed -19
E/BufferQueueProducer: [unnamed-32012-5] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-5] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-5] dequeueBuffer: BufferQueue has been abandoned
E/Surface: dequeueBuffer failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
E/BufferQueueProducer: [unnamed-32012-5] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-5] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-32012-5] dequeueBuffer: BufferQueue has been abandoned
E/Surface: dequeueBuffer failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x92263040)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x92263080)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x922630c0)

这个问题目前解决了吗？

**Comment by lipangit** [comment]
manifest中的横竖屏只会指定进入全屏之前activity的方向，全屏时候会有代码强制修改。

这个改库里的代码了吗，还是demo就是这样

**Comment by DavyLin** [comment]
不好意思，这个是我这边的问题，在全屏播放的activity中没有指定  android:configChanges="screenSize|orientation"  ，目前可以了，谢谢：）

**Comment by zouwansheng** [comment]
我的是demo就是这样。没有改。而且他说的那个问题，我一直是加了的android:configChanges="screenSize|orientation"。这句一直加了
