### ISSUE TITLE
recycleView中item视频，进入全屏后旋转手机闪退

### ISSUE THREAD

**Issue by s949492225** [lipangit/JieCaoVideoPlayer#532]
recycleView在fragment中，视频的view在holder中

这是activity的清单配置
        <activity
            android:name=".ui.MainActivity"
            android:launchMode="singleTask"
            android:theme="@style/AppTheme"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"/>
点击item进入全屏，默认进入的是竖屏，此时旋转手机，4.4，5.0，6.0，7.0版本系统的手机均出现闪退，
下面是log
![image](https://cloud.githubusercontent.com/assets/7496283/20789579/e99d23e8-b7ef-11e6-9b99-333c030a70fe.png)

**Comment by s949492225** [comment]
闪退概率必现

**Comment by s949492225** [comment]
在上传一个上面的log
![image](https://cloud.githubusercontent.com/assets/7496283/20789836/e3d73790-b7f0-11e6-9bb3-0f58ad7c3a15.png)

**Comment by lipangit** [comment]
断点旋转屏幕的时候
是否调用releaseAllVideos()函数
是否调用goToOtherListener()函数

**Comment by s949492225** [comment]
找到原因了，旋转时recycleView中onChildViewDetachedFromWindow的监听会被调用，导致releaseAllVideos()，所以导致空指针。

建议Demo中recycleView中这样写可以避免这个问题：
![image](https://cloud.githubusercontent.com/assets/7496283/20823090/0c4f10f8-b88c-11e6-8468-e14c1cbacb8c.png)

**Comment by lipangit** [comment]
像demo一样不加这个listener不可以吗

**Comment by s949492225** [comment]
这个是当holder滑出当前可见范围时停止播放的，去掉会出问题，可以参考今日头条

**Comment by lipangit** [comment]
这个是不是只有recycleview的函数ListView用不了

**Comment by s949492225** [comment]
是的,listView不支持，得用别的方式来判断，也大同小异吧
