### ISSUE TITLE
ProgressTimerTask leaks JCVideoPlayer

### ISSUE THREAD

**Issue by Maragues** [lipangit/JieCaoVideoPlayer#533]
While integrating version 4.8.3 a memory leaked appeared

    ProgressTimerTask leaks JCVideoPlayer

Looking at the code, ProgressTimerTask is an anonymous class in JCVideoPlayer, which means that it holds a strong reference to it. Furthermore, it's using a handler to post messages, which means that by the time the message is to be processed, JCVideoPlayer may have disappeared.

**Comment by lipangit** [comment]
cool
