### ISSUE TITLE
JCMediaManager.textureView leaks context

### ISSUE THREAD

**Issue by Maragues** [lipangit/JieCaoVideoPlayer#536]
*JCMediaManager.textureView* is a static variable instantiated from *JCVideoPlayer*. It holds a strong reference to a *Context* and is not destroyed unless you invoke *addTextureView()*.

I'm not familiar with *TextureView*, but the easiest fix I can think of without rewriting the code is to move *textureView* to a *WeakReference<TextureView>*. This'd mean that we should check if it's null each time we were to use it. You can see an example of that in https://github.com/lipangit/JieCaoVideoPlayer/pull/535. I don't know if that would have consequences on the logic, I don't think so, but it should be tested.

As I've mentioned in previous issues and PRs, the whole project lacks encapsulation and proper visibility modifiers, which makes it a software architecture nightmare. Since this is really hard to fix, my recommendation would be to try to improve on future developments.

**Comment by lipangit** [comment]
This is import for quality of code but not in hurry
