### ISSUE TITLE
全屏的逻辑快要调吐了

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#537]
![1](https://cloud.githubusercontent.com/assets/13553319/20827586/fa63d4f6-b8ad-11e6-8962-44b75f09bcfb.png)
我在activity onPause的时候调用这些代码 在没有全屏的情况下一切都是正常的。
![2](https://cloud.githubusercontent.com/assets/13553319/20827619/1fc0fd28-b8ae-11e6-98aa-a33fa23f8879.png)
一到了全屏 视频可以被停止掉 但是startButton的状态却怎么也调不对 全屏状态调用的一样的代码 去暂停但是currentStatu 回来的时候却是 ＝2 是播放状态。没有全屏的时候暂停了就是 ＝5 正常的暂停状态。也没找到源码哪里又把currentStatu 改到2去了。

**Comment by RealLee91** [comment]
你可以自定义一个布尔值，来保存是否在播放。

**Comment by junchenChow** [comment]
@RealLee91 这个是最简单的 没有用 我现在碰到的是全屏状态下  强行改starBtn的状态都改不了 没一点反应 我都不去判断了  我直接调用代码 都没一点反应

**Comment by lipangit** [comment]
UI 统一在setUiWitStateAndScreen这个函数里，case不同的播放状态修改ui

**Comment by junchenChow** [comment]
setUiWitStateAndScreen 里面的currentState在全屏下面有问题

**Comment by lipangit** [comment]
我吐过好几遍了
