### ISSUE TITLE
Fullscreen and releaseAllVideos

### ISSUE THREAD

**Issue by Maragues** [lipangit/JieCaoVideoPlayer#539]
Hi, I have a video in a RecyclerView. When a click on the fullscreen button it doesn't work because my activity goes to the *onPause* state and *releaseAllVideos* is invoked.

I've tested in JieCaoVideoPlayer's MainActivity and it never goes to *onPause*, so I might be doing something wrong.

Any hint?

**Comment by lipangit** [comment]
Overrite onBackPress() function,Same as demo MainActivity

**Comment by Maragues** [comment]
@lipangit thanks
