### ISSUE TITLE
横屏下点击home键,onpause()下调用mediaPause()暂停按钮的状态不能切换

### ISSUE THREAD

**Issue by buchuqi** [lipangit/JieCaoVideoPlayer#544]
横屏下点击home键,onpause()下调用mediaPause()暂停按钮的状态不能切换，在回到程序中来，一直是处于播放的一个状态，但是竖屏下同样的操作，却是正常的,这是在横屏时做了哪些特别的处理吗

**Comment by lipangit** [comment]
没有特殊，都是在activity的onPause的时候调用releaseAllVideos()

**Comment by junchenChow** [comment]
这位哥 和我的情况一样  虽然我也很想直接调用releaseAllVideos() 但是产品不允许  T _ T

**Comment by lipangit** [comment]
咱们节操视频播放器和今日头条UI的相似度是98%，操作的相似度是100%，如果产品经理没有头条产品经理的水平，没有像头条那样长时间在视频上的研究就不要乱加乱改了。
