### ISSUE TITLE
有的视频只有声音,没有图像

### ISSUE THREAD

**Issue by oake33** [lipangit/JieCaoVideoPlayer#545]
ios手机自带播放器可以播放,普通的组件videoview也可以播放
http://7ktwa0.com1.z0.glb.clouddn.com/master/20161128171320399307.mp4

**Comment by lipangit** [comment]
最新版本5.0+能播放，但现在是preview版本，可以参考

**Comment by oake33** [comment]
非常感谢,最新的版本什么时候出呢

**Comment by oake33** [comment]
看到最新的了  谢谢分享

**Comment by oake33** [comment]
我用了最新版本preview的jc了,还是同样的问题
http://7ktwa0.com1.z0.glb.clouddn.com/master/20161128171320399307.mp4
有声音,没有视频,讲道理应该比videoview要厉害,可是videoview能播放,jc播放不出画面

**Comment by lipangit** [comment]
确实播放不了，会持续关注这个问题，我去exoplayer上提个issue

**Comment by oake33** [comment]
好的 谢谢 
我也试试exoplayer
