### ISSUE TITLE
视频不居中

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#546]
![a3363d6110e19b375125a1a1fdec39e5](https://cloud.githubusercontent.com/assets/22672329/20914898/8eb10734-bbbd-11e6-9bdf-03d810dd1648.jpg)
如图，视频不居中，右边有一段黑边

**Comment by lipangit** [comment]
是5.0_preivew 版本吗

**Comment by PiPiCaptain** [comment]
@lipangit 4.8.3

**Comment by lipangit** [comment]
很少有人反映不居中的问题，你断点一下onSize函数和Textureview.requestLayout()是否起作用

**Comment by PiPiCaptain** [comment]
@lipangit 好的，我试试，然后给你个反馈
