### ISSUE TITLE
我的视频来源是16:9 但是视频显示是4:3的 这个要怎么设置

### ISSUE THREAD

**Issue by zph666** [lipangit/JieCaoVideoPlayer#548]

**Comment by lipangit** [comment]
你想JCVideoPlayerStandard的容器宽度是固定的，修改高度是16：9对吧，复写init()函数，手动设置容器的高度吧

**Comment by zph666** [comment]
不能提供一个方法动态改变视频的显示模式吗？更具需求 设置视频显示 16：9 、4：3 或者 铺满整个窗口

**Comment by lipangit** [comment]
以前有朋友做过这个功能，好像没做完，也没下文了，你可以尝试做一下

接口是setWidthAndHeight(16, 9);初始化控件的时候会设置比例

**Comment by zph666** [comment]
多谢 帮助，  找到了其他的解决办法。  修改了视频源的参数， 让视频自动适配，我们就不用再去管它了
