### ISSUE TITLE
全屏状态下，竖屏切横屏崩溃

### ISSUE THREAD

**Issue by walkerSun** [lipangit/JieCaoVideoPlayer#549]
进入全屏模式，默认是竖屏，手机横放切换横屏时，崩溃

**Comment by lipangit** [comment]
log

注意参照demo的AndroidManifest

**Comment by dfm899** [comment]
@lipangit 我这边也遇到这个问题
AndroidManifest 里面已经有了这两个设置
 android:configChanges="orientation"
            android:screenOrientation="portrait"
问题一样

**Comment by lipangit** [comment]
log是什么，改库里的内容了吗

**Comment by LaiZN** [comment]
I/JieCaoVideoPlayer: onSurfaceTextureUpdated [943976986] textureSizeChanged=false
I/JieCaoVideoPlayer: onSurfaceTextureUpdated [943976986] textureSizeChanged=false
I/JieCaoVideoPlayer: onSurfaceTextureUpdated [943976986] textureSizeChanged=false
I/JieCaoVideoPlayer: onCompletion  [943976986] 
E/BufferQueueProducer: [unnamed-4264-1] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-4264-1] query: BufferQueue has been abandoned
E/BufferQueueProducer: [unnamed-4264-1] dequeueBuffer: BufferQueue has been abandoned
E/Surface: dequeueBuffer failed (No such device)
E/IJKMEDIA: SDL_Android_NativeWindow_display_l: ANativeWindow_lock: failed -19
I/JieCaoVideoPlayer: onCompletion  [733014343] 
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4614]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4616]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4615]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4638]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4637]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4658]
E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb4b82bc0)
E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb4b82c00)
E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xb4b82c40)
I/IJKMEDIA: av_version_info: ff3.2--ijk0.7.2-20161107--001

**Comment by LaiZN** [comment]
抱歉  我是AndroidManifest没有设置好
