### ISSUE TITLE
直接使用全屏功能，在视频没有加载出来的时候，退出页面，报错

### ISSUE THREAD

**Issue by yongchao1210** [lipangit/jiecaovideoplayer#55]
直接使用全屏功能，在视频没有加载出来的时候，退出页面，有时会会出现报错直接退出应用。。

 java.lang.IllegalArgumentException: The surface has been released                                                                             at android.media.MediaPlayer._setVideoSurface(Native Method)                                                                               at android.media.MediaPlayer.setDisplay(MediaPlayer.java:669)                                                                               at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.surfaceCreated(JCVideoPlayer.java:661)                                                                               at android.view.SurfaceView.updateWindow(SurfaceView.java:543) #

**Comment by lipangit** [comment]
这个确实是个问题，但感觉有点矛盾，在surfacecreated的时候却说surface has been released。

记得全屏onPause的时候就会releaseAllVideos，解决这个问题你有啥想法吗

**Comment by yongchao1210** [comment]
我也是今天刚刚看到运行出来，还没有来得及研究解决办法。。你们考虑怎么解决呢

**Comment by lipangit** [comment]
在develop分支解决了

**Comment by yongchao1210** [comment]
那新版本什么时候上传呢
