### ISSUE TITLE
在未完全加载完成时，拖动进度条到某一位置，视频不再继续加载！只有完全加载完拖动才有效

### ISSUE THREAD

**Issue by zhang8897** [lipangit/JieCaoVideoPlayer#552]
在未完全加载完成时，拖动进度条到某一位置，视频不再继续加载！只有完全加载完拖动才有效；视频一开始播放时，拖动进度条会导致视频停止加载，把进度条调回原来位置也不会播放，直接停止加载了，求解决办法

**Comment by lipangit** [comment]
不知道怎么解决，估计MediaPlayer正在loading的时候不接受新的seek请求，如果你有什么好办法可以分享出来

**Comment by zhang8897** [comment]
我切换了网络，发现这和网络环境有关，网好的情况下不会出现这问题，确实是loading不能seek到新位置
