### ISSUE TITLE
播放这个视频链接时会崩溃

### ISSUE THREAD

**Issue by walkerSun** [lipangit/JieCaoVideoPlayer#553]
http://baoliao-medias.nobaoliao.com/medias/baoliao/161208010647004.mp4

上面这个链接在iOS端可以正常播放，JCVideo播放会程序崩溃

**Comment by walkerSun** [comment]
12-09 15:22:38.764 6481-6481/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onClick start [1009479259] 
12-09 15:22:38.768 6481-6481/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: prepareVideo [1009479259] 
12-09 15:22:38.768 6481-6481/fm.jiecao.jiecaovideoplayer D/JieCaoVideoPlayer: addTextureView [1009479259] 
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_release
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ffpipeline_set_surface()
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_dec_ref(): ref=0
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_shutdown_l()
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_shutdown_l()=void
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_native_setup
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: av_version_info: ff3.1--ijk0.6.0--20160715--001
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ffpipeline_create_from_android()
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque(0x1004c6)
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_inject_opaque()=void
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer V/IJKMEDIA: setDataSource: path http://baoliao-medias.nobaoliao.com/medias/baoliao/161208010647004.mp4
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://baoliao-medias.nobaoliao.com/medias/baoliao/161208010647004.mp4")
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_data_source(url="http://baoliao-medias.nobaoliao.com/medias/baoliao/161208010647004.mp4")=0
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-09 15:22:38.778 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_setLoopCount
12-09 15:22:38.779 6481-6514/fm.jiecao.jiecaovideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-09 15:22:38.779 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_prepareAsync
12-09 15:22:38.779 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_prepare_async()
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: ===== versions =====
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: FFmpeg       : ff3.1--ijk0.6.0--20160715--001
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: libavutil    : 55.27.100
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: libavcodec   : 57.48.101
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: libavformat  : 57.40.101
12-09 15:22:38.780 6481-6643/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_RunThread: [6643] ff_msg_loop
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: libswscale   : 4.1.100
12-09 15:22:38.780 6481-6643/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: message_loop
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: libswresample: 2.1.100
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: ===== options =====
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: player-opts : loop                         = 0
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: format-opts : ijkinject-opaque             = 1049798
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: format-opts : ijkapplication               = 548292050656
12-09 15:22:38.780 6481-6514/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: ===================
12-09 15:22:38.781 6481-6643/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: FFP_MSG_FLUSH:
12-09 15:22:38.782 6481-6644/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_RunThread: [6644] ff_vout
12-09 15:22:38.782 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_prepare_async()=0
12-09 15:22:38.782 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: SDL_RunThread: [6645] ff_read
12-09 15:22:38.782 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_setOptionLong
12-09 15:22:38.804 6481-6481/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1009479259] 
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer I/JieCaoVideoPlayer: set surface
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f9b1c85d4)
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ffpipeline_set_surface()
12-09 15:22:38.805 6481-6514/fm.jiecao.jiecaovideoplayer D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7f9b1c85d4)=void
12-09 15:22:38.909 6481-6645/fm.jiecao.jiecaovideoplayer E/IJKMEDIA: Option ijkinject-opaque not found.
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: max_frame_duration: 10.000
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://baoliao-medias.nobaoliao.com/medias/baoliao/161208010647004.mp4':
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:   Metadata:
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     major_brand     : 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: isom
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     minor_version   : 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 512
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     compatible_brands: 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: isomiso2mp41
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     creation_time   : 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 2009-06-01 18:38:15
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:   Duration: 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 00:00:17.21
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , start: 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 0.000000
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , bitrate: 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 206 kb/s
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Stream #0:0
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: (und)
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: : Video: mpeg4 (mp4v / 0x7634706D), none, 320x192, 204 kb/s
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: , 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 24 fps, 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 24 tbr, 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 24 tbn, 
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 24 tbc
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:  (default)
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:     Metadata:
12-09 15:22:38.979 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:       creation_time   : 
12-09 15:22:38.980 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: 2009-06-01 18:38:15
12-09 15:22:38.980 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA:       handler_name    : 
12-09 15:22:38.980 6481-6645/fm.jiecao.jiecaovideoplayer I/IJKMEDIA: VideoHandler
12-09 15:22:38.980 6481-6645/fm.jiecao.jiecaovideoplayer W/IJKMEDIA: No codec could be found with id 13
12-09 15:22:38.980 6481-6645/fm.jiecao.jiecaovideoplayer A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffffffc05f98 in tid 6645 (Thread-5057)

**Comment by lipangit** [comment]
放到新release的5.0试试

**Comment by walkerSun** [comment]
4.8.3版本程序不崩溃，但是视频加载失败，刚刚试了下

**Comment by walkerSun** [comment]
5.0可以正常播放

**Comment by bravekingzhang** [comment]
这个崩溃是libc.so中出现一个段错误引起的 ，那么新的release 加入了一些什么功能，是否只更新了 so .. @lipangit
