### ISSUE TITLE
3.5版本使用没问题，最新的4.8.3版本播放失败

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [lipangit/JieCaoVideoPlayer#558]
点击播放时，打印出如下Log，3.5版本使用没问题，最新的4.8.3版本播放失败

`12-13 12:49:12.072 24831-24831/kjv.bible.app I/JieCaoVideoPlayer: onClick start [1000548036] 
12-13 12:49:12.072 24831-24831/kjv.bible.app D/JieCaoVideoPlayer: prepareVideo [1000548036] 
12-13 12:49:12.072 24831-24831/kjv.bible.app D/JieCaoVideoPlayer: addTextureView [1000548036] 
12-13 12:49:12.092 24831-24831/kjv.bible.app I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1000548036] 
12-13 12:49:12.092 24831-25905/kjv.bible.app I/JieCaoVideoPlayer: set surface
12-13 12:49:12.092 24831-24831/kjv.bible.app E/JieCaoVideoPlayer: onError -10000 - 0 [1000548036] `

**Comment by lipangit** [comment]
能复现吗，每次都报错吗，4.*用的ijkplayer，3.*用的系统的MediaPlayer，请关注5.*用exoplayer播放

**Comment by ZhaoKaiQiang** [comment]
是的，每次都失败，换成4.6.x版本以后直接Crash，提示Can't find class，因为5.x版本还不稳定，所以暂时不升级了，我们播放的是youtube的视频，有可能ijkplayer不支持吧

**Comment by lipangit** [comment]
5.x用的exoplayer应该支持youtube视频
