### ISSUE TITLE
Does it support stream video (m3u8,..)

### ISSUE THREAD

**Issue by dungnguyendotme** [lipangit/JieCaoVideoPlayer#56]
As the title, please let me know if it support stream video.
Thanks you so much

**Comment by lipangit** [comment]
I have think about other formate , #40 #42 , and we think exoplayer is suit for us, how do think about that?

Now the main work is custom ui, that purpose is user will not write code about video , and user also can custom ui ,user also can add other feature .

**Comment by lipangit** [comment]
A friend online told me , android.media.MeidaPlayer support live stream m3u8 and also support RTSP , you can find here https://developer.android.com/guide/appendix/media-formats.html .

Thank you @axeon

**Comment by lipangit** [comment]
Few days later I will put some example in demo .

**Comment by dungnguyendotme** [comment]
Thanks so much. Hope to see that

**Comment by UC10D** [comment]
use vitamio or ijkplayer replace sys mediaplayer
