### ISSUE TITLE
【注意】以下机型会报couldn't find "libijkffmpeg.so"这个错误

### ISSUE THREAD

**Issue by SunshineExit** [lipangit/JieCaoVideoPlayer#561]
最近发现有的CPU架构是arm64-v8a的手机，Android5.1（不知道系统版本是否有影响），会报找不到这个.so文件错误。初步统计，已有如下机型报错，请尽快修复。
* 金立 M3S
* OPPO R9KM
* OPPO R9TM
* OPPO R9M
* OPPO R9 PLUSM A
* OPPO A37M
* 魅族 M688C
* 魅族 MX5
* 魅族 M1 NOTE
* 魅族 M2 NOTE
希望开发者尽快注意这个问题

**Comment by YuJunKui1995** [comment]
参考#353

**Comment by SunshineExit** [comment]
@YuJunKui1995 不好意思啊，我刚入行没有多久。请问针对我的问题，我只需要在build.gradle里添加
```java
ndk {  
        abiFilters  "armeabi-v8a"
    }  
```
这样吗？
还是我需要添加更多的ndk支持？
还是我将源码中的armeabi-v8a文件下的libijkffmpeg.so文件，复制到本地项目jni文件的armeabi-v8a文件下呢？
希望你有时间能够回复我，谢谢

**Comment by lipangit** [comment]
@SunshineExit 用新版5.+吧朋友，exoplayer没有.so的烦恼
