### ISSUE TITLE
rtsp 流播放失败。。。

### ISSUE THREAD

**Issue by tommyfeng** [lipangit/JieCaoVideoPlayer#567]
我把demo中的url 换成了 rtsp流的地址，但是无法播放，显示 Protocol not found、tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,0)。 请问是自带的底层ijkPlayer没有编译 rtsp协议吗？如果要支持rtsp 的话，要如何修改呢？@lipangit

**Comment by tommyfeng** [comment]
刚刚测试播放 rtmp:// 的地址是有用的，不知为何rtsp:// 的地址不行呢？

**Comment by lipangit** [comment]
try 5.+
