### ISSUE TITLE
onError 方法求助

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#568]
我现在重写了onError方法，onError(int what, int extra)：what和extra，这二个错误代号能不能提供点说明。还有，我想在onError方法里，取得当前播放时间，这个能取到么？

**Comment by lipangit** [comment]
what和extra都是原封不动从MediaPlayer中取得的error参数，你可以在MediaPlayer中找到他们都有哪些值

最好用新版本
