### ISSUE TITLE
求助 在fragment 中怎么使用这个库啊 点击全屏就崩溃了

### ISSUE THREAD

**Issue by Anber-wei** [lipangit/JieCaoVideoPlayer#569]
![42ad27b0-507c-402b-a8e7-18bebe7b20da](https://cloud.githubusercontent.com/assets/23350197/21256967/522c8f36-c3b0-11e6-8945-a7c529ec10c8.png)

在fragment中使用点击全屏崩溃 因为fragment依附的activity继承的是fragmentActivity 所以找不到AppCompatActivity 爆出空指针 这个怎么解决啊 求助各位大神

**Comment by Anber-wei** [comment]
我继承的是AppCompatActivity就是好的  但是我要在fragment中使用这个播放器 承载fragment的activity继承的是FragmentActivity 这种情况点击全屏就崩溃了 求助各位大神

**Comment by lipangit** [comment]
请都继承AppCompatActivity，AppCompatActivity继承fragmentActivity，没问题的
