### ISSUE TITLE
include threshold in gestures 

### ISSUE THREAD

**Issue by scroozer** [lipangit/JieCaoVideoPlayer#570]
I have been using some of your code to create my own videoplayer but with exoplayer and noticed some minor bugs that could help improve the gestures for seeking and volume, due to the THRESHOLD value of the onTouch when the seeking finally kicks in there is a jump between the starting and the currently seeked value due to the threshold not being taken in count in the deltaX value in your onTouch I would propose you do this 
`long totalTimeDuration = exoPlayer.getDuration();
float adjustedDelta = 0;
if (deltaX>0){
adjustedDelta = deltaX-THRESHOLD;
}
else {
 adjustedDelta = deltaX+THRESHOLD;
}
mSeekTimePosition = (int) (mDownPosition + adjustedDelta * totalTimeDuration / screenWidth);`

to get an adjusted value of the deltaX so the user doesnt encounter a jump.

**Comment by lipangit** [comment]
You have got a point there, you are right, Could you please push a pull request it will be great, If I do that I will do it from start and test a lot, waste of time.
