### ISSUE TITLE
有声音没有图像的问题（急）

### ISSUE THREAD

**Issue by Vikaso** [lipangit/JieCaoVideoPlayer#571]
5.0.1版本，在listview中每个item是一个播放控件，一个按钮。点击按钮跳转到一个界面，界面里面是一个播放看控件，播放的视频地址和listview中第一个是一样的，然后点击播放。返回到listview中，在点击播放第一个视频。会出现一直在加载的progress，然后有声音，但是视频图像没有。
然后不知道有没有点击播放自动横屏的方法呢？
希望这个问题能够快点解决的 ，谢谢了

**Comment by lipangit** [comment]
5.+版本有问题，我还在测试，明天争取发布一个正式版

**Comment by Vikaso** [comment]
看到新的了 谢谢了啊
