### ISSUE TITLE
MainActivity leaked

### ISSUE THREAD

**Issue by pishimai** [lipangit/JieCaoVideoPlayer#576]
fm.jiecao.jiecaovideoplayer
static fm.jiecao.jcvideoplayer_lib.JCMediaManger.textureView
references fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.mContext
leaks fm.jiecao.jiecaovideoplayer.MainActivity instance
这是什么原因 应该怎么解决

**Comment by zhaoziliang01** [comment]
同问

**Comment by lipangit** [comment]
onComplete的时候把textureview置空试试。
