### ISSUE TITLE
ListViewNormalActivity leaked

### ISSUE THREAD

**Issue by pishimai** [lipangit/JieCaoVideoPlayer#577]
In fm.jiecao.jiecaovideoplayer:5.1:50.
* fm.jiecao.jiecaovideoplayer.ListViewNormalActivity has leaked:
* GC ROOT static fm.jiecao.jcvideoplayer_lib.JCMediaManager.textureView
* references fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.mContext
* leaks fm.jiecao.jiecaovideoplayer.ListViewNormalActivity instance

* Retaining: 25 KB.
* Reference Key: 05f000f5-a3ab-4112-9829-e65800adb737
* Device: Xiaomi Xiaomi MI 2S aries
* Android Version: 4.1.1 API: 16 LeakCanary: 1.4-beta2 3799172
* Durations: watch=5020ms, gc=178ms, heap dump=923ms, analysis=15211ms

* Details:
* Class fm.jiecao.jcvideoplayer_lib.JCMediaManager
|   static HANDLER_RELEASE = 2
|   static isPreparing = false
|   static JCMediaManager = fm.jiecao.jcvideoplayer_lib.JCMediaManager@1111356136 (0x423df2e8)
|   static textureView = fm.jiecao.jcvideoplayer_lib.JCResizeTextureView@1108145352 (0x420cf4c8)
|   static USER_AGENT = java.lang.String@1111348080 (0x423dd370)
|   static CURRENT_LIST_INDEX = -1
|   static CURRENT_PLAYING_URL = java.lang.String@1108835648 (0x42177d40)
|   static BANDWIDTH_METER = com.google.android.exoplayer2.upstream.DefaultBandwidthMeter@1111350656 (0x423ddd80)
|   static $staticOverhead = byte[264]@1111345593 (0x423dc9b9)
|   static TAG = java.lang.String@1109069112 (0x421b0d38)
|   static savedSurfaceTexture = android.graphics.SurfaceTexture@1116050080 (0x428592a0)
|   static HANDLER_PREPARE = 0
* Instance of fm.jiecao.jcvideoplayer_lib.JCResizeTextureView
|   static $staticOverhead = byte[24]@1111354985 (0x423dee69)
|   static TAG = java.lang.String@1111355280 (0x423def90)
|   mVideoSize = android.graphics.Point@1109588464 (0x4222f9f0)
|   mCanvas = null
|   mLayer = null
|   mListener = fm.jiecao.jcvideoplayer_lib.JCMediaManager@1111356136 (0x423df2e8)
|   mLock = java.lang.Object[0]@1108207208 (0x420de668)
|   mMatrix = android.graphics.Matrix@1119182832 (0x42b55ff0)
|   mUpdateListener = android.view.TextureView$2@1108125352 (0x420ca6a8)
|   mSurface = null
|   mNativeWindowL

**Comment by lipangit** [comment]
@pishimai 哥们你可以帮忙研究一下
