### ISSUE TITLE
Video playing but with black screen

### ISSUE THREAD

**Issue by AnkurJagani** [lipangit/JieCaoVideoPlayer#578]
Hi,

I am playing .mp4 video. But it is displaying black screen only. Sound playing nice. 

Note: I have captured this video from mobile. It is playing nice when playing with default player.

Please help, Thanks in advance.

**Comment by lipangit** [comment]
Show me the log.
You can also go to ask [exoplayer](https://github.com/google/ExoPlayer)

**Comment by YounMario** [comment]
@AnkurJagani  mabe your TextureView surface was destroyed or you passed wrong surface
