### ISSUE TITLE
Loading  Progress Issue

### ISSUE THREAD

**Issue by shahbaz2417** [lipangit/JieCaoVideoPlayer#579]
While buffering from second times the loading progressbar is not visible

**Comment by lipangit** [comment]
Yes ，the effect is not good ,because I can not find buffering listener, can you help me.

**Comment by shahbaz2417** [comment]
Sure. I am also working on it. Update you soon

**Comment by YounMario** [comment]
@lipangit  可以自定义ProgressView 传入播放器的引用,  在onDraw 中主动获取进度然后重新绘制. 效果还是不错的就是绘制有点频繁

**Comment by lipangit** [comment]
@YounMario 没这么复杂

**Comment by YounMario** [comment]
@lipangit  初次之外我能想到的只有timer ，楼主有更好的解决方案么？

**Comment by lipangit** [comment]
@YounMario 你是想在播放的时候如果loading，显示那个loading icon吧，楼主就是这个目的，我现在没有办法，MediaPlayer因为没有回调

**Comment by YounMario** [comment]
@lipangit  我的解决方案是 给ExoPlayer 设置 ExoPlayer.EventListener. 在 onPlayerStateChanged 的中判断如果当前状态是ExoPlayer.STATE_BUFFERING 我就显示loading，在状态变为ExoPlayer.STATE_READY时结束显示。 进度回调的解决方案是，自定义控件引用播放器的控制接口， 然后在onDraw 中主动获取 进度重绘 .目前没有什么异常。

**Comment by bb1690** [comment]
need to reset the video from start used "resetProgressAndTime" but its not taking effect. And without any thumbnail image how can one view a video image instead of black screen with play icon.

**Comment by lipangit** [comment]
@bb1690 As far as I know , we can not get image form videoUrl as thumbnail .
