### ISSUE TITLE
Can JC video player support stop one media player of a list

### ISSUE THREAD

**Issue by jiechu** [lipangit/jiecaovideoplayer#58]
I open a network request to load more data, save to sqlite, then use cursor adapter with recyclerview. When a loading more event was called, the loader should be re-init. for data, it is ok. But for JC player, IllegalStateException occurred if some JC player is playing. I guess it is because the same viewholder already has a mediaplayer playing. But I cannot stop that mediaplayer from JC API.  
Can you have some way to stop, so that the exception can be avoided?

Best wishes

**Comment by lipangit** [comment]
jcvideoplayer.ivStart.performClick();

if normal will play video , if plaing will pause video;

**Comment by lipangit** [comment]
if re-init will call videoPlayer.setUp(url ,title), this will init the videoPlayer , whate ever the state of the videoPlayer , it will be reset. 

and JCVideoPlayer.releaseAllVideos(); can stop all videos.

**Comment by lipangit** [comment]
How's it going？
