### ISSUE TITLE
Fragment使用这个时候的问题

### ISSUE THREAD

**Issue by YaHoYii** [lipangit/JieCaoVideoPlayer#584]
在Fragment中放一个视频列表，点击任意一个视频 直接进入全屏 然后返回的时候  返回的位置不对 退回到的不是放Fragment的Activity 而是上一个Activity  ，而且直接进入全屏的时候最上边的返回按钮是不管用的 然后 横屏也有问题   有可能是我的姿势不对 能提供一种姿势吗

**Comment by lipangit** [comment]
在参照demo的MainActivity中的onPause和onBackPress函数中加几行代码
