### ISSUE TITLE
4.8.3网络.mp4视频时只有声音没有视频画面

### ISSUE THREAD

**Issue by qmy1990** [lipangit/JieCaoVideoPlayer#585]
## 这是打印消息：
12-26 13:46:25.002 4635-4635/com.dsrc.stardaily I/JieCaoVideoPlayer: onClick start [1111148048] 
12-26 13:46:25.022 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: prepareVideo [1111148048] 
12-26 13:46:25.022 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: addTextureView [1111148048] 
12-26 13:46:25.072 4635-4635/com.dsrc.stardaily I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1111148048] 
12-26 13:46:25.072 4635-6464/com.dsrc.stardaily I/JieCaoVideoPlayer: set surface
12-26 13:46:25.332 4635-4635/com.dsrc.stardaily I/JieCaoVideoPlayer: onPrepared  [1111148048] 
12-26 13:46:25.332 4635-2090/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 0/311659 [1107438272] 
12-26 13:46:25.342 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
12-26 13:46:25.342 4635-2093/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 0/311659 [1105969160] 
12-26 13:46:25.342 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
 [ 12-26 13:46:25.352   230:  656 D/         ]
 pcm_write, delay 30ms to wait snd open
12-26 13:46:25.642 4635-2093/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 0/311659 [1105969160] 
12-26 13:46:25.842 4635-4635/com.dsrc.stardaily V/JieCaoVideoPlayer: onBufferingUpdate 4 [1111148048] 
12-26 13:46:25.842 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
12-26 13:46:25.842 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 0/311659 [1114340008] 
12-26 13:46:25.842 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END
12-26 13:46:25.882 4635-4635/com.dsrc.stardaily D/JieCaoVideoPlayer: onInfo what - 10002 extra - 0
12-26 13:46:26.142 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 240/311659 [1114340008] 
12-26 13:46:26.352 4635-4635/com.dsrc.stardaily V/JieCaoVideoPlayer: onBufferingUpdate 10 [1111148048] 
12-26 13:46:26.442 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 540/311659 [1114340008] 
12-26 13:46:26.742 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 839/311659 [1114340008] 
12-26 13:46:26.862 4635-4635/com.dsrc.stardaily V/JieCaoVideoPlayer: onBufferingUpdate 17 [1111148048] 
12-26 13:46:27.042 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 1130/311659 [1114340008] 
12-26 13:46:27.342 4635-2105/com.dsrc.stardaily V/JieCaoVideoPlayer: onProgressUpdate 1428/311659 [1114340008] 

## 这是代码
jcVideoPlayerStandard.setUp(article.getPlay_url()
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");

**Comment by qmy1990** [comment]
这是视频地址：5.1和5.2的可以播放，但是全屏有问题。4.8.3只能播放声音，没有画面
http://ohuypks0j.bkt.clouddn.com/videovideoBehind.mp4?e=1482747810&token=0z_HYMW8-KCuR21XL2GxnrweiU9tdXJwVY7OA7Yg:QWiKtMEjKt8eJaytuc2EJTNVlfk

**Comment by lipangit** [comment]
5.2全屏有bug，用5.2.1吧
