### ISSUE TITLE
JCVideoPlayer类中的NORMAL_ORIENTATION字段不应该写死

### ISSUE THREAD

**Issue by jiang111** [lipangit/JieCaoVideoPlayer#587]
当全屏返回之后，JCVideoPlayer中的NORMAL_ORIENTATION字段会强制把activity写成SCREEN_ORIENTATION_PORTRAIT方向，正确的做法是根据当前activity的方向来调整，建议在JCVideoPlayer的init方法中添加 :   
```
 NORMAL_ORIENTATION = JCUtils.getAppCompActivity(getContext()).getRequestedOrientation();
```
(因为目前正在做一款平板应用，要求全部横屏，才发现了这个问题 :-)

**Comment by jiang111** [comment]
我发现在init中写NORMAL_ORIENTATION的值还是会被当前全屏的状态覆盖掉，看来只能提供个方法给外面调用了

**Comment by lipangit** [comment]
NORMAL_ORIENTATION 这个变量是无状态的，如果你的app的屏幕方向是不统一的，你应该随时修改这个变量
