### ISSUE TITLE
设置高度固定，视频不能充满屏幕、

### ISSUE THREAD

**Issue by huangsongyan** [lipangit/JieCaoVideoPlayer#589]
设置高度固定，视频不能充满屏幕、

**Comment by lipangit** [comment]
这种前提是保证不拉伸视频，5.2.1版本中你可以根据自己视频的大小设置高宽比例，也可以在onSize的回调函数中设置想要的视频高宽

**Comment by heroleon** [comment]
@lipangit 请问，这个onSize回调在哪个类里面？

**Comment by lipangit** [comment]
JCVideoPlayer onVideoSizeChanged()函数

**Comment by heroleon** [comment]
@lipangit 多谢了
