### ISSUE TITLE
能播放data文件下保存的视频吗？

### ISSUE THREAD

**Issue by anjiao** [lipangit/jiecaovideoplayer#59]
/storage/emulated/0/Android/data/hk.hhw.huanxin/hhwapp#hhwapp/5892b74c89db4be49975e3cff49de7b8ideo/40977420-05f6-11e6-bc52-99d984d6b6ed.mp4

我播放类似视频，好像没有成功

**Comment by lipangit** [comment]
肯定可以，用的android.media.MediaPlayer播放视频，肯定能播放本地视频，有log吗，加权限了吗

**Comment by anjiao** [comment]
播放sd卡 不是data文件的视频正常  我明天看看吧

**Comment by lipangit** [comment]
能播放吧^_^
