### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#590]
Caused by: java.lang.ClassNotFoundException: Didn't find class "fm.jiecao.jcvideoplayer_lib.JCResizeImageView" on path: DexPathList[[zip file "/data/app/xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/xxx-1/lib/arm64, /vendor/lib64, /system/lib64]]

**Comment by lipangit** [comment]
Suggest use gradle.

**Comment by PiPiCaptain** [comment]
@lipangit 哥，你还是用中文吧。我只不过是把错误显示出来，别误会我是歪果人。我现在就是用gradle导入这个库的。

**Comment by lipangit** [comment]
哈哈，这应该是gradle的使用经验了，我刚用gradle的时候也是各种各样的问题，加油

**Comment by PiPiCaptain** [comment]
@lipangit 我的项目里，其它类库，存在arm64-v8a、armeabi、armeabi-v7a、x86、x86_64。这些会不会影响？

**Comment by lipangit** [comment]
不会，用新版本5.2.1，不涉及so

**Comment by PiPiCaptain** [comment]
@lipangit 找到问题了，我之前是用4.6.5版本，新版本5.2.1。自定义UI时，在XML布局里多了二个控件，在新版本5.2.1是没有的。太粗心，没留意。
![921d042c-5c6b-49b3-b1fb-18709383c201](https://cloud.githubusercontent.com/assets/22672329/21539967/bcd651b0-cde6-11e6-951d-9919ab0f161c.png)

**Comment by lipangit** [comment]
这种调试一下应该就能找到，平时不需要的东西直接就删除了，文档里没法写的那么详细。感谢你的反馈
