### ISSUE TITLE
竖直全屏，视频不居中？

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#597]
![149f96eb3acaac97638432ec5c3571c0](https://cloud.githubusercontent.com/assets/22672329/21540973/2754266e-cdee-11e6-8cd1-6590655ab607.jpg)
如上图所示

**Comment by lipangit** [comment]
你改库了吗，默认应该是居中，你看一下Textureview没居中，还是图像在Textureview上没居中
