### ISSUE TITLE
问问计划

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#598]
什么时候会有一个基于exoplayer的稳定版本？

**Comment by lipangit** [comment]
5.2.1有什么问题吗

**Comment by PiPiCaptain** [comment]
@lipangit 暂时没发现什么问题。我是被简介上的一句话误导了『Import library but current stable version is still 4.8.3, 5.0 use exoplayer also have many problems.』
