### ISSUE TITLE
多个视频循环播放？

### ISSUE THREAD

**Issue by jokertu** [lipangit/JieCaoVideoPlayer#599]
多个本地视频循环播放，怎么监听一个视频播放结束，启动另一个视频的时候需要做什么操作吗（有什么要注意的吗）？

**Comment by lipangit** [comment]
我没调试过这个需求，onAutoComplete能监听到停止，startButton.performClick能开始一个视频

**Comment by xiapQu** [comment]
这样使用会出现黑屏和加载进度条（本地视频），请问如何解决？

**Comment by lipangit** [comment]
在群里吗，录个小视频看看效果吧
