### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by m5314** [lipangit/JieCaoVideoPlayer#600]
1.jiecaovideoplayer支持什么格式，exoplayer只支持原生mediaplayer支持的那些吧？
2.视频的缓存都放哪去了?能手动清除吗？

**Comment by lipangit** [comment]
1.你需要播放哪些视频格式，[手机上建议使用MP4，其他的对格式的探索，对于我们这个级别来说都是徒劳](https://github.com/lipangit/JieCaoVideoPlayer/issues/431)

2.缓存的问题Exoplayer应该提供了一些接口，但还没细看，你觉得怎么用比较好
