### ISSUE TITLE
mpeg-4视频格式播放不了

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#601]
只有声音没有图像，以前基于ijkplayer的也不能播放，只有很早以前使用mediaplayer能播放，但是3.6.3版本没有现在体验好，请问这个版本能加上mpeg-4格式吗？

**Comment by lipangit** [comment]
应该是不支持你的图像编码，看exoplayer的demo，你可以尝试吧图像编码格式化成h264或h265，如果exoplayer支持的不够多，只能将exoplayer的MediaPlayer换成系统的MediaPlayer

**Comment by my19941001** [comment]
@lipangit 呃，我用ijkplayer现在能播放了，我在ubuntu上面重新编译了ffmpeg加入了mpeg-4的解码器，不过exoplayer没找到相关资料要怎么做，现在只能继续使用ijkplayer了，看来apk瘦身的目的达不到了

**Comment by lipangit** [comment]
一直在酝酿用回系统的MediaPlayer

**Comment by zhangyawentudi** [comment]
建议博主封装Vitamio万能播放器，基于系统的播放器有些格式是不支持的

**Comment by my19941001** [comment]
@zhangyawentudi Vitamio对于企业是收费的

**Comment by lipangit** [comment]
Vitamio 不开源，暂不考虑

**Comment by lipangit** [comment]
在点播方面我觉得系统的MediaPlayer更好用一些，考虑到系统的MediaPlayer直播不好用，如何切换到系统的MediaPlayer上还在酝酿

**Comment by mxlibra** [comment]
在github上面有看到过exoplayer+VLC的lib,是不是会好一些?

**Comment by lipangit** [comment]
系统的播放器应该是点播最好用的播放器，之后可能换回去，不着急

**Comment by my19941001** [comment]
@lipangit 格式的问题可能有解决办法，ijkplayer增加所需的编码器即可，exoplayer更新到最新版本即可播放mpeg-4
