### ISSUE TITLE
我自己仿照你的demo开发的时候，在全屏和恢复的时候会有黑屏

### ISSUE THREAD

**Issue by jaydon** [lipangit/JieCaoVideoPlayer#605]
我自己仿照你的demo开发的时候，在全屏和恢复的时候会有黑屏，但demo不会，参考了相关代码，没有发现应该修改的地方：
/**
     * 全屏操作，横屏
     */
    @SuppressWarnings("unchecked")
    private void fullVideo() {
        mDefaultHeight = getHeight();
        ((Activity)mContext).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);
        ViewGroup decorView = (ViewGroup) ((Activity)mContext).findViewById(Window.ID_ANDROID_CONTENT);
        Constructor<ExoPlayerLayout> constructor = null;
        try {
            constructor = (Constructor<ExoPlayerLayout>) ExoPlayerLayout.this.getClass().getConstructor(Context.class);
            mFullScreenExoPlayerLayout = constructor.newInstance(mContext);
            surfaceContainer.removeView(ExoPlayerManager.getInstance().getTextureView());
            FrameLayout.LayoutParams lp = new FrameLayout.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
            decorView.addView(mFullScreenExoPlayerLayout, lp);
            mFullScreenExoPlayerLayout.setUrl(mUrl);
            mFullScreenExoPlayerLayout.setImageUrl(mImageUrl);
            mFullScreenExoPlayerLayout.addView(ExoPlayerManager.getInstance().getTextureView());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * 恢复竖屏
     */
    public void notFullVideo() {
        mDefaultHeight = -1;
        ((Activity)mContext).setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        ViewGroup decorView = (ViewGroup) ((Activity)mContext).findViewById(Window.ID_ANDROID_CONTENT);
        decorView.removeView(mFullScreenExoPlayerLayout);
        mFullScreenExoPlayerLayout.removeView(ExoPlayerManager.getInstance().getTextureView());
        mFullScreenExoPlayerLayout = null;
        surfaceContainer.addView(ExoPlayerManager.getInstance().getTextureView());
    }
在学习ExoPlayer中，求解。

**Comment by lipangit** [comment]
setSurface是不成功，多半因为这个

**Comment by jaydon** [comment]
了解，因为我自己是直接设置
  //把player通过surfaceTextureListener联系在一起
    mSimpleExoPlayer.setVideoTextureView(mTextureView);
 并没有实现它，TextureView.SurfaceTextureListener，接下来做做测试，谢谢。

**Comment by jaydon** [comment]
可以了，问个问题
