### ISSUE TITLE
listview的header里面播放视频ANR

### ISSUE THREAD

**Issue by diycoder** [lipangit/JieCaoVideoPlayer#606]
在ListView.addHeaderView中，header里面播放视频在ListView加载更多会卡死，给了高度和wrap_conent测试都会出现（4.8.3版本）

**Comment by lipangit** [comment]
不会吧，你看demo中有AutoTinyNormalActivity，有这个demo

**Comment by diycoder** [comment]
好的，最后发现是兼容包的问题...
