### ISSUE TITLE
Progressbar is not updated when enter in fullscreen mode from normal mode

### ISSUE THREAD

**Issue by lucaFaverio** [lipangit/jiecaovideoplayer#61]
Hi, 
In the last version (3.0_preview) When you go from normal mode to fullscreen mode the UI (time, progress bar) is no more updated.
The culprit seems to be the method `JCVideoPlayer.startProgressTimer()` which is not called when a video is resumed in fullscreen mode. As workaround, I added the method to `case CURRENT_STATE_PLAYING:` in `JCVideoPlayer.setStateAndUi(int state)` and it seems to work correctly

**Comment by lipangit** [comment]
Your proposal is very useful， thank you very much.
