### ISSUE TITLE
Player onFinisheListener

### ISSUE THREAD

**Issue by darkmonk942** [lipangit/JieCaoVideoPlayer#613]
How I can check video finish status?

**Comment by my19941001** [comment]
![image](https://cloud.githubusercontent.com/assets/18034743/21706232/70ba5e3c-d400-11e6-9bfa-e5fe97753b1b.png)

**Comment by lipangit** [comment]
Override onAutoComplete()
Override onComplete()

Extends JCVideoPlayerStandard Override these two function can catch finish status.

**Comment by darkmonk942** [comment]
thx
