### ISSUE TITLE
现在ExoPlayer版本是2.0.4，这个版本不支持mp4v格式播放，最新的2.1.1是可以的，能不能升级一下呢？

### ISSUE THREAD

**Issue by my19941001** [lipangit/JieCaoVideoPlayer#614]
现在我已经修改成了2.1.1版本，但是相对于2.0.4版本的话，回调及构造函数有所改变，虽然我修改后仍然可以播放，但是我并不知道会有什么后果，所以拜托一下作者能不能升级一下？

**Comment by lipangit** [comment]
好，这礼拜先升级一下exoplayer
