### ISSUE TITLE
弱网络或无网下，播放器就会回调onError

### ISSUE THREAD

**Issue by PiPiCaptain** [lipangit/JieCaoVideoPlayer#616]
在弱网络或无网下，播放器就会回调onError。能否像bilibili客户端那样，弱网络或无网下，会一直请求视频

**Comment by lipangit** [comment]
这种网络的判断会让代码非常复杂并且不稳定，如果要做的话应该非常谨慎。

**Comment by lipangit** [comment]
有必要吗，有什么问题给个error是了
