### ISSUE TITLE
请问现在5.0版是稳定版吗？我看网页说4.8.3是稳定版

### ISSUE THREAD

**Issue by lovearthhome** [lipangit/JieCaoVideoPlayer#621]
请问现在5.0版是稳定版吗？我看网页说4.8.3是稳定版。因为急需要测试explayer,所以需要问下

**Comment by Weststreet** [comment]
@lovearthhome 5.0换成了exoplayer 4.8.3是稳定版 不是用的exoplayer

**Comment by lipangit** [comment]
现在exoplayer要换成系统的MediaPlayer了

**Comment by Weststreet** [comment]
@lipangit 下版本不用exoplayer了？

**Comment by lipangit** [comment]
对，已经发了preview版本，点播的终极解决办法应该是系统的MediaPlayer

**Comment by PiPiCaptain** [comment]
@lipangit 5.3就是MediaPlayer的preview版本吗？

**Comment by lipangit** [comment]
对，可以用，系统的MediaPlayer在3.*版本之前一直在使用

**Comment by lovearthhome** [comment]
@lipangit @Weststreet @ @PiPiCaptain   您好，我们一直在使用jiecao播放器，我们目前的计划是
1：所有片源换乘mkv
2：播放器要支持字幕
3：播放器支持h265
之前一直期待jiecao里融入exoplayer从而播放字幕。我看exoplayer也支持mkv和h265. 
能问一下，jiecao后续在mkv,字幕,h265方面有没有计划。

**Comment by lipangit** [comment]
系统的播放器支持[mkv格式](https://developer.android.com/guide/topics/media/media-formats.html)
系统的MediaPlayer支持[字幕](https://developer.android.com/reference/android/media/MediaPlayer.html)，但是没调试过，你可以探索一下，然后再来优化这个库
这个库主要做播放逻辑和ui逻辑，如果MediaPlayer不支持的格式只能考虑换掉MediaPlayer。
你可以拿一个url试试能不能播放

**Comment by lovearthhome** [comment]
@lipangit 好的，我试一试，然后，这个jiecaoplayer后面就去掉exoplayer，换成系统的mediaplayer了？

**Comment by yingzi2011** [comment]
exoplayer  应该专门开一个分支，
最近在直接在看exoplayer，准备用到自己的项目里，结果直接更完变成media 了，太容易混淆了
标示一下具体版本，只是个人的建议

**Comment by lipangit** [comment]
[这里](https://github.com/lipangit/JieCaoVideoPlayer/releases)有功能变化。
我觉得系统的MediaPlayer是视频点播的终极状态，那么不建议使用其他播放引擎，如果系统的MediaPlayer没有重大缺陷是不会替换成别的播放引擎的，你为什么专注exoplayer，有什么发现吗
