### ISSUE TITLE
在有些特定机型上会出现这样的问题，能给解答下么，在华为pad（5.1.1）操作系统上

### ISSUE THREAD

**Issue by mlzhang920802** [lipangit/JieCaoVideoPlayer#622]
![default](https://cloud.githubusercontent.com/assets/15686696/21794322/3478b31a-d734-11e6-8cab-3328f5564b82.png)

**Comment by lipangit** [comment]
我平时没这么多机型测试，不知道这些log是怎么来的，表示什么含义。
建议使用新版，用系统MediaPlayer播放视频
