### ISSUE TITLE
快速开启关闭播放页面频繁GC

### ISSUE THREAD

**Issue by mlzhang920802** [lipangit/JieCaoVideoPlayer#623]
当我在快速的开启关闭播放页面的时候会发生频繁的GC，请问这是为什么

**Comment by lipangit** [comment]
开启和关闭包含jcvd的界面的时候，完全不涉及视频相关的内容，因为在点击开始播放的时候才addView Textureview，才prepare video，进入和退出界面只是单纯的ui操作，并不清楚GC是从哪来的。

代码里在onAutoCompletion的时候会调用GC

**Comment by lipangit** [comment]
我觉得在安卓里ffmpeg调用so的方式播放视频不是将来趋势，请使用最新版本 5.3

**Comment by SunshineExit** [comment]
@lipangit 我使用了最新的5.3，但是为什么貌似value-24会有
```java
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
```
这样的错误？

**Comment by lipangit** [comment]
把你项目的v4包去掉，support v7包的版本和jcvd版本相同，或也去掉
