### ISSUE TITLE
怎么点击全屏按钮横屏播放啊

### ISSUE THREAD

**Issue by ZhetengDashen** [lipangit/JieCaoVideoPlayer#625]
现在点击全屏按钮视频还是竖着的。

**Comment by ZhetengDashen** [comment]
我的用的是4.8.3的版本

**Comment by lipangit** [comment]
参照demo的origintationActivity，修改activityInfo

**Comment by ZhetengDashen** [comment]
现在点击全屏可以全屏了 ，按返回键  视屏回到小屏状态， 但是整个页面还是横着的。怎么解决啊。我的思路是监听视频是否全屏然后去更改activity 横竖屏。 现在问题是怎么能监听到视频的全屏和小屏状态啊。

**Comment by lipangit** [comment]
还看这个origintationActivity，配置退出全屏的activityInfo
