### ISSUE TITLE
同一个页面下如果有多个url相同的视频，播放其中一个其他有可能会一起播放

### ISSUE THREAD

**Issue by a3600266** [lipangit/JieCaoVideoPlayer#627]
RT，不修改url的话，请问下有办法解决吗

**Comment by lipangit** [comment]
用5.3，逻辑有变化，不会出这个问题了

**Comment by a3600266** [comment]
然而5.3也会有这种情况。。具体是比如一个listview里有四个url相同的视频，目前看到的是3个，点击播放第一个视频的时候，滑到第4个会发现第4个视频也在播放……然后5.3还有一个问题，就是有时候视频会一直显示加载中的转圈【已经在播放了】，此时因为没有暂停按钮无法暂停……

**Comment by lipangit** [comment]
列表必须是复用的，在滑动的时候通过setUp来release这个item的上一个jcvd
