### ISSUE TITLE
播放直播视频

### ISSUE THREAD

**Issue by jianwenzhao** [lipangit/JieCaoVideoPlayer#629]
请问一下最新版 exoplayer是可以播放直播视频的吗？

**Comment by jianwenzhao** [comment]
就是rtmp的直播流

**Comment by lipangit** [comment]
新版本是基于系统的MediaPlayer，不是exoplayer，支持[rtsp](https://developer.android.com/guide/topics/media/media-formats.html)，不支持rtmp
