### ISSUE TITLE
是否需要添加一个设置显示方式的参数？

### ISSUE THREAD

**Issue by AliveingSoul** [lipangit/jiecaovideoplayer#63]
加载一个视频源的时候碰到，长度是到两边的，然而视频高度看起来却不到屏幕高度的1/3，原因是视频（一部电影）本身上下两边都有黑边，这样看起来，长宽比就不好了

**Comment by lipangit** [comment]
目前的效果是不会拉伸或挤压视频，你想要什么样的效果呢，能把视频地址发过来看看吗

**Comment by AliveingSoul** [comment]
已发邮件，请查看
