### ISSUE TITLE
考虑加入直播逻辑设置

### ISSUE THREAD

**Issue by jyh149129** [lipangit/JieCaoVideoPlayer#630]
比如播放直播的话，可以禁止手势快进和快退
ps：当然也可以由我们自行覆盖处理手势，不过我觉得这个也是一个比较通用的设置，所以建议加上

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard 复写onTouch函数，直接return能屏蔽父类的逻辑禁止手势。
