### ISSUE TITLE
视频快进屏幕卡主   声音还在播放

### ISSUE THREAD

**Issue by Lyl521** [lipangit/JieCaoVideoPlayer#635]
快进视频卡主，只有预加载出来的那一部分才可以快进  ，，没有预加载出来的快进就卡主

**Comment by lipangit** [comment]
网络没问题吧，没加载吗

**Comment by Lyl521** [comment]
网络没有问题  ，就是视频较大会出现这样的情况

**Comment by Lyl521** [comment]
我现在想的是快进的时候只可以让他快进到预加载的地方   但是这样体验不是很好。。。。  小视频快进没有问题

**Comment by lipangit** [comment]
快进到预加载的地方是什么意思

**Comment by Lyl521** [comment]
就是预加载出来多少就最多可以快进多少。没有预加载出来的那部分不可以快进

**Comment by Lyl521** [comment]
几分钟的视频没有快进没有问题   我这个是四十分钟的    ，是不是和视频的大小也有关系

**Comment by lipangit** [comment]
理论上不应该呀，你发我个地址，我试试，出问题的频率怎么样
