### ISSUE TITLE
4.8.1 不支持本地视频地址播放吗

### ISSUE THREAD

**Issue by CodeToxicant** [lipangit/JieCaoVideoPlayer#636]

**Comment by lipangit** [comment]
支持，但是建议使用最新版

**Comment by CodeToxicant** [comment]
已经改了，url字符串貌似传空值就报错了

**Comment by CodeToxicant** [comment]
Map<String,String> headers = new HashMap<String,String>();
                headers.put("Referer","http://");
                jsVideo.setUp(item.getM_video(), JCVideoPlayerStandard.SCREEN_LAYOUT_LIST,headers,"");
进行头信息设置 好像不起作用

**Comment by lipangit** [comment]
url不能是空，header我再测测，这版估计是忘了，你做完也可以把代码提交上来
