### ISSUE TITLE
横屏闪退，很多版本都是

### ISSUE THREAD

**Issue by DavidWeiZhong** [lipangit/JieCaoVideoPlayer#638]
4.8.1横屏闪退
4.8.2横屏闪退
4.8.3横屏闪退
5.3直接不能播放视频

**Comment by lipangit** [comment]
闪退log是什么，4.*版本不建议使用

不能播放的地址是什么

**Comment by DavidWeiZhong** [comment]
不能播放的地址是
http://cmcc.ips.cnlive.com/content/movie?contentId=623206749&productid=2028593060&ratelevel=2

**Comment by DavidWeiZhong** [comment]
谢谢，闪退的问题一斤解决了，现在是5.3的不能播放视频了
不能播放的地址是
http://cmcc.ips.cnlive.com/content/movie?contentId=623206749&productid=2028593060&ratelevel=2

**Comment by lipangit** [comment]
这地址确实播放不了

**Comment by lipangit** [comment]
exoplayer能播放
