### ISSUE TITLE
HUAWEIG750-TO1,API(4.2.2) java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)

### ISSUE THREAD

**Issue by junchenChow** [lipangit/JieCaoVideoPlayer#639]
`java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
	android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)
	android.view.GLES20TextureLayer.setSurfaceTexture(GLES20TextureLayer.java:81)
	android.view.HardwareRenderer$Gl20Renderer.setSurfaceTexture(HardwareRenderer.java:1583)
	android.view.TextureView.getHardwareLayer(TextureView.java:393)
	android.view.View.getDisplayList(View.java:12865)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.draw(View.java:14018)
	android.widget.FrameLayout.draw(FrameLayout.java:526)
	android.view.View.getDisplayList(View.java:12902)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.draw(View.java:14018)
	android.view.View.getDisplayList(View.java:12902)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.getDisplayList(View.java:12897)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.draw(View.java:14018)
	android.widget.FrameLayout.draw(FrameLayout.java:526)
	android.view.View.getDisplayList(View.java:12902)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.getDisplayList(View.java:12897)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.getDisplayList(View.java:12897)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.getDisplayList(View.java:12897)
	android.view.View.getDisplayList(View.java:12951)
	android.view.View.draw(View.java:13708)
	android.view.ViewGroup.drawChild(ViewGroup.java:3083)
	android.view.ViewGroup.dispatchDraw(ViewGroup.java:2931)
	android.view.View.draw(View.java:14018)`

**Comment by lipangit** [comment]
这应该是切换全屏的时候有setTexture导致的，改库了吗，还有其他线索吗

**Comment by junchenChow** [comment]
在数据统计上看到了 全屏切换唯一改的代码就是强制横屏 其他的没有

**Comment by lipangit** [comment]
会持续关注这个问题，当时调试的时候好像遇到过这个问题

**Comment by xxwson** [comment]
我也有遇到同样的问题，在红米手机4.2.2的系统上必现。点击全屏的时候，确实是切换全屏的时候setTexture导致的,目前还不知道是什么原因。

**Comment by lipangit** [comment]
持续关注

**Comment by huashigen** [comment]
4.2.2系统必挂

**Comment by huashigen** [comment]
全屏切换唯一改的代码就是强制横屏，这样在4.2.2上会崩溃，改回去竖屏就可以。但是极少的偶发性崩溃还是有（不限4.2.2）

**Comment by lipangit** [comment]
多谢你的反馈，你看节操精选app有这个问题吗

**Comment by huashigen** [comment]
节操精选没问题。问题复现了：目前测试5.2.1和5.3版本（我运行的demo），在android4.4.4（google nexus）设备上，点击全屏，在竖屏状态下切换到横屏，再切换到竖屏，点击返回，几乎必挂。

**Comment by lipangit** [comment]
这种情况的从横屏切换成竖屏是系统级的屏幕方向的改变，log里的意思surfaceView已经销毁了重新attach，正常情况是不销毁的

**Comment by xqr** [comment]
java.lang.RuntimeException: Error during detachFromGLContext (see logcat for details)
	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:237)

华为 4.2.3 必挂

**Comment by lipangit** [comment]
好像解决不了

**Comment by marothiatechs** [comment]
Use JZVideoPlayer.releaseAllVideos(); before calling fullscreenwindow. It solved the problem for me.
