### ISSUE TITLE
可以滑出屏幕就停止播放，释放掉吗

### ISSUE THREAD

**Issue by dingzhixiang** [lipangit/jiecaovideoplayer#64]

**Comment by lipangit** [comment]
会释放 
先canceltimer，再release MediaPlayer，最后UI设成normal状态。

**Comment by lipangit** [comment]
首先你的listview是要复用viewholder，划出屏幕停止的本质是复用viewholder的时候会setUp，重新配置新的播放器，如果这个播放器是播放状态就会重置它的状态

如果列表是不能复用的，可以用JCVideoPlayer.releaseAllVideos();手动控制

**Comment by dingzhixiang** [comment]
好的 谢谢。
