### ISSUE TITLE
onAudioFocusChange case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT crash 

### ISSUE THREAD

**Issue by lytcom** [lipangit/JieCaoVideoPlayer#640]
@Override
        public void onAudioFocusChange(int focusChange) {
            switch (focusChange) {
                case AudioManager.AUDIOFOCUS_GAIN:
                    break;
                case AudioManager.AUDIOFOCUS_LOSS:
                    releaseAllVideos();
                    Log.d(TAG, "AUDIOFOCUS_LOSS [" + this.hashCode() + "]");
                    break;
                case AudioManager.AUDIOFOCUS_LOSS_TRANSIENT:
                    if (JCMediaManager.instance().mediaPlayer != null &&
                            JCMediaManager.instance().mediaPlayer.isPlaying()) {
                        JCMediaManager.instance().mediaPlayer.pause();
                    }

mediaPlayer.isPlaying()这里有时候会报IllegalStateException，不需要增加个状态判断或保护下吗？

**Comment by lipangit** [comment]
有道理，这版本修改

**Comment by lipangit** [comment]
我感觉try catch就好，不用状态判断了，如果有IllegalStateException错误，当前肯定是不是播放状态，不崩溃就好了。
