### ISSUE TITLE
我使用的是4.8.3版本，项目遇到的问题是，有一部分视频没有图像只有声音，有一部分正常播放

### ISSUE THREAD

**Issue by liukangqi2015** [lipangit/JieCaoVideoPlayer#641]
有一部分视频没有图像只有声音，我想请问是什么原因。

**Comment by 1023459494** [comment]
换5.3版本吧，有声音无画面是解码的问题

**Comment by lipangit** [comment]
这位朋友说的对

**Comment by liukangqi2015** [comment]
@1023459494 项目已经上线，可能年后更换，谢谢

**Comment by liukangqi2015** [comment]
@lipangit 感谢你们开发出这款开源播放器，省去不少麻烦。现在我已经与其他同事沟通，将视频编码格式严格要求，暂时解决这个问题。

**Comment by lipangit** [comment]
@liukangqi2015 感谢你的参与

**Comment by CreamF** [comment]
我现在也遇到了同样的问题，只有音频没有视频，合成视频的伙伴说是用FFmpeg工具合成的，请问这个是否也属于解码的问题？这个可以怎么得到解决？

**Comment by liukangqi2015** [comment]
@CreamF 视频格式建议使用MP4视频格式，图像用h264或h265编码，声音aac编码

**Comment by lipangit** [comment]
用新版，不建议用ijkplayer

**Comment by CreamF** [comment]
@liukangqi2015  这个问题已经解决了。这是自带的不支持FFMPEG的视频媒体，需要扩展外部的视频解码库。exoPlayer谷歌官方只提供了FFMPEG的音频解码。视频解码需要扩展
