### ISSUE TITLE
安卓7.0出现couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by 251068550** [lipangit/JieCaoVideoPlayer#642]
在调用JCVideoPlayer.releaseAllVideos();的时候初始化单例JCMediaManager = new JCMediaManager();
这个库找不到，使用最新版本也不行

**Comment by lipangit** [comment]
release了为什么要new一个JCMediaPlayer

**Comment by 251068550** [comment]
我的意思是调用这个方法JCVideoPlayer.releaseAllVideos();这个方法里有判断JCMediaManager有没有初始化，找不到库的错误就是在初始化的时候报错的。我只调用了释放的方法。

**Comment by lipangit** [comment]
用新版，不建议用ijkplayer了

**Comment by 251068550** [comment]
新版的在哪，不是当前这个项目吗

**Comment by lipangit** [comment]
[5.3](https://github.com/lipangit/JieCaoVideoPlayer)
