### ISSUE TITLE
不能记录播放进度

### ISSUE THREAD

**Issue by AnswerZhao** [lipangit/JieCaoVideoPlayer#643]
只要Activity调用了onPause()就调用releaseAllVideos()，为何这样设置呢？这样导致每个页面的播放进度不能被记录，比如：第一个页面我播放了2分钟，跳转到了第二个页面，再返回第一个页面继续播放时又会从头开始。谢谢。

**Comment by lipangit** [comment]
release的时候会调用onComplete的，会记录播放位置的，你断点一下

**Comment by AnswerZhao** [comment]
@lipangit 是的。当前记录是以播放路径为key保存到本地的，如果前后两个页面播放同一视频且暂停在不同的进度，那么页面的播放进度还是会乱掉的。在onPause()时就releaseAllVideos()是出于什么考虑呢？为了节省内存？

**Comment by lipangit** [comment]
两个页面播放同一个视频，他们保存的应该是同一个进度

onPause的时候release视频，只是一个播放器的逻辑

**Comment by AnswerZhao** [comment]
@lipangit 不一定啊，第一个页面播放了10s，进入第二个页面播放到20s，再返回第一个页面应该还是从10s开始的

**Comment by lipangit** [comment]
现在的进度是以视频的url为key保存的，

你遇到的情况需要怎样保存
