### ISSUE TITLE
no option to add header map data

### ISSUE THREAD

**Issue by hitec16** [lipangit/JieCaoVideoPlayer#647]
In version 4.6 we could send hashmap of header data but in new version I can't find any option to send header data via setUp() method. Is there anyway to add it?

I tried hardcoding mapData inside JCMediaManager then only first video in recyclerview gets played after that I get unknown error from mediaplayer.

**Comment by lipangit** [comment]
I was focused on other feature, ignore header data thar time.

You can use new version 5.4, this version is stable.

**Comment by hitec16** [comment]
But in latest version of the library there is no option to add headers? I pass authorization tokens in header.

**Comment by lipangit** [comment]
jcvideoPlayerStandard.headData this param is mediaPlayer header data
