### ISSUE TITLE
Width on version latest version 5

### ISSUE THREAD

**Issue by ivanviragine** [lipangit/JieCaoVideoPlayer#649]
Hi,

When updating from 4.8.3 to 5.4, my video is not taking all the space available, even when I use width=fill_parent.
Switching back to 4.8.3, full width is correct.

Any idea why?

**Comment by lipangit** [comment]
As I remember, there no defferent in layout.xml between 4.+ and 5.+ . 

You can test by other train of tought.

**Comment by ivanviragine** [comment]
@lipangit I'm using the fresco layout (because I use fresco), exactly like the example...

**Comment by lipangit** [comment]
On the bases of jc_layout_standard.xml in version 5.4

**Comment by ivanviragine** [comment]
@lipangit I'm not sure if I know what you meant in your last message...

**Comment by lipangit** [comment]
@ivanviragine :)

**Comment by lipangit** [comment]
just check jc_layout_standard.xml
