### ISSUE TITLE
5.4点击全屏横屏后崩掉

### ISSUE THREAD

**Issue by qmy1990** [lipangit/JieCaoVideoPlayer#652]
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err: java.lang.IllegalStateException
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at android.media.MediaPlayer.getDuration(Native Method)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getDuration(JCVideoPlayer.java:731)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.setProgressAndText(JCVideoPlayer.java:741)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.setProgressAndText(JCVideoPlayerStandard.java:294)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask$1.run(JCVideoPlayer.java:706)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at android.os.Looper.loop(Looper.java:136)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5120)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
02-02 09:59:25.623 22897-22897/com.dsrc.stardaily W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by lipangit** [comment]
getDuration有问题是不是当前视频播放也有问题。这块也可以单纯try cache一下，但是如果视频播放有问题的话，进了全屏也播放不了。

本质上应该是timer的问题，没能及时关闭，你如果感兴趣可以调试一下这块，看看是哪不能正常关闭timer。

**Comment by dwh178659824** [comment]
只需要在清单文件中加上android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="portrait"就可以了

**Comment by yangyiRunning** [comment]
@dwh178659824  正解，不仅解决了全屏问题，还解决了全屏后继续播放的问题
