### ISSUE TITLE
V5.3在看视频时，播放进去超过加载进度时会报错

### ISSUE THREAD

**Issue by Weststreet** [lipangit/JieCaoVideoPlayer#653]
在看视频时，播放进去超过加载进度时会报错

**Comment by lipangit** [comment]
log是什么

你是说正在prepareing的时候seek进度会报错吗

**Comment by qingyc** [comment]
播放在线视频 缓冲到某个位置就停止缓冲了  然后视频播放到这个停止位置就停止播放了

**Comment by lipangit** [comment]
这个现象不像播放器的问题，需要更多信息才能了解你遇到的问题
