### ISSUE TITLE
请问怎么支持播放https的视频

### ISSUE THREAD

**Issue by mangZengLiao** [lipangit/JieCaoVideoPlayer#655]

**Comment by lipangit** [comment]
直接传参https的视频地址就可以

**Comment by mangZengLiao** [comment]
直接传参https的视频地址试了不行,需要在setDataSource方法之前忽略证书

**Comment by lipangit** [comment]
@mangZengLiao 如何忽略证书

**Comment by mangZengLiao** [comment]
在setDataSource之前设置一下代码:
 try {

                            final TrustManager[] trustAllCerts = new TrustManager[]{
                                    new X509TrustManager() {
                                        @Override
                                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                                        }

                                        @Override
                                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {
                                        }

                                        @Override
                                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                                            return new java.security.cert.X509Certificate[]{};
                                        }
                                    }};
                            // Install the all-trusting trust manager
                            final SSLContext sslContext = SSLContext.getInstance("SSL");
                            sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
                            // Create an ssl socket factory with our all-trusting manager
                            final javax.net.ssl.SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
                            HttpsURLConnection.setDefaultSSLSocketFactory(sslSocketFactory);
                            HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
                                @Override
                                public boolean verify(String hostname, SSLSession session) {
                                    return true;
                                }
                            });
                        } catch (Exception e) {
                            throw new RuntimeException(e);
                        }

**Comment by JoshuaJanJ** [comment]
@mangZengLiao 具体怎么做验证或者直接忽略
