### ISSUE TITLE
Aspect ratio issue

### ISSUE THREAD

**Issue by shahbaz2417** [lipangit/JieCaoVideoPlayer#656]
Aspect ratio is not setting on recyclerview or list. In previous versions that was perfect.

**Comment by lipangit** [comment]
Does it good in the [demo](https://github.com/lipangit/JieCaoVideoPlayer/releases/download/v5.4/jiecaovideoplayer-5.4.apk).

Do you mean jcVideoPlayerStandard_1_1.widthRatio = 1;jcVideoPlayerStandard_1_1.heightRatio = 1;is not work in UISmallChangeActivity in [demo](https://github.com/lipangit/JieCaoVideoPlayer/releases/download/v5.4/jiecaovideoplayer-5.4.apk)?

**Comment by shahbaz2417** [comment]
yes its not working. As well as video is not at all playing in recyclerview in my project. What should be scenario for not playing in recycler

**Comment by ivanviragine** [comment]
Same here...

**Comment by lipangit** [comment]
@ivanviragine this is pure layout problem, you can make some change to fit you project, I do not know your real situation.
