### ISSUE TITLE
UI布局X号应该在父布局右方吧？

### ISSUE THREAD

**Issue by pengfeigao** [lipangit/JieCaoVideoPlayer#658]
今日头条的播放器右上角是X关闭，最新版本的返回按钮和X号都在左边且叠加了
![qq 20170207141059](https://cloud.githubusercontent.com/assets/9261499/22679738/4d7e49c6-ed3f-11e6-89c6-23f398725ecc.png)

**Comment by lipangit** [comment]
兄弟你这用法不对吧，这个X是关闭小窗用的，全屏时候和头条是一样的

**Comment by pengfeigao** [comment]
原来如此......但是我默认不设置地址时候他和那个返回按钮是重合在一起的

**Comment by flyzend** [comment]
这个问题在5.7上面还是存在
