### ISSUE TITLE
Play Local Video File

### ISSUE THREAD

**Issue by avtarsingh1122** [lipangit/jiecaovideoplayer#66]
How can I play local video file stored in sdcard or internal memory of device or in assets of our app ?
I want to play it in fullscreen mode
I am using this code

JCFullScreenActivity.toActivity(MainActivity.this,
    "path_of_local_file.mp4",
    JCVideoPlayerStandard.class,
    "TestApp");

I am trying to pass uri of the path of video "video1.mp4" placed in "raw" directory but it accepts string only
String uriPath = "android.resource://in.example.testapp/"+R.raw.video1;
Uri uri = Uri.parse(uriPath);

**Comment by avtarsingh1122** [comment]
Its solved as "uri.toString"

**Comment by lipangit** [comment]
^_^

**Comment by cywmm** [comment]
is ok?
