### ISSUE TITLE
请问有知道如何设置静音的吗？

### ISSUE THREAD

**Issue by warmcheng** [lipangit/JieCaoVideoPlayer#661]
需要将视频设置为静音，默认静音播放

**Comment by lipangit** [comment]
没研究过相关问题，就是系统MediaPlayer的配置问题，你可以研究一下分享出来

**Comment by ldy441040480** [comment]
/**
     * 开启静音
     */
    public void openVideoMute() {
        if (mMediaPlayer != null) {
            mMediaPlayer.setVolume(0f, 0f);
        }
    }

    /**
     * 关闭静音
     * @param audioManager
     */
    public void closeVideoMute(AudioManager audioManager) {
        if (mMediaPlayer != null && audioManager != null) {
            mMediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            int a = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
            mMediaPlayer.setVolume(a, a);
        }
    }

**Comment by lipangit** [comment]
@ldy441040480 多谢，这版本把这两个方法加进去

**Comment by lipangit** [comment]
@ldy441040480 你在群里吗 给你个管理员

**Comment by ldy441040480** [comment]
不在的~非常感谢你的项目，很不错，也改了很多
