### ISSUE TITLE
How to change color media controller ?

### ISSUE THREAD

**Issue by ridojito** [lipangit/JieCaoVideoPlayer#662]
I'm using JieCaoVideo Player version 4.8.3 and I would like to change color seekbar/slider bar of media controller . But I cannot found the way . Could you help me ?

**Comment by lpflpy** [comment]
public void setSeekbarColor() {
        if (customColor == 0) {
            return;
        }
        //底部进度条的颜色
        if (bottomProgressBar != null) {
            LayerDrawable bottomProgressDrawable = (LayerDrawable) bottomProgressBar.getProgressDrawable();
            ClipDrawable progressDrawable = (ClipDrawable) bottomProgressDrawable.findDrawableByLayerId(android.R.id.progress);
            progressDrawable.setDrawable(new ColorDrawable(customColor));
        }

        if (progressBar != null) {
            //seekbar的颜色
            LayerDrawable seekbarDrawable = (LayerDrawable) progressBar.getProgressDrawable();
            ClipDrawable seekbarClipDrawable = (ClipDrawable) seekbarDrawable.findDrawableByLayerId(android.R.id.progress);
            seekbarClipDrawable.setDrawable(new ColorDrawable(customColor));
        }
    }

**Comment by ridojito** [comment]
Thank you for your respone but  I mean change color of media controller not bottomProgressbar . You can refer this image below
[http://imgur.com/cwIex40](url)

**Comment by lipangit** [comment]
Extends JCVideoPlayerStandard, Override showProgressDialog(), you can design your own progressDialog.

**Comment by ridojito** [comment]
Thank you so much , I did it 👍
