### ISSUE TITLE
MediaPlayer: Error (261,-1008)

### ISSUE THREAD

**Issue by mangZengLiao** [lipangit/JieCaoVideoPlayer#663]
请问这个错误是怎么引起的,要怎么解决

**Comment by lipangit** [comment]
不清楚，MediaPlayer里没有这两个code的代码，具体什么情况

**Comment by mangZengLiao** [comment]
播放的是微信小视频(MP4格式的),不知道微信小视频做了什么特殊的处理,播放就出现MediaPlayer: Error (261,-1008) ,为什么微信的视频播放不了呢?
