### ISSUE TITLE
JieCaoVideoPlayer: onError 1 - -2147483648 [27888034] 

### ISSUE THREAD

**Issue by lpflpy** [lipangit/JieCaoVideoPlayer#665]
小米5手机播放1.4G的大视频时，报错，视频链接为http://172.16.3.93:8888/nccourseserver/ware/0001UU1000000000BOOO.mp4

W/cr.BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 8984
 E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
 E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
 W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
 W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
 E/MediaPlayer: error (1, -2147483648)
 E/MediaPlayer: Error (1,-2147483648)
 E/JieCaoVideoPlayer: onError 1 - -2147483648 [20069325]

**Comment by lpflpy** [comment]
视频的编码格式为H.264，AC3，网上查了上面的(1,-2147483648) 解释为不支持的视频格式，但是三星手机是正常的，小米手机的其他播放器也是可以播放的，不知道问题出在哪里了。。。。

**Comment by lipangit** [comment]
你的视频格式如果不是用户上传的，最好做出让步适应播放器

**Comment by lpflpy** [comment]
简单写了个mediaplayer可以播放1.4g的大视频
用节操的demo就不能播放。。。

**Comment by lipangit** [comment]
不能播放的现象是什么，log是什么

大视频我亲自试过了，在本地机器上部署的tomcat上可以用jcvd播放1.8G的1080P的视频，全屏和seek进度没有问题

**Comment by lpflpy** [comment]
log 在上面写过了，现象是seekbark可以显示视频时长（01:58），但是视频一播放就显示当前进度为01:58
目前小米5是这样的现象，三星手机可以播放视频，但是只有画面，没有声音。。。

**Comment by lpflpy** [comment]
定位到问题，播放视频时报错 E/JieCaoVideoPlayer: onError 1 - -2147483648 [27888034] ，这时候先调用JCMediaManager.onError， 再调用了JCMediaManager.onCompletion，调用onError的时候 setUiWitStateAndScreen(CURRENT_STATE_ERROR),调用onCompletion的时候调用了setUiWitStateAndScreen(CURRENT_STATE_AUTO_COMPLETE)，所以视频当前进度显示最后，而没有显示出错误的感叹号。如果把onError 和onCompletion 中过滤掉2147483648这个错误后，视频可以播放画面，播不出声音。
猜测原因可能是小米5不支持AC3的音频格式。

**Comment by lipangit** [comment]
-2147483648这个是system error，注释的意思好像是版本低

**Comment by jfjbYXY** [comment]
我也遇到同样的问题，视频源890M的大小。
检测到不断打印日志：MediaHTTPConnection: proxy null port 0
不知道和这个有关系吗。。。。。。

Error日志是：
MediaPlayer: Error (1,-2147483648)
JieCaoVideoPlayer: onError 1 - -2147483648 [53789519]

**Comment by zhangshaobo87** [comment]
我也是遇到了这个问题，请问具体该怎么解决呢

E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
E/JiaoZiVideoPlayer: onError 1 - -2147483648 [131445027]

**Comment by lipangit** [comment]
@zhangshaobo87 请到ijkplayer项目中提问，超出本项目解决范围

**Comment by AnYuer** [comment]
JiaoZiVideoPlayer: onError 1 - -1004 [45801592]  大神，报这个错，是什么原因呀？有错误码对照说明吗？谢谢

**Comment by lipangit** [comment]
木有
