### ISSUE TITLE
使用RecyclerView播放视频，视频不能充满屏幕 

### ISSUE THREAD

**Issue by wvisible** [lipangit/JieCaoVideoPlayer#666]
我用RecyclerView播放视频，设置高度200dp，宽度充满屏幕，但是播放的时候，宽度没有充满屏幕，我设置宽高比例1:1，可以充满，但是会调整我的高度大小，我应该怎么设置呢？

**Comment by lipangit** [comment]
你的视频的宽高比是怎样的？如果视频的宽高比是1:1的话你设置高度是200dp两边肯定是黑色的，这没办法。你把布局代码和效果接个图看看吧，现在没法给具体的建议，也可以qq或邮箱发给我

**Comment by wvisible** [comment]
我已经发送到你的邮箱里

**Comment by lipangit** [comment]
你截图看到了，很正常啊，你想要一个正方形的视频充满在长方形的容器里，怎么可能

**Comment by yilylong** [comment]
正想问问 可以设置视频的宽高比吗  不如全屏 自适应 4:3 16:9 等

**Comment by wvisible** [comment]
充满全屏会变形，可以这样设置宽度充满屏幕
`public class MyVideoView extends JCVideoPlayerStandard {
    public MyVideoView(Context context) {
        super(context);
    }

    public MyVideoView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void onVideoSizeChanged() {
        JCMediaManager.textureView.setVideoSize(new Point(DisplayUtil.getScreenW(getContext()), DisplayUtil.dip2px(getContext(), 200)));
    }
}`
