### ISSUE TITLE
想问一下播放视频的时候进入了后台，，怎么让视频暂停啊  回来以后点击在接着播放，因为我看项目中是onPause()中调用的 JCVideoPlayer.releaseAllVideos();这个。。自己怎么实现呢

### ISSUE THREAD

**Issue by Lyl521** [lipangit/JieCaoVideoPlayer#667]

**Comment by yale8848** [comment]
就调用JCVideoPlayer.releaseAllVideos();这个就暂停了，onRestart里在调用jcVideoPlayer.startButton.performClick();就接着播放了么

**Comment by Lyl521** [comment]
JCVideoPlayer.releaseAllVideos();这个不是释放视频资源吗   我想从后台回来接着播放调用那个方法啊

**Comment by Lyl521** [comment]
我现在是onPause()这个方法自己调用你的jcVideoPlayer点击事件的里面的暂停  可是从后台回来再点击播放的时候就是没有画面  只有生意

**Comment by Lyl521** [comment]
我用的不是最新的

**Comment by lipangit** [comment]
这时候surfaceView销毁重建的，需要setSurface一下

**Comment by WooYu** [comment]
if(play && pagenum == mCurPage){
               JCMediaManager.instance().mediaPlayer.setSurface(
                        new Surface(JCMediaManager.savedSurfaceTexture)
                );
                //JCMediaManager.instance().mediaPlayer.start();
 //               videoplayer.startButton.performClick();
            }else{
               // JCMediaManager.instance().mediaPlayer.pause();
//                JCVideoPlayer.releaseAllVideos();
            }
 我用这几种方式切换没效果， @Lyl521你的怎么解决的

**Comment by gaoyuan117** [comment]
@lipangit 没有暂停播放的方法吗？

**Comment by lipangit** [comment]
jcVideoPlayer.startButton.performClick() 模拟点击开始按钮暂停视频
