### ISSUE TITLE
请问一下 我是recyclerview中的一个item用的播放器  进来的时候会出现一下闪屏

### ISSUE THREAD

**Issue by Jevis** [lipangit/JieCaoVideoPlayer#669]

**Comment by lipangit** [comment]
不知道具体是什么样的效果，来个小视频看看效果吧。

demo里有闪屏的问题吗

**Comment by Jevis** [comment]
http://www.17sysj.com/video/lpds_479cee8d6275a   这个是我录屏的一个地址 您看一下  感觉就是类似JCVideoPlayer一加载出来的时候 就会闪一下屏

**Comment by Jevis** [comment]
之后我以为把JCMediaplayer的实例放在了
![image](https://cloud.githubusercontent.com/assets/22912429/22810551/70f3d34e-ef74-11e6-9fcc-04f9641725cf.png)

**Comment by Jevis** [comment]
之后 我把 JCMediaManager.instance();放在了adapter的构造函数中 还是会有
    public RecommendAdapter(RecommendEntity recommendEntity, Context context) {
        this.recommendEntity = recommendEntity;
        this.context = context;
         JCMediaManager.instance();
    }

**Comment by lipangit** [comment]
你的这个闪屏是整个屏幕都闪了一下，不仅是列表，包括actionbar，toolbar也都闪。。感觉不像adapter的问题

**Comment by Jevis** [comment]
我一开始用的是jiecaovideoplayer:3.4 之后改成了jiecaovideoplayer:4.8.3 就解决啦

**Comment by lipangit** [comment]
用5.4
