### ISSUE TITLE
auto close JieCaoVideoPlayer 

### ISSUE THREAD

**Issue by amjad9636** [lipangit/JieCaoVideoPlayer#673]
Hi

I have a problem.. auto close JieCaoVideoPlayer if url stream doesn't work.. I want to get a windows error or message 

how ?

**Comment by lipangit** [comment]
extends JCVideoPlayerStandard {
    @Override 
    onError(){
        //catch error event here
    }
}

**Comment by amjad9636** [comment]
extends JCVideoPlayerStandard {
 
but get Error


public class VideoViewActivity extends JCVideoPlayerStandard {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_view);


        @Override
        public void onError(){
            //catch error event here
        }
    }
}

**Comment by amjad9636** [comment]
how add ?

2017-02-13 12:23 GMT+04:00 Nathen <notifications@github.com>:

**Comment by lipangit** [comment]
What do you want?  you can do you logic in function onError()

**Comment by amjad9636** [comment]
yes ..

this code .. how add function onError()

2017-02-13 18:35 GMT+04:00 Nathen <notifications@github.com>:
