### ISSUE TITLE
if when running player online, press home and back again video not play

### ISSUE THREAD

**Issue by abbasalim** [lipangit/JieCaoVideoPlayer#674]
hello,
if whene running player online, press home and back again video not play

`   @Override
    protected void onPause() {
        super.onPause();
 JCVideoPlayer.releaseAllVideos();
    }`

**Comment by lipangit** [comment]
Yes the design is so.

U can change it by yourself

**Comment by abbasalim** [comment]
but how?

**Comment by lipangit** [comment]
I do not know how to press home and back go on play video , but I know some people made it.
This feature can be done.

**Comment by omuradil** [comment]
It may be no need to call JCVideoPlayer.releaseAllVideos() in onResume?

**Comment by lipangit** [comment]
This is one point.  Come on.
