### ISSUE TITLE
播放中如果切换为wifi，未提示

### ISSUE THREAD

**Issue by parcool** [lipangit/JieCaoVideoPlayer#678]
一进入播放做了检测。如果是播放中再关掉wifi就直接用数据开始放了。。。能加上提示吗？

**Comment by lipangit** [comment]
中途切换有必要加提示吗，目前在prepare的时候检测网络状态，我试试头条怎么做的

**Comment by lipangit** [comment]
哎呀，兄弟，头条在关闭wifi的时候会提示你用流量，我们也跟着考虑添加这个功能了，怎么做你有什么建议吗

**Comment by lipangit** [comment]
并且头条的ui更新了，有时间也更新一下

**Comment by parcool** [comment]
广播监控一下，断wifi后就暂停提示。本来自己也可以做，你里面做好了更方便撒

**Comment by lipangit** [comment]
有道理，这版本加上

**Comment by DoImp** [comment]
怎样用代码隐藏播放按钮？急！急！急！

**Comment by DoImp** [comment]
怎样用代码隐藏播放按钮？急！急！急！ @lipangit

**Comment by lipangit** [comment]
@DoImp 参照demo中smallChangeUiActivity

**Comment by DoImp** [comment]
@lipangit JCVideoPlayerStandard.startButton.setVisibility(View.GONE)不就可以隐藏播放键吗？可是为什么没有效果？有没有类似于这种的简单的一行代码就可以隐藏？

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写setUiWitStateAndScreen函数case 各个状态，修改各个状态的ui
