### ISSUE TITLE
怎么让视频自动播放，循环播放

### ISSUE THREAD

**Issue by fansangg** [lipangit/JieCaoVideoPlayer#68]

**Comment by lipangit** [comment]
可以复写onCompilet();方法，这里能监控到视频停止， 然后再手动开始播放，ivStart.performClick();
这时候会重新加载视频。

MediaPlayer在播放完之后再重新开始好像都要重新加载视频，具体逻辑你是不是想要自动把进度调到最开始

**Comment by lipangit** [comment]
JCMediaManager.intance().mediaPlayer.setLooping(true); 可以循环播放
