### ISSUE TITLE
横竖屏切换时报空

### ISSUE THREAD

**Issue by caozenghui** [lipangit/JieCaoVideoPlayer#680]
JCUtils.getAppCompActivity(getContext()).setRequestedOrientation(NORMAL_ORIENTATION);
我用的不是AppCompatActivity  我看到JCUtils里面有scanForActivity方法  这里为什么不用这个方法？

**Comment by lipangit** [comment]
如果是AppCompatActivity的话actionbar不能隐藏，因为隐藏的api不一样。

你的activity继承什么activity?
