### ISSUE TITLE
Eclipse使用问题

### ISSUE THREAD

**Issue by hm1027** [lipangit/JieCaoVideoPlayer#681]
请问Eclipse该如何使用此库？

**Comment by hm1027** [comment]
解决了，分享下方法：
第一步：将aar文件解压(如不能直接解压，将后缀名改为zip后再解压)
第二步：在解压得到的目录里创建一个libs文件夹，然后将classes.jar文件和jni文件夹下的所有文件移到libs文件夹下
第三步：将proguard.txt文件的内容拷贝到你的项目的proguard-project.txt文件中（若没有proguard.txt文件则跳过这步）
第四步：在解压得到的目录里创建project.properties文件，内容如下：
target=android-22  
android.library=true  
 第五步：删除aapt和jni文件夹以及R.txt和proguard.txt文件
至此一个Eclipse Library项目已经构建完成了，接下来只需打开Eclipse导入项目并在你的项目中配置引用这个项目即可。

**Comment by lipangit** [comment]
恩，建议使用新版5.4
