### ISSUE TITLE
播放本地视频画面卡住

### ISSUE THREAD

**Issue by ZhouHoubin** [lipangit/JieCaoVideoPlayer#683]
版本:
`compile 'fm.jiecao:jiecaovideoplayer:5.4'`
代码:
`JCVideoPlayerStandard.setUp("file:///sdcard/Wildlife.wmv", JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "本地播放");`
操作:
点击播放图标,拖动进度条
问题:
1.拖动进度条后画面卡死
2.进度会自动重置为0并继续,画面依然不动,但是声音依然在播放

视频:https://1drv.ms/v/s!AkUK73gRtD3tgm3MtOwIFofrRa7j

**Comment by lipangit** [comment]
这个问题是普遍的吗，原封不动的demo里的video有这个问题吗，这本地视频和网络也没关系呀。

**Comment by FrankLove** [comment]
@lipangit 有可能是对于这种格式的视频文件解码支持有问题

**Comment by lipangit** [comment]
[支持的格式](https://developer.android.com/guide/topics/media/media-formats.html)都在这了，包含了大部分的视频格式，我们应该向着能播放的视频格式努力
