### ISSUE TITLE
为什么视频经常放一半就卡住不动了！！

### ISSUE THREAD

**Issue by zhouzhipeng** [lipangit/JieCaoVideoPlayer#684]
如题，网络是正常的，返回重新进入，手动拖动到上次卡住的地方又是可以播放的，使用下来发现是会经常性的放一段时间就卡住了，也没有自动重试或者加载

**Comment by lipangit** [comment]
排除网络不稳定的情况，有log吗，有初步的解决思路吗

如果卡主时间过长会进入error状态。
