### ISSUE TITLE
Layout height is not increasing

### ISSUE THREAD

**Issue by RudreshJR** [lipangit/JieCaoVideoPlayer#685]
<fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                    android:id="@+id/custom_videoplayer_standard"
                    android:layout_width="match_parent"
                    **android:layout_height="250dp"**
                    />
How to increase layout height video layout is coming fixed size

**Comment by lipangit** [comment]
android:layout_height="250dp"  it will increaseing height in theory.

In recycleview?

**Comment by RudreshJR** [comment]
I'm using in list view but it is not increasing video player size

**Comment by alaaodeh95** [comment]
@lipangit 
the same issue here , layout_height is fixed in recycler view 
any solution ?
can the height be dynamic depends on the video ?

**Comment by lipangit** [comment]
I did not think about the height dynamic depends on the video, I think dynamic height is not good.
This problem this pure layout problem not video problem, you can made it in your project.

**Comment by RudreshJR** [comment]
Previously i was using  compile 'fm.jiecao:jiecaovideoplayer:4.6.2' in that video was coming full screen
now using compile 'fm.jiecao:jiecaovideoplayer:5.4' video player size was fixed

**Comment by lipangit** [comment]
Show me url I have a try.

**Comment by RudreshJR** [comment]
@lipangit
I'm talking about videoplayer size not  for particular video url
![screenshot_2017-02-21-13-00-23-360](https://cloud.githubusercontent.com/assets/23492635/23155258/ed81b590-f837-11e6-950d-6464a1f45cd2.jpeg)
![screenshot_2017-02-21-13-10-33-247](https://cloud.githubusercontent.com/assets/23492635/23155257/ed7f1e2a-f837-11e6-935c-bd7517ad8c16.jpeg)

**Comment by lipangit** [comment]
I think the bottom picture is regular, set height is 200dp, you can click fullscreen button the video will be full of screen.

**Comment by RudreshJR** [comment]
Im not changing anything in layout xml file..... Im just changing in gradle file.

**Comment by RudreshJR** [comment]
One more problem in 5.5version when we are watching in fullscreen if we change orientation of screen automatically closing video and coming back to previous screen but it is working fine in 4.6.2 version

**Comment by lipangit** [comment]
5.5 and 4.6.2 fullscreen logic is the same, you can see OrientationActivity in demo to get your fullscreen config.

**Comment by thackerronak** [comment]
Hello @lipangit, I'm facing both the case height not increase in listview and if we change orientation in  fullscreen  then screen automatically closing video and coming back to previous screen. 
both the case are mandatory for basic app building. can you please help us to solving out this issue?

**Comment by thackerronak** [comment]
```
2802-22802/com.geekco.flipnpik W/System.err: java.lang.IllegalStateException
04-09 09:17:47.968 22802-22802/com.geekco.flipnpik W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:724)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:473)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:764)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:44)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:824)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.flipnpik.module.user.UserNewsFeedActivity.onPause(UserNewsFeedActivity.java:334)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Activity.performPause(Activity.java:6819)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4489)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.-wrap19(ActivityThread.java)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by thackerronak** [comment]
2802-22802/com.geekco.flipnpik W/System.err: java.lang.IllegalStateException
04-09 09:17:47.968 22802-22802/com.geekco.flipnpik W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:724)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:473)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:764)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:44)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:824)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.flipnpik.module.user.UserNewsFeedActivity.onPause(UserNewsFeedActivity.java:334)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Activity.performPause(Activity.java:6819)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4489)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.-wrap19(ActivityThread.java)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)``

**Comment by thackerronak** [comment]
```
2802-22802/com.geekco.flipnpik W/System.err: java.lang.IllegalStateException
04-09 09:17:47.968 22802-22802/com.geekco.flipnpik W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:724)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:473)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:764)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:44)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:824)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.flipnpik.module.user.UserNewsFeedActivity.onPause(UserNewsFeedActivity.java:334)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Activity.performPause(Activity.java:6819)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4489)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.-wrap19(ActivityThread.java)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.os.Looper.loop(Looper.java:154)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-09 09:17:47.969 22802-22802/com.geekco.flipnpik W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by thackerronak** [comment]
```
W/System.err: java.lang.IllegalStateException
at android.media.MediaPlayer.getCurrentPosition(Native Method)
  at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:724)
 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:473)
 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.onCompletion(JCVideoPlayerStandard.java:764)
 at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:44)
at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:824)
 at com.flipnpik.module.user.UserNewsFeedActivity.onPause(UserNewsFeedActivity.java:334)
 at android.app.Activity.performPause(Acativity.java:6819)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
 at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3740)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3717)
   at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3691)
   at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4489)
    at android.app.ActivityThread.-wrap19(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
  at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
 at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by lipangit** [comment]
@thackerronak Do you want landscape when fullscreen?

**Comment by thackerronak** [comment]
@lipangit Yes

**Comment by thackerronak** [comment]
@lipangit I have two devices one is samsung galaxy s5 in the list view size showing fixed 200dp and in another one lenovo phab 2 showing dynamic size what i have set. So how can i resolve this isssue?
