### ISSUE TITLE
How to hide components and always playing in FullScreen Mode?

### ISSUE THREAD

**Issue by omuradil** [lipangit/JieCaoVideoPlayer#686]
How to hide all components of video management software (such as start, pause, etc.) and was always fullscreen, that is, even if the video will end still did not react? well, to always play the video list, and it was impossible to control buttons.

I'm at the end of another video automatically inserted and playing, but after the first video bottom progressbar remains at 100% and does not change. And if you click on the screen,
at once a black screen with the play button, and the video plays in the background, how to fix it?

**Comment by lipangit** [comment]
Hide all components : 
```
extends JCVideoPlayerStandard {
  @Override 
  setUiWitStateAndScreen(){
    super.setUiWitStateAndScreen()
    //This function control all components visibility
  }
}
```

second paragraph do you mean you want to play two videos in the same JCVideoPlayerStandard layout?

Is your mother language English, do you have interest in make readme in native English.

**Comment by omuradil** [comment]
English I'm not a native language. Yes, I want to auto play 2 or more files, the list can be changed dynamically ...

**Comment by omuradil** [comment]
```
public void initViews(View view) {
        videoPlayer = (PLVideoPlayerStandard) view.findViewById(R.id.videoplayer);
        PLVideoPlayer.setJcUserAction(userAction);
}
```

The fact that I call the method playDownloadedFiles() in onEvent On_AUTO_COMPLETE:

PLUserAction userAction = new PLUserAction() {
        @Override
        public void onEvent(int type, String url, int screen, Object... objects) {
            if (type == PLUserAction.ON_AUTO_COMPLETE) {
                playDownloadedFiles();
            }
        }
 };

public void playDownloadedFiles() {
        List<Video> allVideoList = getExistVideoList(videoList);
        if (allVideoList != null && allVideoList.size() > 0) {

            Video video = allVideoList.get(filmNum);
            videoPlayer.setUp("file://" + Application.video_path + video.getName(),
                    PLVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, video.getName());
            videoPlayer.startVideo();
           Toast.makeText(activity, videoPlayer.getDuration(), Toast.LENGTH_SHORT).show();

            if (filmNum != allVideoList.size() - 1) {
                filmNum++;
            } else {
                filmNum = 0;
            }
        }
    }
```

The first time when the call playDownloadedFiles () method works correctly and returns getDuration(). But after completion, I call back playDownloadedFiles () method and the video is played, only getDuration returns 0, SeekBar does not change, that is, stops at 100%. If you click on the screen,
then a black screen with the play button and a black screen but the sound of the video is playing on the background.

**Comment by lipangit** [comment]
Do not write logic in eventListener.

extends JCVideoPlayerStanard{
  //Your logic about video
}

**Comment by omuradil** [comment]
But I also need AppCompatActivity, a how to do without him?

**Comment by lipangit** [comment]
you need AppCompatActivity,Why you do without AppCompatActivity?

If you want to cache video you can compile [this project](https://github.com/danikula/AndroidVideoCache)

**Comment by omuradil** [comment]
If I inherit from JcVideoPlayerStandard, the same can not inherit from AppCompatActivity, no?

**Comment by lipangit** [comment]
Activity JcVideoPlayerStandard inherit from AppCompatActivity， the activity inherit from AppCompatActivity

**Comment by omuradil** [comment]
I forgot to ask about FullScreen Mode.  What I need to write in setUiWitStateAndScreen() method that after playing video, did not change the screen to remain in mode Full Screen?

**Comment by lipangit** [comment]
What you ask, what refrence between setUiWitStateAndScreen and FullscreenMode.
