### ISSUE TITLE
点击视频右下角的全屏按钮，直接以横屏的模式全屏显示视频如何设置？

### ISSUE THREAD

**Issue by liang926** [lipangit/JieCaoVideoPlayer#688]

**Comment by lipangit** [comment]
参照demo，api activity 的origintation，原理差不多，改那两个参数。

**Comment by wangxiaowei000** [comment]
请问能不能具体一点啊？改的是那俩个参数，具体要怎么改啊？

**Comment by lipangit** [comment]
@wangxiaowei000 
![image](https://cloud.githubusercontent.com/assets/2038071/23542453/20343600-0028-11e7-91d2-05f345773c06.png)

这两个变量一个普通状态下的屏幕方向，一个全屏状态下的屏幕方向
