### ISSUE TITLE
无法全屏

### ISSUE THREAD

**Issue by zhaoxiuyu** [lipangit/JieCaoVideoPlayer#69]
小米手机  ，无法全屏，

**Comment by lipangit** [comment]
我的是小米note 3 可以全屏，你的具体什么症状，全屏之后有图像吗，有声音吗

**Comment by lipangit** [comment]
#77 把代码发过来我调试一下也行，全屏的问题非常重要

**Comment by zhaoxiuyu** [comment]
代码就是从你GitHub上面下载的，没有改动什么东西。你可以找个红米二 试试看

在 2016-05-10 14:41:37，"Nathen" <notifications@github.com> 写道：


#77 把代码发过来我调试一下也行，全屏的问题非常重要

**Comment by lipangit** [comment]
我们这有小米2A 红米note3，都能正常进入和退出全屏，你那具体有什么症状呢

**Comment by lipangit** [comment]
有log吗

**Comment by lipangit** [comment]
顶住，同学
