### ISSUE TITLE
未播放情况下，显示的图，能不能直接从视频提取首帧？不用再配置一张图传入

### ISSUE THREAD

**Issue by cocosjiang** [lipangit/JieCaoVideoPlayer#691]
如题？

**Comment by lipangit** [comment]
够呛，你可以研究一下然后分享出来。

**Comment by sujianqingfeng** [comment]
我记得问题里面有一个解决办法    
MediaMetadataRetriever media = new MediaMetadataRetriever();
                        media.setDataSource(s, new HashMap<String, String>());
                        Bitmap  bitmap= media.getFrameAtTime();

**Comment by lipangit** [comment]
@sujianqingfeng 试过一次，网络视频好像取不到，setDataSource这行会报错。

**Comment by sujianqingfeng** [comment]
我没有报错。。。。

**Comment by yizuochengchi** [comment]
请问你是怎么解决的？

**Comment by lipangit** [comment]
@sujianqingfeng 哥们能把你取得网络视频缩略图的demo给我发一份研究一下吗

我之前弄过但是网络的就报错，取得不到图像

**Comment by pahoehoe** [comment]
你是想显示网网络视频的缩略图吗？

#获取网络视频缩略图的[方法](http://blog.csdn.net/ydcool/article/details/20926715)

#可以使用上述方法[结合Glide](http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0927/3521.html)来显示图片，这样就不用去处理内存溢出图片缓存等问题了。

@lipangit @yizuochengchi 
@sujianqingfeng

**Comment by lipangit** [comment]
这个试过，但是在我的手机上没成功取得缩略图，你测试的结果是怎么样的@pahoehoe

**Comment by o199666** [comment]
列表情况，获取第一帧视频图片是真的卡。方法都试过了。不好用。
