### ISSUE TITLE
清单文件合并失败

### ISSUE THREAD

**Issue by pencilso** [lipangit/JieCaoVideoPlayer#692]
通过gridle集成的，在build的时候，提示清单合并失败，建议将JieCaoVideoPlayer的清单文件清空掉，
只留manifest节点，Application也删掉。
后来我创建了一个moudle，把代码导入过来。清空清单文件内容，然后添加依赖，build成功。

**Comment by lipangit** [comment]
有道理

删掉application需要留下uses-permission

**Comment by lipangit** [comment]
fix in e4d4e9d

**Comment by pencilso** [comment]
什么鬼

**Comment by lipangit** [comment]
删除库项目manifest下的application节点
