### ISSUE TITLE
能不能把这个播放器支持的在线视频格式给列出来

### ISSUE THREAD

**Issue by FrankLove** [lipangit/JieCaoVideoPlayer#693]
1、能不能把这个播放器支持的在线视频格式给列出来
2、这个播放器支持rtmp 直播流吗
3、为什么这个工程无法导入android studio ，我的是2.1.2版本。导入的时候一直卡在build info这个进度条这

**Comment by lipangit** [comment]
1. https://developer.android.com/guide/topics/media/media-formats.html
2. 不支持
3.我感觉studio版本和导入项目没关系，我一直用stable的最新版，现在2.2.3

**Comment by shaobin0604** [comment]
@FrankLove 
3. 估计是在下载 gradle, 使用命令行 ./gradlew task 看输出什么东西
