### ISSUE TITLE
fill screen 

### ISSUE THREAD

**Issue by amjad9636** [lipangit/JieCaoVideoPlayer#694]
close

**Comment by lipangit** [comment]
视频会变形的

**Comment by amjad9636** [comment]
No problem, but how?

**Comment by lipangit** [comment]
```
extends JCVideoPlayer{
  @Override
  onVideoSizeChanged(){
    //you can get video real size here
    //then set size you want
  }
}
```
You can see black on top and bottom in the video, the black is a part of the video, Video also has problem.

**Comment by amjad9636** [comment]
i want fill full screen .. 

can write full code

**Comment by lipangit** [comment]
I will tell you your shortcut is good effect. you do not need to change .

**Comment by amjad9636** [comment]
don't work :(


  @Override
  onVideoSizeChanged(){
    //what write here     
  }
}

i want fill for all device

**Comment by lipangit** [comment]
How is it going

**Comment by amjad9636** [comment]
you have skype ?

**Comment by lipangit** [comment]
No,  we use Wechat, skype need to spend money.
