### ISSUE TITLE
能不能把支持播放格式给列出来

### ISSUE THREAD

**Issue by bigzhulove** [lipangit/JieCaoVideoPlayer#697]
1：这个网址打不开https://developer.android.com/guide/topics/media/media-formats.html
2：哪位好心人把所以支持格式给切割图或者复制一下，非常感谢！！！！！！！！！

**Comment by Droidin** [comment]
![fireshot capture 1 - supported media formats i android deve_ - https___developer android com_guide_2](https://cloud.githubusercontent.com/assets/16255157/23155940/c0df2c1c-f84f-11e6-8f00-df2ff49a260f.png)

**Comment by bigzhulove** [comment]
非常感谢，还有一个小疑问，您上面截图中，我看到有音频，视频，图片三种格式显示了分别支持哪些，比如音频WAV，上面写有支持，我用节操播放器，是否就能实现给个url在线听到音频那？

**Comment by lipangit** [comment]
这里有有就能播，不用试
