### ISSUE TITLE
5.5 部分机型播放m3u8无法播放 

### ISSUE THREAD

**Issue by daobao** [lipangit/JieCaoVideoPlayer#698]
目前看到的有4.3 4.4.2 4.4.4   手机 红米1s vivoX3play OPPO R7S 酷派y90 目前测试的是5,.0下会出现这样的问题

**Comment by lipangit** [comment]
应该是安卓系统的锅

**Comment by jyh149129** [comment]
我这里也是，红米4.4系统无法播放，5.0正常，hls流
