### ISSUE TITLE
全屏返回时，图像没有变化，虽然在播放

### ISSUE THREAD

**Issue by MycroftWong** [lipangit/JieCaoVideoPlayer#70]
- 全屏返回时，图像没有变化，虽然在播放

正在播放视频，点击全屏，返回时进度条仍然在走，但是图像是视频第一帧，并没有在播放

**Comment by lipangit** [comment]
你用的播放器是什么版本，请下载最新的3.0版本
或者录个几秒钟的小视频，我的微信是 lipanhelloworld
要么把代码打包过来我调试一下

**Comment by MycroftWong** [comment]
- 2.0版本在断网的时候会出现崩溃

- 正好前段时间看到你升级了，所以我也更新到了3.0的版本，但是刚才发现这个问题。稍等，我给你发视频吧
