### ISSUE TITLE
Exo版本的后续还会支持么？

### ISSUE THREAD

**Issue by Weststreet** [lipangit/JieCaoVideoPlayer#702]
感觉Exo播放的效果好很多

**Comment by lipangit** [comment]
哪些好处，请列举出来

**Comment by Weststreet** [comment]
@lipangit 1.Exo的适配好很多，非exo在某些机型上无法播放视频。2.播放视频出错方面exo也会好很多，非exo经常会出现播放一半就出错的情况。3.加载视频启动速度exo也会好一些。

**Comment by lipangit** [comment]
第一条对m3u8支持非常差，有的能播有的不能播。
第二条不以为然，我觉得系统的MediaPlayer更稳定些
第三条没错，ijkplayer的prepare比exoplayer还快

你要播放什么格式的视频？

**Comment by Weststreet** [comment]
@lipangit 主要是播放微博小视频

**Comment by lipangit** [comment]
听我的没问题，用5.5

**Comment by Weststreet** [comment]
@lipangit 嗯 我用了5.5的版本，用户反馈还是有问题，有些机型无法播放视频，点进去就回自动退出，（比如htc m8），然后我换成exo的就可以了

**Comment by lipangit** [comment]
能知道log吗

**Comment by Weststreet** [comment]
@lipangit umeng没有抓到相关log，要不我就直接反馈了

**Comment by lipangit** [comment]
好吧，你也帮忙研究研究
