### ISSUE TITLE
在listview中使用，播放完成后item的点击事件被屏蔽了

### ISSUE THREAD

**Issue by yilylong** [lipangit/JieCaoVideoPlayer#704]
测试在未播放前，播放中，item的点击事件可以响应。当视频播放完成后item的点击事件无响应。

**Comment by lipangit** [comment]
你描述的现象无法用科学解释，我司项目也有itemclick并无屏蔽现象

可以断点一下是不是item的点击事件被set null了

**Comment by yilylong** [comment]
用demo测试过确实有 同一个item播放完成后不点击其他item的播放 这个item的点击就没效果了，重新点击播放按钮播放后 又恢复了


发自网易邮箱 iPhone 版
在2017年02月24日 16:44，Nathen 写道：

你描述的现象无法用科学解释，我司项目也有itemclick并无屏蔽现象

可以断点一下是不是item的点击事件被set null了

**Comment by lipangit** [comment]
是不是缩略图的点击事件影响了item的点击事件。

demo的列表里都是都是充满item的，应该相应不到item的点击，发个小视频看看效果吧，qq、邮箱都行

**Comment by yilylong** [comment]
是的demo是item只有一个player充满了，然后我加了一个textview上去留出了空隙。你可以随便加个控件上去试下


发自网易邮箱 iPhone 版
在2017年02月24日 19:21，Nathen 写道：

是不是缩略图的点击事件影响了item的点击事件。

demo的列表里都是都是充满item的，应该相应不到item的点击，发个小视频看看效果吧，qq、邮箱都行

**Comment by lipangit** [comment]
真有这个问题，我研究一下

**Comment by lipangit** [comment]
节操精选app就没有这个问题，你可以试一下

**Comment by lipangit** [comment]
非常奇怪, 有时候还有点一次不响应onItemclick，再点几次才相应itemclick的情况

节操精选app就没这个问题，我什么也没做

我新建了分支，你可以帮着研究一下。 OnItemClickBug 分支

**Comment by yilylong** [comment]
可能是底部的进度条那一栏的控件抢占了焦点 只要下面的那一栏显示 item就无法点击 隐藏后就能点击了。

**Comment by yilylong** [comment]
在jc_layout_standard.xml 加上 android:descendantFocusability="blocksDescendants" 这句

**Comment by lipangit** [comment]
@yilylong 妙哉!!
