### ISSUE TITLE
How to play other video when video is playing

### ISSUE THREAD

**Issue by ridojito** [lipangit/JieCaoVideoPlayer#707]
As title , when video is playing , I want to use Action.Move to rewind video , and videoPlayer will play other video . How to make that ?

**Comment by lipangit** [comment]
We should have patient，I want to know what is your question.

MediaPlayer is single instance,  and video play auto complete it will stop and can not play other video automaticly

 what reference between rewind video and play other video?

**Comment by lipangit** [comment]
Is English your mother language can you help me to improve readme.md.

**Comment by ridojito** [comment]
it means that when I rewind the video, I can pass one another and play 1 video url others. 
Such as when I see  live video I cannot rewind this, but when I used to rewind action.move gesture will transmit to one another url for mediaplayer and it will play one another for my live video  .
