### ISSUE TITLE
Pass header data

### ISSUE THREAD

**Issue by mchenani** [lipangit/JieCaoVideoPlayer#71]
Hi and thanks for this great library, I want to path token in headers for authentication. I this any way to do it in your lib? thanks

**Comment by lipangit** [comment]
This library use android.media.MediaPlayer to play video.
I don't know how to path token to MediaPlayer.

It is glad to tell us what do you think about this.

**Comment by lipangit** [comment]
http://stackoverflow.com/questions/8959300/how-do-i-include-http-headers-with-mediaplayer-setdatasource

I will learn from that page , next version will add this function.

Thank you your question.

**Comment by amspayam** [comment]
hi thanks for your library , i want to add token as header too but your library dosnt support it yet, please do something about it
