### ISSUE TITLE
Play portrait video in fullscreen

### ISSUE THREAD

**Issue by shrivastavaanurag** [lipangit/JieCaoVideoPlayer#710]
Hello JieCao

In my android app i recorded a video in portrait mode, and want to play it in landscape mode. But the issue is, it leave some blank space on either sides of video. is there any method that i can fit this video to the screen. thanks in advance.

**Comment by lipangit** [comment]
Video will auto fit the screen. Yours situation is bug.

onVideoSizeChanged() in JCVideoPlayer.java this methods can get video real size of the video, then change textureview size, you can reference it.

**Comment by lipangit** [comment]
Is your mother language English, can you help to improve readme.md.

**Comment by sanurag51** [comment]
yeah sure.

**Comment by lipangit** [comment]
Nice

You can change every thing make English native
