### ISSUE TITLE
如何去除图片黑边？

### ISSUE THREAD

**Issue by QueryGad** [lipangit/JieCaoVideoPlayer#714]
JCVideoPlayer.setThumbImageViewScalType(ImageView.ScaleType.FIT_XY);网上搜到的是这种方法但是版本用的不一样我用的是5.5该用哪种方法去除黑边？

**Comment by lipangit** [comment]
JCVideoPlayer.thumbImage.setScalType(ImageView.ScaleType.FIT_XY)

缩略图的imageview是public的可以拿到
