### ISSUE TITLE
关于全屏状态栏

### ISSUE THREAD

**Issue by mjbstc** [lipangit/JieCaoVideoPlayer#715]
1.进入视频播放页，该Activity设置为 android:screenOrientation="landscape"和getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);这样该页就是横向全屏并且无状态栏了。
按播放键播放视频，视频播放完毕，此时，再按播放，系统的状态栏就出现了，求教！
2.如何隐藏底部的进度条？

**Comment by lipangit** [comment]
1.你想要什么效果，demo里有吗

2.继承JCVideoPlayerStandard，复写setUiWitStateAndScreen函数，分别设置各个state是否显示进度条
