### ISSUE TITLE
高度设置无效问题的解决方法

### ISSUE THREAD

**Issue by XXiaoQing** [lipangit/JieCaoVideoPlayer#716]
以前的版本采用 后台返回视频的宽高，手机端进行等比例拉升，最近发现视频列表中视频都是一个高度了，各种设置都是没有用的，看源码发现  在 JCVideoPlayer  中 onMeasure 中进行了处理，这个感觉不太友好，
建议加个设置提醒什么的，  

解决方法：复写 onMeasure  _方法，`
      @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        widthRatio = 0;
        heightRatio = 0;
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }`

**Comment by yilylong** [comment]
嗦嘎难怪我设置宽高没有用
