### ISSUE TITLE
Android MediaCodec硬解，视频退后台，再恢复到前台，黑屏或花屏

### ISSUE THREAD

**Issue by wutongluxjtu** [lipangit/JieCaoVideoPlayer#717]
请问如何解决？

**Comment by lipangit** [comment]
后台运行的时候TextureView或SurfaceView的surface会销毁，恢复到前台会重新create，此时要重新setSurface

**Comment by wutongluxjtu** [comment]
@lipangit 是要重新setSurface.  但是并没有解决切回到前台后 黑屏或花屏 问题啊

**Comment by lipangit** [comment]
没遇到过，项目里全屏的过程就是重新setSurface的过程，和退到后台再恢复到前台的过程如出一辙，没有黑屏或花屏的问题。

**Comment by wutongluxjtu** [comment]
@lipangit 压到后台setSurface(null), 恢复到前台，setSurface( new_surface ). 只使用setSurface的话，底层MediaCodec会reconfig，此时MediaCodec buffer会clear掉，紧接着的解码会由于没有参考帧而花屏，同时在reconfig阶段会黑屏. https://github.com/Bilibili/ijkplayer/issues/1324

**Comment by bingxuebage** [comment]
@lipanggit  
在JCMediaManager  里HANDLER_PREPARE 里new IjkMediaPlayer()后添加
“ mediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "mediacodec-all-videos", 1 );”
Android MediaCodec硬解打开
demo全屏和返回视频时就黑屏花屏了！

**Comment by lipangit** [comment]
@bingxuebage 如果是视频点播的话建议用v5.5.2版本

**Comment by ranchohxk** [comment]
@bingxuebage @wutongluxjtu  这个最后采用什么方案解决的呢
