### ISSUE TITLE
How To Stop the video player?

### ISSUE THREAD

**Issue by omuradil** [lipangit/JieCaoVideoPlayer#718]
How to stop the video by click Stop button?

**Comment by lipangit** [comment]
jcVideoPlayerStandard.startButton.performClick();

**Comment by lipangit** [comment]
Is your mother language English , Could you help me to make readme.md int native English.

**Comment by omuradil** [comment]
I'd love to, but I write with the help of Google Translator :)

**Comment by omuradil** [comment]
Thank You for answer. One moment, performClick - isStop or Pause. That is, the video progress is will reset?

**Comment by lipangit** [comment]
Maybe is bug, the video progress have no relationship with stop or pause, It should not affected by it.
