### ISSUE TITLE
全屏怎么这只为横屏？

### ISSUE THREAD

**Issue by wangxiaowei000** [lipangit/JieCaoVideoPlayer#719]
点击视频右下角的全屏按钮，怎么让全屏是横屏的啊！具体怎么设置？

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/23542435/0583037c-0028-11e7-8401-efe4d487f76d.png)
修改这个变量

**Comment by wangxiaowei000** [comment]
你好，不知道你测试过没有，这个参数改完之后是有问题的，点击全屏之后视频没有继续播放，而且点击播放按钮又退出了全屏，不知道是不是我这个参数改变的有问题。

**Comment by lipangit** [comment]
参照ApiActivity-》origintationActivity，这里有这两个参数的使用。

**Comment by wangxiaowei000** [comment]
![image](https://cloud.githubusercontent.com/assets/19278475/23640198/136e809a-0327-11e7-891e-c380759b3854.png)
大哥，你说的是这俩个参数吧？但这不是我想要的效果啊！我要的是半屏的时候是竖屏，而全屏的时候是横屏并且继续播放，你说的这俩个参数改完之后第一次全屏是吧屏幕变成横向的了，然后再点一次全屏才起作用。

**Comment by yangyiRunning** [comment]
@wangxiaowei000  我现在也想实现你这样的效果，发现了和你同样的问题，请问你最终的解决方案是什么？

**Comment by wangxiaowei000** [comment]
@yangyiRunning 
![image](https://cloud.githubusercontent.com/assets/19278475/25731490/622d0cf8-3179-11e7-8e09-e14da65a5465.png)就加上这句就好了，和上面作者说的一样

**Comment by TracyEminem** [comment]
我加上那句话后，点进去全屏了，但是没有播放，点播放按钮就推出了

- 

-
