### ISSUE TITLE
auto close after click window error

### ISSUE THREAD

**Issue by mrbala4** [lipangit/JieCaoVideoPlayer#723]
Hi

Problem: after click window or icon error.. the window close.. 

![screenshot_ -](https://cloud.githubusercontent.com/assets/26039102/23589620/bfa8308e-01e9-11e7-9589-191a9a6839a0.png)

I want after click window error tries replay video .. how ?

I add this @Override in JCVideoPlayerStandard 

 @Override
    public void onError(int what, int extra) {
        super.onError(what, extra);

but same problem .. close window

**Comment by lipangit** [comment]
Do you mean you click the error in fullscreen, the window will close.

I will try to test it then answer you.

**Comment by mrbala4** [comment]
yes .. 

Ok .. I am waiting for you

**Comment by mrbala4** [comment]
hi .. done solve ?

**Comment by lipangit** [comment]
do not worry
