### ISSUE TITLE
Auto Start Video, Hide Full Screen Button, On Complete Close Activity

### ISSUE THREAD

**Issue by SopMar** [lipangit/JieCaoVideoPlayer#725]
Here is the code, which I am using to play Video from SD Card, In Manifest, I am using orientation as landscape... 

```
<activity android:name=".VideoPlayerActivity"
            android:configChanges="orientation|screenSize|keyboardHidden"
            android:screenOrientation="landscape"
            android:theme="@style/AppTheme.NoTitle"
            android:launchMode="singleTop">
```

In VideoPlayerActivity.java, I am using following code:

```

public class VideoPlayerActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player);

        String fileName = "toystory.mp4";
        String completePath = Environment.getExternalStorageDirectory() + "/Download/" + fileName;

        JCVideoPlayerSimple jcVideoPlayerSimple = (JCVideoPlayerSimple) findViewById(R.id.custom_videoplayer);
        jcVideoPlayerSimple.setUp(completePath);

    }

}
```

Now, I would like to do _3 major improvements_ in my program, like:
1. Auto start video (without doing tap on start button)
2. Want to hide full screen button
3. On complete want to close the Activity

**Note:** I do not want to use `JCFullScreenActivity` because as I wrote above, I want to exit Activity, once user do tap on back, but I am unable to do same with `JCFullScreenActivity`

**Comment by lipangit** [comment]
1.jcVideoPlayer.startButon.performClick() simulator user click startbutton.
2.create class extends JCVideoPlayerStanard Override setUp(), hide fullscreen button
3.create class extends JCVideoPlayerStanard Override onComplete(), close activity

**Comment by prateek54** [comment]
hey @lipangit  can you help me with https://github.com/lipangit/JiaoZiVideoPlayer/issues/2136
