### ISSUE TITLE
compile 导入失败 我需要去哪里 修改配置呢?

### ISSUE THREAD

**Issue by hongyang51** [lipangit/JieCaoVideoPlayer#727]
Error:Could not find jiecaovideoplayer.jar (fm.jiecao:jiecaovideoplayer:5.5.1).
Searched in the following locations:
    https://jcenter.bintray.com/fm/jiecao/jiecaovideoplayer/5.5.1/jiecaovideoplayer-5.5.1.jar

**Comment by bigtotorouk** [comment]
i have the same err. i think should try early version.

**Comment by hongyang51** [comment]
@bigtotorouk   ok thanks !   I download the source code for compilation.
