### ISSUE TITLE
setUp 第三个参数 objects..... BUG

### ISSUE THREAD

**Issue by hongyang51** [lipangit/JieCaoVideoPlayer#728]
如果 不输入只写前面两个参数, 会导致 返回箭头 跟 ✘ 永久显示 并且 放大 缩小 不动态变化. 

建议 JCVideoPlayerStandard  setUp 中的 ` if (objects.length == 0) return; `改为` if (!(objects.length == 0)) `执行下面的 方法

**Comment by lipangit** [comment]
第一个参数是url，第二个参数表示视频在列表里，还是全屏，这两个参数必须有，操作视频的过程会调用第二个参数的

**Comment by hongyang51** [comment]
@lipangit  恩 谢谢您的讲解 .  我刚才测试了 将 第三个参数  设置 title 这个 不填写 确实 会出现以上情况  填写了""  之后就 箭头 八叉都消失  并且 放大缩小正常..

**Comment by hongyang51** [comment]
@lipangit   相对于一些 不需要 视频title 的这种 按现在的 逻辑 只能后面加一个  ""  设置title 了 .

**Comment by hongyang51** [comment]
@lipangit 还有就是 最新的  5.5.1  无法通过 compile 方式 引入 可能最新版 还未被收录? 还是 未提交成功? 4.7.0 没有问题 可以引入

**Comment by lipangit** [comment]
5.5.1不知道maven仓库怎么回事，已经上传了但gradle引入有问题

**Comment by lipangit** [comment]
可以将title设为“”
