### ISSUE TITLE
5.5.2报错

### ISSUE THREAD

**Issue by z376368673** [lipangit/JieCaoVideoPlayer#731]
![default](https://cloud.githubusercontent.com/assets/21307181/23783118/f7f436d8-0593-11e7-83f3-baf62519cab9.png)
不知道怎么解决

**Comment by lipangit** [comment]
你引用了百度的什么包，有时间我试试

**Comment by z376368673** [comment]
老实说这个项目里面引入了很多乱七八糟遭的东西 ，还可能是你把编译SDK设的太高（25），而我的项目以前只有24，为了引入你的才改成25 ，很可能是这方面的原因，而我用你的3.3版的就没有错误

**Comment by lipangit** [comment]
编译版本就是跟着google官方发布的稳定版本升级的，这问题还没解决吗

**Comment by Chenhengquan** [comment]
在4.7.2版本升级到 5.5.2 我也是这个错误，请问有什么好的解决方法吗

**Comment by lipangit** [comment]
把build.gradle里涉及的环境的版本和jcvd一样，jcvd就是及时更新google发布的stable版本
