### ISSUE TITLE
ProgressTimerTask导致内存泄露

### ISSUE THREAD

**Issue by sujianqingfeng** [lipangit/JieCaoVideoPlayer#733]
我是在fragment 调用全屏返回 ProgressTimerTask泄露 有些大4-5M

**Comment by lipangit** [comment]
这个问题有点严重，能提个pr帮忙修改一下吗，我也持续关注这个问题

**Comment by Weststreet** [comment]
@sujianqingfeng 播放完成取消task即可

**Comment by lipangit** [comment]
@Weststreet 对

**Comment by sujianqingfeng** [comment]
不好意思 前两天有些忙 我现在改了下 你看行不
