### ISSUE TITLE
直播流是宽屏的，播放出来是窄屏的

### ISSUE THREAD

**Issue by i2863CookieZJ** [lipangit/JieCaoVideoPlayer#735]

**Comment by lipangit** [comment]
来个截图看看吧

**Comment by i2863CookieZJ** [comment]
![qq 20170315112831](https://cloud.githubusercontent.com/assets/23622439/23936356/a0cae634-098c-11e7-8d52-818e0e7143a1.jpg)
![qq 20170315112928](https://cloud.githubusercontent.com/assets/23622439/23936355/a0c2bcde-098c-11e7-939d-f0344d7323e9.jpg)

**Comment by i2863CookieZJ** [comment]
ios和安卓获取同样的流，播放一宽一窄

**Comment by lipangit** [comment]
发现安卓的视频被挤压了，继承JCVideoPlayerStandard 复写onSize()函数，可以取得MediaPlayer传回来的视频大小，然后修改TextureView的大小，断点看看这个过程有什么问题

**Comment by i2863CookieZJ** [comment]
是onSizeChanged()吗？没有发现onSize方法

**Comment by lipangit** [comment]
是你说的那个

**Comment by i2863CookieZJ** [comment]
怎么改，JCMediaManager.textureView.setVideoSize(JCMediaManager.instance().getVideoSize());是这么用吗

**Comment by lipangit** [comment]
这个调试一下videoSize的高和宽，看看这个视频设置成多少合适

**Comment by i2863CookieZJ** [comment]
已解决，覆写onchangedsize(),注释掉super就可以了

**Comment by lipangit** [comment]
原因是什么，mediaPlayer返回的宽高不正确吗
