### ISSUE TITLE
能支持https的视频播放吗

### ISSUE THREAD

**Issue by newer-android** [lipangit/JieCaoVideoPlayer#736]
将地址换成https webview可以播放，但是使用这个提示错误

**Comment by lipangit** [comment]
什么错误，记得有issue提到了不验证https的解决办法

**Comment by DnAGroup** [comment]
Hi, I have the same problem. Here is what I get

Couldn't open https://tempry.co/api/data/post/video/567/video.mp4: java.io.FileNotFoundException: No content provider: https://tempry.co/api/data/post/video/567/video.mp4
05-13 23:06:21.482 4582-4582/com.tempry D/MediaPlayer: setDataSource IOException | SecurityException happend
