### ISSUE TITLE
demo  列表  JCVideoPlayerStandard 复用问题

### ISSUE THREAD

**Issue by XXiaoQing** [lipangit/JieCaoVideoPlayer#737]
当第一个位置的  JCVideoPlayerStandard  加载出错出现  error 图标  ，往后滑动，复用这个  item的时候，还是显示  error 图标，正常应该只显示  start和 thumbImageView

**Comment by lipangit** [comment]
怎么可能，复用的时候直接重新setUp，重新初始化了。

你看看这个时候点击重新播放，他们的url是同一个吗
