### ISSUE TITLE
播放时候出现onError 1 - -1004 [168415800] 

### ISSUE THREAD

**Issue by gangqihong** [lipangit/JieCaoVideoPlayer#739]
有些视频会，有些快进就出现。

**Comment by lipangit** [comment]
保持关注

**Comment by jkdevKK** [comment]
我的也出现了，有些可以放有些不可以，好像是视频格式问题，具体报错为：
`MediaPlayer: error (1, -1004)
MediaPlayer: Error (1,-1004)
JieCaoVideoPlayer: onError 1 - -1004 [1254912680] `
仅供参考

**Comment by yale8848** [comment]
我这边也出现了，是同一个视频，有时候就报这个错，视频地址如下：
http://lftresource-cdn.daoxuehao.com/dxhclass/video/fa6cc8a1013e4df08ece3c1074dcc92f.mp4
继续追踪看看。。。

**Comment by lpflpy** [comment]
遇到了同样的问题，小米手机播放一分多分钟之后出现onError 1 - -1004 [126376750]

**Comment by yale8848** [comment]
去掉error listener就可以正常播放，但是这不是解决之道

**Comment by lipangit** [comment]
@yale8848 http://lftresource-cdn.daoxuehao.com/dxhclass/video/fa6cc8a1013e4df08ece3c1074dcc92f.mp4 这个链接能播，红米note4稳定播放

**Comment by KikisHuang** [comment]
我的也出现了这个 MediaPlayer: error (1, -1004) 的问题，7.0虚拟机、真机都会播放到一半卡住，视频格式是MP4的，换成了mov格式7.0版本就没问题了，但是android 低版本格式mov又不兼容。头疼！

**Comment by lipangit** [comment]
可达鸭 头疼!
