### ISSUE TITLE
如何活动获得播放的第一帧，然后设置成视频列表的图片呢？

### ISSUE THREAD

**Issue by liuxgchi** [lipangit/JieCaoVideoPlayer#741]
请问有没有办法获取视频第一帧，然后把设置成视频列表图片显示呢？谢谢！

**Comment by lipangit** [comment]
没有，系统的提供的方法，取得http链接视频的指定时间的缩略图也不好使

缩略图是自己生成的，和视频是不相关的东西

**Comment by lipangit** [comment]
如果你找到了稳定好用的取得缩略图的方法分享出来吧
