### ISSUE TITLE
请问下如何拿到视频的时长？

### ISSUE THREAD

**Issue by CocoForAndroid** [lipangit/JieCaoVideoPlayer#742]

**Comment by CocoForAndroid** [comment]
我想在onPrepared里拿到视频时长 但是没有找到这个回调？

**Comment by lipangit** [comment]
JCMeidaPlayerManager.instance().mediaPlayer.getDuration(),prepared之后调用

**Comment by CocoForAndroid** [comment]
大神你好，JCVideoplayerStard里哪个方法是触发 JCMediaManager.instance().mediaPlayer.setOnPreparedListener里的onPrepare回调方法呢？
我没有找类似mediaplayer里prepareAsyn这样的方法，谢谢

**Comment by CocoForAndroid** [comment]
大神其实我就想知道JCVideoPlayerStard有Prepared回调吗，我想在它的回调方法里做一些逻辑业务.谢谢

**Comment by lipangit** [comment]
继承JCVidepPlayerStandard 复写onPrepared函数

**Comment by luoxiaojing** [comment]
> 继承JCVidepPlayerStandard 复写onPrepared函数

JCVidepPlayerStandard 这个在哪里啊

**Comment by lipangit** [comment]
jzvdstd
