### ISSUE TITLE
5.5.2 QCMediaPlayer mediaplayer NOT present

### ISSUE THREAD

**Issue by zhangzhichaolove** [lipangit/JieCaoVideoPlayer#743]
目前用4.8.3版本，会有so库，文件大点，用了5.5.2后，不会在apk打包so库，体积小了很多，不过播放一直报错：
03-17 17:31:55.198 13388-13388/com.app.chao.chaoapp E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
03-17 17:31:55.578 13388-14160/com.app.chao.chaoapp E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
03-17 17:31:56.578 13388-14205/com.app.chao.chaoapp E/MediaPlayer: error (1, -2147483648)
03-17 17:31:56.578 13388-14160/com.app.chao.chaoapp E/MediaPlayer: Error (1,-2147483648)
03-17 17:31:56.578 13388-13388/com.app.chao.chaoapp E/JieCaoVideoPlayer: onError 1 - -2147483648 [968382699] 
我的播放地址（在4.8.3能播放）：http://cmcc.ips.cnlive.com/content/movie?contentId=625038788&productid=2028593060&ratelevel=2&devModel=2
用你的地址播放则不会出错。videoplayer.setUp("http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4" , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子闭眼睛");

**Comment by lipangit** [comment]
直播的格式系统播放器支持的不好，我对格式的研究不深，https://developer.android.com/guide/topics/media/media-formats.html，官网明确说支持hls，但是大家都反应问题很大，如果能把这块研究清楚功力肯定非常深厚了。

也可以研究一下集成exoPlayer的5.2.1版本，这个对直播有很好的支持

**Comment by zhangzhichaolove** [comment]
好的，感谢。
