### ISSUE TITLE
5.5.2播放rtsp需要做什么处理呢

### ISSUE THREAD

**Issue by qq574259582** [lipangit/JieCaoVideoPlayer#744]

**Comment by lipangit** [comment]
直接怼url就可以播放 [这是支持的格式](https://developer.android.com/guide/topics/media/media-formats.html)  

https://github.com/lipangit/JieCaoVideoPlayer/issues/745 你那有这个问题吗

**Comment by qq574259582** [comment]
现在还没具体用这个去试 ，只是先确定下，用了在提issue

**Comment by lipangit** [comment]
兄弟 这个提前量可以

**Comment by charmeleon2** [comment]
直接setup放不出来啊，需要做什么处理吗？我用ijk和vlc都能放，不是流的问题
