### ISSUE TITLE
Error issue in some devices

### ISSUE THREAD

**Issue by vishwa11** [lipangit/JieCaoVideoPlayer#745]
In motorola, lenevo, xiaomi  when i launch app first time playing live video stream works well. But after closing app and reopening it doesn't play the live video. It gives error. It works well in samsung devices.
What is the cause of this please provide me solution as soon as possible.
Thank you

**Comment by lipangit** [comment]
If if works well first time , reopen it will also work well logically. what log?
What your video format? Can you show video url?

**Comment by vishwa11** [comment]
# **Following error coming in Huawei at first time playing and also this error come in other device like motorola, lenevo , xioami. But works perfectly in samsung device.**

### I used following url 
## http://playertest.longtailvideo.com/adaptive/bbbfull/bbbfull.m3u8

E/MediaPlayer: Java MediaPlayer currentThread is 1695
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: prepareAsync called in state 0
E/MediaPlayer: EventHandler handleMessage thread id is 1695
E/MediaPlayer: Error (-38,0)
E/JieCaoVideoPlayer: onError -38 - 0 [1105617296] 
E/PushMonitorLog: mHandler,msg.arg1:178

**Comment by lipangit** [comment]
That url works well on my Xiaomi note4. 

You can see in source code 
![image](https://cloud.githubusercontent.com/assets/2038071/24097281/1b82e73e-0da0-11e7-9f98-b5693647c86f.png)

code -38 will not influecnt play video so I ignore it.

**Comment by lipangit** [comment]
If first time play well, you can check onComplete(), if some code in onComplete() let reopen video error.
