### ISSUE TITLE
列表播放时,进入详细页面时不能不间断播放

### ISSUE THREAD

**Issue by satng** [lipangit/JieCaoVideoPlayer#75]
像头条,列表页时播放,点击进入详情页(内容页)新的Activity, 不能做到不间断连续播放.

**Comment by lipangit** [comment]
同学，什么意思，什么需求

**Comment by satng** [comment]
![screenshot_2016-05-13-09-19-55](https://cloud.githubusercontent.com/assets/6063500/15235273/62f36f5c-18ec-11e6-9542-550ad709b2c7.jpg)
![screenshot_2016-05-13-09-20-07](https://cloud.githubusercontent.com/assets/6063500/15235282/73f82946-18ec-11e6-8b18-c1684325b02e.jpg)


这个效果，界面跳转，连续播放。我试图修改一下代码，但还是播放的没有头条这么顺畅。

**Comment by lipangit** [comment]
哦知道你的需求了，你觉的该怎么改

顺畅问题确实没有原版做的好，反汇编也找不到头绪，发现头条操作MediaPlayer都是用message传的消息，可能是解决卡顿的问题，然后全屏切换头条能做到声音不间断，进度很连续，这个目前还做不到。

**Comment by lipangit** [comment]
集成exoplayer就不间断了
