### ISSUE TITLE
全屏播放的情况下，切换视频源报错

### ISSUE THREAD

**Issue by wtwt91** [lipangit/JieCaoVideoPlayer#751]
如题，在全屏播放的情况下，切换视频源，同时startVideo,报错了
`
03-21 00:21:52.039 17543-17543/com.fortune.mobile.unitv W/System.err: java.lang.IllegalStateException
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at android.media.MediaPlayer.getCurrentPosition(Native Method)
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:720)
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:469)
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.prepareMediaPlayer(JCVideoPlayer.java:199)
03-21 00:21:52.040 17543-17543/com.fortune.mobile.unitv W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.startVideo(JCVideoPlayerStandard.java:238)`

请问这个需要怎么解决呢

**Comment by lipangit** [comment]
这个建议断点一下releaseAllVideos()这个函数，getCurrentPositionWhenPlaying()这个函数报错多半是因为在不应该releaseVideo的时候releaseVide，应该会有一些线索
