### ISSUE TITLE
如何关闭全屏按钮

### ISSUE THREAD

**Issue by zj2050** [lipangit/JieCaoVideoPlayer#752]
如何关闭全屏切换？

谢谢

**Comment by lipangit** [comment]
参照smallChangeUiActivity，继承JCVideoPlayerStandard，复写setUiAndStat(具体的名字忘记了)函数，case每个状态，隐藏全屏按钮。

**Comment by zj2050** [comment]
@lipangit  太可怕了，要是能提供一个设置参数就好了

**Comment by lipangit** [comment]
兄弟，所有的控件都要参数控制吗

**Comment by zj2050** [comment]
起始总共也没几个按钮， 控件的作用就是为了方便吗
只是建议，谢谢

**Comment by lipangit** [comment]
恩，我想想
