### ISSUE TITLE
关于是否在使用WiFi观看视频的提示对话框问题

### ISSUE THREAD

**Issue by icefly118** [lipangit/JieCaoVideoPlayer#755]
`if (!url.startsWith("file") && !JCUtils.isWifiConnected(getContext()) && !WIFI_TIP_DIALOG_SHOWED) {
                    showWifiDialog();
                    return;
                }`
Issue 1:
 对于本地视频的判断只依靠url.startsWith("file"), 是否有点局限性, 如果直接遍历SD卡中的视频,通过绝对路径播放本地视频, 在没有连接WiFi时, 可能也会显示该对话框;

Issue 2:
 当WiFi没有连接且移动网络没有开启的情况下, 播放网络视频, 可能也会显示该对话框.

Issue 3: 
  JCUtils.isWifiConnected(getContext())  ACCESS_NETWORK_STATE 在Android6.0 及以上是需要动态申请权限的, 请问该如何处理? 谢谢!

**Comment by lipangit** [comment]
1. 有道理，添加url.startWith("/")也不是显示dialog
2. 你觉得如果wifi和移动数据都没开启该如何显示？
3. 你想解决的问题是什么？如果拒绝一次网络权限，之后的播放视频的请求会没反应是吗？

**Comment by lipangit** [comment]
解决
