### ISSUE TITLE
 prepareVideo()方法中 ifNeedCreateSurfaceView = true

### ISSUE THREAD

**Issue by KateChris** [lipangit/JieCaoVideoPlayer#76]
嗨,大神请救救我,我把demo里jcvideoplayer-lib的整个路径的代码直接拷贝到项目里,接入此项目后有个bug一直复现,我研究了两天一直没弄明白.
当我在listview中的某一条正在播放的视频点击进入全屏,全屏之后会接着之前listview那条视频的进度继续播放,可是当从全屏播放的页面返回后,listview中的那条视频并没有像demo中那样,用退出全屏播放时的进度继续进行播放,而是视频直接被重置了,如果此时点击listview里上下相邻的另一条视频进行播放,会报如下错误:

java.lang.IllegalArgumentException: The surface has been released
                                                                 at android.media.MediaPlayer._setVideoSurface(Native Method)
                                                                 at android.media.MediaPlayer.setDisplay(MediaPlayer.java:695)
                                                                 at com.nfdaily.nfplus.module.video.JCVideoPlayer.prepareVideo(JCVideoPlayer.java:222)
                                                                 at com.nfdaily.nfplus.module.video.JCVideoPlayer.onClick(JCVideoPlayer.java:153)
                                                                 at com.nfdaily.nfplus.module.video.JCVideoPlayerStandard.onClick(JCVideoPlayerStandard.java:114)
                                                                 at android.view.View.performClick(View.java:4488)
                                                                 at android.view.View$PerformClick.run(View.java:18860)
                                                                 at android.os.Handler.handleCallback(Handler.java:808)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                 at android.os.Looper.loop(Looper.java:193)
                                                                 

具体报错代码是这一行:
JCVideoPlayer类里,prepareVideo() 方法中的 JCMediaManager.intance().mediaPlayer.setDisplay(surfaceHolder);

根据 The surface has been released的提示,
我在JCVideoPlayer类中的 prepareVideo()方法里加入了
ifNeedCreateSurfaceView 的打印代码,
发现在报错前, ifNeedCreateSurfaceView = true;
我在demo里看到 ifNeedCreateSurfaceView 并没有实际用到,
故想请教大神,
当 ifNeedCreateSurfaceView = true 时,我该做什么操作来避免bug.

以下是我加入打印日志的 prepareVideo()方法: 
protected void prepareVideo() {
        if (JCMediaManager.intance().listener != null) {
            JCMediaManager.intance().listener.onCompletion();
        }
        JCMediaManager.intance().listener = this;
//        addSurfaceView();
        JCMediaManager.intance().prepareToPlay(getContext(), url);
        if (!IF_CURRENT_IS_FULLSCREEN) {

            LogUtil.d("ifNeedCreateSurfaceView", ifNeedCreateSurfaceView);
            if (ifNeedCreateSurfaceView) {
                surfaceHolder = surfaceView.getHolder();
                surfaceHolder.addCallback(this);
                surfaceCreated(surfaceHolder);
            }
            JCMediaManager.intance().mediaPlayer.setDisplay(surfaceHolder);
        }
        setStateAndUi(CURRENT_STATE_PREPAREING);
}
此方法不能解决问题,只能拜托大神看有没有好的解决办法了,不甚感激.

**Comment by lipangit** [comment]
同学
1.请使用最新3.0版本，用gradle引入，不建议直接拷贝代码，在理念上想让这个代码尽量灵活，不仅能继承JCVideoPlayer，还尽量让变量public，尽量让大家自己就能解决各自的问题。

2.不要在activity的onResume的时候调用setUp，这会重置视频。

3.The surface has been released 这个问题已经在新版添加了特殊判断，会重新生成surfaceview。

4.从全屏返回时可能重置视频的问题也在3.0修改了，如果还有问题请反馈给我。

5.版本3.1会在下礼拜一之前release，添加了手势修改进度和音量功能，也修改了可能导致视频播不了的bug，请及时更新。

**Comment by KateChris** [comment]
@lipangit  嗨,十分感谢回复,我在用gradle引入后,The surface has been released 这个bug已经不再重现;
此时出现了一个新的bug,在全屏切换回来后,listview中的视频会继续接着进度播放了,但是画面会全黑,声音却一直有在播放,请问这是什么原因导致的呢,可有不更新3.1版本就能解决的方法?

**Comment by lipangit** [comment]
这个问题不是每次都出现吧，是概率的吧

断点一下public void surfaceCreated(SurfaceHolder holder) 这个函数，是不是每个setDisplay都没进去

**Comment by KateChris** [comment]
@lipangit  嗨,又来麻烦你了,这个问题的确不是每次出现,概率出现,当从全屏返回后,十次大概有两次是会黑屏,只出现声音.
当黑屏时public void surfaceCreated(SurfaceHolder holder) 这个方法并没有执行,我在里边设置的打印代码也没有输出.

**Comment by lipangit** [comment]
在从全屏返回的时候，surfaceCreated这个方法里会判断是否要setDisplay

surfaceCreated这个方法应该触发的，因为进入全屏的时候原来的surfaceview会distroy，然后surfaceview可见的时候就必须要create

什么手机，这个问题可能一时半会我也不知道怎么办。

**Comment by lipangit** [comment]
你的那个手机跑demo正常吗

**Comment by KateChris** [comment]
测试机型为Oppo R7,系统为4.4.4,跑demo很正常,我要再多测试几次,找下规律,有实质性进展的时候再来请教,今天真的很感谢你哦.

**Comment by lipangit** [comment]
加油啊骚年

**Comment by lipangit** [comment]
来个star吧

**Comment by syMobile** [comment]
您好。请问您的可以播放吗？我下载demo的apk安装到手机上怎么没法播放啊。我也按照步骤自己写了个例子，运行在手机上也是不能播放视频，点击播放后只有缓存圆圈在转动怎么回事啊？求解答

**Comment by KateChris** [comment]
@syMobile  demo可以正常播放的,可以先检测一下网络环境,如果不行再试试加载本地视屏,播放功能在demo上一切正常的哦.

**Comment by KateChris** [comment]
@lipangit  嗨,我又研究了一阵,只有声音,画面黑屏的bug大概是这样的情况,
1. 在全屏页面执行
surfaceDestroyed(SurfaceHolder holder) 的时候BACK_FROM_FULLSCREEN = true,
2. 返回列表视频的时候,surfaceview的回调
surfaceCreated(SurfaceHolder holder) 当中,BACK_FROM_FULLSCREEN = false,
故没有执行surfaceCreated(SurfaceHolder holder)方法中的这句代码:
       if (BACK_FROM_FULLSCREEN) {
            setDisplayCaseFailse();
            BACK_FROM_FULLSCREEN = false;
        }

3. 在把 BACK_FROM_FULLSCREEN 设为static 后, 上述代码会顺利执行进入setDisplayCaseFailse();
然而此时依然会黑屏,只有声音.
4. 查证在setDisplayCaseFailse()方法里,不执行catch语块的代码时, 都会出现列表中的视频没有图像只有声音的bug, 目测是JCMediaManager.intance().mediaPlayer.setDisplay(surfaceHolder)中的surfaceHolder出了问题.此问题依然待解决.

**Comment by lipangit** [comment]
你看log在setDisplay的时候是不是有IllegalStateException，这个exception在develop上前天加进去的，下个版本会带上

**Comment by KateChris** [comment]
的确会有IllegalStateException,我在代码里加过试了一下,代码如下:
private void setDisplayCaseFailse() {
        try {
            JCMediaManager.intance().mediaPlayer.setDisplay(surfaceHolder);
        } catch (IllegalArgumentException e) {
            LogUtil.e("IllegalArgumentException", "recreate surfaceview");
            FalseSetDisPlay = true;
            addSurfaceView();
            e.printStackTrace();
        } catch (IllegalStateException e) {
            LogUtil.e("IllegalStateException", "recreate surfaceview");
            FalseSetDisPlay = true;
            addSurfaceView();
            e.printStackTrace();
        }
    }

而后我发现黑屏必定出现的情况了:
1. 列表视频里执行surfaceCreated(SurfaceHolder holder)方法时,有时会执行catch语块里addSurfaceView()方法,这个方法里面会新建一个surfaceView,此时列表视频播放完全正常.
2. 如果这时从列表视频进入全屏播放,也一切正常.
3. 若再从全屏播放返回列表视频,列表视频就会出现黑屏并只播放声音.
4. 结论是只要listview界面执行过addSurfaceView()方法,进入全屏后再从全屏页面返回,listview里的视频就会出现黑屏只有声音的情况.

**Comment by lipangit** [comment]
嗯 3.1就好了

**Comment by KateChris** [comment]
可以告诉我修改的方法或者思路吗?

**Comment by lipangit** [comment]
明天或后天release 3.1版本，用这个就好了

**Comment by lipangit** [comment]
多谢你的反馈，我研究一下

**Comment by lipangit** [comment]
你看issue_76分支，这个分支测试的目的是看在一个播放器中用代码addSurfaceView之后再继续退出这个播放器的全屏会没有图像只有声音。

这种情况理论上应该是退出全屏的时候没走到JCMediaManager.intance().mediaPlayer.setDisplay(surfaceHolder)，这行代码不运行，就没图像。

![4f57ec68-fa7e-4f86-becf-03bbfaaf0056](https://cloud.githubusercontent.com/assets/2038071/15272238/b702e80e-1aa2-11e6-88c2-384bcc2a00a1.png)

这段代码的测试结果表明从代码中添加的surfaceview和不局文件中的surfaceview并无区别，并且这个分支打包的代码没发现你说的问题，在你的手机上运行一下试试

**Comment by lipangit** [comment]
How is it going

**Comment by KateChris** [comment]
试过在全屏返回后的列表视频surfaceCreated时通过比较当前url是否为全屏退出时同一个url的方式,如果是同一个url就执行一遍setDisplayCaseFailse,然而依旧没用.怀疑是listview里childview错位引起的,在往这方面查.

**Comment by lipangit** [comment]
你看JCMediaPlayer中，的25和26行
  public JCMediaPlayerListener listener;
  public JCMediaPlayerListener lastListener;
这两个参数是lastListener是全屏前的JCVideoPlayer，listener是当前正在播放的JCVideoPlayer，不要用url判断。

**Comment by lipangit** [comment]
如果是库的问题，我希望能在库里帮你解决

建议不要修改库里的代码，然后引入gradle的配置文件或aar文件，然后严格参照例子中的fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardShowShareButtonAfterFullscreen.java继承JCVideoPlayerStandard再写自己的逻辑，这个完全可以满足简单修改UI的需求

**Comment by KateChris** [comment]
我在项目里新开个分支试试,目测还是自己的代码问题,因为demo运行很正常,谢谢大神啦~

**Comment by KateChris** [comment]
大神,我确认应该不是库的问题了,我自己在新分支里面用像demo这样添加视频代码,是完全没有问题的,应该还是自己代码的adapter里逻辑比较混乱,那里有影响到了,接手的这个项目原先外包公司做的,要添加视频的这个adapter类接近4000行代码,看的脑袋都要炸裂.(┬＿┬)
现在已经把全屏返回后就停止全部视频播放这样做把项目上线了,很感谢大神这么长久以来的指点.

**Comment by lipangit** [comment]
这么长时间，相信你已经解决了
