### ISSUE TITLE
 onError 1 - -12 [240354212] 

### ISSUE THREAD

**Issue by franciscerio** [lipangit/JieCaoVideoPlayer#763]
Hello,

I'm getting this error. My video file is 4096 × 2160, 17:9 aspect ratio. I don't know why i am getting this error. I tried to search what (-12) is and I can't find anything. 

Thanks,
Cerio

**Comment by lipangit** [comment]
Does this often occur?

**Comment by lipangit** [comment]
Is your mother luangage English? can you help me to improve README.md in native English.

**Comment by franciscerio** [comment]
This occur often if your video file resolution is more than 4k. 

Nope. Sorry but I'm not good in english. :)

**Comment by lipangit** [comment]
I tryed a 3G video played well, I think your situation is bug by MediaPlayer

**Comment by franciscerio** [comment]
I played the video using android local storage. My video is 4k resolution and I always get this error. Do you have any idea how did the error occur?

**Comment by lipangit** [comment]
Maybe google fix 4k video bug in android 7.0 or above
