### ISSUE TITLE
怎么获取当前已播放时间，和监听视频是否播放完成？

### ISSUE THREAD

**Issue by ArnoldHuang** [lipangit/JieCaoVideoPlayer#766]
上传数据时和，下一首播放用到，但是好像没有找到方法

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写onAutoComplete监听播放完成，复写设置进度条的函数能取得播放时间

**Comment by 793383996** [comment]
加个回调监听更好啊，老哥

**Comment by lipangit** [comment]
不要回调，都要继承JZVideoPlayerStandard
