### ISSUE TITLE
自动播放不起作用

### ISSUE THREAD

**Issue by czzltp** [lipangit/JieCaoVideoPlayer#767]
在Activity的onCreate方法中写了 JcVideoPlayerStandard.startButton.performClick(); 但没起作用,还是需要手动点击才能播放,请教一下,如何解决,还是什么原因造成的.

**Comment by lipangit** [comment]
这就是模拟点击开始按钮，只要点击开始按钮能播放performClick就能播放

**Comment by lipangit** [comment]
按照README和demo

**Comment by czzltp** [comment]
好的 谢谢
