### ISSUE TITLE
How to play video automatically in listview

### ISSUE THREAD

**Issue by Cruzbenhur** [lipangit/JieCaoVideoPlayer#77]
Hi Nathen Very nice example,

From the issues I found out how to play video automatically by using the following code
jCVideoPlayer.ivStart.performClick(); 

But it doesn't work in listview.I need to play video automatically when particular list item becomes visible.

Kindly help me out in solving the issue.

Thanks

**Comment by lipangit** [comment]
You should modify your listview like this project
https://github.com/danylovolokh/VideoPlayerManager

Your demand is focuse on the listview , then call jCVideoPlayer.ivStart.performClick()

**Comment by Cruzbenhur** [comment]
Hi Nathen,
           Thanks for your quick response i will try as your suggestion.I will let you know if i have any queries.

**Comment by lipangit** [comment]
On standby
