### ISSUE TITLE
返回按钮和关闭按钮同时出现

### ISSUE THREAD

**Issue by apple2360541** [lipangit/JieCaoVideoPlayer#770]
在全屏播放视频的时候，默认是有关闭的叉叉按钮的，但是点击屏幕后返回按钮出现了，而且还在关闭按钮上面，两个按钮同时出现，严重影响美观

**Comment by lipangit** [comment]
叉叉按钮是用来退出小窗的，‘左箭头’按钮是退出全屏的按钮，他们不应该同时出现，估计是接口调错了，如果是直接开启全屏请参照demo中fullscreenDirectlyActivity的代码

**Comment by apple2360541** [comment]
我发现问题了,JCVideoPlayerStandard.startFullscreen(context, JCVideoPlayerStandard.class, ".mp4");如果我不传那个标题参数这个方法，退出全屏按钮和退出小窗窗口两个按钮会同时出现,只有加入标题参数(可以为""),那个退出小屏按钮才不会出现

**Comment by lipangit** [comment]
对，标题要给个空字符
