### ISSUE TITLE
断网情况下会提示正在用移动网络，而且返回按钮不可点击

### ISSUE THREAD

**Issue by apple2360541** [lipangit/JieCaoVideoPlayer#771]
断网情况下全屏播放，进入视频会提示您正在使用移动网络，是否继续观看的英文提示dialog，而且此时点击返回按钮不可用，无法返回，只能点击返回键,还要返回键跟关闭按钮两个同时出现混在一起

**Comment by lipangit** [comment]
1.dialog的语言是系统的语言
2.既不是wifi也不走流量的情况应该不弹出提示网络的对话框，我再确认一下
3.出现dialog的时候点返回按钮和点停止播放按钮都能让dialog消失，你说的’混在一起‘什么意思没听明白
