### ISSUE TITLE
用RecyclerView播放m3u8直播流，第一次点可以正常播，点其他的再回到这个条目就不能播了

### ISSUE THREAD

**Issue by fzxm** [lipangit/JieCaoVideoPlayer#772]
麻烦您有空看一下啦 我播放m3u8的直播流 参照你的Recyclerview列表视频 写了Demo但是 列表视频第一次按都能正常播放 然后播放其它视频 再回到这个 视频就播放不了了 但是用你的mp4格式没问题  这个问题咋解决 呢 谢谢了

**Comment by fzxm** [comment]
不回答么 真扯淡

**Comment by lipangit** [comment]
朋友，先确认一下播放不了和Recyclerview是否有关系。如果没关系把你的视频地址发给我调试一下。

**Comment by fzxm** [comment]
谢谢了 
凤凰卫视香港,http://14.17.115.9/live/hongkong800k.m3u8
凤凰卫视香港,http://zv.3gv.ifeng.com/live/hongkong.m3u8
凤凰卫视香港,http://119.167.138.8/live/hongkong.m3u8
凤凰卫视香港,http://zv.3gv.ifeng.com/live/hongkong800k.m3u8_
我参照你写的 RecyclerView列表 第一次可以播放 播放其他的 回到这个条目就不能播了 
这是错误日志
![default](https://cloud.githubusercontent.com/assets/19965666/24687041/fc1a84be-19e9-11e7-8462-307ba8be68c9.jpg)

**Comment by koJer** [comment]
第二次播放m3u8视频时。mediaplayer获取duration失败。麻烦解决下

**Comment by wufannet** [comment]
遇到相同问题.改播放器尝试隐藏进度条和取消调用相关方法
