### ISSUE TITLE
刷新遇到问题

### ISSUE THREAD

**Issue by wangshaolei** [lipangit/JieCaoVideoPlayer#775]
假如我在scrollview 嵌套一个JCVideoPlayerStandard
我在刷新完请求后 又setUp一遍 
会报java.lang.NullPointerException: Attempt to invoke virtual method 'void com.york.library_jcvideoplayer.JCResizeTextureView.setVideoSize(android.graphics.Point)' on a null object reference
@lipangit

**Comment by wangshaolei** [comment]
@lipangit 页面刚进去刷新 setUp没问题，第一遍播放完以后，再刷新 setUp就会报这个错误。

**Comment by lipangit** [comment]
是应该判空一下，但是以前一直觉得如果JCResizeTextureView为空，setVideoSize的代码不应该执行，有时间调查一下。
