### ISSUE TITLE
如何做到按Home键后回来继续播放？

### ISSUE THREAD

**Issue by kobebryantwx** [lipangit/JieCaoVideoPlayer#776]
按Home键后回来继续播放。

**Comment by kobebryantwx** [comment]
全屏播放按下Home,再回到应用，继续播放视频只有声音没有图像。

**Comment by lipangit** [comment]
这个功能没做过没法给出具体的建议，
有声音没图像的原因是TextureView是否avalible，生成之后是否surface。这两步有一步没做都会没图像。

**Comment by kobebryantwx** [comment]
谢谢。
