### ISSUE TITLE
希望添加一个与系统多媒体音量无关的静音模式

### ISSUE THREAD

**Issue by EricInCD** [lipangit/JieCaoVideoPlayer#777]
比如作为登录界面的背景视频。
这种情况下需求是：视频静音，并且播放时按音量调节按钮不会调节多媒体音量，而是系统默认的调节铃声音量。

**Comment by lipangit** [comment]
你的需求问题不大，MediaPlayer有相关的功能，你觉得接口如何设计为好

**Comment by EricInCD** [comment]
我还没有用到这个库，只是看了下文档觉得好像没有这个功能，而且刚好项目中有这个需求。
简单方式就加一个类似于setSilent的方法，能动态改变就更好了。

**Comment by EricInCD** [comment]
当然，是否静音，默认肯定是false的。😁

**Comment by mengfantao** [comment]
是的，应该有个接口设置MediaPlayer静音和解除静音

**Comment by zsl5684** [comment]
这个需求我在自己的项目中已经实现，当播放器静音的时候，不影响系统其他声音，当播放器非静音的时候，系统声音暂停，并且调节声音也是调节相应的

**Comment by w0080626** [comment]
@zsl5684 talk is cheap , show me the code.

**Comment by w0080626** [comment]
@EricInCD 你的问题我有个解决方案 [#1549](https://github.com/lipangit/JiaoZiVideoPlayer/issues/1549)
