### ISSUE TITLE
Fragment 嵌套 FragmentPager , Pager 里面的Fragment 是ListView, ListView 里面的Item 有视频, 播放视频全屏旋转后,首先黑屏,然后跳转到最外层Fragment,但是仍然有视频的声音

### ISSUE THREAD

**Issue by 164738777** [lipangit/JieCaoVideoPlayer#778]
RT

**Comment by lipangit** [comment]
这个过程有点复杂，‘ 跳转到最外层Fragment’是什么过程？全屏之后黑屏是什么情况，demo有相同的问题吗？

**Comment by 164738777** [comment]
我的应用基础框架是RadioButton+Fragment+ViewPager那种点选页面型应用, 简单就定义为第一层Fragment,有5个Fragment.

其中第2个Fragment里面结构是ViewPager+Fragment,里面有6个Fragment,暂且定义为第二层Fragment

再其中第二层的最后一个Fragment结构是ListView,Item是播放器.

播放视屏后点击全屏,不旋转是正常的,一旋转就出现黑屏,然后过几秒马上就变成第一层Fragment,效果相当于重新进入应用那样.但是视频的声音仍在播放.

**Comment by lipangit** [comment]
断点一下，旋转视频的时候是否调用了releaseAllVideo或者release视频 相关的函数。

**Comment by lipangit** [comment]
记得之前调试的时候遇到过列表里全屏旋转视频黑屏的问题，是调了releaseVideo函数，但是视频停止了的，和你这个不大一样

**Comment by 164738777** [comment]
旋转视频没有调用任何有关release的方法.我在releaseAllVideo以及Media的相关release的方法里面打了断点,都没有触发到.

**Comment by 164738777** [comment]
已解决,在这个复杂布局的Activity的清单文件里面,加上   
`android:configChanges="orientation|screenSize"`
从生命周期上面防止各种复杂问题的出现，防止旋转屏幕导致生命周期重新加载

还有，建议楼主加上2个API，毕竟有些需求不是release就可以解决了，就像有时候切换Fragment，希望视频暂停。

`  public static void stopAllVideos() {
    try {
      if (JCMediaManager.instance().mediaPlayer != null && JCMediaManager.instance().mediaPlayer.isPlaying()) {
        JCMediaManager.instance().mediaPlayer.pause();
      }
    } catch (IllegalStateException e) {
      e.printStackTrace();
    }
  }

  public static void resumeVideo() {
    try {
      if (JCMediaManager.instance().mediaPlayer != null && !JCMediaManager.instance().mediaPlayer.isPlaying()) {
        JCMediaManager.instance().mediaPlayer.start();
      }
    } catch (RuntimeException e) {
      e.printStackTrace();
    }
  }`

以上纯粹是个人建议而已。

**Comment by lipangit** [comment]
多谢热心的朋友

1. android:configChanges="orientation|screenSize" 在readme的第五步写了
2.这两个函数用在什么地方？你的这两个函数只控制了MediaPlayer，ui怎么办

**Comment by 164738777** [comment]
这两个函数当时是为了方便引用，因为打算封装个类似releaseAll的方法来搞个stopAll，封装在Video里面。在播放的时候缩回界面再回到应用，这两个方法还是可以勉强用一下的，毕竟最小化应用不需要每次都release什么的吧。
然而问题也是无法修改player的状态。(┬＿┬)
