### ISSUE TITLE
不能播放

### ISSUE THREAD

**Issue by syMobile** [lipangit/JieCaoVideoPlayer#78]
我把demo安装在手机上上面，点击播放图标，只有缓存圆圈在转动，视频不播放，怎么回事啊？

**Comment by syMobile** [comment]
是我手机的问题吗？我的手机Android系统4.1.1 华为C8813。支持的最低Android系统是多少啊？在别的手机上是可以的。

**Comment by lipangit** [comment]
看看网络能连接吗，播放应该肯定能播，全屏和退出全屏才有可能有问题

**Comment by syMobile** [comment]
网络是可以连接的，是不是手机系统版本的问题啊？换了一个手机就可以了

**Comment by lipangit** [comment]
你能看到有什么关于jcvd的log吗
