### ISSUE TITLE
支持播放跳转后解析到视频地址的吗？

### ISSUE THREAD

**Issue by umeitime** [lipangit/JieCaoVideoPlayer#782]
http://parse.idol001.com/play_m3u8.php?url=http://video.weibo.com/show?fid=1034:1bd8d6f42fb86c169f29e734801f1430 这种

**Comment by lipangit** [comment]
朋友你可以先试一下，之前遇到过一次是可以的

**Comment by umeitime** [comment]
我试了试并不支持。这个能完善下吗？

**Comment by lipangit** [comment]
如何从这个地址取得真实的mp4地址，用curl请求这个地址没有返回数据。

你可以继承JCVideoPlayerStandard，自己先拿到真实的地址再播放

**Comment by umeitime** [comment]
他是跳转的
