### ISSUE TITLE
关于视频结束弹出对话框的问题

### ISSUE THREAD

**Issue by 18257346341** [lipangit/JieCaoVideoPlayer#785]
大神 你好 我现在需要做的一个需求是，我在一个页面点击一张图片，然后变成横屏的全屏播放。
播放完毕后，退出全屏，然后需要在此页面弹出一个对话框做一些提示功能。

我的代码是这样写的
JCVideoPlayerStandard.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;//直接横屏播放
                JCVideoPlayerStandard.startFullscreen(WatchMovieActivity.this, JCVideoPlayerStandard.class, url, title);

请问需要怎么实现呢？ 十分感谢

**Comment by lipangit** [comment]
播放完成弹出对话框需要在onAutoComplete的时候弹，继承JCVideoPlayerStandard，复写onAutoComplete函数弹出对话框。全屏的代码没问题

**Comment by 18257346341** [comment]
好的 谢谢你 现在对话框可以弹出来了 但是我的对话框点击“确定”要跳到另外的一个Acticvity，要怎么实现呢？

@Override
    public void onAutoCompletion() {
        super.onAutoCompletion();
        cancelDismissControlViewTimer();
        showBasicNoTitle();

    }

    @Override
    public void onCompletion() {
        super.onCompletion();
        cancelDismissControlViewTimer();
    }

    public void showBasicNoTitle() {
        new MaterialDialog.Builder(getContext())
                .content("试看完毕")
                .positiveText("去购买VIP")
                .negativeText("取消")
                .negativeColor(0xff999999)
                .onPositive(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        //这里如何做跳转呢
                    }
                })
                .onNegative(new MaterialDialog.SingleButtonCallback() {
                    @Override
                    public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                        dialog.dismiss();
                    }
                })
                .show();
    }

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写showDialog(具体函数名忘了)函数，不调用super()，你可以组建自己的对话框了

**Comment by 18257346341** [comment]
我现在就是不太明白怎么把我的Activity传进来 让他跳转到这个Activity 0.0

**Comment by 18257346341** [comment]
老哥们 我的问题解决了 我把我自己写的继承的播放器的java放在了自己的App里面 就可以实现Actity跳转了

**Comment by lipangit** [comment]
么么哒
