### ISSUE TITLE
没有videoplayer.thumbImageView.setImage（String）方法

### ISSUE THREAD

**Issue by z376368673** [lipangit/JieCaoVideoPlayer#786]
videoplayer.thumbImageView.setImage("url");
怎么没有这个方法？

**Comment by z376368673** [comment]
![qq 20170407165707](https://cloud.githubusercontent.com/assets/21307181/24793097/440885d0-1bb3-11e7-8bca-10da1599ca1a.png)
这个方法不存在啊

**Comment by 164738777** [comment]
thumbImageView其实就是一个**普通的ImageView**,如果想set网络图片什么的,要自己另外用Glide等等之类的,自己处理

**Comment by lipangit** [comment]
参照demo，并没有setImageResource的方法，就是想告诉大家可以拿到缩略图imageView的变量自己去设置图片

**Comment by z376368673** [comment]
汗 看来我还是太笨了 这个都没想到 完全走入那个误区了

**Comment by z376368673** [comment]
那有没有方法直接取视频的第几帧？这样就更完美了

**Comment by lipangit** [comment]
[这个项目](https://github.com/wseemann/FFmpegMediaMetadataRetriever)可以，你可以自己加进去，暂时觉得这个没法加到节操视频播放器里

**Comment by slumcattt** [comment]
How did you sort out the issue ?

**Comment by lipangit** [comment]
@slumcattt this library will not include that library before that library work works perfect.

**Comment by billrancho** [comment]
Use universal image loader to load image with URI on thumb image view
smth like :  Utils.loadImage(this,URL,videoPlayer.thumbImageView);
