### ISSUE TITLE
怎么改变视频的播放比例?

### ISSUE THREAD

**Issue by xuekaiqi** [lipangit/JieCaoVideoPlayer#790]
列表播放显示item 左右两边有黑边，我调整下高度  上下又有黑边  请问下怎么能改变播放比例？让它始终充满屏幕？

![Uploading QQ图片20170410105541.jpg…]()

**Comment by lipangit** [comment]
如果你的视频的宽高比和控件的宽高比比不一样，黑边是不可避免的

**Comment by shenjiabing** [comment]
能不能改变视频的宽高，最终控件与视频宽高相同？

**Comment by lipangit** [comment]
首先你要在没播放视频的时候知道视频的宽高，修改控件的高宽就是修改layout的高宽
