### ISSUE TITLE
6.0以上播放MP4格式音频没反应

### ISSUE THREAD

**Issue by chen2tu** [lipangit/JieCaoVideoPlayer#792]
版本  v 5.5.2

点击播放按钮，音频没有播放，进度条也没有动
log里面只有这一条：
I/JieCaoVideoPlayer: onClick start [175006174] 

如果点击进度条的话，会toast"play video first"

在6.0以下的系统上面播放正常

 minSdkVersion 19
 targetSdkVersion 25  刚开始改成了22，现在改成25还是不行。

其他的改动：

我是直接使用的 JCVideoPlayerSimple ， 然后添加了一张图片，其他的没变

<FrameLayout
        android:id="@+id/surface_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <ImageView
            android:id="@+id/iv_voice_bg"
            android:src="@drawable/bg_voice"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="fitXY"
            />
    </FrameLayout>

我把图片相关的代码都去掉了还是不行

**Comment by lipangit** [comment]
如果build成功能启动和那些版本应该没关系了。

参照demo看看是不是有的参数没传全

**Comment by chen2tu** [comment]
我把示例代码下载下来，在ApiActivity中，将 JcVideoPlayerSimple的url换成我自己的url，还是那样的效果


mJcVideoPlayerSimple.setUp("http://media.snxw.com/masvod/public/2016/12/09/20161209_158e2263f56_r1_64k.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子在家吗");

**Comment by chen2tu** [comment]
我去看看你们的源码吧，谢谢您能回答

**Comment by chen2tu** [comment]
如果，我先播放一下视频，然后来播放音频文件，就可以正常播放了。如果安装了直接来播放音频，就不行

**Comment by lipangit** [comment]
@chen2tu 不可能吧，音频和视频没区别，我之前也试过直接播放音频的情况
