### ISSUE TITLE
流量网络下 JCVideoPlayerStandard.startFullscreen 界面卡死

### ISSUE THREAD

**Issue by weixinjie** [lipangit/JieCaoVideoPlayer#793]
移动网络下，调用  JCVideoPlayerStandard.startFullscreen ，弹出是否继续播放的对话框后点击“不继续播放”按钮，界面会卡死

**Comment by weixinjie** [comment]
已解决：
重写showWifiDialog函数

 @Override
    public void showWifiDialog() {
        super.showWifiDialog();
        AlertDialog.Builder builder = new AlertDialog.Builder(getContext());
        builder.setMessage(getResources().getString(R.string.tips_not_wifi));
       ...
        builder.setNegativeButton(getResources()
                        .getString(R.string.tips_not_wifi_cancel)
                , new DialogInterface.OnClickListener() {
                    @Override
                    public void onClick(DialogInterface dialog, int which) {
                        dialog.dismiss();
                        JCUtils.getAppCompActivity(getContext()).setRequestedOrientation(NORMAL_ORIENTATION);
                        setVisibility(View.GONE);
                        JCVideoPlayerStandard.releaseAllVideos();
                    }
                });
        builder.create().show();
    }

**Comment by lipangit** [comment]
这块是有问题

**Comment by lipangit** [comment]
fix on 913b61a
