### ISSUE TITLE
How to make it full screen onCreateView?

### ISSUE THREAD

**Issue by slumcattt** [lipangit/JieCaoVideoPlayer#794]
Is there anyway to lunch the app full screen at start, instead of clicking the player and full screen manually?

**Comment by lipangit** [comment]
You can simulation custom action, startButton.performClick() ,this methods can play video automaticly.

**Comment by woyoudianhuai** [comment]
but  use  startButton.performClick() 会出现全屏时数据初始化问题

**Comment by lipangit** [comment]
全屏时数据初始化是什么意思

**Comment by woyoudianhuai** [comment]
我的需求是一开始就进入全屏页面就播放，而且得修改JcVideoPlayer 的UI，修改UI后，UI中的评论数或者点赞的值传进去了，但是数据却依然是UI上默认的值，我调用的是startWindowFullscreen（）方法

**Comment by lipangit** [comment]
传参的时候注意setUp(String url, int screen, Object... objects) 方法，最后一个objects，这个参数是可以全屏和非全屏传递，把需要传的变量强制转型成Object，放到setUp的最后这个参数中，自己新建的变量无法传递给全屏
