### ISSUE TITLE
部分机型暂停状态下全屏或者退出全屏界面变绿

### ISSUE THREAD

**Issue by zzh3321** [lipangit/JieCaoVideoPlayer#799]
现在已知的我手上的魅族MX5有这种情况
在播放的时候点击暂停, 然后全屏或者退出全屏, 播放画面会变为绿色
再次点击播放能恢复正常

**Comment by zzh3321** [comment]
github上提供的demo有同样的问题

**Comment by jhonween** [comment]
@lipangit 你好 这个问题 有找出原因吗 怎么解决

**Comment by lipangit** [comment]
应该是系统的坑

**Comment by jhonween** [comment]
那这坑jcv播放器能解决不

**Comment by lipangit** [comment]
超出老臣能力范围

**Comment by taixiang** [comment]
@zzh3321  @jhonween   请问你们这个问题解决没
