### ISSUE TITLE
ListView中的播放问题

### ISSUE THREAD

**Issue by wmhqnyh** [lipangit/jiecaovideoplayer#8]
当我在ListView播放视频的时候，单击画面出现暂停按钮的时候(暂停按钮和标题出现)，如果此时滚动ListView，以后的item会复用这个样式。

**Comment by lipangit** [comment]
这个理论上样式是复用的，但是内容应该都是重置的，无论播放器的状态。我再测测，你如果看出来哪有毛病能修改的话给你加到开发者里。
