### ISSUE TITLE
为什么跳转到全屏的时候时间和小屏播放时 ,时间不一样呢

### ISSUE THREAD

**Issue by xiyanglove** [lipangit/JieCaoVideoPlayer#80]
跳转到大屏幕的时候,时间会缩短几秒钟

**Comment by lipangit** [comment]
这个问题还没想到怎么解决，因为setDisplay(videoHolder)的时候必然进度会有问题，这里也是咱们进入全屏和退出全屏的重点，如果你有什么想法欢迎一起交流
