### ISSUE TITLE
v7包资源不存在

### ISSUE THREAD

**Issue by charmeleon2** [lipangit/JieCaoVideoPlayer#800]
引入5.5.2就会
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
以前的版本可以，貌似和v7包里的东西冲突了？

**Comment by charmeleon2** [comment]
原来要把compileSdkVersion改成24

**Comment by lipangit** [comment]
么么哒
