### ISSUE TITLE
无法播放rtsp直播流吗

### ISSUE THREAD

**Issue by charmeleon2** [lipangit/JieCaoVideoPlayer#801]
看日志似乎是获取不到视频长度
04-14 10:17:33.055 11180-11180/com.archery.archery.tv I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
04-14 10:17:33.068 11180-11180/com.archery.archery.tv D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
04-14 10:17:33.069 11180-11180/com.archery.archery.tv D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
04-14 10:17:33.136 11180-11180/com.archery.archery.tv E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
04-14 10:17:33.136 11180-11180/com.archery.archery.tv E/MediaPlayer: error (-38, 0)
04-14 10:17:33.136 11180-11850/com.archery.archery.tv E/MediaPlayer: Error (-38,0)
04-14 10:17:33.137 11180-11180/com.archery.archery.tv E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
04-14 10:17:33.137 11180-11180/com.archery.archery.tv E/MediaPlayer: error (-38, 0)
04-14 10:17:33.142 11180-11850/com.archery.archery.tv E/MediaPlayer: Error (-38,0)
04-14 10:17:33.649 11180-11180/com.archery.archery.tv E/JieCaoVideoPlayer: onError -38 - 0 [1030548935] 
04-14 10:17:33.649 11180-11180/com.archery.archery.tv E/JieCaoVideoPlayer: onError -38 - 0 [1030548935] 
04-14 10:17:33.656 11180-11180/com.archery.archery.tv E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
04-14 10:17:33.656 11180-11180/com.archery.archery.tv E/MediaPlayer: error (-38, 0)
04-14 10:17:33.657 11180-11850/com.archery.archery.tv E/MediaPlayer: Error (-38,0)
04-14 10:17:33.657 11180-11180/com.archery.archery.tv E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
流本身应该是没问题的，用其他播放器可以播放。
还是说播放rtsp需要特殊处理

**Comment by lipangit** [comment]
这应该是系统的MediaPlayer的坑，这个坑安卓开发没法填也不应该跳进去，相信更高的安卓系统版本官方会解决。

你可以参考5.5.2版本封装了exoplayer，3.8.*版本封装了ijkplayer。
