### ISSUE TITLE
可否出一个接口，让用户自行选择播放器，ijk exo 或者mediaplayer

### ISSUE THREAD

**Issue by tysheng** [lipangit/JieCaoVideoPlayer#802]

**Comment by lipangit** [comment]
分别列出你需要ijk和exo的理由吧

**Comment by lipangit** [comment]
这个问题我纠结了半年多，我觉得作为一个开源库最主要的是判断趋势，我觉得在安卓中使用ffmpeg点播视频在未来是非常臃肿和无法理解的，我相信多数安卓开发都比较排斥10M+的框架(不限于视频框架)，并且我们也做到了相对完善的基于系统MediaPlayer的播放框架。

如果是视频格式有问题，我希望播放的视频和视频的来源的格式都是统一的，现在主流的大平台播放格式都是mp4，其他对视频格式的探索可以说都是徒劳。

你可以分别列出ijk和exo能取代系统MediaPlayer的理由，如果趋势判断错误应该及时修正，我相信所有直接集成这个库和参考这个库的app都是精致的拿得出的手作品。

**Comment by tysheng** [comment]
我本人也是极简的推崇者，把原来项目的30+大小缩到10+，以前是播放mp4没什么问题，现在需要播放m3u8格式，花了几天时间把库升级到最新，不改源码的情况下，捣鼓了一下界面、逻辑以到达需求,在我两个手机6.0+，7.0+，都是可以完美运行播放的。

可到了机型测试的时候，发现不少4.0+，5.0+的机型出现有声音无画面的情况，但是用VLC都是可以播放的，对视频直播这块不太了解，私以为ijk或者exo会比mediaplayer适应性更广一点(个人没有证实过，但是如果可以多几种选择去尝试，当然更好)。

看了一下库现有的逻辑，提供接口切换播放器应该不难。最重要的一点，我是极度不想修改开源项目源码的人，对以后的更新迭代都不好。

**Comment by lipangit** [comment]
总结一下你的理由是安卓4.0 5.0对m3u8的视频格式支持不好。 我再想想

**Comment by tysheng** [comment]
```java
    public void initTextureView() {
        removeTextureView();
        JCMediaManager.textureView = new JCResizeTextureView(getContext());
        JCMediaManager.textureView.setSurfaceTextureListener(JCMediaManager.instance());
    }

    public void addTextureView() {
        Log.d(TAG, "addTextureView [" + this.hashCode() + "] ");
        FrameLayout.LayoutParams layoutParams =
                new FrameLayout.LayoutParams(
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        ViewGroup.LayoutParams.MATCH_PARENT,
                        Gravity.CENTER);
        textureViewContainer.addView(JCMediaManager.textureView, layoutParams);
    }

    public void removeTextureView() {
        JCMediaManager.savedSurfaceTexture = null;
        if (JCMediaManager.textureView != null && JCMediaManager.textureView.getParent() != null) {
            ((ViewGroup) JCMediaManager.textureView.getParent()).removeView(JCMediaManager.textureView);
        }
    }
```
可以把这些在```JCVideoPlayer```中耦合的方法都写到```JCMediaManager```中，

在```JCVideoPlayer```中设一个方法，
```
   public MediaManager getMediaPlayer() {
        return JCMediaManager.instance();
    }
```
让用户可以自定义manager，仿照```JCMediaManager```写就好了

**Comment by tysheng** [comment]
用之前的exo版本和ijk版本都测试过了，均可以播放，用最新的mediaplayer版本没有画面只有声音

**Comment by lipangit** [comment]
你可以提交一个能直接运行的分支上来给大家参考

**Comment by tysheng** [comment]
ok

**Comment by tysheng** [comment]
我的思路已经提了pr了@lipangit 查看一下

**Comment by lipangit** [comment]
好滴好滴

**Comment by lipangit** [comment]
@tysheng 这个不能再lib中，只能在demo中
