### ISSUE TITLE
楼主直接用的AppCompatActivity局限性也太大了

### ISSUE THREAD

**Issue by xuezj** [lipangit/JieCaoVideoPlayer#803]
当改用集成Activity是，你在全屏是做的一些东西明显有问题，直接获取SupportActionBar，这个让开发人员很不好办啊

**Comment by xuezj** [comment]
建议设置视频区域点击监听，以及视频区域部分影藏监听，让开发自己实现他的title等

**Comment by ghyzx** [comment]
遇到类似问题，直接闪退了
Attempt to invoke virtual method 'android.support.v7.app.ActionBar android.support.v7.app.AppCompatActivity.getSupportActionBar()' on a null object reference

**Comment by lipangit** [comment]
已经列入工作计划，争取这礼拜就解决这个问题

**Comment by 12d** [comment]
这么问题解决了吗

**Comment by lipangit** [comment]
还没解决
