### ISSUE TITLE
视频重复播放问题

### ISSUE THREAD

**Issue by weixinjie** [lipangit/JieCaoVideoPlayer#805]

**Comment by weixinjie** [comment]
使用JCVideoPlayerStandard播放视频，然后全屏播放，然后坐等视频播放完成的时候会出现问题：1.屏幕回到竖屏的时候会重复播放视频 2.此时点击屏幕，屏幕会出现暂停UI，但是视频仍在播放

**Comment by weixinjie** [comment]
已解决：
继承JCVideoPlayerStandard.java重写changeUiToCompleteShow()函数，加入  JCVideoPlayer.releaseAllVideos();
整体代码如下：
    public void changeUiToCompleteShow() {
        switch (currentScreen) {
            case SCREEN_LAYOUT_NORMAL:
            case SCREEN_LAYOUT_LIST:
                setAllControlsVisible(View.VISIBLE, View.VISIBLE, View.VISIBLE,
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE);
                updateStartImage();
                JCVideoPlayer.releaseAllVideos();
                break;
            case SCREEN_WINDOW_FULLSCREEN:
                setAllControlsVisible(View.VISIBLE, View.VISIBLE, View.VISIBLE,
                        View.INVISIBLE, View.VISIBLE, View.INVISIBLE, View.INVISIBLE);
                updateStartImage();
                JCVideoPlayer.releaseAllVideos();
                break;
            case SCREEN_WINDOW_TINY:
                break;
        }
    }

**Comment by feaoes** [comment]
遇见了同样的问题。谢谢
