### ISSUE TITLE
播放时候出现onError 1 - -1004 [107700575]

### ISSUE THREAD

**Issue by MisayaS** [lipangit/JieCaoVideoPlayer#806]

**Comment by lpflpy** [comment]
遇到同样的问题  小米手机播放一分多分钟之后出现onError 1 - -1004 [126376750]

**Comment by AndroidAdu** [comment]
测试发现Android 5.0，5.1 都没有问题，就是6.0播放一段时间会出现onError

**Comment by lipangit** [comment]
保持关注 么么哒

**Comment by MisayaS** [comment]
恩，小米手机，Android 6.0版本就会出现这个问题。现在尝试4.8.3的ijkPlayer版本可以正常播放，感觉部分视频源还是需要ffmpeg支持。

**Comment by lipangit** [comment]
@MisayaS 始终推荐服务器上就要统一视频的格式，建议大家不要在探索视频格式上白下功夫。

**Comment by jfjbYXY** [comment]
extra：-1004
具体是什么错误啊？debug出现这个数字的时候，视频停止播放。
一般视频播放不超过10分钟就会出这个错

**Comment by lipangit** [comment]
@jfjbYXY 如果经常出现的话这个问题可以说比较严重

**Comment by dasamanren** [comment]
这边也有出现,小米5 版本7.0 视频播放到一半的时候突然报-1004
E/MediaPlayer: error (1, -1004)
E/MediaPlayer: Error (1,-1004)
E/JieCaoVideoPlayer: onError 1 - -1004 [202540674] 
前面播得好好的,然后就只报这句error,然后就退出来了,其他什么都没有

**Comment by MisayaS** [comment]
@dasamanren 试试将视频源的格式利用格式工厂改成H264+ACC。

**Comment by dasamanren** [comment]
@MisayaS 不行,我试了几台,发现都是Android 7.0的手机会出现这个问题
