### ISSUE TITLE
大神，这个播放器是基于exoplayer的吗？

### ISSUE THREAD

**Issue by focus2846** [lipangit/JieCaoVideoPlayer#809]

**Comment by lipangit** [comment]
3.8.*版本基于ijkplayer 5.1.*基于exoplayer 今后的版本都会基于系统的MediaPlayer

**Comment by focus2846** [comment]
谢谢回复，问下，Google出的exoplayer是不是会比 系统的MediaPlayer 稳定，好点呢？今后的版本为啥用系统的MediaPlayer啊？

**Comment by lipangit** [comment]
readme中写的：
目前认为安卓中视频点播的终极状态是系统的MediaPlayer，其他的播放引擎并不是未来的趋势，虽然系统的MediaPlayer也有缺点我认为我们应该做出一些让步，如果系统的MediaPlayer没有重大缺陷将不会考虑替换它。

**Comment by focus2846** [comment]
谢谢回复，这个视频库很好

**Comment by lipangit** [comment]
issues都回复的 ^_^
