### ISSUE TITLE
建议最低支持Android4.0

### ISSUE THREAD

**Issue by facexxyz** [lipangit/JieCaoVideoPlayer#810]
既然在Android4.0下也能运行，本项目作为依赖库，建议将library的minSdkVersion改为14，方便Android4.0开发者使用。

**Comment by lipangit** [comment]
这里用到了4.1的api了，如果不用全屏有问题，最低兼容到api16

**Comment by facexxyz** [comment]
@lipangit 能提供下api方法名吗？谢谢

**Comment by lipangit** [comment]
textureView.setSurfaceTexture(savedSurfaceTexture);

**Comment by facexxyz** [comment]
谢谢，学习了，附API地址。
[setSurfaceTexture](https://developer.android.com/reference/android/view/TextureView.html#setSurfaceTexture(android.graphics.SurfaceTexture))
