### ISSUE TITLE
Cannot play video from Raw asset folder

### ISSUE THREAD

**Issue by BanterClaus** [lipangit/JieCaoVideoPlayer#811]
The video player does not seem to be playing video from raw asset folder.
I'm using the following code to set up the playing of the video:

```
        int resID = context.getResources().getIdentifier(fileName , "raw", context.getPackageName());

        filePath = base + resID;
        videoView.setUp(filePath, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, name);
```

This resolves and plays the video fine using Androids native VideoView.setVideoURI(), however, I can't get JC to play any video from raw?

Thanks

**Comment by lipangit** [comment]
jcvd.setUp(URI , ...);//set up with uri

 I will do it as soon as possible.

**Comment by BanterClaus** [comment]
Thanks a lot! 👍

**Comment by XXP1228** [comment]
@lipangit  can you tell me how to rewrite setUp method to support URI ？

**Comment by lipangit** [comment]
no way in this Architecture，

You  can download source code and change it.

next version will fix the problem, next version you can custom mediaplayer. see media_interface branch

**Comment by XXP1228** [comment]
@lipangit  thanks,another question is can this player play the avi format video? my recent project needs put the avi format video in the asserts or raw folder and play it.

**Comment by lipangit** [comment]
no, support fomate is all [here](https://developer.android.com/guide/topics/media/media-formats.html)

**Comment by chnouman** [comment]
@lipangit  any update related to this?

**Comment by lipangit** [comment]
no update.  It just put the url to the MediaPlayer
