### ISSUE TITLE
Fragment下ListView需要怎么滑出屏幕停止播放

### ISSUE THREAD

**Issue by junwen0814** [lipangit/JieCaoVideoPlayer#814]
我的视频列表在Fragment下，用了RecycleView好像没效果，看到例子用了ListView，好像也必须是在Actviity才可以？可是Fragment该怎么实现这个功能？Item滑出屏幕后停止播放，看有的人也问过这个问题，不过不太懂的怎么判断holder是否正在播放，不然滑动的时候，正在播放的视频也被误停止了。

**Comment by lipangit** [comment]
当前的判断是列表复用的时候，setUp会release正在播放的视频，完美解决方式应该是监听滑动。

**Comment by zhengjinyao** [comment]
为什么我每次都崩掉，视频列表在Fragment下
JCUtils.scanForActivity(getContext())为null

**Comment by lipangit** [comment]
@zhengjinyao 包含视频的activity要继承Appcompactactivity

**Comment by littlegreatness** [comment]
判断当前播放的条目位置是不是在RecycleView的FirstVisibleItemPosition   和 LastVisibleItemPosition  之间吧

**Comment by lipangit** [comment]
@littlegreatness 对对对，能写个demo吗，你就如太阳般闪耀
