### ISSUE TITLE
关于m3u8格式的播放

### ISSUE THREAD

**Issue by gaodengjiaoyu** [lipangit/JieCaoVideoPlayer#815]
您好，使用您这个播放器播放m3u8格式的视频有一些问题。我测试了3个手机，三星6.0系统的没问题。可是中兴手机  4.4版本和中兴手机4.2版本播放就播放不出来。播放地址如下
http://vod.gslb.cmvideo.cn/depository/asset/zhengshi/1000/275/818/1000275818/media/1000275818_5000850692_54.mp4.m3u8?msisdn=null&sid=1500273491&timestamp=20170419160505&Channel_ID=317800000000002&pid=2028600181&extInfo=a0fcc45a-54ef-44a7-a989-782dab18e37e&ProgramID=624243689&encrypt=e713d3be2c4ee91ed55c061e07ea942a
您这边能帮忙看下吗？

**Comment by tysheng** [comment]
低版本系统 mediaplayer 对 这个格式支持不太好，可以用ijk或者exo试试

**Comment by lipangit** [comment]
链接请求遭到拒绝。安卓4.*版的视频格式兼容性确实没有高版本的好，google的坑没办法。

如果条件允许建议统一使用mp4格式的视频，这是首选解决方案，其次可以参考3.8.*版本，基于ijkplayer和5.2.1版本基于exoplayer

**Comment by gaodengjiaoyu** [comment]
好的 谢谢大牛 我试试exoplayer，感谢解答。
