### ISSUE TITLE
全屏类型转换异常

### ISSUE THREAD

**Issue by mengfantao** [lipangit/JieCaoVideoPlayer#817]
Cannot cast 'android.view.ContextThemeWrapper' to 'android.support.v7.view.ContextThemeWrapper'
在JCUtils类的方法
 /**
     * Get AppCompatActivity from context
     *
     * @param context
     * @return AppCompatActivity if it's not null
     */
    public static AppCompatActivity getAppCompActivity(Context context) {
        if (context == null) return null;
        if (context instanceof AppCompatActivity) {
            return (AppCompatActivity) context;
        } else if (context instanceof ContextThemeWrapper) {
            **return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());**
        }
        return null;
    }

**Comment by mengfantao** [comment]
activity用的事AppCompatActivity，页面是基于fragment写的

**Comment by mengfantao** [comment]
是这句话报的return getAppCompActivity(((ContextThemeWrapper) context).getBaseContext());

**Comment by lipangit** [comment]
activity继承了AppCompatActivity，那应该没什么问题啊

**Comment by mengfantao** [comment]
刚刚试了下，用android.support.design.widget.AppBarLayout嵌套就会出这个问题，不嵌套就没问题

**Comment by mengfantao** [comment]
<android.support.design.widget.AppBarLayout
        android:id="@+id/app_bar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

这个样式去调就好类  android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"

**Comment by tysheng** [comment]
不科学啊，已经做了 instanceof 判断了，为什么还会执行。

难道 'android.view.ContextThemeWrapper'  'android.support.v7.view.ContextThemeWrapper'
这两个内部可以互相转化？

**Comment by lipangit** [comment]
解决了就好
