### ISSUE TITLE
如何在播着视频的时候，跳转界面后，再回来时重新播放，而不是继续播放？

### ISSUE THREAD

**Issue by loonggg** [lipangit/JieCaoVideoPlayer#819]
如何在播着视频的时候，跳转界面后，再回来时重新播放，而不是继续播放？

**Comment by tysheng** [comment]
videoplayer里有个saveProgress，设置为false

**Comment by loonggg** [comment]
@tysheng 我看文档，在setUp之后，设置 loop = true之后，重复播放没效果，怎么回事？

**Comment by tysheng** [comment]
要在点击事件之前设置

**Comment by lipangit** [comment]
loop=true是自动播放完成后自动重新继续播放。
JCVideoPlayer. saveProgress=false 不保存播放进度

**Comment by yt511652502** [comment]
@lipangit  最新的版本里是不是取消这个变量了？ JCVideoPlayer. saveProgress

**Comment by lipangit** [comment]
JCVideoPlayer.SAVE_PROGRESS
