### ISSUE TITLE
Does it support local videos

### ISSUE THREAD

**Issue by mkodekar** [lipangit/JieCaoVideoPlayer#82]
DOES IT SUPPORT LOCL VIDEOS

**Comment by lipangit** [comment]
of course

**Comment by mkodekar** [comment]
How , I am actually giving the path and the path is not loaded , please can you explain me.

**Comment by lipangit** [comment]
This library use android.media.MediaPlayer to play video, it support local video.

Local path will parse to Uri, you can try some other way to represent the path of video.

**Comment by mkodekar** [comment]
I am getting paths in string and there only one Method where I can pass the uri or string of the path 

.setup I don't see any method that ask for the uri

**Comment by lipangit** [comment]
develop branch , fm.jiecao.jcvideoplayer_lib.JCMediaManager  line 48 

mediaPlayer.setDataSource(context, Uri.parse(url), mapHeadData);

Your string will parse to uri

**Comment by mkodekar** [comment]
Thanks for it , whereas the media player  so coconfusing and I am actually decrypting videos and after the completion of the decryption I have to run the video controls are like jammed and don't run.

**Comment by lipangit** [comment]
I cann't help you with decrypting videos, if you use persistence as your good friend, you will make it.

**Comment by mkodekar** [comment]
now tell me how can i add the mediaManager to the videoView

**Comment by lipangit** [comment]
VideoView is not inflexible.
