### ISSUE TITLE
请问自动播放下一集 如何设置？

### ISSUE THREAD

**Issue by MinchinWang** [lipangit/JieCaoVideoPlayer#820]

**Comment by MinchinWang** [comment]
正常屏幕下和全屏下的 两种 自动播放下一集，如何写？

**Comment by lipangit** [comment]
正常屏幕下，继承JCVideoPlayerStandard复写onAutoComplete函数监听到播放完毕，这时播放你想播放的下一个视频，startButton.performClick()模拟用户点击开始播放视频

全屏模式下思路也是如此，监听播放完毕，然后setUp()设置下一个视频的参数，然后模拟点击开始按钮播放视频

大概思路应该是这样

**Comment by MinchinWang** [comment]
1.  JCVideoPlayer.setJcUserAction(new MyUserActionStandard());

 2. class MyUserActionStandard implements JCUserActionStandard {

        @Override
        public void onEvent(int type, String url, int screen, Object... objects) {
            switch (type) {
                   case JCUserAction.ON_AUTO_COMPLETE:
                    selectVideo ++ ;
                    toastShow(selectVideo + "");
                    ItemsBean itemAtPosition = anthologyBeanList.get(selectVideo);
                    anthologyAdapter.setSelect(itemAtPosition);
                    videoplayer.setUp(itemAtPosition.url, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");

                    videoplayer.startButton.performClick();

                    Log.i("USER_EVENT", "ON_AUTO_COMPLETE" + " title is : " + (objects.length == 0 ? "" : objects[0]) + " url is : " + url + " screen is : " + screen);
                    break;
}

这样子设置 但是还是不行呀，请问哪里出错了？

**Comment by lipangit** [comment]
JCUserActionStandard 这个是用户埋点，统计数据用的，不要在这里写逻辑相关的东西

继承JCVideoPlayerStandard复写onAutoComplete函数监听到播放完毕

**Comment by MinchinWang** [comment]
继承JCVideoPlayerStandard 里面没看到 onAutoComplete的这个函数。
楼主可以写个例子么?

**Comment by MinchinWang** [comment]
急求回复~~ 谢谢了

**Comment by lipangit** [comment]
JCVideoPlayerStandard 继承JCVideoPlayer ，onAutoComplete在JCVideoPlayer里

**Comment by MinchinWang** [comment]
JCVideoPlayer里面 我没看到onAutoComplete这个方法呀？
![123](https://cloud.githubusercontent.com/assets/3407244/25314203/148546b0-2872-11e7-833e-8d31736d874c.png)

**Comment by MinchinWang** [comment]
![abc](https://cloud.githubusercontent.com/assets/3407244/25314209/3268fd5c-2872-11e7-9586-040c182bd919.png)

**Comment by MinchinWang** [comment]
解决了 谢谢

**Comment by lipangit** [comment]
么么哒

**Comment by liuchenyang** [comment]
@MinchinWang   请问你是怎么解决的    我在遇到了这个问题 。。。

**Comment by qinyang1018** [comment]
@MinchinWang 解决了能贴下代码吗？  这样也能帮助其他遇见同样问题的人  谢谢了
