### ISSUE TITLE
JCVideoPlayerStandard 似乎默认锁定了长宽比例

### ISSUE THREAD

**Issue by wyj365372704** [lipangit/JieCaoVideoPlayer#821]
Hello大神！
    我在xml中引入JCVideoPlayerStandard (SDK V:5.5.4)，对其设置android:layout_width="match_parent"
            android:layout_height="160dp"  似乎没有按照高度160dp走，而是在宽度优先情况下按照了一个比例值去动态调动了高度。如果这是成立的，请问这么做的出发点是什么，我们又该如何去个性化定制长款比例或者取消这种限制按照给出的width/height 测量JCVideoPlayerStandard。

PS:在SDK V：4.7.0 中android:layout_width="match_parent"
            android:layout_height="160dp"可以将高度设置有效。

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/25336047/4a03619e-2928-11e7-92fa-0e52ead7739b.png)

这个版本可以参照这个修改屏幕比例

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/25336136/b6708802-2928-11e7-82cf-47916a10ad59.png)

你把这两个变量设置成0就可以设置你想要的高度了，这个是我的疏忽，这两个变量本来就应该是0。
