### ISSUE TITLE
关于内存泄露

### ISSUE THREAD

**Issue by zzCool** [lipangit/JieCaoVideoPlayer#822]
hello大神，用leakcanary检测到JCMediaManager.textureView存在内存泄露，望解决

**Comment by lipangit** [comment]
这个问题我也纠结很久，我也知道怎么做能不泄漏，但是对于咱们开源项目我想做一些有突破的东西，根据我的分析，把textureview设为static变量会极大的简化我们代码的复杂度，使textureview和设置surfacetexture相关的代码非常直观和简洁。

如果想让内存不泄露，你可以把JCMediaManager的textureview和surfaceTexture相关的函数加上textureView和surfaceTexture的参数，在JCVideoPlayer调用的时候直接给函数赋值当前JCVD的textureView成员变量。

还有UserEvent部分也会内存泄漏，最终的目标让这部分代码既简洁直观又不泄漏，如果发现会第一时间修改。

**Comment by tysheng** [comment]
```public void onCompletion()```中最后释放掉textureview的代码为什么要注释掉，保留可以解决这个内存泄露的问题，而且没什么其他的影响(已使用几天)

@lipangit

**Comment by lipangit** [comment]
这个是为了解决一个空指针的问题，还没来得及仔细查

**Comment by lipangit** [comment]
知道了，以后会修复的

**Comment by zzCool** [comment]
@lipangit 我在 JCVideoPlayer.releaseAllVideos();之前JCMediaManager.textureView = null;就没有内存泄漏了
