### ISSUE TITLE
播放youku的多个片段问题

### ISSUE THREAD

**Issue by moyaying** [lipangit/JieCaoVideoPlayer#823]
请问怎么播放youku的一个视频，多个切段问的问题？

**Comment by lipangit** [comment]
你是说多个视频无缝连续播放吗，没做过相关的功能

**Comment by abc20899** [comment]
1、JZMediaIjkplayer 加入配置：
      ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,
                "protocol_whitelist", "rtmp,concat,ffconcat,file,subfile,http,https,tls,rtp,tcp,udp,crypto");
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0);
2、JZVideoPlayer.setMediaInterface(JZMediaIjkplayer())  切换播放引擎
3、播放列表文件 111.ffconcat  
      ffconcat version 1.0
      file 'http://vali.cp31.ott.cibntv.net/657194E073Fxxxxxxxxxxx'
      duration 390
      file 'http://vali.cp31.ott.cibntv.net/6571FA18xxxxxxxxx'
      duration 392
      file 'http://vali.cp31.ott.cibntv.net/677329C0D69387163xxxxxxxxx'
      duration 389
      file 'http://vali.cp31.ott.cibntv.net/6572xxxxxxxxx'
      duration 392
4.播放
     url0 = "file:///sdcard/111.ffconcat"
     jzVideo.setUp(url0, JZVideoPlayerStandard.SCREEN_WINDOW_NORMAL, name)

**Comment by lipangit** [comment]
没验证过，收藏了
