### ISSUE TITLE
为什么全屏后播放就是竖屏播放呢？

### ISSUE THREAD

**Issue by Object-Ping** [lipangit/JieCaoVideoPlayer#825]

**Comment by lipangit** [comment]
参照demo里origintationActivity，配置全屏前后的屏幕方向

**Comment by yangyiRunning** [comment]
我现在想点击播放器的全屏按钮后实现水平的全屏，看了上面所说的origintationActivity类，播放器设置屏幕方向的代码却找不到触发的时机，因为点击全屏按钮这个操作是在源码里的，求解决方案

**Comment by lipangit** [comment]
origintationActivity 里有
JCVideoPlayer.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
JCVideoPlayer.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;

**Comment by yangyiRunning** [comment]
Done  3Q @lipangit

**Comment by lipangit** [comment]
么么哒
