### ISSUE TITLE
亮度调节有bug

### ISSUE THREAD

**Issue by Dwan-xie** [lipangit/JieCaoVideoPlayer#826]
当将亮度调制最低后，再次调节亮度会先亮度升高然后在回到调节中的亮度上。

**Comment by lipangit** [comment]
是有问题，竟然才发现

**Comment by Dwan-xie** [comment]
补充一下。
现在获取的是system的亮度，在系统设置自动亮度的时候。
mGestureDownBrightness = Settings.System.getInt(getContext().getContentResolver(), Settings.System.SCREEN_BRIGHTNESS);
这个方法返回的是个固定值，并不是我们调节之后的亮度，问题应该是由这个导致的。
我这边有做一些调整，不获取系统的亮度而是获取当前应用的亮度，可以避免这个问题。

**Comment by lipangit** [comment]
@Dwan-xie 怎么取得应用当前的亮度，只发现了Settings.System.SCREEN_BRIGHTNESS系统亮度这个参数。

**Comment by Dwan-xie** [comment]
你下面其实修改的就是当前layout的亮度。
我的思路是获取layout的亮度，在修改layout亮度，这样可以避免系统自动亮度而导致的初始值不对的问题。
context.getWindow().getAttributes().screenBrightness(0.0 ~ 1.0的值)，context就是你的JCUtils.getAppCompatActivity()。然后伴随着这里的修改后面的亮度算法也有一些修改。
`if (mChangeBrightness) {
						deltaY = -deltaY;
						float deltaV = deltaY * 3f / mScreenHeight;
						float screenBrightness = mGestureDownBrightness + deltaV;
						WindowManager.LayoutParams params = mContext.getWindow().getAttributes();
						if (screenBrightness >= 1) {//这和声音有区别，必须自己过滤一下负值
							screenBrightness = 1;
						} else if (screenBrightness <= 0) {
							screenBrightness = 0.05f;
						}
						params.screenBrightness = screenBrightness;
						mContext.getWindow().setAttributes(params);
						//dialog中显示百分比
						int brightnessPercent = (int)(screenBrightness * 100);
						LogUtil.d("brightness : " + deltaV + " " + brightnessPercent + " " + deltaY + " " + mGestureDownBrightness);
						showBrightnessDialog(brightnessPercent);
					}`

**Comment by lipangit** [comment]
已解决

**Comment by 18667366881** [comment]
最新版本是多少 大神

**Comment by 18667366881** [comment]
调整亮度还是不对的     似乎设置亮度无效

**Comment by lipangit** [comment]
@18667366881 亲测手势调亮度很好用啊，你的什么效果，可以录个小视频看看

**Comment by 18667366881** [comment]
![1 00_00_05 20170703-204901-0](https://user-images.githubusercontent.com/20569012/27793481-c8e1282c-6030-11e7-9ebd-47edd526aec5.PNG)

**Comment by 18667366881** [comment]
我就是这样在手机上调整   亮度无效  不管大小  都无效

**Comment by lipangit** [comment]
真机上呢，我这没问题

**Comment by 18667366881** [comment]
您好  真机上   就这样调整 亮度不变    最大最小  都没有变化

**Comment by lipangit** [comment]
什么版本，demo 有这问题吗

**Comment by 18667366881** [comment]
嗯 最新版本 我的代码层级是   TabActivity  ->AppCompatActivity  ->   viewpage->    Fragment ->NewsFragmentPagerAdapter ->VideoListAdapter

**Comment by 18667366881** [comment]
demo  是没问题的  是不是我的代码层级问题呢

**Comment by lipangit** [comment]
跟层级没关系，断点一下库里的代码onTouch这块

**Comment by 18667366881** [comment]
嗯好的

**Comment by 18667366881** [comment]
你好  在点击全屏的时候  是新建了一个对象进行播放的   我有个想法   我想在全屏的时候  启动一个activity 播放   这样对内存是不是少一点了？

**Comment by lipangit** [comment]
新建activity也可以，但是当前的这种做法应该是最优化的

**Comment by chnouman** [comment]
@lipangit  how to remove brightness control from on touch event?

**Comment by lipangit** [comment]
override onTouch() function.
