### ISSUE TITLE
平板中兼容unity问题

### ISSUE THREAD

**Issue by zhang71896** [lipangit/JieCaoVideoPlayer#827]
请问下如何解决,在android studio 上打包到三星平板系统6.01上面播放器可以正常播放，通过在android studio 中生成jar的形式 ,导入到unity项目中，再通过unity5.5打包,播放器无法正常播放，一直处于加载状态的问题.

**Comment by lipangit** [comment]
看一下log，jiecaovideoplayer相关的内容，启动的步骤到了哪步

**Comment by zhang71896** [comment]
亲，已经解决了哈，需要在具体的activity中加一个android:hardwareAccelerated="true"允许硬件加速.谢谢勒哈

**Comment by lipangit** [comment]
么么哒
