### ISSUE TITLE
在播放页面自定义一个下载按钮，当前activity在小屏的时候点击有反应，全屏的时候点击没反应

### ISSUE THREAD

**Issue by liuchenyang** [lipangit/JieCaoVideoPlayer#829]
MainActivity.class 里面

jcVideoPlayer.findViewById(R.id.upload).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(getApplicationContext(),"启动下载任务",Toast.LENGTH_LONG).show();
            }
        });

**Comment by lipangit** [comment]
在全屏的时候会创建另一个JCVideoPlayerStandard，监听并不能通用

你需要继承JCVideoPlayerStandard，复写init函数，在init函数中设置监听
