### ISSUE TITLE
能否支持视频缓存

### ISSUE THREAD

**Issue by Logan676** [lipangit/JieCaoVideoPlayer#83]
每次观看视频时都需要重新下载，能否支持已经播放的视频缓存到本地呢？

**Comment by lipangit** [comment]
如果你的项目需求强烈的话只能手动下载视频文件再播放本地视频。

这个项目的JCVideoPlayerStandard.java的目标是所有细节极致模仿头条，头条没有缓存功能，在我的认知水平会认为缓存功能很难，需要放一放。

我也意识到有缓存功能只有好处没有坏处，之前有查过资料或者尝试都无功而返，以后也会密切关注这个功能，一旦有所突破，瞬间集成!!
