### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by zhaoyujie** [lipangit/JieCaoVideoPlayer#830]
按照ReadMe文件中的集成方式，使用gradle添加依赖库5.5.4，点击播放，出现如下的问题：
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err: java.lang.reflect.InvocationTargetException
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:83)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err: Caused by: java.io.IOException: setDataSource failed.: status=0x80000000
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.media.MediaPlayer.nativeSetDataSource(Native Method)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1093)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1082)
04-26 17:30:30.096 7144-7383/com.example.zhaoyujie.jiecaodemo W/System.err: 	... 5 more

**Comment by zhaoyujie** [comment]
不好意思，是我错了，没有加网络权限导致的，一时没有看明白

**Comment by lipangit** [comment]
么么哒
