### ISSUE TITLE
为啥播放视频不是从0开始啊！！！

### ISSUE THREAD

**Issue by tommyfeng** [lipangit/JieCaoVideoPlayer#833]
怎么点击播放时进度都不是从0开始播的，很怪啊。。。

**Comment by diov** [comment]
会缓存上一次看的位置的，看一下 sharedpreference

**Comment by lipangit** [comment]
是上次观看缓存的位置，可以JCVideoPlayer.SAVE_PROGRESS=false把这个功能关掉
