### ISSUE TITLE
Increment Preloader Buffering

### ISSUE THREAD

**Issue by HackJoues** [lipangit/JieCaoVideoPlayer#836]
Hello, im trying to play some files in 720p Quality, the file size is 1Gb, and in some times, the video playing, pauses for wait the preloader buffer. 
How I can increase the buffering preloader?

**Comment by lipangit** [comment]
Maybe there is no interface .

**Comment by HackJoues** [comment]
I don't understand?

**Comment by lipangit** [comment]
android.media.MediaPlayer don't have this function
