### ISSUE TITLE
全屏返回键不能退出全屏

### ISSUE THREAD

**Issue by pck77627** [lipangit/JieCaoVideoPlayer#838]
全屏播放的时候点击返回键，无法退出全屏？

**Comment by HackJoues** [comment]
您的活动

@Override
public void onBackPressed() {
    if (JCVideoPlayer.backPress()) {
        return;
    }
    super.onBackPressed();
}

**Comment by lipangit** [comment]
这个问题参照demo和readme，肯定有地方漏掉了，readme里有详细的步骤。
