### ISSUE TITLE
引入jar包的方式，提示找不到JCVideoPlayer

### ISSUE THREAD

**Issue by axkza** [lipangit/JieCaoVideoPlayer#84]
你好，我用eclipse，引入2个jar，1个arr包，但是项目中提示JCVideoPlayer cannot be resolved，请问这个怎么解决呢？

**Comment by lipangit** [comment]
只需要引入一个aar，aar包含代码和资源文件，是不是重复引入了，jar解压之后会发现没有资源文件还要手动拷贝资源文件

我司的项目就是引入aar，加油，坚持不懈，你会成功
