### ISSUE TITLE
在单个视频详情界面，暂停后点home回到桌面，再次点击回到详情，播放器变黑

### ISSUE THREAD

**Issue by TonyEasy** [lipangit/JieCaoVideoPlayer#840]
如题

**Comment by lipangit** [comment]
按home键之后会release视频的，请参照reademe的代码。

**Comment by hengtongjie** [comment]
我没有release，而是((JCVideoPlayerStandardShowTitle) JCVideoPlayerManager.listener()).startButton.performClick();采用了这个办法将视频暂停，但是回到详情页之后还是黑屏

**Comment by lipangit** [comment]
我发现头条已经有home键继续播放的功能了，我们会尽快添加这个功能

**Comment by hengtongjie** [comment]
home键自动播放功能，我自己实现了，就是在pause时判断

**Comment by lipangit** [comment]
能分享一下你的代码吗，能减少我的功能量^_^，提交个pr或者发我邮箱、qq

**Comment by mrldroid** [comment]
@TonyEasy  请问那个问题解决了吗

**Comment by mrldroid** [comment]
@lipangit

**Comment by lipangit** [comment]
解决了 参考demo的apiActivity
