### ISSUE TITLE
mediaPlayer prepareAysnc()  导致error -38

### ISSUE THREAD

**Issue by feaoes** [lipangit/JieCaoVideoPlayer#844]
日志如下：
I/JieCaoVideoPlayer: onClick start [879264280]
D/JieCaoVideoPlayer: prepareMediaPlayer [879264280]
D/JieCaoVideoPlayer: addTextureView [879264280]
I/JieCaoVideoPlayer: onSurfaceTextureAvailable [107980740]
D/JieCaoVideoPlayer: onInfo what - 701 extra - 0
D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_START
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
E/JieCaoVideoPlayer: onError -38 - 0 [879264280]
I/JieCaoVideoPlayer: onVideoSizeChanged  [879264280]
I/JieCaoVideoPlayer: onPrepared  [879264280]
I/JieCaoVideoPlayer: onSurfaceTextureSizeChanged [107980740]
D/JieCaoVideoPlayer: onInfo what - 3 extra - 0
D/JieCaoVideoPlayer: onInfo what - 702 extra - 0
D/JieCaoVideoPlayer: MEDIA_INFO_BUFFERING_END
D/JieCaoVideoPlayer: releaseAllVideos
I/JieCaoVideoPlayer: onCompletion  [879264280]

当修改成prepare()之后，没有问题。
版本号是Android5.0 平板
在此给需要的朋友说明一下

**Comment by wf08314110101** [comment]
兄弟，我在小米盒子3上遇到这个问题，按照你说的修改后可以播放了，但是没有画面，你有遇到这个问题吗？
