### ISSUE TITLE
能否自由设置宽高

### ISSUE THREAD

**Issue by junmei520** [lipangit/JieCaoVideoPlayer#845]
我想把高设置为300dp, 宽设置为match_parent，不起作用。
设置了宽高比，但是好像每次都是以宽为基准的，还是没办法达到正常显示
高：300dp, 宽：match_parent的播放器？？？

**Comment by lipangit** [comment]
设置jcvideoPlayer.widthRatio=0 jcvideoPlayer.heightRatio=0
