### ISSUE TITLE
how can i fast forward in live buffered video?

### ISSUE THREAD

**Issue by surindersinghbindra** [lipangit/JieCaoVideoPlayer#847]
I'm unable to fast forward the Video. Please let me know if there is any Method/ Params that i need to change for fast forwarding/rewinding.

**Comment by lipangit** [comment]
android.media.MediaPlayer do not have fast forward function.

**Comment by surindersinghbindra** [comment]
is there any way to fast forward the video?

**Comment by lipangit** [comment]
Change MediaPlayer to IJKplayer

**Comment by surindersinghbindra** [comment]
can i change MediaPlayer to IJKplayer inside the JCV player so the video full screen and tiny screen would work same like now
