### ISSUE TITLE
自己的类继承自JCVideoPlayerStandard后，重写getLayoutId传入自定义布局，导致NPL

### ISSUE THREAD

**Issue by yangyiRunning** [lipangit/JieCaoVideoPlayer#848]
通过阅读源码得知，JCVideoPlayer中的find的ID都是写死的，这是不是说明我在自定义布局的时候，ID必须和源码的ID保持一致？？？

另外有没有更加有拓展性的方法？？可以让自定义布局可以随意起名ID？？？

以上

3Q

**Comment by lipangit** [comment]
这个暂时无法拓展，需要仔细核对id
