### ISSUE TITLE
E/JieCaoVideoPlayer: onError 1 - -1005 [117224239]

### ISSUE THREAD

**Issue by ExcellentLife-FeiFan** [lipangit/JieCaoVideoPlayer#849]
05-04 09:59:03.381 19373-19384/com.ytxd.zb D/MediaHTTPConnection: setReadTimeout with 30000ms
05-04 09:59:03.381 19373-19384/com.ytxd.zb I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-04 09:59:03.381 19373-19384/com.ytxd.zb I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-04 09:59:03.421 19373-19384/com.ytxd.zb I/MediaHTTPConnection: response code = 400
05-04 09:59:03.421 19373-19384/com.ytxd.zb W/MediaHTTPConnection: request failed with error => 400
05-04 09:59:03.421 3112-25018/? E/GenericSource: [MEDIA_ERROR_IO]
05-04 09:59:03.421 19373-19556/com.ytxd.zb D/MediaHTTPConnection: setReadTimeout with 30000ms
05-04 09:59:03.421 19373-19556/com.ytxd.zb I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-04 09:59:03.421 19373-19556/com.ytxd.zb I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-04 09:59:03.441 19373-19556/com.ytxd.zb I/MediaHTTPConnection: response code = 400
05-04 09:59:03.441 19373-19556/com.ytxd.zb W/MediaHTTPConnection: request failed with error => 400
05-04 09:59:03.441 3112-25018/? E/GenericSource: ERROR_IO from getMIMEType()
05-04 09:59:03.441 3112-25018/? V/GenericSource: Deepak :abortPrepare
05-04 09:59:03.441 3112-25018/? V/GenericSource: [Flag] clear 0x48 -> mFlags = 0x0
05-04 09:59:03.441 3112-25017/? V/NuPlayer: msg : 100, ext1 : 1, ext2 : -1005
05-04 09:59:03.441 3112-25017/? D/NuPlayerDriver: notifyListener_l(0xe796f320), (100, 1, -1005)
05-04 09:59:03.441 3112-25017/? V/MediaPlayerService: [257] notify (0xe2ab8400, 100, 1, -1005)
05-04 09:59:03.441 3112-25017/? E/NuPlayer: Network errror is occured (-1004)
05-04 09:59:03.441 3112-25017/? D/NuPlayer: set mHTTPStreaming = FALSE
05-04 09:59:03.441 19373-19556/com.ytxd.zb V/MediaPlayer: message received msg=100, ext1=1, ext2=-1005
05-04 09:59:03.451 19373-19556/com.ytxd.zb E/MediaPlayer: error (1, -1005)
05-04 09:59:03.451 19373-19556/com.ytxd.zb V/MediaPlayer: callback application
05-04 09:59:03.451 19373-19556/com.ytxd.zb V/MediaPlayer: back from callback
05-04 09:59:03.451 19373-24625/com.ytxd.zb E/MediaPlayer: Error (1,-1005)
05-04 09:59:03.451 19373-19373/com.ytxd.zb E/JieCaoVideoPlayer: onError 1 - -1005 [117224239] 

就是用有些的视频网址老师报这个错误，播放不了，但有些视频网址又能正常播放，没有问题

怎么回事呀？

**Comment by lipangit** [comment]
MediaHTTPConnection: response code = 400

应该是服务器的问题，哪个能播就向那个的环境看齐。
