### ISSUE TITLE
对象在其他类中无法访问父类属性

### ISSUE THREAD

**Issue by bombp** [lipangit/JieCaoVideoPlayer#85]
jcVideoPlayerStandard.ivStart.performClick();中jc对象在其他类中无法访问父类的ivstart(protected)等属性

**Comment by lipangit** [comment]
请用最新的3.1

**Comment by bombp** [comment]
嗯！谢谢！是否有提供播放界面各个按钮的监听，比如我想全屏之后有相应提示？

**Comment by lipangit** [comment]
可以继承JCVideoPlayer，在里面修改相当灵活。

可以参考demo里的fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardShowShareButtonAfterFullscreen

**Comment by bombp** [comment]
已经用其他方式解决了，3Q！

**Comment by bombp** [comment]
为什么这个toActivityFromNormal不暴露出来呢

**Comment by lipangit** [comment]
因为这个是专门给非全屏到全屏的方法，你有什么需要吗
