### ISSUE TITLE
小屏切换到全屏后，进度条的缓冲进度没有显示

### ISSUE THREAD

**Issue by 164738777** [lipangit/JieCaoVideoPlayer#850]
RT
详细情况：
小屏缓冲了一小段视频后马上断网，然后切换到全屏，缓冲进度没显示。如果打开网继续缓冲，进度才显示。估计在切换到全屏的时候，没有初始化缓冲进度（估计是secondaryProgress吧？）？

**Comment by lipangit** [comment]
是的，切换屏幕的时候并不传递缓存的进度，打开网络MediaPlayer才调回调缓存的函数，才有缓存进度。

这个细节还是有道理，想想如何传递缓存进度。
