### ISSUE TITLE
暫停狀態下切換播放時間點，seekbar仍會運作

### ISSUE THREAD

**Issue by ice459pp** [lipangit/JieCaoVideoPlayer#852]
如標題，附上影片：
https://drive.google.com/open?id=0B1qFBLwrd2LcQmNncDBTV2oxM28

**Comment by lipangit** [comment]
不是每次都这样吧，有什么前兆吗，如何复现。

**Comment by ice459pp** [comment]
您好，步驟是這樣的，一開始隨意挑選一個播放時間按下暫停，狀態處於暫停後，然後把seekbar thumb按住往“更早”的時間軸移動，bug就發生了。但我想這只是UI控制上的bug。

**Comment by lipangit** [comment]
现在的版本没这毛病了
