### ISSUE TITLE
高度无法设置全屏吗

### ISSUE THREAD

**Issue by RangerAnan** [lipangit/JieCaoVideoPlayer#855]
![aa](https://cloud.githubusercontent.com/assets/14307249/25771431/37545cec-3283-11e7-9f88-6c0dc84fe72a.png)
我设置了heightRatio=0,widthRatio=0,需要全屏显示，设置了高度无效，标题栏和底部控制器总占据了固定高度。请问这怎么解决呢

**Comment by lipangit** [comment]
截图里的是非全屏的状态吗，标题栏肯定会占位置的。

底部控制占据高度是什么意思，这不是会自动隐藏吗

**Comment by RangerAnan** [comment]
是非全屏状态，我重写了addTextureView方法，自定义了高度，但是发现maxHeight就是图中的状态。我试了下设置全屏，结果也是这样（画面有点被压缩了）。能不能让标题栏和底部控制器变透明呢？让TextureView全屏展示。

**Comment by RangerAnan** [comment]
@lipangit  师兄，底部控制器隐藏了，但是textureView依然不是全屏
![bbad](https://cloud.githubusercontent.com/assets/14307249/25793261/1ce98d7e-33fe-11e7-80fd-28fb7b8a103b.png)

**Comment by lipangit** [comment]
视频的宽高比和屏幕的宽高比一样吗？如果视频不被拉伸，上下的间隙应该是有的。

**Comment by RangerAnan** [comment]
我是全屏录制的小视频，现在没有全屏播放，就会有一定压缩。

**Comment by RangerAnan** [comment]
@lipangit 师兄，我想让TextureView全屏播放，设置了widthRatio、heightRatio为屏幕宽高值，也重写了addTextureView方法，设置了屏幕宽高JCMediaManager.textureView.setVideoSize(point);依然达不到效果。跟踪了JCResizeTextureView日志，多次测量时，第一次是有效的：
JCResizeTextureView: videoWidth = 1080, videoHeight = 1921
后来莫名的这样了：
JCResizeTextureView: videoWidth = 480, videoHeight = 640。然后宽高就被修正了

**Comment by RangerAnan** [comment]
多谢师兄，确实是视频的宽高比和屏幕的宽高比不一样，被修正了。
