### ISSUE TITLE
Redirect video link is not playing in android version 4.4(Kitkat)

### ISSUE THREAD

**Issue by ShantiRanjanDas** [lipangit/JieCaoVideoPlayer#856]
Redirected video links are not playing as "http" leads to an "https" link, while it is playing above kitkat version. I am using a viemo url for playing a video.

Here is the link, its a viemo video link, which i am facing the problem.

http://player.vimeo.com/external/210709564.sd.mp4?s=a4002b9acb9a09a2b32d40a2f749ce61e24eea83&profile_id=164&oauth2_token_id=336345293, http://player.vimeo.com/external/210709564.sd

Error which I got:-
E/DrmMtkUtil/DrmUtil: checkExistence failed, reason [No such file or directory]
05-06 15:29:12.068 145-725/? E/DrmMtkUtil/DrmUtil: checkDcf: file does not exist.
05-06 15:29:13.626 145-12058/? E/chromium-libstagefright: external/chromium/net/socket/ssl_client_socket_openssl.cc:792: [0506/152913:ERROR:ssl_client_socket_openssl.cc(792)] handshake failed; returned -1, SSL error code 1, net_error -107
05-06 15:29:13.628 29401-29413/mm3.vod.com E/MediaPlayer: error (261, -1003)
05-06 15:29:13.631 29401-30224/mm3.vod.com E/MediaPlayer: Error (261,-1003)
05-06 15:29:13.635 29401-29401/mm3.vod.com E/JieCaoVideoPlayer: onError 261 - -1003 [1121672576] 
05-06 15:29:13.638 145-12058/? E/chromium-libstagefright: external/chromium/net/socket/ssl_client_socket_openssl.cc:792: [0506/152913:ERROR:ssl_client_socket_openssl.cc(792)] handshake failed; returned -1, SSL error code 1, net_error -107

**Comment by lipangit** [comment]
Redirected video links maybe can not use.
