### ISSUE TITLE
能否再更新下exoplayer的版本

### ISSUE THREAD

**Issue by jyh149129** [lipangit/JieCaoVideoPlayer#859]
对于hls 流，不管是首帧加载速度、播放稳定性来看 exoplayer都明显要好很多，希望能再更新下基于exoplayer的版本

**Comment by lipangit** [comment]
老臣尽力

**Comment by jyh149129** [comment]
谢谢！题外话：还是希望作者能切换回exo，我觉得exo脱离系统，可以更新较快，稳定性、兼容性都要好很多，相信也是以后android媒体播放的事实标准

**Comment by lipangit** [comment]
咱们5.2.1版本用的exoplayer，4.8.*版本用的ijkplayer，4.8.*之前用的系统播放器，用了一圈发现还是系统的播放器舒服，以后不排除换播放器的可能

**Comment by lipangit** [comment]
这不是题外话，研究明白用哪个播放器这很重要

**Comment by cgztzero** [comment]
我一直用的是exoplayer的版本，刚刚更新EXOplayer到r2.4.0版本。感觉EXO初始化会稍慢一点，但是播放高清长视频会更稳定。

**Comment by lipangit** [comment]
有典型的高清长视频的地址吗，播放中就会崩溃那种，我试试，我试过播放1080P的2G的电影，我觉得系统的MediaPlayer没那么糟糕，

**Comment by cgztzero** [comment]
Mediaplayer高清长视频观看不完整，是有几个用户反馈给我的。然后我更换了EXO给用户做了测试，那几个用户没有问题。然后一直到现在也没有反馈过，播放到一般无法播放的问题，所以就一直延续了EXO。当时好像记得有问题的俩机器是三星的好像。不知道别人还有没有遇到过类似的。

**Comment by lipangit** [comment]
我知道了，我需要时间想想
