### ISSUE TITLE
未开始播放的显示截图解决，谢谢楼主

### ISSUE THREAD

**Issue by wlsh** [lipangit/JieCaoVideoPlayer#86]
//jiecaovideoplayer播放视频
        videoPath = "http://2449.vod.myqcloud.co/2449_bfbbfa3cea8f11e5aac3db03cda99974.f20.mp4";
        jieCao_video.setUp(videoPath, "你好污啊");
        //获取视频的缩略图显示在开始
        MediaMetadataRetriever media = new MediaMetadataRetriever();
        media.setDataSource(videoPath, new HashMap<String, String>());
        Bitmap bitmap = media.getFrameAtTime();
        //显示在上面
        jieCao_video.ivThumb.setImageBitmap(bitmap);
       
![qq 20160519164238](https://cloud.githubusercontent.com/assets/10937358/15387680/f4df4a28-1de0-11e6-9688-0ce8ca78ef40.png)

**Comment by lipangit** [comment]
啥意思，你是想如果没有缩略图地址，可以在视频中取得缩略图是吗

**Comment by wlsh** [comment]
对，根据视频流来得到一个截图，作为刚开始的展示，我是新手，，，，

**Comment by lipangit** [comment]
缩略图一般是后台给一个图片地址，给用户预览用

你这个也给了我别的启发，可能在暂停状态进入全屏的时候会用到

**Comment by lipangit** [comment]
多谢提醒
