### ISSUE TITLE
横竖屏切换和点击物理返回键会卡住一会

### ISSUE THREAD

**Issue by 18180540870** [lipangit/JieCaoVideoPlayer#860]
请问横竖屏切换和点击物理返回键的时候画面会卡住一会，但是声音是继续播放的，切换成功之后画面和声音能够同步到一起，有什么好的解决办法吗？

**Comment by lipangit** [comment]
明显吗，其他手机一样吗，我以前没察觉这个事。

**Comment by 18180540870** [comment]
我这边华为荣耀，1加3t，vivo测试了下，都有遇到这个问题。切屏，切屏以后点击返回键，或者切屏后退出全屏的时候画面会暂停住，但是声音是一直都在的。卡住的时间大概有4秒左右吧

**Comment by lipangit** [comment]
4秒！

**Comment by lipangit** [comment]
切屏是什么意思  你再仔细描述一下过程

**Comment by 18180540870** [comment]
就是横竖屏切换，横屏切竖屏，竖屏切横屏

**Comment by 18180540870** [comment]
点击全屏默认是竖屏的，把手机横着放，画面会卡几秒才切换成横屏播放

**Comment by lipangit** [comment]
什么版本，你做了什么修改吗，demo有这个问题吗，发个小视频看看

**Comment by 18180540870** [comment]
compile 'fm.jiecao:jiecaovideoplayer:5.5.4' ，没有做修改，直接添加的依赖包。

**Comment by 18180540870** [comment]
https://pan.baidu.com/s/1bpL8g5T     录了个小视屏，30多M，传不上去，发到百度网盘了

**Comment by 18180540870** [comment]
看了下demo，你们的不卡

**Comment by 18180540870** [comment]
![14qs2r 0 6uvv oee821e6](https://cloud.githubusercontent.com/assets/21095406/25944117/c2b32792-3674-11e7-8969-b0792dbe5a71.png)
![a rm dosm3zpb su c 6p](https://cloud.githubusercontent.com/assets/21095406/25944120/c50675da-3674-11e7-8ce3-d723dfae43d5.png)
![zaoec z9vtk fel4k9kc 9](https://cloud.githubusercontent.com/assets/21095406/25944121/c63635e4-3674-11e7-8260-0ee6f7de65f8.png)
![v3z2ldy 8 q nrxm879r _3](https://cloud.githubusercontent.com/assets/21095406/25944122/c718bfea-3674-11e7-96bd-3f219ab7b509.png)
![z h6 4g6_a2 p _v 3647e](https://cloud.githubusercontent.com/assets/21095406/25944124/c82c1ca6-3674-11e7-9619-9a0ed956562a.png)
这个五个步骤都有。还加了重力感应的方法
![iut5 j 3 l 7ujhwppxj](https://cloud.githubusercontent.com/assets/21095406/25944177/efdf49ee-3674-11e7-9b58-013bf7c95bd0.png)
![97m 0q1x3 rgl b g uey](https://cloud.githubusercontent.com/assets/21095406/25944214/125e4632-3675-11e7-82db-73118732469a.png)

**Comment by 18180540870** [comment]
是这样的吧

**Comment by lipangit** [comment]
这代码没看出什么问题。

这些代码的目的是在非全屏状态下检测屏幕的重力感应，然后进入全屏。进入全屏之后这些代码就不工作了，库里会判断屏蔽掉重力感应，全屏之后的屏幕方向的转变是系统监听重力感应旋转屏幕，是系统级别的。所以，你的这个卡顿是系统旋转屏幕的时候的卡顿，和这些代码没关系。

从视频上看就知道这么多，对了，你看看卡顿的时候视频进度的回调卡主了吗，是app卡主了，还是TextureView卡主了

**Comment by 18180540870** [comment]
我把视频的链接单独拿出来写了个demo，也不卡。应该是我们的App卡掉了。非常感谢你的帮助。谢谢
