### ISSUE TITLE
请问如何获取当前播放状态，如何监听当前播放状态呢？

### ISSUE THREAD

**Issue by mylove2693** [lipangit/JieCaoVideoPlayer#861]
主要就是我加了一个显示视频总时长的TextView，在点击开始播放时需要隐藏这个TextView。另外我没有找到原始JCVideoPlayerStandard有显示总时长的控件，就是模仿今日头条，在播放之前右下角显示视频总时长。

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard 复写setUiWitStateAndScreen函数，case各个状态

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard 复写getLayoutId函数，指定自己的布局文件，复写setUp函数，设置时长textView

**Comment by mylove2693** [comment]
谢谢大神
