### ISSUE TITLE
内存泄漏 memory leak

### ISSUE THREAD

**Issue by jhonween** [lipangit/JieCaoVideoPlayer#864]
In fm.jiecao.jiecaovideoplayer:5.5.4:59.
* fm.jiecao.jiecaovideoplayer.PlayDirectlyActivity has leaked:
* GC ROOT java.util.Timer$TimerImpl.<Java Local>
* references fm.jiecao.jcvideoplayer_lib.JCVideoPlayer$ProgressTimerTask.this$0
* references fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard.mContext
* leaks fm.jiecao.jiecaovideoplayer.PlayDirectlyActivity instance
* Retaining: 331 KB.
* Reference Key: ad7592d3-816d-42a9-b97b-dc0cf5d0348c
* Device: HUAWEI Huawei HUAWEI MT7-CL00 MT7-CL00
* Android Version: 6.0 API: 23 LeakCanary: 1.4-beta2 3799172
* Durations: watch=5013ms, gc=179ms, heap dump=3377ms, analysis=287758ms

In fm.jiecao.jiecaovideoplayer:5.5.4:59.
 * fm.jiecao.jiecaovideoplayer.PlayDirectlyActivity has leaked:
 * GC ROOT static fm.jiecao.jcvideoplayer_lib.JCMediaManager.textureView
* references fm.jiecao.jcvideoplayer_lib.JCResizeTextureView.mContext
* leaks fm.jiecao.jiecaovideoplayer.PlayDirectlyActivity instance
* Retaining: 179 KB.
* Reference Key: abb2c545-7c7d-4f75-88ba-f2e96aee561b
* Device: HUAWEI Huawei HUAWEI MT7-CL00 MT7-CL00
* Android Version: 6.0 API: 23 LeakCanary: 1.4-beta2 3799172
* Durations: watch=5012ms, gc=177ms, heap dump=3093ms, analysis=270081ms

以上是leakcanary反馈的2处内存泄漏信息   麻烦修复下

**Comment by lipangit** [comment]
好的
