### ISSUE TITLE
关于点击物理返回键退出全屏的问题↓↓↓

### ISSUE THREAD

**Issue by yangyiRunning** [lipangit/JieCaoVideoPlayer#866]
README中如下所示：

4.在Activity中

@Override
public void onBackPressed() {
    if (JCVideoPlayer.backPress()) {
        return;
    }
    super.onBackPressed();
}
@Override
protected void onPause() {
    super.onPause();
    JCVideoPlayer.releaseAllVideos();
}

Q：在Fragment中如何监听？？Fragment中没有onBackPressed的回调函数

**Comment by mylove2693** [comment]
在Activity中监听返回键就可以了，Fragment中的JCVideoPlayer会退出全屏

**Comment by yangyiRunning** [comment]
@mylove2693    现在已经这么写了。播放器在Fragment中，Fragment的母体Activity按照文档重写了上述物理返回键的回调方法，然后实际效果是点击返回按键仍然会退出整个activity。

**Comment by yangyiRunning** [comment]
找到问题了，base类里面有个方法覆盖。谢谢你的解答。 @mylove2693
