### ISSUE TITLE
横竖屏下播放器对象不同的问题⬇️

### ISSUE THREAD

**Issue by yangyiRunning** [lipangit/JieCaoVideoPlayer#869]
通过阅读源码得知，在全屏时，会创建一个新的对象，如下：
`
Constructor<JCVideoPlayer> constructor = (Constructor<JCVideoPlayer>) JCVideoPlayer.this.getClass().getConstructor(Context.class);
            JCVideoPlayer jcVideoPlayer = constructor.newInstance(getContext());`

这就导致了竖屏时的播放器和横屏时的播放器，不是一个对象，而横竖屏的播放器中往往有很多逻辑是需要同步的，比如按钮的显示状态等，在不同的播放器对象下，播放器的状态如何保证同步？？？

**Comment by lipangit** [comment]
setUp的最后一个参数object数组，这会在全屏和非全屏之间互相传递，建议把其他参数都放到object数组中

**Comment by yangyiRunning** [comment]
看了一下JCVideoPlayer中有一个public的currentStatus，请问这个参数应该传什么？？当前状态具体是指？？另外这个参数在setUp的Object...的参数中，是否为必传的？？

**Comment by lipangit** [comment]
currentStatus是当前的播放状态，有普通状态、准备状态、播放中、暂停、error、seek进度中、播放完毕

Object数组是给开发者准备，如果你有其他参数传到jcvd中，比如副标题、视频时长、其他数据结构等，这个数组自己传的自己用不是必须的

**Comment by mylove2693** [comment]
楼主@yangyiRunning 是否解决了JCVideoPlayer滑出屏幕不会自动停止播放的问题？

**Comment by lipangit** [comment]
这个问题竟然暂时没法解决，setUp复用时当前的代码结构无法取得正在播放的JCVideoPlayer。我再研究研究

**Comment by lipangit** [comment]
@mylove2693 只能用一些不规则的方法解决，这样会打乱代码结构，有时间我再搞一搞

**Comment by mylove2693** [comment]
@lipangit 好的，感谢大神！
