### ISSUE TITLE
关于全屏的需求

### ISSUE THREAD

**Issue by ZhenMrLee** [lipangit/JieCaoVideoPlayer#876]
需求：在列表里播放视频，这时候屏幕横过去，就切换到全屏状态。
但是我在fragment里面监听不到onConfigurationChanged的状态改变

**Comment by 164738777** [comment]
Fragment 需要 Activity作为载体才能使用，所以可以在Activity里面设置监听。

**Comment by lipangit** [comment]
刚进入全屏状态是竖屏的
