### ISSUE TITLE
退出后进入屏幕变绿

### ISSUE THREAD

**Issue by jhonween** [lipangit/JieCaoVideoPlayer#878]
步骤如下
程序进入后台 调用@Override
    protected void onPause() {
        super.onPause();
        JCMediaManager.instance().mediaPlayer.pause();
    }
进入前台 调用 @Override
    protected void onResume() {
        JCMediaManager.instance().mediaPlayer.start();
        super.onResume();
    }
然后视频变绿一会 然后正常播放
这个是什么原因？

**Comment by lipangit** [comment]
为什么这里要操作播放器，参照demo和readme吧

**Comment by jhonween** [comment]
我的场景是这样的 视频是全屏的  视频全屏播放时 按home键后暂停播放 回到视频页面后 继续播放 这样的场景 我在需求没看到

**Comment by lipangit** [comment]
你可以来群里问问，这个需求好多朋友完成了，有时间我也把这个加到demo里。
