### ISSUE TITLE
嵌套在fragment中的Listview的时候  当item不可见的时候仍在播放

### ISSUE THREAD

**Issue by wangyi1993** [lipangit/JieCaoVideoPlayer#88]

**Comment by lipangit** [comment]
listview的item是需要复用的，在listview中视屏不可见就停止播放的本质是item复用的时候调用setUp，就会重置上一个视频播放。

**Comment by lipangit** [comment]
如果列表的item是多种holder混合使用的，就在getHolder的时候判断一下，是否releaseAllVideos

**Comment by wangyi1993** [comment]
好的 谢谢 我现在就是有多种holder 我试试这样能不能解决

**Comment by wangyi1993** [comment]
我现在在getHolder的时候判断 当前holder是否是播放视频的item  如果不是的话releaseAllVideos
但是这样的话正在播放并且可见的item会停止播放

**Comment by lipangit** [comment]
朋友，这个确实是个问题，我司的项目也有这个问题，只是混合holder中视频比较密集，没发现，下周一之前发一个版本会解决这个问题

添加一个release()方法，这里判断如果自己在播放就release自己

多谢你的反馈

**Comment by lipangit** [comment]
试一下3.2，有release()方法了

**Comment by wangyi1993** [comment]
请问在什么时候调用release()?

**Comment by lipangit** [comment]
在getView中，getHolder的时候，如果是包含视频的holder，直接调用release();
这意味着，如果上一个包含视频holder被复用，不管复用它的是不是视频，都调用release();
结果是正在播放的视频拖出视野就会被release

**Comment by wangyi1993** [comment]
好的   谢谢 我试试

**Comment by lipangit** [comment]
How is it going

**Comment by lipangit** [comment]
重点是复用列表
