### ISSUE TITLE
How can I use this library with https server?

### ISSUE THREAD

**Issue by DnAGroup** [lipangit/JieCaoVideoPlayer#881]
I know this question has been raised before, but we are still having issues. Could you recommend anything for us? This is what we receive from a server.

Couldn't open https://tempry.co/api/data/post/video/567/video.mp4: java.io.FileNotFoundException: No content provider: https://tempry.co/api/data/post/video/567/video.mp4
05-13 23:06:21.482 4582-4582/com.tempry D/MediaPlayer: setDataSource IOException | SecurityException happend

**Comment by lipangit** [comment]
I will try the url

**Comment by DnAGroup** [comment]
@lipangit thank you very much, waiting for your answer

**Comment by DnAGroup** [comment]
@lipangit any news on my problem? Could we do something wrong or did we miss anything?

**Comment by lipangit** [comment]
I have test the url and see some log , Unfortunately I do not understandard the log mean, I can not help you on https.
