### ISSUE TITLE
从列表也切换到详情页续播，播放器无缝切换

### ISSUE THREAD

**Issue by littlegreatness** [lipangit/JieCaoVideoPlayer#883]
观看了一部分今日头条的视频，在播放状态下点击进入详情页，在详情页是直接播放的，没有进行初始化加载的那些操作。JCPlayer能不能做到这样，在跳转到另外界面的时候越过prepareMediaPlayer  直接续播呢？？

**Comment by lipangit** [comment]
理论上可以，这和进入全屏是一个道理

**Comment by littlegreatness** [comment]
理论上是的，主要是切换了TextureView，但是是在不同的页面不同的 ViewGroup了， 有什么好的实现建议吗

**Comment by lipangit** [comment]
你可以详细看一下startWindowFullscreen(),这个方法进入全屏，把TextureView remove掉，然后在其他viewGroup中添加textureView
