### ISSUE TITLE
播放这种的就不行啊？

### ISSUE THREAD

**Issue by umeitime** [lipangit/JieCaoVideoPlayer#886]
http://parse.idol001.com/play_m3u8.php?url=http://video.weibo.com/show?fid=1034:875630b6d2dd8cb1515624926086aa88

**Comment by lipangit** [comment]
无法播放跳转的视频链接，只能播放直接的视频链接，你可以继承JCVideoPlayerStandard，在视频播放之前在android里取得直接的视频链接。
