### ISSUE TITLE
怎么能在Activity中监听到视频播放完成？？

### ISSUE THREAD

**Issue by MonkeyEatBanana** [lipangit/JieCaoVideoPlayer#887]
找了好长时间没找到，继承JCVideoPlayerStandard的我知道了，但不符合我的需求，求指教

**Comment by lipangit** [comment]
只能在所继承的JCVideoPlayerStandard的类里监听视频播放完成，和其他关于视频的操作。其他地方就像readme中一样五步使用你新建的类，不写和视频相关的逻辑

**Comment by MonkeyEatBanana** [comment]
哦，好，谢谢
