### ISSUE TITLE
没发改变视频高度

### ISSUE THREAD

**Issue by BruceAnda** [lipangit/JieCaoVideoPlayer#889]
`<fm.jiecao.jcvideoplayer_lib.JCVideoPlayerStandard
                android:id="@+id/video_view"
                android:layout_width="match_parent"
                android:layout_height="400dp" />`
不论高度设置多少高度在手机上都是同一高度。 200dp和400dp高度都一样

**Comment by lipangit** [comment]
设置jcVideoPlayer.widthRatio和jcVideoPlayer.heightRatio

**Comment by BruceAnda** [comment]
我设了720和480，仍旧不变，我看你是默认值是16：9，这个数字有什么限制吗？我看没有文档，能否在这里说一下

**Comment by lovearthhome** [comment]
@lipangit @BruceAnda 同问，我把16换成64，32也可以，就是不能是720，有些视频不是正好的的16:9或者4：3，需要视频窗口精确适应视频，所以需要ratio的数字越高越好。望作者答复下，感谢先。

**Comment by lipangit** [comment]
没有限制，这个就是控制整个空间的宽高比。可以看看相关的源码，本质上市宽度不变，根据比例设置控件的高度。
