### ISSUE TITLE
关于标题栏

### ISSUE THREAD

**Issue by saurylip** [lipangit/JieCaoVideoPlayer#890]
您好大佬 我目前想实现的效果是 在recyclerview列表页播放时候不显示标题栏,但是在全屏(横屏)时要显示标题栏中的返回按钮,我是要复写setUiWitStateAndScreen方法实现吗?

**Comment by lipangit** [comment]
你是想全屏的时候和非全屏的时候界面上的控件不一样是吧，参照demo的smallChangeUiActivity
