### ISSUE TITLE
横屏的activity播放视屏，播放完成继续播放下一个视屏会强制切换为竖屏

### ISSUE THREAD

**Issue by magicdra** [lipangit/JieCaoVideoPlayer#893]
继承JCVideoPlayerStandard后复写setUiWitStateAndScreen方法
 public void setUiWitStateAndScreen(int state) {
        super.setUiWitStateAndScreen(state);
        switch (currentState){
            case CURRENT_STATE_AUTO_COMPLETE:
                setUp("http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4", JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子闭眼睛");
                thumbImageView.setImageURI(Uri.parse("http://p.qpic.cn/videoyun/0/2449_43b6f696980311e59ed467f22794e792_1/640"));
                startButton.performClick();
//                changeUiToCompleteShow();
//                cancelDismissControlViewTimer();
//                bottomProgressBar.setProgress(100);
                break;
        }
    }
可以继续播放，但是会强制切换为竖屏

**Comment by skydar** [comment]
碰到一樣的情況

**Comment by skydar** [comment]
找到答案了
https://github.com/lipangit/JieCaoVideoPlayer/issues/825
