### ISSUE TITLE
调取直播视频->release ->再次调取直播视频 播放器Error

### ISSUE THREAD

**Issue by weixinjie** [lipangit/JieCaoVideoPlayer#894]
1.打开直播页面，可以正常播放
2.用户点击stop button，JCVideoPlayer.release();来停止直播视频
3.用户点击resume button,再次走setUP方法的时候出错

 onError -2147483648 - 0 [71868782]

**Comment by weixinjie** [comment]
找了个比较扯的解决方法，点击stop button的时候  JCMediaManager.instance().releaseMediaPlayer();
不过这样貌似在getDuration方法的时候死循环了  麻烦作者看下吧

**Comment by lipangit** [comment]
解决了就好
