### ISSUE TITLE
可不可以让用户点击了播放按钮之后再setup()?

### ISSUE THREAD

**Issue by zhouyiting666** [lipangit/JieCaoVideoPlayer#895]

**Comment by lipangit** [comment]
当前的逻辑是不可以，setUp之后才知道url，用户点击了开始还不知道视频的地址呢。

**Comment by liugongce** [comment]
自己给个缩略图,播放按钮是自己的,用户电你播放按钮,然后再执行setup,直接startvideo应该就可以了吧

**Comment by lipangit** [comment]
也可以，你把播放按钮的逻辑掏出来，点了播放按钮之后先setUp，再执行播放的逻辑
