### ISSUE TITLE
官方apk的demo在4.1.1、4.4.4、5.0.0模拟器下播放不了，咋回事？

### ISSUE THREAD

**Issue by beelzebub2006** [lipangit/JieCaoVideoPlayer#897]
官方apk的demo在4.1.1、4.4.4、5.0.0的genymotion模拟器下播放不了，咋回事？

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/26231819/4072dd66-3c84-11e7-9553-b9cfd9c3bfbf.png)

模拟器缺东西

**Comment by beelzebub2006** [comment]
是的，用真机好的，谢谢。
