### ISSUE TITLE
如何确定是第几个item在播放呢？

### ISSUE THREAD

**Issue by umeitime** [lipangit/JieCaoVideoPlayer#899]
我的listview里面如果要删除第一个item,第一个正在播放，我要停止播放，但是我不知道是第几个item在播放？而且从JCVideoPlayer里面也拿不到播放的url或者播放有没有在播放的状态等信息。

**Comment by lipangit** [comment]
这个需求只能你自己做标记，库里没有相关的支持

**Comment by umeitime** [comment]
@lipangit 那播放状态的回调应该有的吧~

**Comment by lipangit** [comment]
有 继承JCVideoPlayerStandard 复写setUiandState函数
