### ISSUE TITLE
今日头条全屏时bottomcontrol的布局和非全屏时不同

### ISSUE THREAD

**Issue by lipangit** [lipangit/jiecaovideoplayer#9]
需要不同的布局文件

**Comment by lipangit** [comment]
![image](https://cloud.githubusercontent.com/assets/2038071/13309754/80868ca8-dbba-11e5-8620-ae4ddc5a713c.png)

全屏之后bottomcontrol中的控件间隔小了

**Comment by ehaahe** [comment]
我也需要这样的效果，不知能否实现？

**Comment by ehaahe** [comment]
想在全屏后添加可以切换码率的功能，不知道怎么实现？

**Comment by lipangit** [comment]
切换码率本质上是能切换多个视频地址，对不对

**Comment by ehaahe** [comment]
是的，本质上是这样

**Comment by lipangit** [comment]
嗯 是个需求

**Comment by lipangit** [comment]
fullscreen buttom ui complet
