### ISSUE TITLE
切换到全屏的时候，声音和图像都会停顿一下

### ISSUE THREAD

**Issue by iceAnson** [lipangit/JieCaoVideoPlayer#90]
切换到全屏的时候，声音和图像都会停顿一下，然而今日头条很流畅；我看了下代码，不是很明白，为什么要在JCFullActivity里重新构造JSPlayer呢。这样就从头开始走了；

**Comment by lipangit** [comment]
头条确实很流畅，但是不知道头条是怎么做的T_T，如果有什么新发现一起交流

**Comment by lipangit** [comment]
头条是横屏，重新布局，正在研究
