### ISSUE TITLE
JieCaoVideoPlayer的点击播放监听

### ISSUE THREAD

**Issue by ASheng-Bisheng** [lipangit/JieCaoVideoPlayer#901]
我想重写JCVideoPlayerStandard里面的thumbImageView（点击播放按钮）点击方法，要怎么弄，我看到上面没有设置thumbImageView重写的方法啊

**Comment by lipangit** [comment]
重写thumbImageView是什么意思，这只是个普通的ImageView，你可以完全隐藏这个ImageView，新加一个新的控件

**Comment by ASheng-Bisheng** [comment]
我的意思是我重写父类的JCVideoPlayer点击播放的事件方法，但是子类重写的点击事件并未执行，然后v.getId() ==的是原父类的 start 的 id 我想在点击播放的时候加其他的事件，但是重写不了。

**Comment by ASheng-Bisheng** [comment]
![image](https://cloud.githubusercontent.com/assets/20983615/26300492/d5a09d0e-3f10-11e7-89a5-476a7b02ce32.png)
