### ISSUE TITLE
全屏的时候怎么自动播放下一集

### ISSUE THREAD

**Issue by liuchenyang** [lipangit/JieCaoVideoPlayer#902]
当前处于小屏的不是全屏的时候我MyJCVideoPlayerStandard继承JCVideoPlayerStandard，重写了setUiWitStateAndScreen（方法）
    @Override
    public void setUiWitStateAndScreen(int state) {
        super.setUiWitStateAndScreen(state);
        switch (currentState) {
            case CURRENT_STATE_AUTO_COMPLETE:
                setUp("http://2449.vod.myqcloud.com/2449_22ca37a6ea9011e5acaaf51d105342e3.f20.mp4",
                        JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "哎呦喂");
                startButton.performClick();
                break;
        }
    }

这个可以自动播放下一集，但是全屏的时候播放完之后就直接返回小屏，并且也不会自动播放下一集，请问怎么解决

**Comment by lipangit** [comment]
如果你们播放的不是连续剧而是类似头条那样的小视频，你应该和产品据理力争，干掉这个功能。

你贴出来的代码思路没有问题，自动播放完设置新的视频地址，把setUp的第二个参数改成JCVideoPlayerStandard.SCREEN_LAYOUT_FULLSCREEN试试

**Comment by liuchenyang** [comment]
试了  还是不行   现在功能其实就是相当于连续剧的那种 ，  视频很长，是把一个视频分成好多个小视频的

**Comment by lipangit** [comment]
卡在哪步，前一个视频的结束能监听到吧，然后不退出全屏，设置url，开始播放下一个视频

**Comment by qinyang1018** [comment]
@lipangit  我现在也有类似的需求  视频的结束通过重写onAutoCompletion  监听到了
但是不退出全屏怎么控制呢?  这个没找到解决办法。
@liuchenyang   你解决了吗？

**Comment by lipangit** [comment]
@qinyang1018 onAutoCompletion里不调用super方法，写自己的方法可以吗

**Comment by qinyang1018** [comment]
@lipangit 可以  但是我在onAutoCompletion通过自己的接口回调，从列表到全屏后set的接口变成空了？

**Comment by lipangit** [comment]
set的接口是哪个，setUp吗

思路就是播放完成之后，拦截原有的逻辑，通过setUp设置新的视频地址，调用播放函数开始播放。

**Comment by qinyang1018** [comment]
```java
public class VideoPlayer extends JCVideoPlayerStandard {

    private onComletionListener mOnComletionListener;

    public VideoPlayer(Context context) {
        super(context);
    }

    public VideoPlayer(Context context, AttributeSet attrs) {
        super(context, attrs);
        KLog.e("初始化videoPlayer");
    }

    @Override
    public void onAutoCompletion() {
//        super.onAutoCompletion();
        if (mOnComletionListener != null) {
            mOnComletionListener.onAutoCompletion();
        }
        if(currentScreen ==SCREEN_WINDOW_FULLSCREEN){
            fullscreenButton.setImageResource(R.drawable.jc_shrink);
        } else

        {
            fullscreenButton.setImageResource(R.drawable.jc_enlarge);
        }
    }

    @Override
    public void setUiWitStateAndScreen(int state) {
        super.setUiWitStateAndScreen(state);
    }

    public void setComletionListener(onComletionListener mOnComletionListener) {
        this.mOnComletionListener = mOnComletionListener;
    }

    public interface onComletionListener {
        void onAutoCompletion();
    }
}
```

我在列表的adapter中设置```setComletionListener```,   ``` if (mOnComletionListener != null) {
            mOnComletionListener.onAutoCompletion();
        }```回调正常。
但是全屏后mOnComletionListener变为null了

**Comment by lipangit** [comment]
全屏和非全屏是两个不同jcvd，他们是两个实例。

如果想在全屏和非全屏之间传递参数参照setUp(... objects)的最后一个参数objects，把你想要的参数放到这里，可以实现全屏和非全屏间的传递

**Comment by lizilindea** [comment]
@qinyang1018 请问你这个问题解决了吗

**Comment by qinyang1018** [comment]
@lizilindea 解决了

**Comment by NoEndToLF** [comment]
@qinyang1018 能分享一下你是怎么解决的吗，万分感谢！我现在可以连续播放，但是全屏的时候就不行了

**Comment by qinyang1018** [comment]
@NoEndToLF o   你现在应该是全屏播放完会自己关闭全屏吧？我是改了代码

**Comment by zzh12138** [comment]
@qinyang1018 可以具体说下怎么解决的吗，我现在重写了onAutoCompletion()方法，全屏播放完了不会退出全屏了，然后再onStateAutoComplete()方法里面重新设置uri，调用start方法，然后播放器就自动退出全屏了，方便的话可以交流一下吗

**Comment by qinyang1018** [comment]
@zzh12138  不好意思 最近忙才来回答  重新设置完url后 要判断下现在如果是全屏 就直接调用 直接全屏播放的那个那个方法
