### ISSUE TITLE
How to remove cancel or back view while video fetching.

### ISSUE THREAD

**Issue by ShantiRanjanDas** [lipangit/JieCaoVideoPlayer#905]
While loading video, video-view is showing a cross and back button in top left corner. How to hide this views while loading ?

Here is an [screen shot](https://cloud.githubusercontent.com/assets/28480802/26294593/8f24dd1e-3ee2-11e7-9533-ae1f84276288.png) of it.

**Comment by lipangit** [comment]
This phenomena is not call setUp(). Call setUp() will see thumbnail and not see top left corner icons.

**Comment by ShantiRanjanDas** [comment]
Here is, what I have implemented. And I have used setUp only.

mJcVideoPlayerStandard.setUp(bundle.getString(ValueConstants.VIDEO_LINK),
JCVideoPlayerStandard.SCREEN_WINDOW_FULLSCREEN, "");
        Picasso.with(TrailerActivity.this).load(bundle.getString(ValueConstants.IMAGE_URL))
                .placeholder(ContextCompat.getDrawable(TrailerActivity.this, R.drawable.large_lanscape))
                .error(ContextCompat.getDrawable(TrailerActivity.this, R.drawable.large_lanscape))
                .into(mJcVideoPlayerStandard.thumbImageView);

**Comment by lipangit** [comment]
after setUp() it should in CURRENT_STATE_NORMAL state, then it will call setUiWitStateAndScreen , this function control the ui. you can break point that function, and check currentState.
