### ISSUE TITLE
有些机型不能播放视频问题

### ISSUE THREAD

**Issue by powerwolfman** [lipangit/JieCaoVideoPlayer#906]
暂时发现是小米note还有oppoR9s不能播放视频，不知道是手机的问题还是别的问题，可比可以麻烦解答一下，谢谢！

**Comment by lipangit** [comment]
视频格式是什么，你下载节操精选app试试里面的视频能播放吗

**Comment by a327037419** [comment]
66大屏平板TV 不能播放
