### ISSUE TITLE
由于动态添加SurfaceView，会在进入activity时导致闪烁一下

### ISSUE THREAD

**Issue by wangyi1993** [lipangit/JieCaoVideoPlayer#91]
我通过这篇文章解决了问题 http://blog.csdn.net/hym2111/article/details/50424720

**Comment by lipangit** [comment]
多谢你的关注

你用的时候会闪烁吗，SurfaceView刚开始在布局文件里就有了，如果退出全屏继续播放的时候，检测到列表中surfaceview没调用SurfaceCreate，就会在代码动态添加SurfaceView，整个过程应该不会闪烁

**Comment by wangyi1993** [comment]
不知道为什么 我发现你们自己的app确实没有闪烁  但是我在fragment 和activity中都会出现闪烁        然后通过在actvity 的oncreate方法中  添加这行代码 getWindow().setFormat(PixelFormat.TRANSLUCENT);解决了闪烁的问题

**Comment by lipangit** [comment]
你是怎么集成的呀，请参照DEMO中
fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardShowShareButtonAfterFullscreen.java
使用，如果设成translucent，在后退的时候会提前看到透明的桌面吧，或者上个activity吧

**Comment by lipangit** [comment]
不应该让用户添加getWindow().setFormat(PixelFormat.TRANSLUCENT);这种累赘的代码
3.2已经release了，试试

**Comment by wangyi1993** [comment]
好的 我明天试试

**Comment by UC10D** [comment]
surfaceview  的问题，可以在开屏页加个 宽高都为0 的 surfaceview

**Comment by lipangit** [comment]
目前没发现闪的情况
