### ISSUE TITLE
dalvikvm: 'android.media.PlaybackParams'.

### ISSUE THREAD

**Issue by ABBIGADDU** [lipangit/JieCaoVideoPlayer#910]
i am getting this error ..

dalvikvm: Could not find class 'android.media.PlaybackParams', referenced from method com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.handleMessage

this is the log i am getting..

05-24 02:42:33.565 271-3154/? E/AudioFlinger: no more track names available
05-24 02:42:33.565 597-1094/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:33.565 597-1094/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:33.881 271-622/? E/AudioFlinger: no more track names available
05-24 02:42:33.881 597-1094/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:33.889 597-1094/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:33.909 271-3154/? E/AudioFlinger: no more track names available
05-24 02:42:33.909 597-1094/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:33.913 597-1094/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:33.921 271-622/? E/AudioFlinger: no more track names available
05-24 02:42:33.921 597-1094/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:33.925 597-1094/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:33.945 271-3154/? E/AudioFlinger: no more track names available
05-24 02:42:33.945 597-649/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:33.945 597-649/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:34.241 271-622/? E/AudioFlinger: no more track names available
05-24 02:42:34.241 597-649/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:34.241 597-649/system_process E/SoundPool: Error creating AudioTrack
05-24 02:42:34.245 271-271/? E/AudioFlinger: no more track names available
05-24 02:42:34.249 597-649/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
05-24 02:42:34.249 597-649/system_process E/SoundPool: Error creating AudioTrack

the video is not playing ..

class on backpressed listener is not responding from jcvideoplayer 
@Override
    public void onBackPressed() {
        DrawerLayout drawer = (DrawerLayout) findViewById(R.id.drawer_layout);
        try {
            sensorManager.unregisterListener(sensorEventListener);
            JCVideoPlayer.releaseAllVideos();

        } catch (Exception je) {
            je.printStackTrace();
        }

        if (JCVideoPlayer.backPress()) {

            return;
        } else {
            moveTaskToBack(true);
            android.os.Process.killProcess(android.os.Process.myPid());
            System.exit(1);
       
        }
        super.onBackPressed();
    }

it's returns the my main screen not from the player returns.. 

give the solutions...!

**Comment by lipangit** [comment]
Exoplayer for disqualification, new edition for appeal

**Comment by ABBIGADDU** [comment]
Then what i have to do for that ...!

**Comment by lipangit** [comment]
use version 5.5.4
