### ISSUE TITLE
小米note lte无法横屏

### ISSUE THREAD

**Issue by ZhenMrLee** [lipangit/JieCaoVideoPlayer#912]
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

**Comment by lipangit** [comment]
不知道原因，持续关注
