### ISSUE TITLE
如何让视频充满控件

### ISSUE THREAD

**Issue by 694177407** [lipangit/JieCaoVideoPlayer#915]
我的JCVideoPlayerStandard的width是720，height是480。但是我的视频是竖着的，在listview的列表中小屏播放竖向视频的时候，两边都有黑边。请问大神大大，如何设置，才能截取视频中间部分，让视频充满这个JCVideoPlayerStandard控件啊

**Comment by lipangit** [comment]
没研究过视频截取，我这边没什么好办法

**Comment by 694177407** [comment]
好的，多谢，我在研究研究

**Comment by cgztzero** [comment]
是想做新浪微博在列表里播放的样式吗？那个需要修改JCResizeTextureView的onMeasure方法就可以了

**Comment by 694177407** [comment]
多谢

**Comment by wonTonx** [comment]
我觉得他说的截图中间部分 不是视频中段的意思 而是画面吧 就是想实现想imageview的center-crop的效果

**Comment by ldy441040480** [comment]
1、TextureView 的onMeasure中按照视频的宽高以及屏幕宽算出自己想要展示的视图大小 setMeasuredDimension(height, width)
2、layout(int left, int top, int right, int bottom)
super.layout(left, top, right, bottom)
中可以调整视频显示的位置
