### ISSUE TITLE
在电视上使用的时候如何用遥控器控制快进快退呢？

### ISSUE THREAD

**Issue by whatisjava** [lipangit/JieCaoVideoPlayer#917]
如题

**Comment by lipangit** [comment]
没试过在电视上播放的情况，是否可以自定义事件，先收到遥控器的快进快退事件就好办了，然后自己的代码里控制进退

**Comment by whatisjava** [comment]
嗯，我现在的困惑点是在我用遥控器拖动seekbar的时候如何暂停掉播放，等我停止拖动的时候再定位到新位置继续播放，参考了onTouch里面的处理，感觉还是没有找到关键点，现在的现象就是我左右快进快退的时候seekbar那个小圆点总是来回移动

**Comment by lipangit** [comment]
是不是可以不去直接操作进度条，直接seekMediaPlayer的进度，进度条会自动修改到正确的时间的。

**Comment by whatisjava** [comment]
噢，果然可以，非常感谢！

**Comment by Loyea** [comment]
@whatisjava 你好，我也遇到了这样的需求，想请教你一下。可以给个联系方式吗？ 或者劳烦您加我一下qq 573零5974零  谢谢了

**Comment by whatisjava** [comment]
把你的问题就在这里说吧 @Loyea
