### ISSUE TITLE
华为 荣耀 v9 系统版本 7.0 播放视频 出现Error(1,-1004)

### ISSUE THREAD

**Issue by NutBear** [lipangit/JieCaoVideoPlayer#918]
测试机是5.1.1的系统，没有问题，缓存进度会自动加载。使用模拟器测试 是7.0  出现Error(1,-1004) 几率极高 几乎100%  感觉此问题和7.0系统有关，现在7.0系统使用量开始增长，建议作者尽快解决此问题。

**Comment by lipangit** [comment]
别用模拟器测试，模拟器缺东西 https://github.com/lipangit/JieCaoVideoPlayer/issues/897

**Comment by NutBear** [comment]
@lipangit 恩 但是用户的荣耀 v9 出现了那种错误 而且是不同的视频 我上午租了v9云真机 也是出现的那个问题
