### ISSUE TITLE
视频播放完毕后 ，手动调整进度条到中间，点击播放，视频还是从头播放

### ISSUE THREAD

**Issue by ZhenMrLee** [lipangit/JieCaoVideoPlayer#919]
如题

**Comment by lipangit** [comment]
没错，是这样的

**Comment by ZhenMrLee** [comment]
能解决嘛

**Comment by lipangit** [comment]
暂时不认为这是个问题，如果你有这个需求也能做。

在播放完成的状态修改进度条就去修改seekToInAdvance变量，这个变量就是控制视频缓冲结束后从哪里开始播放，估计能解决你的问题。

**Comment by ZhenMrLee** [comment]
这个我感觉不太友好，我还改不好  这就扎心了

**Comment by lipangit** [comment]
能具体列出来吗，我也感觉有不少问题，正在酝酿解决

**Comment by ZhenMrLee** [comment]
就是播放完成后，拖动进度条无效
其他的都没什么问题

**Comment by lipangit** [comment]
恩，头条在播完会隐藏进度条，我们下一步会跟着修改。
