### ISSUE TITLE
unable to go to fullscreen, didnt modify anything.urgent,need help.

### ISSUE THREAD

**Issue by thegppradeep** [lipangit/JieCaoVideoPlayer#92]
The app crashes whenever i click on the fullscreen button 
i get java.lang.IllegalStateException 
at android.media.MediaPlayer.getCurrentPosition(Native Method)
at JCVideoPlayer.setTextAndProgress(JCVideoPlayer.java:586)
at JCVideoPlayer$1$1.run(JCVideoPlayer.java:569)

**Comment by lipangit** [comment]
I think videoplayer is preparing , then getCurrentPosition , some phone will onError(-38 , 0) but other phone like yours will crash.

Next version v3.2 will release in 2 days , it will fix your problem.

Thank your feedback.

**Comment by lipangit** [comment]
release v3.2
