### ISSUE TITLE
HLS

### ISSUE THREAD

**Issue by SnowsonZ** [lipangit/JieCaoVideoPlayer#920]
支持hls流视频吗？

**Comment by lipangit** [comment]
支持 https://developer.android.com/guide/appendix/media-formats.html

**Comment by SnowsonZ** [comment]
我直接传m3u8文件地址，播放不了

**Comment by lipangit** [comment]
超出了我的解决范围

**Comment by SnowsonZ** [comment]
播放HLS流视频应该传m3u8的地址吗，还是应该怎么使用？

**Comment by SnowsonZ** [comment]
更换了5.1.2版本后可以播放

**Comment by lipangit** [comment]
系统播放器对m3u8支持不怎么好
