### ISSUE TITLE
有虚拟键的手机上并不是真的全屏播放

### ISSUE THREAD

**Issue by littlegreatness** [lipangit/JieCaoVideoPlayer#921]
有虚拟键的手机上并不是真的全屏播放,参考了今日头条，他们的是连虚拟键也给隐藏了的

**Comment by lipangit** [comment]
当前全屏的时候，头条能通过手势再把虚拟按键调出来吗？

**Comment by ymw2017** [comment]
请问楼主虚拟按键怎么隐藏的？

**Comment by lipangit** [comment]
你的什么现象，虚拟按键不会隐藏吗

**Comment by littlegreatness** [comment]
全屏播放的是调用hide的方法：
` /**
     * 隐藏虚拟按键，并且全屏
     */
    public static void hideNavigationBar(Activity activity) {
        int uiOptions = activity.getWindow().getDecorView().getSystemUiVisibility();
        int newUiOptions = uiOptions;

        boolean isImmersiveModeEnabled =
                ((uiOptions | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY) == uiOptions);
        //之前如果是IMMERSIVE状态，就不用再隐藏了
        if (!isImmersiveModeEnabled) {

            if (Build.VERSION.SDK_INT >= 14) {
                newUiOptions |= View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
            }

            if (Build.VERSION.SDK_INT >= 16) {
                newUiOptions |= View.SYSTEM_UI_FLAG_FULLSCREEN;
            }
            if (Build.VERSION.SDK_INT >= 18) {
                newUiOptions |= View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
            }

            activity.getWindow().getDecorView().setSystemUiVisibility(newUiOptions);
        }
    }`
退出全屏的时候，再调用show的方法：
` /**
     * 显示虚拟按键
     */
    public static void showNavigationBar(Activity activity) {

        int uiOptions = activity.getWindow().getDecorView().getSystemUiVisibility();
        int newUiOptions = uiOptions;
        boolean isImmersiveModeEnabled =
                ((uiOptions | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY) == uiOptions);
        //之前如果是IMMERSIVE状态，就显示NavigationBar
        if (isImmersiveModeEnabled) {

            //先取 非 后再 与， 把对应位置的1 置成0，原本为0的还是0

            if (Build.VERSION.SDK_INT >= 14) {
                newUiOptions &= ~View.SYSTEM_UI_FLAG_HIDE_NAVIGATION;
            }

            if (Build.VERSION.SDK_INT >= 16) {
                newUiOptions &= ~View.SYSTEM_UI_FLAG_FULLSCREEN;
            }

            if (Build.VERSION.SDK_INT >= 18) {
                newUiOptions &= ~View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
            }
            activity.getWindow().getDecorView().setSystemUiVisibility(newUiOptions);

        }
    }`

**Comment by lipangit** [comment]
好的好的，能提交一个pr吗
