### ISSUE TITLE
小米4 android android版本：6.0.1

### ISSUE THREAD

**Issue by zhimeiyue** [lipangit/JieCaoVideoPlayer#925]
小米4 android android版本：6.0.1，点击播放视频，一直在转菊花，播放不了。
在红米手机（android 5.0）就可以。
但是我运行了你的demo，小米4是可以播放的，这个怎么回事啊？？

**Comment by lipangit** [comment]
应该是本身没什么问题，是不是你引用有问题，断点一下MediaPlayer是否工作

**Comment by zhimeiyue** [comment]
@lipangit 

断点，发现MediaPlayer没启动。没有运行下面的方法：
`   public JCMediaManager() {
        mMediaHandlerThread = new HandlerThread(TAG);
        mMediaHandlerThread.start();
        mMediaHandler = new MediaHandler((mMediaHandlerThread.getLooper()));
        mainThreadHandler = new Handler();
    }`

是什么原因造成的？？

**Comment by zhimeiyue** [comment]
@lipangit

断点，发现MediaPlayer没启动。断点发现没运行MediaHandler这个类。

是什么原因造成的？？

**Comment by zhimeiyue** [comment]
原来是，在JCMediaManager的onSurfaceTextureAvailable的方法没调用。

在Activity里加下面的代码，就可以了：
Window w = this.getActivity().getWindow();		w.setFlags(WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);

开启硬件加速，问题解决了，但是不知道会不会有影响。

感谢 @lipangit

**Comment by lipangit** [comment]
么么哒
