### ISSUE TITLE
开源精神值得鼓励 

### ISSUE THREAD

**Issue by wensefu** [lipangit/JieCaoVideoPlayer#926]
但是这个库坑略多。。。
代码架构还有比较多的改善空间。

**Comment by wensefu** [comment]
setAllControlsVisible  这个接口真的是设计的太草蛋了，这完全是只管今天不管明天的设计。

**Comment by wensefu** [comment]
试用半天后： 代码灵活性太差，不能忍受。
还是自己写吧！

**Comment by lipangit** [comment]
代码结构和接口设计的问题是一方面，以后努力改进。

你遇到了坑都有什么，能说说吗
