### ISSUE TITLE
怎样监听视频播放结束

### ISSUE THREAD

**Issue by AIlll** [lipangit/JieCaoVideoPlayer#927]
播放SD卡视频，如何监听播放结束

**Comment by AIlll** [comment]
播放结束是必须会再次竖屏吗，不能保持横屏吗

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写onAutoComplete函数，播放结束会退出全屏，你可以试试能不能拦截父类函数

**Comment by 18667366881** [comment]
大神   onAutoComplete函数  没找到

**Comment by lipangit** [comment]
onAutoCompletion

**Comment by 18667366881** [comment]
谢谢

**Comment by 18667366881** [comment]
嘻嘻  （继承JCVideoPlayerStandard，复写onAutoComplete函数，播放结束会退出全屏，你可以试试能不能拦截父类函数） 怎么重写 可以简单写一下吗？  谢谢

**Comment by lipangit** [comment]
onAutoCompletion里不是要super.onAutoCompletion()，不加这super就完了呗，再把super里的代码选择性的粘贴出来

**Comment by 18667366881** [comment]
了解  谢谢大神
