### ISSUE TITLE
youtube video??

### ISSUE THREAD

**Issue by vishalpatel1327** [lipangit/JieCaoVideoPlayer#93]
how to play youtube video in this library

like
[https://www.youtube.com/watch?v=BFyv2f4fTkU](url)

**Comment by lipangit** [comment]
Can you get that page mp4 address.

This library use android.media.MediaPlayer to play video.

Do you have example to play youtube video in android

**Comment by vishalpatel1327** [comment]
[](https://www.youtube.com/watch?v=4P27ASWMv9g)

this type of video

**Comment by lipangit** [comment]
It doesn't work .

**Comment by vishalpatel1327** [comment]
ohk thanks for quick responce you are great man

**Comment by lipangit** [comment]
Will continue focuse on this problem

**Comment by ravindu1024** [comment]
Hey @lipangit I know this is a closed request, but youtube links still don't play. Is this expected or would you be fixing it for html5 videos? Thanks!

**Comment by lipangit** [comment]
Show me a url on youtube please.

**Comment by ravindu1024** [comment]
Try this: https://www.youtube.com/watch?v=CUFsQ5lTo6g

**Comment by lipangit** [comment]
Which player can play this link？

**Comment by lipangit** [comment]
you can change mediaplayer engine by one line code.  jzvd.setMediaInterface();

Play that link is out of any player control.
