### ISSUE TITLE
设置 seekToInAdvance 没用作用

### ISSUE THREAD

**Issue by jingyuhai** [lipangit/JieCaoVideoPlayer#930]
jcVideoPlayerStandard.seekToInAdvance = 500;
设置之后点击播放，还是从头播放，我用的是最新的版本5.5.4。
"devBrand":"samsung"
"devModel":"SM-N9006"
系统5.0

**Comment by lipangit** [comment]
确实不好使，怎么办，JCMediaManager.instance().mediaPlayer.seekTo(seekToInAdvance);已经执行，但是不起作用

**Comment by scar1et** [comment]
@jingyuhai @lipangit 在onPrepared里面直接调用JCMediaManager.instance().mediaPlayer.seekTo(position)；
这样实测有效。

**Comment by jingyuhai** [comment]
非常感谢你的回答，我已经处理了，方法跟你提供的一样，谢谢！


来自 魅族手机

-------- 原始邮件 --------
发件人：scar1et <notifications@github.com>
时间：周五 6月30日 08:16
收件人：lipangit/JieCaoVideoPlayer <JieCaoVideoPlayer@noreply.github.com>
抄送：jingyuhai <jingyuhai2014@163.com>,Mention <mention@noreply.github.com>
主题：Re: [lipangit/JieCaoVideoPlayer] 设置 seekToInAdvance 没用作用 (#930)

**Comment by AnYuer** [comment]
大神，seekToInAdvance设置完时间点后，一开始展示了正确的时间，但是 一闪而过，立马往前推了好几秒，有时候甚至是往前十几秒，导致播放时间点不正确了，跪求帮助，该怎么在设置完时间点后，继续播放，而不是往前推。
