### ISSUE TITLE
如果要播放的时候让底部的所有按钮全部不显示该怎么做？

### ISSUE THREAD

**Issue by coolyunyun** [lipangit/JieCaoVideoPlayer#931]
我有个需求  播放10秒的短视频，就像微信朋友圈的那种，很短，只需要播放和暂停按钮就可以
底部的其他按钮都不需要( 顶多就放个全屏按钮 ) 请问该如何做？

**Comment by coolyunyun** [comment]
如何在播放的时候隐藏掉

**Comment by coolyunyun** [comment]
自己搞定了  
 videoplayer.totalTimeTextView.setVisibility(View.GONE);
                videoplayer.currentTimeTextView.setVisibility(View.GONE);
                videoplayer.progressBar.setVisibility(View.GONE);
                videoplayer.fullscreenButton.setVisibility(View.GONE);
擦  原来这么简单。。。

**Comment by lipangit** [comment]
么么哒
