### ISSUE TITLE
升级成5.5.4后报这个是什么东西

### ISSUE THREAD

**Issue by lizixian18** [lipangit/JieCaoVideoPlayer#932]
![image](https://cloud.githubusercontent.com/assets/16240767/26712586/35091a32-479a-11e7-8ec4-552ff78c93a9.png)

**Comment by lipangit** [comment]
是不是要升级项目的依赖版本

**Comment by LLhon** [comment]
我也遇到类似的问题,应该是minSdkVersion,targetSdkVersion与app下的build.gradle里的版本不一致导致

**Comment by lipangit** [comment]
应该是，项目里会和google发布的stable版本保持一致
