### ISSUE TITLE
fragment列表里面播放，点击全屏后把手机横屏就报这个错，在activity里面是没事的。

### ISSUE THREAD

**Issue by lizixian18** [lipangit/JieCaoVideoPlayer#933]
fragment列表里面播放，点击全屏后把手机横屏就报这个错，在activity里面是没事的
![image](https://cloud.githubusercontent.com/assets/16240767/26716250/4daf8f1a-47ab-11e7-9620-69744201dbe7.png)
报错位置：
![image](https://cloud.githubusercontent.com/assets/16240767/26716304/7d0c3dee-47ab-11e7-99da-5a2bb55c714c.png)

activity继承的是AppCompatActivity，fragment继承的是Fragment

**Comment by lipangit** [comment]
是新版吗，记得之前改过getPosition的问题

**Comment by lizixian18** [comment]
不是新版，5.5.2的，因为升级新版报了我提的那个错，就没升了

**Comment by lizixian18** [comment]
这个如果是bug的话，希望尽快修复，因为影响有点大(泪奔~)

**Comment by lipangit** [comment]
哥们，参照demo，fragment的onPause里不用调releaseAllVideos方法。

**Comment by lizixian18** [comment]
你demo里面全是activity啊

**Comment by lipangit** [comment]
只需要在包含fragment的activity里调用releaseAllVideos方法，fragment的onPause不用调用

**Comment by lizixian18** [comment]
在activity里也会哦，放不了图，复制下来：

 I/JieCaoVideoPlayer: onCompletion  [209169771] 
 W/System.err: java.lang.IllegalStateException
 W/System.err: at android.media.MediaPlayer.getCurrentPosition(Native Method)
 W/System.err: at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.getCurrentPositionWhenPlaying(JCVideoPlayer.java:720)
 W/System.err: at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.onCompletion(JCVideoPlayer.java:469)
 W/System.err: at fm.jiecao.jcvideoplayer_lib.JCVideoPlayerManager.completeAll(JCVideoPlayerManager.java:42)
 W/System.err: at fm.jiecao.jcvideoplayer_lib.JCVideoPlayer.releaseAllVideos(JCVideoPlayer.java:819)
 W/System.err: at com.appgame.differ.module.main.MainActivity.onPause(MainActivity.java:206)
 W/System.err: at android.app.Activity.performPause(Activity.java:6399)
 W/System.err: at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1322)
 W/System.err: at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3537)
 W/System.err: at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3510)
 W/System.err: at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4246)
 W/System.err: at android.app.ActivityThread.access$1000(ActivityThread.java:180)
 W/System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
 W/System.err: at android.os.Handler.dispatchMessage(Handler.java:111)
 W/System.err: at android.os.Looper.loop(Looper.java:207)
 W/System.err: at android.app.ActivityThread.main(ActivityThread.java:5710)
 W/System.err: at java.lang.reflect.Method.invoke(Native Method)
 W/System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
 W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by lizixian18** [comment]
在fragment里面播放横竖屏切换确实有问题，我新建一个项目来测也蹦了

**Comment by lipangit** [comment]
我在demo里加个fragment的例子试试

**Comment by teprinciple** [comment]
@lipangit 我恰好也遇见这个问题，麻烦帮忙看看

**Comment by lipangit** [comment]
demo已经更新，包含了fragment的demo
