### ISSUE TITLE
三星s8会出现播放的时候有声音，当时图像一直停留在加载的地方

### ISSUE THREAD

**Issue by Vikaso** [lipangit/JieCaoVideoPlayer#934]

**Comment by lipangit** [comment]
正常播放的时候，播放一会会没图像吗，log是什么

**Comment by rwz657026189** [comment]
我这边也刚刚收到反馈，三星s8不能播放视频

**Comment by Vikaso** [comment]
刚刚才拿到s8的手机，大概的定位了下，是可以播放的 就是因为上面的一层图片没有隐藏，导致覆盖了视频的

**Comment by lipangit** [comment]
顶住，有也是系统的坑

**Comment by liulance** [comment]
@lipangit 我这边也出现三星s8播放视频，只有声音，没有画面，一直在加载状态，运行的是github上面的demo

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27869693-4bdd1742-61d3-11e7-83ab-0ac197519c77.png)

这个就能解决问题，明天我测试一下，加到下个版本里

**Comment by liulance** [comment]
@lipangit 加上你说的方法，还是不行，不知道你验证了没

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/issues/938
