### ISSUE TITLE
自动连续播放视频问题

### ISSUE THREAD

**Issue by whatisjava** [lipangit/JieCaoVideoPlayer#935]
在自动连续播放视频的时候，第一个视频播完后开始播放第二个视频，第二个视频刚开始播放就收到播放结束的事件JCUserAction.ON_AUTO_COMPLETE，这是怎么回事呢？我是设置了 player.setJcUserAction(new MyUserActionStandard());

**Comment by whatisjava** [comment]
解决了，好像是因为我不正确使用了seektoinadvance这个变量所致。。

**Comment by whatisjava** [comment]
不能用seekToInAdvance这个变量来seekto mediaplayer吗？

**Comment by whatisjava** [comment]
连续播放的时候好像需要延时一下才能正常播放下一集，否则直接播放的话会播放失败

**Comment by lipangit** [comment]
seekToInAdvance这个目前有问题，MediaPlayer.seekTo不知道为什么不起作用
