### ISSUE TITLE
三星s8有声音没画面

### ISSUE THREAD

**Issue by Z008** [lipangit/JieCaoVideoPlayer#937]
进度条一直在转，有声音，但是没画面

**Comment by lipangit** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98  参照有声音无图像

**Comment by mastergyp** [comment]
一样遇到s8用户反馈，手机没有机器。

**Comment by Guoooooo** [comment]
请问是否解决
