### ISSUE TITLE
How to set temporary cache 

### ISSUE THREAD

**Issue by akhilesh0707** [lipangit/JieCaoVideoPlayer#939]
VideoPlayer load video every time when start playing

**Comment by lipangit** [comment]
no temporary, [this project](https://github.com/danikula/AndroidVideoCache) can set cache you can reference it, but that project is not perfect, so will not put it in jcvd.

**Comment by thealpha** [comment]
> VideoPlayer load video every time when start playing

did you solve the problem @akhilesh0707

**Comment by omidraha** [comment]
did you solve the problem @akhilesh0707 @thealpha @lipangit
