### ISSUE TITLE
点击播放按钮之后，能否不要显示控制界面？

### ISSUE THREAD

**Issue by axeon** [lipangit/JieCaoVideoPlayer#94]
点击播放按钮之后，能否不要显示控制界面？
这样子感觉怪怪的。。。虽然2500之后会自动隐藏。

另外，一些按钮和图标有些小了，是不是放错目录了？

**Comment by lipangit** [comment]
头条就是这样的，如果你有需要你可以参照demo中的fm.jiecao.jiecaovideoplayer.View.JCVideoPlayerStandardShowShareButtonAfterFullscreen.java去继承JCVideoPlayerStandard写自己的UI逻辑

图标问题，每个图标都在布局文件里都指定了他的宽和高，可以参照JCVideoPlayerStandardShowShareButtonAfterFullscreen.java完全重新定义UI，并且不需要写一行关于操作视频的代码，只需要完成ui逻辑和其他自己需要的功能
