### ISSUE TITLE
请问支持指定范围播放吗?

### ISSUE THREAD

**Issue by tianqiujie** [lipangit/JieCaoVideoPlayer#941]
需求是这样的  做视频截取  本地视频 比如指定中间某个时间段 然后就是播放这一段时间的视频? 我看有指定起始播放时间 没有限制终止播放时间?

**Comment by lipangit** [comment]
暂时没这个功能，你可以继承JCVideoPlayerStandard，复写setProgressAndText()在播放进度的回调里终止播放

**Comment by tianqiujie** [comment]
好的 谢谢大佬
