### ISSUE TITLE
在一个JCVideoPlayerStandard中自动连续播放多个视频

### ISSUE THREAD

**Issue by QinAndroid** [lipangit/JieCaoVideoPlayer#943]
在列表中每个Item是一个JCVideoPlayerStandard，能不能让JCVideoPlayerStandard连着自动连续播放多个视频？

**Comment by lipangit** [comment]
像微博和空间那样吧。继承JCVideoPlayerStandard，复写onAutoComplete函数能取得播放完毕，startButton.performClick()能播放视频，至于播放哪个视频需要你自己研究了。

**Comment by cjjwzj** [comment]
@lipangit 大神startButton.performClick()这个方法是模拟点击 如果手机开启了点击反馈音 是会有点击音效的 ,有没有直接开始播放的方法>?

**Comment by lipangit** [comment]
不确定是否有音效，按钮监听调用的代码就是直接播放的代码，复制一下就好，主要是两个部分，一加载MediaPlayer 二是修改ui
