### ISSUE TITLE
5.5.4版本，mp4格式可以播放，rmvb格式无法播放

### ISSUE THREAD

**Issue by AndroidHensen** [lipangit/JieCaoVideoPlayer#948]
亲测好多遍，mp4格式可以播放，rmvb不可以播放，给作者一个测试的api

mp4（能播放）：http://218.15.154.154:8081/upload/2017/05/05/590c7ba4b5b06.mp4
rmvb（不能播放）：http://218.15.154.154:8081/upload/2017/06/06/59367da1af5ba.rmvb

麻烦作者测试一下

**Comment by lipangit** [comment]
不支持rmvb https://developer.android.com/guide/appendix/media-formats.html
