### ISSUE TITLE
RecyclerView展示时能禁用全屏按钮吗？或者让全屏按钮小时

### ISSUE THREAD

**Issue by MarkerBrother** [lipangit/JieCaoVideoPlayer#949]
现在不想列表展示时候出现全屏按钮，只是展示一个列表

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写setUiWitStateAndScreen()，在这个函数里隐藏全屏按钮
如果不想隐藏，复写setUp函数，disable全屏按钮。

**Comment by MarkerBrother** [comment]
谢谢啊，给隐藏了
