### ISSUE TITLE
demo中viewpager部分，感觉左右滑动特别卡

### ISSUE THREAD

**Issue by axkza** [lipangit/JieCaoVideoPlayer#95]
没有之前下载的eclipse版本的demo流畅（com.jc.videoplayer），很明显感觉出卡顿
主要是现在的demo运行之后，能感觉到按住屏幕左右拖动，图片貌似失真抖动？

**Comment by lipangit** [comment]
这个没有eclipse版本呀

demo为什么会卡呢，demo特简单没有别的逻辑，你有啥发现吗

**Comment by axkza** [comment]
http://dl.download.csdn.net/down11/20160418/3e707b78f4eba6324d228d7b8263069a.zip?response-content-disposition=attachment%3Bfilename%3D%22JCVideoPlayerDemo.zip%22&OSSAccessKeyId=9q6nvzoJGowBj4q1&Expires=1463113697&Signature=96rAGUozhekTZUoYaKSmGkggWYk%3D
下载这个demo，是eclipse版本的，可能是网友友情编写的，我的项目引用里面的src/lib文件，在viewpager中滑动就特别顺畅，刚刚用了3.1版本的JieCaoVideoPlayer后自己的程序左右滑动有点卡卡的

**Comment by lipangit** [comment]
那个地址的是2.0版本，3.0版本多了自定义UI功能，逻辑基本没变，按照你描述的情况我好像也没啥办法

**Comment by lipangit** [comment]
要么你加我微信吧 发个小视频看看，  lipanhelloworld

**Comment by axkza** [comment]
已加

**Comment by lipangit** [comment]
兄弟看了小视频之后，发现虽然差距非常细微，但是仔细想想之后认为这里的猫腻非常深，已经列入工作计划，感谢你的反馈。

**Comment by lipangit** [comment]
哥们你的发现堪称传奇! 
头条不抖，很有可能是surfaceview的问题，这几天必将仔细研究

**Comment by lipangit** [comment]
done in branch feature/make_ui_smooth

**Comment by lipangit** [comment]
release 3.2

**Comment by lipangit** [comment]
这个问题让我对流畅和surfaceview有了更高级的认识，感谢你的反馈
