### ISSUE TITLE
ViewPager Fragment左右切换时候没有停止播放

### ISSUE THREAD

**Issue by MarkerBrother** [lipangit/JieCaoVideoPlayer#950]
这个该怎么解决呢？我切换其他界面再返回来发现还正在播放。应该是我去其它界面时候停止播放的吧。

**Comment by lipangit** [comment]
参照demo，viewpager的滑动监听停止播放视频。activity的onPause停止播放视频。

**Comment by MarkerBrother** [comment]
那我先把这边demo给跑起来。。。

**Comment by lipangit** [comment]
可以直接下载demo apk

**Comment by MarkerBrother** [comment]
demo我这里总是超时，下载不下来。你那边有现成的吗？





夕阳最美时，也总是将近黄昏。
  
世上有很多事都是这样子的，尤其是一些特别辉煌美好的事。 

所以你不必伤感，也不用惋惜，纵然到江湖去赶上了春，也不必留住它。 

因为这就是人生，有些事你留也留不住。 

你一定要先学会忍受它的无情，才会懂得享受它的温柔。
 
发件人： Nathen
发送时间： 2017-06-13 19:58
收件人： lipangit/JieCaoVideoPlayer
抄送： nan_shen; Author
主题： Re: [lipangit/JieCaoVideoPlayer] ViewPager Fragment左右切换时候没有停止播放 (#950)
可以直接下载demo apk

**Comment by lipangit** [comment]
[lantern](https://github.com/getlantern/lantern)翻墙试试
