### ISSUE TITLE
Player was not playing the videos

### ISSUE THREAD

**Issue by ABBIGADDU** [lipangit/JieCaoVideoPlayer#951]
JCVideoPlayer is not playing for some videos i am getting the no url error ...

below log is for your references....

E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: Attempt to call getDuration without a valid mediaplayer
E/MediaPlayer: error (-38, 0)
E/MediaPlayer: Error (-38,0)
E/MediaPlayer: Error (-38,0)
E/JieCaoVideoPlayer: onError 1 - -2147483648 [1411827676] 
E/JieCaoVideoPlayer: onError -38 - 0 [1411827676] 
E/JieCaoVideoPlayer: onError -38 - 0 [1411827676]

**Comment by hardikJoshi123** [comment]
I am having same issue. Can you please suggest anything ?

**Comment by ABBIGADDU** [comment]
no idea.. i complete total app except this one...

**Comment by hardikJoshi123** [comment]
I downloaded demo and replaced my URL with existing, and same issue. I am getting same errors like above mentioned by @ABBIGADDU

**Comment by lipangit** [comment]
maybe something wrong with server or video.

**Comment by ABBIGADDU** [comment]
No I check with everything ... that is player problem

**Comment by hardikJoshi123** [comment]
Yup I agree with @ABBIGADDU  Here is my video URL : https://s3.amazonaws.com/blastchat/BlastVideos/CD0C3074-F35B-4F6B-B554-04ECC44F5814.MOV

**Comment by lipangit** [comment]
@hardikJoshi123 your url is ok, as I have tryed

**Comment by ABBIGADDU** [comment]
@Nathen yes nathen i am also facing the same problem so please solve it
ASAP...



Thanks & Best Regards,
Aravind.V
91-9491445710
91-7386164491

**Comment by hardikJoshi123** [comment]
Hello @lipangit  you mean video played successfully if you replace URL in demo with my URL ? :O

**Comment by lipangit** [comment]
@hardikJoshi123 your url in demo played well

**Comment by hardikJoshi123** [comment]
Hello @lipangit  I am using "JieCaoVideoPlayer-develop" project. and it show error, do i require to download other branch?

**Comment by hardikJoshi123** [comment]
**jcvideoplayer-lib** version : 

 versionCode 30
        versionName "3.6.2"

 Is it latest?

**Comment by lipangit** [comment]
5.5.4 is latest

**Comment by ABBIGADDU** [comment]
in latest 5.5.4 version also i am getting same issue ...


Thanks & Best Regards,
Aravind.V
91-9491445710
91-7386164491

**Comment by hardikJoshi123** [comment]
Yup dont know why it show error :(

**Comment by ABBIGADDU** [comment]
ignore the error i want just play the video .... that one also not working
....


Thanks & Best Regards,
Aravind.V
91-9491445710
91-7386164491

**Comment by hardikJoshi123** [comment]
I also tried with gradle. 
` compile 'fm.jiecao:jiecaovideoplayer:5.5.4'`


```
videocontroller1.setUp(https://s3.amazonaws.com/blastchat/BlastVideos/CD0C3074-F35B-4F6B-B554-04ECC44F5814.MOV,
                            JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");
```

Same errors as my screenshot

**Comment by cjjwzj** [comment]
@ABBIGADDU @hardikJoshi123 Samsung s8?

**Comment by ABBIGADDU** [comment]
In all mobiles I am verifying

**Comment by hardikJoshi123** [comment]
I am testing in RedMi note3, is this device specific issue? :O

**Comment by ABBIGADDU** [comment]
No all mobiles I tested same issue

**Comment by hardikJoshi123** [comment]
Don't know wht to do

**Comment by ABBIGADDU** [comment]
Are else guide me the same type of library guys....!

>

**Comment by hardikJoshi123** [comment]
Try with this : https://github.com/google/ExoPlayer
