### ISSUE TITLE
如果在列表只显示缩略图 点击后播放全屏

### ISSUE THREAD

**Issue by CodeToxicant** [lipangit/JieCaoVideoPlayer#952]
如果在列表只显示缩略图 点击后播放全屏的话 如何搞
还有就是 全屏哪个界面可以自定义吗？还是自己写一个仿控件的界面

**Comment by lipangit** [comment]
列表显示图片，这个图片和播放器没有关系，然后点击图片后参照demo的playDirectlyWithoutLayoutActivity，直接全屏播放
