### ISSUE TITLE
请问该视频播放控件是基于Bilibili/ijkplayer吗？编解码用的是FFmpeg吗？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JieCaoVideoPlayer#955]

**Comment by longzekai** [comment]
我也想了解下，节操播放器的解码能力如何。

**Comment by DB-boy** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/blob/develop/README-ZH.md

**Comment by StevenNick88** [comment]
https://github.com/lipangit/JieCaoVideoPlayer/blob/develop/README-ZH.md   这上面只说了使用的是系统的MediaPlayer，并未提及编解码，是使用google原生的编解码吗？

**Comment by lipangit** [comment]
https://developer.android.com/guide/appendix/media-formats.html 编解码参照这里
