### ISSUE TITLE
为什么我监听Item的 position打印不怎么正确 有时.我item有很多样式

### ISSUE THREAD

**Issue by lichafeng** [lipangit/JieCaoVideoPlayer#956]
viewHolder4.videoPlay.setJcUserAction(new JCUserAction() {
                    @Override
                    public void onEvent(int type, String url, int screen, Object... objects) {
                        Log.e("videoImage", "position=" + i);

**Comment by lipangit** [comment]
setJCUserAction这是全局函数，用来监听用户的操作事件，这是专门给友盟等事件统计用的，不能写其他逻辑。

**Comment by lichafeng** [comment]
那我在listView  怎么获取播放的postition 位置?

**Comment by lipangit** [comment]
目前的代码结构取得不了，要自己设置了

**Comment by lichafeng** [comment]
提供下思路 在播放item 看不见的时候 我想让他停止播放

**Comment by lipangit** [comment]
这也是我一直想做的，以前做了一半卡在无法得到这个item看不见的回调，通过各种办法都取得不到一个item不可见。
