### ISSUE TITLE
项目中使用5.5.4，三星note3手机，播放m3u8格式的视频，会出现花屏、黑屏，拖动seekbar有时出现卡屏。

### ISSUE THREAD

**Issue by DB-boy** [lipangit/JieCaoVideoPlayer#958]
如题，想了解下有没有解决方法，或者优化方法、

**Comment by StevenNick88** [comment]
有没有url地址，贴一个我测试下，我这边除了wmv，vob , swf，其它都能播放

**Comment by lipangit** [comment]
老臣对视频格式研究不深，解决这些问题无能为力啊，用的都是系统的api

**Comment by DB-boy** [comment]
@StevenNick88 demo里面有m3u8格式的，我这都是内部的链接，不好给你。
