### ISSUE TITLE
头条视频中点击某一个视频item跳转到这个视频的详情页，视频没有重新加载，而是直接播放，这种无缝播放是怎么做到的？楼主能不能在RecyclerViewNormalActivity中实现无缝播放调转到详情页的功能？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JieCaoVideoPlayer#959]

**Comment by lipangit** [comment]
可以。
正常的进入详情页声音也可以不间断，头条有间断间断。进入全屏和进入详情页是一个道理，参照咱们的进入全屏的过程，可以做到声音不间断。

**Comment by StevenNick88** [comment]
什么时候demo中会实现啊？能否帮忙快速实现。急急急

**Comment by liweiGe** [comment]
> 什么时候demo中会实现啊？能否帮忙快速实现。急急急

已经实现了吗?有没有代码参考

**Comment by lipangit** [comment]
新版的分支正在做这个功能，预计一个礼拜能有预览版

**Comment by liweiGe** [comment]
> 新版的分支正在做这个功能，预计一个礼拜能有预览版

very good,现在是把播放进度传到详情页,直接seekto的形式,这样会有loading等待,后面优化这需要在activity间无缝切换的效果,坐等实现后应用到项目里

**Comment by lipangit** [comment]
重写了70%，相当于开了一个新项目

**Comment by StevenNick88** [comment]
无缝播放这个功能现在实现了吗？

**Comment by lipangit** [comment]
还在做，你看attach_to_other_view这个分支，工作量很大

**Comment by StevenNick88** [comment]
该功能的预计完成时间是什么时候？

**Comment by lipangit** [comment]
基础功能已经开发完毕，如果和旧版一样多的功能还需要三四个礼拜，之后还会开发更多功能

**Comment by StevenNick88** [comment]
请问该功能的进度如何了？

**Comment by lipangit** [comment]
进度缓慢

**Comment by StevenNick88** [comment]
请问楼主该功能能在4月底完成吗？
我已经找到了实现该功能的基础库，实现得还不错，但我还是想用你们的库。          

实现的库是   ：https://github.com/jiajunhui/PlayerBase
他的无缝续播的原理是：

类似于今日头条等应用的列表播放效果，在列表中播放时无缝续播进入详情页或者无缝进入全屏页面。

原理：解码器动态关联不同的渲染视图（RenderView），比如使用MediaPlayer动态关联SurfaceView，就如同一个电脑主机不断连接不同的显示器。

版本3.2.0之后增加了关联助手，让无缝续播的使用更加简单化。使用关联播放时，您需要提供一个播放视图的容器。比如您要把正在view1容器中播放的画面切换到view2容器中，那么您只需要把view2的容器关联到助手即可。如下示例：

public class TestActivity extends AppcompatActivity{

	RelationAssist mAssist;
	ViewGroup view2;

	public void onCreate(Bundle saveInstance){
		super.onCreate(saveInstance);
		 
		//...
		 
		mAssist = new RelationAssist(this);
		mAssist.setEventAssistHandler(eventHandler);
		mReceiverGroup = ReceiverGroupManager.get().getLiteReceiverGroup(this);
		mAssist.setReceiverGroup(mReceiverGroup);
		DataSource dataSource = new DataSource();
		dataSource.setData("http://...");
		dataSource.setTitle("xxx");
		mAssist.setDataSource(dataSource);
		mAssist.attachContainer(mVideoContainer);
		mAssist.play();
		    
		//...
		switchPlay(view2);
	}
	
	private void switchPlay(ViewGroup container){
		 mAssist.attachContainer(container);
	}

}
更加详细的操作请参见项目demo。

以上希望能帮到楼主。

**Comment by lipangit** [comment]
7.0版本是把整个jzvd移动到其他布局中的。

**Comment by lipangit** [comment]
https://github.com/lipangit/JZT  最近正在酝酿这个  感兴趣吗  我好像有你的qq

**Comment by StevenNick88** [comment]
我上班忙啊，没有多余的时间，有时间看。这个功能是还在做是吗？

**Comment by lipangit** [comment]
在做

**Comment by StevenNick88** [comment]
请问楼主该功能现在要完成了吗？

**Comment by lipangit** [comment]
7.0已经改完了，底层已经支持跳转详情页了。

**Comment by StevenNick88** [comment]
那有demo吗？我下载下来没找到啊

**Comment by lipangit** [comment]
底层支持  具体功能还没做。。

**Comment by StevenNick88** [comment]
什么时候会做啊？

**Comment by lipangit** [comment]
兄弟，你对这个研究到什么程度，有时间帮忙研究一下，有啥资料让我学习一下吗

**Comment by StevenNick88** [comment]
https://github.com/jiajunhui/PlayerBase： 这个库实现了无缝播放
还有这个库也实现了：https://github.com/CarGuo/GSYVideoPlayer    你下载代码下来研究下，我水平有限也看得不是很懂啊

**Comment by StevenNick88** [comment]
关于这个问题，我现在有了新的方案：
1、列表页的布局是：
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/video_item_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginLeft="15dp"
    android:layout_marginTop="10dp"
    android:layout_marginRight="15dp">

    <FrameLayout
        android:id="@+id/video_container"
        android:layout_width="match_parent"
        android:layout_height="185dp" >

        <cn.jzvd.JzvdStd
            android:id="@+id/video_player"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </FrameLayout>

    <RelativeLayout
        android:id="@+id/video_info"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/video_container">

        <TextView
            android:id="@+id/name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="17dp"
            android:layout_marginBottom="20dp"
            android:fontFamily="@string/roboto_medium"
            android:tag="@string/skin_textColor_textColor4"
            android:textSize="15sp" />
    </RelativeLayout>
</RelativeLayout>

JzvdStd用FrameLayout包裹起来，详情页的布局和列表页一样，JzvdStd也用FrameLayout包裹起来。

列表点击进入详情的直接调转到详情页的activity：
      if (Jzvd.CURRENT_JZVD ！= null) {
            Intent intent = new Intent(getActivity(), DetailVideoActivity.class);
            intent.putExtra("currentPlayPosition", holder.getAdapterPosition());
            intent.putExtra("isNeedResumePlay", true);
            intent.putExtra("videoID", item.getVideoID());
            getActivity().startActivity(intent);
       }

详情页中接收列表页视频的处理：
      playerContainer = findViewById(R.id.video_container);
      if (isNeedResumePlay){
            playerContainer.removeAllViews();
            JzvdStd player = (JzvdStd) Jzvd.CURRENT_JZVD;
            if (player != null) {
                player.attachToContainer(playerContainer);
            }
        }

![image](https://user-images.githubusercontent.com/20816593/59179897-0662bc00-8b96-11e9-81ae-b97185af01d8.png)

这样列表中正在播放的视频进入详情就实现了无缝播放，但是发现了一个问题，就是进入详情页后点击视频全屏按钮不起作用了，不会全屏。请帮忙处理一个这个问题。谢谢！

**Comment by lipangit** [comment]
兄弟，能在最新分支上提交pr吗，可运行的。有[JZT](https://github.com/lipangit/JZT)赠送

**Comment by StevenNick88** [comment]
好的，等我忙完了这阵子添加上去。

**Comment by lipangit** [comment]
挤时间就加上去吧，忙完这阵子还有下阵子要忙。新建个activity，里面你随便折腾。

**Comment by lipangit** [comment]
兄弟你qq微信多少 加我一下。

**Comment by StevenNick88** [comment]
qq:1461190907   微信：13025473609
我这周发版本啊，下周应该有空了，到时候我加上去，现在天天11点下班，哎！！！

**Comment by StevenNick88** [comment]
我加你qq了
