### ISSUE TITLE
有没有可以知道缓冲完成的事件通知

### ISSUE THREAD

**Issue by wf08314110101** [lipangit/JieCaoVideoPlayer#960]
如题

**Comment by lipangit** [comment]
没听说过。。你可以查下系统的api，有就有，没有自己也没法写

**Comment by wf08314110101** [comment]
我看到你内部有设置缓存进度的代码setBufferProgress，那是不是当进度满了的时候就是换成完毕呢，那是不是可以在currentState里面加一个类型CURRENT_STATE_PLAY_BUFFERING_COMPLETION呢

**Comment by lipangit** [comment]
@wf08314110101  对

**Comment by wf08314110101** [comment]
谢谢解答哈

**Comment by lipangit** [comment]
哦 你说的是视频的缓存进度，还以为是视频开始时候的loading进度

**Comment by wf08314110101** [comment]
- -!
