### ISSUE TITLE
如何在全屏的时候禁止拖动进度条在线等

### ISSUE THREAD

**Issue by zhouyong0330** [lipangit/JieCaoVideoPlayer#961]
我在小屏的时候可以禁止拖动进度条，在全屏的时候就不行。
这是我调用的监听
videoplayer.progressBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
            @Override
            public void onProgressChanged(SeekBar seekBar, int i, boolean b) {

            }

            @Override
            public void onStartTrackingTouch(SeekBar seekBar) {
                //这里可以进行判断是否禁止拖动
                seekBar.setEnabled(false);
               
                Toast.makeText(context, "禁止拖动", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onStopTrackingTouch(SeekBar seekBar) {
            }
        });

但是在全屏就不起作用，我自定义了一个属性，发现全屏的时候这个属性初始化了，是不是全屏的时候要重新构建对象了？
求解答

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写setUp，disable seekbar

**Comment by zhouyong0330** [comment]
好，我研究研究看

**Comment by lipangit** [comment]
恩，所有的逻辑都在继承JCVideoPlayerStandard的类里写。

**Comment by sserf** [comment]
作者，我也遇到了，这个怎么写啊

**Comment by lipangit** [comment]
@sserf 继承JCVideoPlayerStandard，复写各个状态，分别修改想修改的ui
