### ISSUE TITLE
作者有没有计划支持rtmp协议的直播流

### ISSUE THREAD

**Issue by jayleco** [lipangit/JieCaoVideoPlayer#962]
现在直播非常火，很多都是采用rtmp协议来接收流播放，ijk虽然支持但是使用较复杂，而且没什么文档说明，好多需要rtmp协议的播放器都选择去啃ijkplayer，希望作者啥时候能加上rtmp协议播放支持

**Comment by lipangit** [comment]
播放器支持什么视频格式完全取决于使用哪个播放引擎，比如系统的MediaPlayer，ijkplayer，exoplayer，vlc等播引擎。综合因素考虑目前选择用系统的MediaPlayer。
