### ISSUE TITLE
Error:MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present,华为手机可以正常播放m3u8视频，而vivo则报错，无法播放，请问怎么进行相应的机型匹配？

### ISSUE THREAD

**Issue by junmei520** [lipangit/JieCaoVideoPlayer#963]
Error:MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present,华为手机可以正常播放m3u8视频，而vivo则报错，无法播放，请问针对这个问题，该怎么进行相应的机型匹配？

**Comment by lipangit** [comment]
不知道，这是google的坑
