### ISSUE TITLE
拖拽进度条超出缓冲进度时 , 播放器中间出现惊叹号 , 然后又重新加载了.

### ISSUE THREAD

**Issue by xunshishi** [lipangit/JieCaoVideoPlayer#964]
如题 
视频缓冲中 , **拖拽进度条超出当前缓冲进度时** , 播放器中间出现惊叹号 , 然后视频又重头加载了 , 不能做到随着进度条的拖拽缓冲视频 . 这算不算是bug?

**Comment by lipangit** [comment]
什么情况会出这个问题，哪个版本，demo里有这个问题，能复现吗

**Comment by xunshishi** [comment]
一直有这个问题,就是最新的版本.

**Comment by xunshishi** [comment]
就是拖拽进度条 超出当前缓冲进度时

**Comment by lipangit** [comment]
demo的url有这个问题吗，能在log里发现什么吗
