### ISSUE TITLE
头条视频中点击某一个视频item跳转到这个视频的详情页，视频没有重新加载，而是直接播放。这个我参照全屏的功能实现了，但是在新的详情页的页面里面，全屏的按钮事件和返回键的处理有很多bug。请楼主在RecyclerViewNormalActivity中实现无缝播放调转到详情页的功能。急急急

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JieCaoVideoPlayer#967]

**Comment by lipangit** [comment]
哥们，这个功能以前我就想做，如果做的全面比较复杂，进入全屏，进入详情页，进入小窗，从小窗进入全屏，进入详情之后再全屏，本来我想统一管理这些东西，但是实现起来极其复杂。如果没有通用性放到库里没有意义，所以你在你的项目里做出适合你的需求就好了。这个不会放弃，一旦有突破还会继续做下去

**Comment by StevenNick88** [comment]
确实很复杂，我调了两天了，还是没有头绪。虽然不具有通用性，但是demo中加上这些功能，让开发者有参照，对于该控件的推广是很有意义的。
