### ISSUE TITLE
JCMediaManager的currentVideoWidth/Height没有正确置0

### ISSUE THREAD

**Issue by axeon** [lipangit/JieCaoVideoPlayer#97]
JCMediaManager的currentVideoWidth/Height没有正确置0。
库中使用了currentVideoWidth/Height设置了布局，但是在退出或者停止播放后，没有对其设置0。
当两个视频宽高比不一致的时候，打开新视频可能会导致布局错乱。

**Comment by lipangit** [comment]
这个你是遇到这样的情况了吗
理论上在MediaPlayer回调视频大小的时候才会resize SurfaceView，就是说resize SurfaceView之前视频大小的变量会被赋值，置零可有可无

**Comment by axeon** [comment]
从列表页进入只有一个视频的详细页时，如果上一个上竖屏的，下一个是宽屏的，进入的时候宽屏的布局错乱了，高度和上一个竖屏的一致，宽屏的视频显示在下方，上半部分都是黑的。

**Comment by lipangit** [comment]
啊，有道理，有可能会有这么一瞬间，我整理一下高宽的代码

**Comment by axeon** [comment]
如果可能，请增加一个MaxHeight属性来控制预览图和播放器，这样就完美了。
我们因为这个属性，在外围干了很多愚蠢的事情。

**Comment by lipangit** [comment]
发版时间到了，下版会做

**Comment by axeon** [comment]
ok

**Comment by lipangit** [comment]
fixed
