### ISSUE TITLE
画面声音不同步

### ISSUE THREAD

**Issue by 694177407** [lipangit/JieCaoVideoPlayer#970]
http://yixiaomiao.img-cn-beijing.aliyuncs.com/video/609_1497146633_95723_qncaf_1.mp4
http://yixiaomiao.img-cn-beijing.aliyuncs.com/video/609_1497159665_85779_m0d3a_1.mp4
这个视频是正常的，但是用JieCaoVideopalyer播放时明显的声音画面不同步

**Comment by lipangit** [comment]
超出老臣能力范围
