### ISSUE TITLE
在demo RecyclerViewNormalActivity中播放item0，当我向下拖动到item4的时候才停止播放，而不是item0看不见的时候。有两个问题：1、为什么拖动到item4的时候会停止播放？2、停止播放是触发了什么方法？

### ISSUE THREAD

**Issue by StevenNick88** [lipangit/JieCaoVideoPlayer#971]

**Comment by lipangit** [comment]
首先列表复用的，在列表复用的时候调用setUp的时候如果正在播放会停止播放

**Comment by AmbitChen** [comment]
你试着自己把JCVideoPlayerStandard代码Copy一份，然后重写onWindowVisibilityChanged
@Override
    protected void onWindowVisibilityChanged(int visibility) {
        super.onWindowVisibilityChanged(visibility);
        if (visibility == View.GONE) {
                        this.release();
                    }
    }

之后列表的Item使用你自己写的Class~~

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27946895-4fce5128-6326-11e7-920f-680fa093609b.png)

在列表中来回拖动列表，之后可见，没有划出界面的回调，这方法的判断有问题

**Comment by AmbitChen** [comment]
什么问题啊？我还没测出来

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27947343-0e377d14-6328-11e7-8512-4b5d61939849.png)

滑动上图的列表，onWindowVisibilityChanged函数无法取得item不可见

**Comment by AmbitChen** [comment]
![8wert qb 7 7n 8_ d144kp](https://user-images.githubusercontent.com/20348442/27947520-bfbf5976-6328-11e7-9044-a432432c5563.png) 我的完全可以呀!

**Comment by lipangit** [comment]
你在哪改的我试试，提交个分支吧

**Comment by AmbitChen** [comment]
是onWindowVisibilityChanged 不是 onVisibilityChanged  。

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27950049-6dfd327a-6332-11e7-8537-70bf63322132.png)

这两个函数的效果一样，log只有可以见 没有不可见，我试试你的代码  821537155@qq.com, 把你修改的类发过来
