### ISSUE TITLE
Button not visible on mobile data consumption alert

### ISSUE THREAD

**Issue by bb1690** [lipangit/JieCaoVideoPlayer#972]
I have Integrated library in my code,and it works well on wifi but when i try to play video using mobile data it shows alert regarding. nut buttons are not visible. On trying to click blindly is shows but little faded

**Comment by lipangit** [comment]
What effect do you want?  Can you elaborate on it?

**Comment by lipangit** [comment]
I do not know what you mean.

It will show alert when use mobile data, what do you think about the alert

**Comment by bb1690** [comment]
![device-2017-06-19-100740](https://user-images.githubusercontent.com/24837111/27269796-50135d8e-54d7-11e7-84f8-8b51923b3f00.png)
Alert is fine. Its just i can see buttons,Please check attached img

**Comment by lipangit** [comment]
You should check your style.xml,I search the library did not find where change the style

**Comment by bb1690** [comment]
Thanks.. Got it.
