### ISSUE TITLE
Nginx mp4 streamming can not connect more than 10 player app

### ISSUE THREAD

**Issue by harishnv** [lipangit/JieCaoVideoPlayer#973]
I am using  Nginx mp4 streamming to get mp4 video stream.
I have used JieCaoVideoPlayer to play the stream in Application.
Whenever I connect more than 10 mobiles the all clients goes into buffer mode.
In documentation it has mention  [Support https and rtsp]
mine server is on http not https.
Is this could be the reason?
If I run same video stream on native android videoview it can play more than 40 clients without hiccups.

**Comment by lipangit** [comment]
I think JieCaoVideoPlayer and native android VideoView is same. only VideoView is base on surfaceview JieCaoVideoPlayer is base on TextureView
