### ISSUE TITLE
Full screen view

### ISSUE THREAD

**Issue by arpitjoshi08** [lipangit/JieCaoVideoPlayer#976]
this lib working so well but i am getting  one issue is .bottom view (seekbar , full screen button) only show when video start to play and  also click listener work only when video play but  i need to show every time and button click listener also work how is it possible using this library.

**Comment by lipangit** [comment]
Extends JCVideoPlayerStandard, override onClickUiToggle() get hide bottom event.

override setUiWitStateAndScreen() change ui in every state.
