### ISSUE TITLE
小米手机播放m3u8视频的时候，只有声音不显示图像

### ISSUE THREAD

**Issue by baiyinshi** [lipangit/JieCaoVideoPlayer#982]
![image](https://user-images.githubusercontent.com/8284992/27326797-15352db0-55df-11e7-93d0-c373855384e8.png)

**Comment by lipangit** [comment]
超出老臣的能力范围

**Comment by lipangit** [comment]
可能不在这个的解决范围
![image](https://user-images.githubusercontent.com/2038071/27340247-96e13412-560c-11e7-971b-5c19c0741be5.png)

把getDurationzhu's注释掉试试

**Comment by LLhon** [comment]
小米2,系统5.0测试播放m3u8格式是没问题的

**Comment by WoodyGuo** [comment]
试一下 #938 中Z008 的方法
