### ISSUE TITLE
视频被压扁的问题

### ISSUE THREAD

**Issue by coder-pig** [lipangit/JieCaoVideoPlayer#983]
如图，视频被压扁了，PC和iOS打开都是正常的，想问下可能是什么问题？

![][1]

  [1]: http://static.zybuluo.com/coder-pig/qorhbw7j0lushifbklz4nub0/image_1bj2ghqm18eg19821gkn527lga9.png

**Comment by coder-pig** [comment]
试了下Android自带的播放器也是变形...

**Comment by lipangit** [comment]
继承JCVideoPlayerStandard，复写onVideoSizeChanged函数，这里可以特殊指定textureView的大小

**Comment by lipangit** [comment]
onVideoSizeChanged靠这个函数自动修正textureView的大小，达到视频不变形的目的，如果android自带的播放器也变形，建议处理视频本身。
