### ISSUE TITLE
判断是否是播放本地视频的问题

### ISSUE THREAD

**Issue by cenoo** [lipangit/JieCaoVideoPlayer#984]
你好，播放本地视频的时候，本地视频url开头是"/storage"开头，仍然会提示是否使用流量播放的对话框。视频路径是通过ContentResolver查询MediaStore得到的，视频文件放在sd卡中，机器型号三星s5，系统是官方6.0

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27520734-509c020c-5a44-11e7-8231-b1fb62054091.png)

确认一下路径，如果以/开头是不会有wifi提示的

**Comment by cenoo** [comment]
在JCVideoPlayer类中onClick()方法下的startButton的点击逻辑判断中，没有`!url.startsWith("/")`，所以点击startButton会仍提示使用流量的对话框，点击屏幕其他地方开始播放就没有提示。

**Comment by Virczz** [comment]
@lipangit 我对比了5.6版本中JCVideoPlayerStandard的197行和JCVideoPlayer的165行，里面关于判断是否是本地视频的逻辑不一样，在JCVideoPlayer里面少写了 `!url.startWith("/")` 这一条判断。

**Comment by lipangit** [comment]
没错，疏忽了，多谢你的提醒@Virczz

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/28063722-bdfffa7a-6664-11e7-9d00-cff483fb2644.png)
这句话什么意思 

JCVideoPlayer.WIFI_TIP_DIALOG_SHOWED 这个变量是判断是否提示过wifi

**Comment by Virczz** [comment]
因为我在其它issue里面，看见当定义JCVideoPlayer.WIFI_TIP_DIALOG_SHOWED这个变量为true以后，就不会弹出Dialog了。因为我做的项目，都是本地视频，所以我现在是直接把这个变量定为true的。
