### ISSUE TITLE
没有监听进度的接口

### ISSUE THREAD

**Issue by liliuchen** [lipangit/JieCaoVideoPlayer#985]
如果想监听播放进度，直接添加监听器最好了

**Comment by lipangit** [comment]
可以复写setProgressAndText函数，这能得到进度监听，正在准备把各种时间的监听规范的暴露出来

**Comment by gordonpro** [comment]
listener callback 在等

**Comment by lipangit** [comment]
别用listener，用复写函数的形式

**Comment by Destiny01** [comment]
怎么复写？

**Comment by lipangit** [comment]
参考MainActivity的MyJZVideoPlayerStandard
