### ISSUE TITLE
小米盒子3播放出现what -38 extra 0

### ISSUE THREAD

**Issue by wf08314110101** [lipangit/JieCaoVideoPlayer#987]
系统版本
android.os.Build.MODEL + ","
                + android.os.Build.VERSION.SDK + ","
                + android.os.Build.VERSION.RELEASE 
MIBox3,22,5.1.1

在手机上测试多个系统都没有这个问题

**Comment by wf08314110101** [comment]
按照#844兄弟说的将prepareAysnc()改成prepare()这个样子可以播放，但是只有声音，界面一直在转圈圈

**Comment by WoodyGuo** [comment]
试一下 #938 中Z008 的方法
