### ISSUE TITLE
为什么4.几版本播放不了视频

### ISSUE THREAD

**Issue by sssjjjqqq** [lipangit/JieCaoVideoPlayer#989]
我试了下4.2的和4.4的都不行

**Comment by lipangit** [comment]
log是啥

**Comment by sssjjjqqq** [comment]
点击播放出来个感叹号

**Comment by sssjjjqqq** [comment]
@lipangit 点击播放以后 log没有报错，显示一个感叹号

**Comment by lipangit** [comment]
4.*用的ijkplayer播放器

**Comment by LLhon** [comment]
亲测4.4以下系统播放m3u8格式视频不行,mp4格式是没问题的

**Comment by lipangit** [comment]
系统的坑，老臣填不起啊

**Comment by nanweiqing** [comment]
@lipangit ，很奇怪，为什么之前很早的1.6版本可以在4.4以下播放m3u8格式呢，为什么现在的5.4版本不能，内部实现很大不一样吗

**Comment by lipangit** [comment]
1.6和5.4本质上是一样的，应该都能播放，用的都是系统的MediaPlayer，不可能一个能播放一个不能吧

**Comment by nanweiqing** [comment]
@lipangit ，真的是这样，我本身想用最新版本，在4.4.4的机器上就是放不了m3u8，只能用回1.6版本，就能播放，求查下问题原因，我真的想用最新版本

**Comment by lipangit** [comment]
这怎么查，你新建个项目，简简单单用MediaPlayer和TexTureView播放个视频，这个要是能播，咱们的JCVD就能播

**Comment by sssjjjqqq** [comment]
是我模拟器的原因，真机上都可以的
