### ISSUE TITLE
我想问一下，从那个版本开始把SurfaceView换成TexureView的呢？我想用最新的SurfaceView版的

### ISSUE THREAD

**Issue by whatisjava** [lipangit/JieCaoVideoPlayer#990]

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27465238-c504aa3c-5804-11e7-8dda-50e5b160d7ee.png)

可以参照16年6月2号之前的版本

**Comment by whatisjava** [comment]
好的非常感谢！

**Comment by whatisjava** [comment]
好像是这个版本 v3.2
 1975cca
Surface view will not in xml

**Comment by lipangit** [comment]
如果只改surfaceVIew的话你可以在当前版本改，这个只改一个类，v3.2这些之前的版本不好用

**Comment by whatisjava** [comment]
嗯，这个我了解，但是在阿里云智能电视上还有单双声道的的问题，而老版本上没有，所以只能先用老版本了。
