### ISSUE TITLE
求教，小米note在系统4.4.4下onError -38 - 0 [1118573208] 无法播放问题

### ISSUE THREAD

**Issue by lvbell** [lipangit/JieCaoVideoPlayer#991]
06-06 18:01:43.356 31856-31856/com.xcar.activity I/JCResizeTextureView: onMeasure  [1119758608] 
06-06 18:01:43.356 31856-31856/com.xcar.activity I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
06-06 18:01:43.356 31856-31856/com.xcar.activity I/JCResizeTextureView: viewRotation = 0
06-06 18:01:43.356 31856-31856/com.xcar.activity I/JCResizeTextureView: onMeasure  [1119758608] 
06-06 18:01:43.356 31856-31856/com.xcar.activity I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: viewRotation = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: onMeasure  [1119758608] 
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: viewRotation = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: onMeasure  [1119758608] 
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: videoWidth = 0, videoHeight = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JCResizeTextureView: viewRotation = 0
06-06 18:01:43.366 31856-31856/com.xcar.activity I/JieCaoVideoPlayer: onSurfaceTextureAvailable [1119987416] 

以下是错误
06-06 18:01:43.366 31856-32522/com.xcar.activity E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present
06-06 18:01:43.376 31856-32522/com.xcar.activity E/MediaPlayer: error (-38, 0)
06-06 18:01:43.376 31856-32522/com.xcar.activity W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
06-06 18:01:43.376 31856-32522/com.xcar.activity E/MediaPlayer: prepareAsync called in state 0
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err: java.lang.IllegalStateException
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err:     at android.media.MediaPlayer.prepareAsync(Native Method)
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err:     at fm.jiecao.jcvideoplayer_lib.JCMediaManager$MediaHandler.handleMessage(JCMediaManager.java:98)
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err:     at android.os.Looper.loop(Looper.java:136)
06-06 18:01:43.376 31856-32522/com.xcar.activity W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
06-06 18:01:43.376 31856-32522/com.xcar.activity E/MediaPlayer: Error (-38,0)
06-06 18:01:43.386 31856-31856/com.xcar.activity E/JieCaoVideoPlayer: onError -38 - 0 [1118573208] 

小米note，系统4.4.4，在recyclerview中，无法播放

**Comment by lvbell** [comment]
@lipangit  作者你好，我发现4.x的系统，播放m3u8都有问题，这是因为surfaceholder没有被及时创建的问题么

**Comment by lipangit** [comment]
应该不是

**Comment by lvbell** [comment]
我后来确定了一下，5.0系统以下的m3u8都播放不了，不单是小米的问题

**Comment by lipangit** [comment]
系统的坑，超出老臣解决范围
