### ISSUE TITLE
本地视频播放不了

### ISSUE THREAD

**Issue by Aarondue** [lipangit/JieCaoVideoPlayer#992]
相关改动代码如下，我把Demo首页自带的url改成本地视频的url，不知道为什么，播放不了，视频格式MP4，编码格式AVC1（属于H.264中的一种）：

protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mTinyWindow = (Button) findViewById(R.id.tiny_window);
        mAutoTinyWindow = (Button) findViewById(R.id.auto_tiny_window);
        mPlayDirectly = (Button) findViewById(R.id.play_directly_without_layout);
        mAboutListView = (Button) findViewById(R.id.about_listview);
        mAboutApi = (Button) findViewById(R.id.about_api);
        mAboutWebView = (Button) findViewById(R.id.about_webview);

        mTinyWindow.setOnClickListener(this);
        mAutoTinyWindow.setOnClickListener(this);
        mAboutListView.setOnClickListener(this);
        mPlayDirectly.setOnClickListener(this);
        mAboutApi.setOnClickListener(this);
        mAboutWebView.setOnClickListener(this);

        mJcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
        final String url = "/storage/emulated/0/DCIM/Camera/VID_20170603_162547.mp4";
//        final String url = "http://video.jiecao.fm/11/23/xin/%E5%81%87%E4%BA%BA.mp4";
        mJcVideoPlayerStandard.setUp(url, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        Picasso.with(this)
                .load("http://img4.jiecaojingxuan.com/2016/11/23/00b026e7-b830-4994-bc87-38f4033806a6.jpg@!640_360")
                .into(mJcVideoPlayerStandard.thumbImageView);

        JCVideoPlayer.setJcUserAction(new MyUserActionStandard());
    }

**Comment by lipangit** [comment]
不是路径问题就是格式问题，先分开确认一下

如果是格式问题就格式化视频源了

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27527871-499aa5e4-5a80-11e7-813a-20d8497db817.png)

**Comment by Aarondue** [comment]
我使用本地url加载视频，注释掉上线的，本地还是加载不出来啊？。。。。。。。

        mJcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
//        mJcVideoPlayerStandard.setUp("http://video.jiecao.fm/11/23/xin/%E5%81%87%E4%BA%BA.mp4"
//                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        Picasso.with(this)
                .load("http://img4.jiecaojingxuan.com/2016/11/23/00b026e7-b830-4994-bc87-38f4033806a6.jpg@!640_360")
                .into(mJcVideoPlayerStandard.thumbImageView);
        mJcVideoPlayerStandard.loop = true;
        mJcVideoPlayerStandard.headData = new HashMap<>();
        mJcVideoPlayerStandard.headData.put("key", "value");
        JCVideoPlayer.SAVE_PROGRESS = false;
        /** Play video in local path, eg:record by system camera **/
        cpAssertVideoToLocalPath();
        mJcVideoPlayerStandard.setUp(Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        /** Play video in assert **/
//        mJcVideoPlayerStandard.setUp("file:///android_asset/local_video.mp4"
//                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");

**Comment by Aarondue** [comment]
@lipangit 我使用本地url加载视频，注释掉上线的，本地还是加载不出来啊？。。。。。。。
    mJcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
// mJcVideoPlayerStandard.setUp("http://video.jiecao.fm/11/23/xin/%E5%81%87%E4%BA%BA.mp4"
// , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
Picasso.with(this)
.load("http://img4.jiecaojingxuan.com/2016/11/23/00b026e7-b830-4994-bc87-38f4033806a6.jpg@!640_360")
.into(mJcVideoPlayerStandard.thumbImageView);
mJcVideoPlayerStandard.loop = true;
mJcVideoPlayerStandard.headData = new HashMap<>();
mJcVideoPlayerStandard.headData.put("key", "value");
JCVideoPlayer.SAVE_PROGRESS = false;
/** Play video in local path, eg:record by system camera /
cpAssertVideoToLocalPath();
mJcVideoPlayerStandard.setUp(Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"
, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
/ Play video in assert **/
// mJcVideoPlayerStandard.setUp("file:///android_asset/local_video.mp4"
// , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");

**Comment by Aarondue** [comment]
@lipangit 我如下先后两种方式加载本地视频，可仍然不能播放，这怎么回事？
        mJcVideoPlayerStandard = (JCVideoPlayerStandard) findViewById(R.id.jc_video);
//        mJcVideoPlayerStandard.setUp("http://video.jiecao.fm/11/23/xin/%E5%81%87%E4%BA%BA.mp4"
//                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        JCVideoPlayer.SAVE_PROGRESS = false;
        /** Play video in assert **/
//        mJcVideoPlayerStandard.setUp("file:///android_asset/local_video.mp4"
//                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        /** Play video in local path, eg:record by system camera **/
        cpAssertVideoToLocalPath();
        mJcVideoPlayerStandard.setUp(Environment.getExternalStorageDirectory().getAbsolutePath() + "/DCIM/Camera/local_video.mp4"
                , JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "嫂子不信");
        
        Picasso.with(this)
                .load("http://img4.jiecaojingxuan.com/2016/11/23/00b026e7-b830-4994-bc87-38f4033806a6.jpg@!640_360")
                .into(mJcVideoPlayerStandard.thumbImageView);
        mJcVideoPlayerStandard.loop = true;
        mJcVideoPlayerStandard.headData = new HashMap<>();
        mJcVideoPlayerStandard.headData.put("key", "value");

**Comment by Aarondue** [comment]
@lipangit Demo默认把本地加载视频的两段代码注释的，你放开注释后重新运行，你瞅瞅能正常播放吗？我这里不能呢。

**Comment by lipangit** [comment]
刚才 亲测能播

**Comment by Aarondue** [comment]
@lipangit 方便再截一张代码的图吗？还有你使用的什么手机

**Comment by Aarondue** [comment]
@lipangit 亲，急解决该问题，线上等，感谢！！！

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/27532852-23f0a0b4-5a94-11e7-953e-d00046dc4df8.png)

解开这两行代码的注释，会自动往那个路径复制一个视频，直接点播放就好了

**Comment by lipangit** [comment]
红米note3

**Comment by Aarondue** [comment]
@好无语，我代码和你一模一样，就是播放不出来。我重新再下载一份代码解压后试试，你有没有手动添加so文件进来？加个QQ呗，1941771036

**Comment by Aarondue** [comment]
@lipangit 好无语，我代码和你一模一样，就是播放不出来。我重新再下载一份代码解压后试试，你有没有手动添加.so等文件进来？加个QQ呗，1941771036

**Comment by lipangit** [comment]
用最新的5.5.4版本，不需要so，库的大小就100k，用系统的MediaPlayer播放。 主页有群
