### ISSUE TITLE
请问处理原视频被旋转的核心代码在哪里？

### ISSUE THREAD

**Issue by 529523346** [lipangit/JieCaoVideoPlayer#993]
请问处理原视频被旋转的核心代码在哪里？我想参考下，谢谢大神指教

**Comment by lipangit** [comment]
JCVideoPlayer.onVideoSizeChanged

**Comment by lipangit** [comment]
我记得之前某个版本有个哥们改过，忘记了，现在找不到了。

**Comment by 529523346** [comment]
@lipangit `这个应该你本来的项目中就有写，就是我一个视频源本来是旋转的（因为拍摄的时候摄像头没有翻转），但是你这个播放器对这种视频作了处理使得原视频能正常播放，请问对这种情况的处理代码在哪？[  // 如果判断成立，则说明显示的TextureView和本身的位置是有90度的旋转的，所以需要交换宽高参数。
        if (viewRotation == 90 || viewRotation == 270) {
            int tempMeasureSpec = widthMeasureSpec;
            widthMeasureSpec = heightMeasureSpec;
            heightMeasureSpec = tempMeasureSpec;
        }]
我原先以为是这个，但是并不是

**Comment by Aarondue** [comment]
作者回答一下#992 本地视频播放不了 呗

**Comment by 529523346** [comment]
@Aarondue 我的本地视频是能播放的，你检查下你的播放路径问题

**Comment by Aarondue** [comment]
@529523346 我使用如下两种方式的url路径，在本地都能找到，就是播放不出来，求助，可以贴出你的本地url的处理方式吗，万谢，折腾我好几天了：
（1）final String url = new File(Environment.getExternalStorageDirectory() + File.separator + "DCIM" + File.separator + "Camera" + File.separator + "VID_20170603_162547.mp4").getPath();
（2）final String url  = "/storage/emulated/legacy/DCIM/Camera/VID_20170603_162547.mp4";

**Comment by lipangit** [comment]
对这块如果播放录像的视频的话应该旋转一下的，也在这里通过你的判断然后旋转textureView，这样试试

**Comment by Aarondue** [comment]
@529523346 我使用的oppo手机，我下载的Bilibili/ijkplayer的官方Demo，将路径final String url = "/storage/emulated/legacy/DCIM/Camera/VID_20170603_162547.mp4";传入都可以直接播放的，但是在这个lipangit/JieCaoVideoPlayer的Demo就播放不了。。。。

**Comment by 529523346** [comment]
@lipangit 我测试过，好像textureView onMeasure里的     int viewRotation = (int) getRotation();返回的旋转角度一直是0，单实际上这个视频是被旋转过的，而且我注释掉onMeasure里面的代码发现播放视频还是正常的所以你处理视频旋转的方法不在这onMeasure这里？

**Comment by 529523346** [comment]
@Aarondue 这是我的url格式“/storage/emulated/0/com.app.shanjiang/video/cbef058ff7164b82ff3799c0591517a7.mp4”我使用的是
   NEVideoPlayerActivity.start(context, path);这个方法，调起后直接可以播放本地视频

**Comment by lipangit** [comment]
getRotation是textureView的旋转，没旋转过textureView肯定是0，拿到视频的旋转，然后设置textureView的旋转

**Comment by 529523346** [comment]
@lipangit 哦哦，拿到视频的旋转信息的代码在哪里呢？我看你的demo能正常播放被旋转的视频，谢大神指教

**Comment by lipangit** [comment]
老臣能说不知道吗 T_T  ，自动的

**Comment by 529523346** [comment]
不可能吧，自动的？你没代码处理过这种情况？我用其他播放器貌似不能正常播放呐，(⊙﹏⊙)b

**Comment by 529523346** [comment]
@lipangit 不可能吧，自动的？你没代码处理过这种情况？我用其他播放器貌似不能正常播放呐，(⊙﹏⊙)b

**Comment by 529523346** [comment]
@Aarondue 不好意，刚刚弄错了，是这个代码：  JCVideoPlayerStandard.startFullscreen(context, JCVideoPlayerStandard.class, path, "");
