### ISSUE TITLE
Autoplay video on recyclerview scroll idle for an amount of time

### ISSUE THREAD

**Issue by mradzinski** [lipangit/JieCaoVideoPlayer#995]
Hi, first and foremost: Cool library you have here.

My requirement is the following one: I have a recycler view which contains videos and photos (imagine something like the Facebook or Instagram feed.) Is there a way to automatically play the current on screen video after the user stopped scrolling for a certain amount of time?

Thanks!

**Comment by lipangit** [comment]
Demo does not have the feathure, You should make some change to achive your goal.

First get when video in screen and outof screen.
Then jcVideoPlayerStandard.startButton.performClick() to start video,
releaseAllVideos() to stop video.
