### ISSUE TITLE
使用最新版的5.5.4，怎么一进来就自动播放,不用自手动点击？还有就是播放完怎么自动重拨？

### ISSUE THREAD

**Issue by myfGitup** [lipangit/JieCaoVideoPlayer#997]

**Comment by lipangit** [comment]
jcVideoPlayerStandard.startButton.performClick() 模拟手动点击开始播放

**Comment by myfGitup** [comment]
设置了，loop = true;     和.startButton.performClick();  在4.4.4 版本没有一点问题，但是在5.1    6.0.1版本上只能手动点击播放了

**Comment by lipangit** [comment]
也有人反映loop在个别机型上不好使

**Comment by myfGitup** [comment]
我是这样的顺序写的，在recyclerview里面的
videoView_type.setUp(path, JCVideoPlayerStandard.SCREEN_LAYOUT_NORMAL, "");
videoView_type.loop = true;
videoView_type.startButton.performClick();
